In [41]:
import pandas as pd
import os

import re

from Bio import SeqIO
import h5py
import json

from tqdm import tqdm
import numpy as np

## prepare mapping between splits and species names

In [42]:
dir = '/mnt/20tb/vsfishman/nn_interpretator/mammals_fasta_dataset/dataset'
metadata_df = pd.read_csv(os.path.join(dir, 'mammals_dataset_metadata3.txt'), sep='\t')
metadata_df

,assembly_accession,organism_name,n_autosomes,number_of_x,number_of_y
0,GCF_004115215.2,Ornithorhynchus anatinus,21,5,20
1,GCF_015852505.1,Tachyglossus aculeatus,31,5,9
2,GCF_902635505.1,Sarcophilus harrisii,6,1,1
3,GCF_011100635.1,Trichosurus vulpecula,9,10,0
4,GCF_030445035.1,Dasypus novemcinctus,46,1,0
...,...,...,...,...,...
120,GCF_002776525.5,Piliocolobus tephrosceles,21,1,1
121,GCF_903992535.2,Arvicola amphibius,17,1,0
122,GCF_019320065.1,Cervus canadensis,33,1,1
123,GCF_028023285.1,Balaenoptera ricei,54,1,0
124,GCF_029407905.1,Bubalus kerabau,23,1,0

In [43]:
TEST_SPECIES = ["Sarcophilus harrisii", "Monodelphis domestica", "Manis pentadactyla", "Equus asinus", "Sus scrofa", "Camelus dromedarius", 
        "Phyllostomus discolor", "Myotis daubentonii", "Suncus etruscus", "Lepus europaeus", "Ochotona princeps", 
        "Sciurus carolinensis", "Nycticebus coucang", "Lemur catta", "Cynocephalus volans", 'Elephas maximus indicus', 'Loxodonta africana',
        "Choloepus didactylus", "Ornithorhynchus anatinus", "Tachyglossus aculeatus"]

VALID_SPECIES = ["Lynx canadensis", "Neofelis nebulosa", "Eubalaena glacialis", "Balaenoptera musculus", "Cervus canadensis", "Dama dama",
                "Meriones unguiculatus", "Chionomys nivalis", "Jaculus jaculus", "Callithrix jacchus"]

no_autosomes = ["Mastomys coucha", 'Ursus arctos']

metadata_df = metadata_df[(metadata_df['number_of_x'] != 0) & (metadata_df['number_of_y'] != 0) & (metadata_df['n_autosomes'] != 0)]

TRAIN_SPECIES = metadata_df[metadata_df['organism_name'].apply(lambda x: (x not in VALID_SPECIES) and (x not in TEST_SPECIES))].organism_name.to_list()

In [44]:
split2organism_name = {
    "train": TRAIN_SPECIES,
    "valid": VALID_SPECIES,
    "test": TEST_SPECIES
}

with open('mammals_gender_data/split2organism_name.json', 'w') as f:
    json.dump(split2organism_name, f)

In [45]:
print(len(TRAIN_SPECIES))
print(len(VALID_SPECIES))
print(len(TEST_SPECIES))

28
10
20

# check if all the species have haploid chromosome sets

In [46]:
def read_chunk_from_hdf5(hdf5_path, dataset_name, start, length):
    with h5py.File(hdf5_path, 'r') as hdf5_file:
        dset = hdf5_file[dataset_name]
        chunk = dset[start:start + length].astype(str)
        return ''.join(chunk)

In [47]:
chr_df = pd.read_csv('mammals_gender_data/mammals_diploid_chr_number.tsv')

In [48]:
for split in ['train', 'valid', 'test']:
    for species in split2organism_name[split]:
        print(species)
        assembly_id = metadata_df[metadata_df['organism_name'] == species]['assembly_accession'].values[0]
        
        with h5py.File(f"mammals_gender_data/{split}.h5", 'r') as hdf5_file:
            autosomes = []
            sex_chromosomes = []
            
            for chr in list(hdf5_file[assembly_id].keys()):
               chr_name = re.findall(r'chromosome\s+([0-9]{1,2}|[A-Za-z]{1,2})', chr)[0]
               if chr_name != "Y" and chr_name != "X":
                   try:
                       autosomes.append(int(chr_name))
                   except:
                       autosomes.append(chr_name)
               else:
                   sex_chromosomes.append(chr_name)

            autosomes = list(set(autosomes))
            sex_chromosomes = list(set(sex_chromosomes))
            autosomes.sort()
            
            print("Sex chromosomes in dataset:", " ".join(sex_chromosomes))
            print("Autosomes in dataset:", autosomes)
            print("Diploid number of chromosomes in dataset:", len(autosomes) * 2 + len(sex_chromosomes))
            print("Diploid number of chromosomes:", chr_df[chr_df['species_name'] == species]['diploid_chr_number'].values[0])
            print(chr_df[chr_df['species_name'] == species]['diploid_chr_number'].values[0] == len(autosomes) * 2 + len(sex_chromosomes))
            print()

Macaca mulatta
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Diploid number of chromosomes in dataset: 42
Diploid number of chromosomes: 42
True

Papio anubis
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Diploid number of chromosomes in dataset: 42
Diploid number of chromosomes: 42
True

Pan paniscus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Diploid number of chromosomes in dataset: 48
Diploid number of chromosomes: 48
True

Pongo abelii
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Diploid number of chromosomes in dataset: 48
Diploid number of chromosomes: 48
True

Homo sapiens
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
Diploid number of chromosomes in dataset: 46
Diploid number of chromosomes: 46
True

Canis lupus familiaris
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]
Diploid number of chromosomes in dataset: 78
Diploid number of chromosomes: 78
True

Lutra lutra
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
Diploid number of chromosomes in dataset: 38
Diploid number of chromosomes: 38
True

Meles meles
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Diploid number of chromosomes in dataset: 44
Diploid number of chromosomes: 44
True

Mustela lutreola
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
Diploid number of chromosomes in dataset: 38
Diploid number of chromosomes: 38
True

Zalophus californianus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Diploid number of chromosomes in dataset: 36
Diploid number of chromosomes: 36
True

Delphinus delphis
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Diploid number of chromosomes in dataset: 44
Diploid number of chromosomes: 44
True

Globicephala melas
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Diploid number of chromosomes in dataset: 44
Diploid number of chromosomes: 44
True

Tursiops truncatus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Diploid number of chromosomes in dataset: 44
Diploid number of chromosomes: 44
True

Bos javanicus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
Diploid number of chromosomes in dataset: 60
Diploid number of chromosomes: 60
True

Bos taurus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
Diploid number of chromosomes in dataset: 60
Diploid number of chromosomes: 60
True

Bos indicus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
Diploid number of chromosomes in dataset: 60
Diploid number of chromosomes: 60
True

Ovis aries
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
Diploid number of chromosomes in dataset: 54
Diploid number of chromosomes: 54
True

Mus musculus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Diploid number of chromosomes in dataset: 40
Diploid number of chromosomes: 40
True

Rattus norvegicus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Diploid number of chromosomes in dataset: 42
Diploid number of chromosomes: 42
True

Rattus rattus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
Diploid number of chromosomes in dataset: 38
Diploid number of chromosomes: 38
True

Apodemus sylvaticus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Diploid number of chromosomes in dataset: 48
Diploid number of chromosomes: 48
True

Neomonachus schauinslandi
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
Diploid number of chromosomes in dataset: 34
Diploid number of chromosomes: 34
True

Mustela erminea
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Diploid number of chromosomes in dataset: 44
Diploid number of chromosomes: 44
True

Budorcas taxicolor
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
Diploid number of chromosomes in dataset: 52
Diploid number of chromosomes: 52
True

Mesoplodon densirostris
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Diploid number of chromosomes in dataset: 42
Diploid number of chromosomes: 42
True

Arvicanthis niloticus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Diploid number of chromosomes in dataset: 44
Diploid number of chromosomes: 44
True

Macaca thibetana thibetana
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Diploid number of chromosomes in dataset: 42
Diploid number of chromosomes: 42
True

Piliocolobus tephrosceles
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Diploid number of chromosomes in dataset: 44
Diploid number of chromosomes: 44
True

Lynx canadensis
Sex chromosomes in dataset: X Y
Autosomes in dataset: ['A', 'B', 'C', 'D', 'E', 'F']
Diploid number of chromosomes in dataset: 14
Diploid number of chromosomes: 38
False

Neofelis nebulosa
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
Diploid number of chromosomes in dataset: 38
Diploid number of chromosomes: 38
True

Eubalaena glacialis
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Diploid number of chromosomes in dataset: 42
Diploid number of chromosomes: 42
True

Balaenoptera musculus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Diploid number of chromosomes in dataset: 44
Diploid number of chromosomes: 44
True

Cervus canadensis
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
Diploid number of chromosomes in dataset: 68
Diploid number of chromosomes: 68
True

Dama dama
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
Diploid number of chromosomes in dataset: 68
Diploid number of chromosomes: 68
True

Meriones unguiculatus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Diploid number of chromosomes in dataset: 44
Diploid number of chromosomes: 44
True

Chionomys nivalis
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
Diploid number of chromosomes in dataset: 54
Diploid number of chromosomes: 54
True

Jaculus jaculus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Diploid number of chromosomes in dataset: 48
Diploid number of chromosomes: 48
True

Callithrix jacchus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
Diploid number of chromosomes in dataset: 46
Diploid number of chromosomes: 46
True

Sarcophilus harrisii
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6]
Diploid number of chromosomes in dataset: 14
Diploid number of chromosomes: 14
True

Monodelphis domestica
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8]
Diploid number of chromosomes in dataset: 18
Diploid number of chromosomes: 18
True

Manis pentadactyla
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Diploid number of chromosomes in dataset: 40
Diploid number of chromosomes: 40
True

Equus asinus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
Diploid number of chromosomes in dataset: 62
Diploid number of chromosomes: 62
True

Sus scrofa
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
Diploid number of chromosomes in dataset: 38
Diploid number of chromosomes: 38
True

Camelus dromedarius
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
Diploid number of chromosomes in dataset: 74
Diploid number of chromosomes: 74
True

Phyllostomus discolor
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Diploid number of chromosomes in dataset: 32
Diploid number of chromosomes: 32
True

Myotis daubentonii
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Diploid number of chromosomes in dataset: 44
Diploid number of chromosomes: 44
True

Suncus etruscus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Diploid number of chromosomes in dataset: 42
Diploid number of chromosomes: 42
True

Lepus europaeus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
Diploid number of chromosomes in dataset: 48
Diploid number of chromosomes: 48
True

Ochotona princeps
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
Diploid number of chromosomes in dataset: 68
Diploid number of chromosomes: 68
True

Sciurus carolinensis
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Diploid number of chromosomes in dataset: 40
Diploid number of chromosomes: 40
True

Nycticebus coucang
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
Diploid number of chromosomes in dataset: 50
Diploid number of chromosomes: 50
True

Lemur catta
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
Diploid number of chromosomes in dataset: 56
Diploid number of chromosomes: 56
True

Cynocephalus volans
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
Diploid number of chromosomes in dataset: 38
Diploid number of chromosomes: 38
True

Elephas maximus indicus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
Diploid number of chromosomes in dataset: 56
Diploid number of chromosomes: 56
True

Loxodonta africana
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
Diploid number of chromosomes in dataset: 56
Diploid number of chromosomes: 56
True

Choloepus didactylus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
Diploid number of chromosomes in dataset: 56
Diploid number of chromosomes: 56
True

Ornithorhynchus anatinus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
Diploid number of chromosomes in dataset: 44
Diploid number of chromosomes: 52
False

Tachyglossus aculeatus
Sex chromosomes in dataset: X Y
Autosomes in dataset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
Diploid number of chromosomes in dataset: 56
Diploid number of chromosomes: 64
False

In [49]:
# metadata_df[metadata_df['organism_name'] == 'Ursus arctos']

In [50]:
# metadata_df[metadata_df['organism_name'] == 'Mastomys coucha']

## Merging mammals, human and mouse data

In [51]:
def create_links(source_file, target_file, source_filename, path="/"):
    """
    Create external links from all groups and datasets in source_file to target_file,
    placing them directly in the root of the target file (no prefixes).
    """
    for key in source_file:
        item = source_file[key]
        target_path = f"{path}{key}"
        if isinstance(item, h5py.Group):
            # Create group in the target and recursevely add links of its subgroups
            if key not in target_file:
                grp = target_file.create_group(key)
            else:
                grp = target_file[key]
            create_links(item, grp, source_filename, path=target_path + "/")
        else:
            target_file[key] = h5py.ExternalLink(source_filename, target_path)


for split in ['train', 'valid', 'test']:
    with h5py.File(f'mammals_gender_data/merged_links_{split}.h5', 'w') as merged_file:

        mammals_file = f'mammals_gender_data/{split}.h5'
        with h5py.File(mammals_file, 'r') as f:
            create_links(f, merged_file, source_filename=mammals_file)

        human_file = f'/mnt/20tb/ykuratov/gender_data_v1/{split}.h5'
        with h5py.File(human_file, 'r') as f:
            create_links(f, merged_file, source_filename=human_file)

        mouse_file = f'/mnt/20tb/ykuratov/mouse_gender_data/{split}.h5'
        with h5py.File(mouse_file, 'r') as f:
            create_links(f, merged_file, source_filename=mouse_file)

    print(f"Merged file 'mammals_gender_data/merged_links_{split}.h5' created.")

OSError: Unable to synchronously create file (unable to truncate a file which is already open)

In [12]:
with h5py.File('mammals_gender_data/merged_links_train.h5', 'r') as f:
    print(len(f.keys()))
    print(f.keys())
    print(f['129P2_OlaHsd']['OlaHsd_chr1'][0:10].astype(str))

81
<KeysViewHDF5 ['129P2_OlaHsd', 'A_J', 'BTBR_T+_Itpr3tf_J', 'BUB_BnJ', 'C3H_HeH', 'C57BL_6NJ', 'C58_J', 'CAST_EiJ', 'CBA_J', 'GCF_000001405.40', 'GCF_000001635.27', 'GCF_000247795.1', 'GCF_002201575.2', 'GCF_002263795.3', 'GCF_002776525.5', 'GCF_003339765.1', 'GCF_008632895.1', 'GCF_008728515.1', 'GCF_009762305.2', 'GCF_009829155.1', 'GCF_011064425.1', 'GCF_011762505.1', 'GCF_011762595.1', 'GCF_014441545.1', 'GCF_016772045.2', 'GCF_023065955.2', 'GCF_023091745.1', 'GCF_024542745.1', 'GCF_025265405.1', 'GCF_028885655.2', 'GCF_029289425.2', 'GCF_030435805.1', 'GCF_032452875.1', 'GCF_036323735.1', 'GCF_902655055.1', 'GCF_922984935.1', 'GCF_947179515.1', 'GCF_949987515.1', 'GCF_963455315.1', 'HG00109', 'HG00118', 'HG00243', 'HG00281', 'HG00371', 'HG00589', 'HG01072', 'HG01501', 'HG01529', 'HG01868', 'HG01946', 'HG01993', 'HG02604', 'HG02966', 'HG02984', 'HG03082', 'HG03129', 'HG03342', 'HG03442', 'HG03446', 'HG03649', 'HG04056', 'HG04177', 'HG04219', 'I_LnJ', 'LP_J', 'MOLF_EiJ', 'NA12873', 'NA18602', 'NA18633', 'NA18640', 'NA19026', 'NA19092', 'NA19431', 'NA20504', 'NA20520', 'NA20521', 'NA20533', 'NOD_ShiLtJ', 'NZB_B1NJ', 'WSB_EiJ', 'ZALENDE_EiJ']>
['T' 'T' 'C' 'T' 'G' 'T' 'T' 'T' 'C' 'T']

## Merging metadata

In [13]:
for split in ['train', 'valid', 'test']:
    
    human_metadata_df = pd.read_csv(f'/mnt/20tb/ykuratov/gender_data/{split}.csv', index_col=0)
    mouse_metadata_df = pd.read_csv(f'/mnt/20tb/ykuratov/mouse_gender_data/{split}.csv', index_col=0)

    species = split2organism_name[split]
    mammals_metadata_df = metadata_df[metadata_df['organism_name'].isin(species)]
    mammals_metadata_df = mammals_metadata_df[['organism_name', 'assembly_accession']]
    mammals_metadata_df.rename(columns={'assembly_accession': 'assembly_accession/sample_id'}, inplace=True)
    mammals_metadata_df['sex'] = None
    mammals_metadata_df['diploid'] = False

    human_metadata_df['organism_name'] = 'Homo sapiens'
    human_metadata_df.rename(columns={'sample': 'assembly_accession/sample_id'}, inplace=True)
    human_metadata_df['diploid'] = True
    human_metadata_df['sex'] = human_metadata_df['sex'].map({1: '0', 2: '1'})

    mouse_metadata_df['organism_name'] = 'Mus musculus'
    mouse_metadata_df.rename(columns={'strain_name': 'assembly_accession/sample_id'}, inplace=True)
    mouse_metadata_df.rename(columns={'gender': 'sex'}, inplace=True)
    mouse_metadata_df['sex'] = mouse_metadata_df['sex'].map({'M': 0, 'F': 1})
    mouse_metadata_df['diploid'] = False
    mouse_metadata_df = mouse_metadata_df[['organism_name', 'assembly_accession/sample_id', 'sex', 'diploid']]
    
    all_metadata_df = pd.concat([mammals_metadata_df, human_metadata_df, mouse_metadata_df])
    all_metadata_df.reset_index(drop=True, inplace=True)

    all_metadata_df.to_csv(f'mammals_gender_data/{split}_merged_metadata.csv', index=False)

In [14]:
all_metadata_df

               organism_name assembly_accession/sample_id   sex  diploid
0   Ornithorhynchus anatinus              GCF_004115215.2  None    False
1     Tachyglossus aculeatus              GCF_015852505.1  None    False
2       Sarcophilus harrisii              GCF_902635505.1  None    False
3                Lemur catta              GCF_020740605.2  None    False
4         Nycticebus coucang              GCF_027406575.1  None    False
5         Loxodonta africana              GCF_030014295.1  None    False
6               Equus asinus              GCF_016077325.2  None    False
7                 Sus scrofa              GCF_000003025.6  None    False
8        Camelus dromedarius              GCF_036321535.1  None    False
9          Ochotona princeps              GCF_030435755.1  None    False
10           Lepus europaeus              GCF_033115175.1  None    False
11     Monodelphis domestica              GCF_027887165.1  None    False
12      Choloepus didactylus              GCF_015220235.1  None    False
13      Sciurus carolinensis              GCF_902686445.1  None    False
14     Phyllostomus discolor              GCF_004126475.2  None    False
15        Myotis daubentonii              GCF_963259705.1  None    False
16   Elephas maximus indicus              GCF_024166365.1  None    False
17           Suncus etruscus              GCF_024139225.1  None    False
18       Cynocephalus volans              GCF_027409185.1  None    False
19        Manis pentadactyla              GCF_030020395.1  None    False
20              Homo sapiens                      HG00284     0     True
21              Homo sapiens                      NA20287     1     True
22              Homo sapiens                      HG01809     1     True
23              Homo sapiens                      HG01980     1     True
24              Homo sapiens                      HG04100     0     True
25              Homo sapiens                      NA20279     0     True
26              Homo sapiens                      NA11839     0     True
27              Homo sapiens                      HG02309     1     True
28              Homo sapiens                      HG02861     1     True
29              Homo sapiens                      HG03833     0     True
30              Homo sapiens                      NA12286     0     True
31              Homo sapiens                      NA19121     0     True
32              Homo sapiens                      HG01550     0     True
33              Homo sapiens                      NA20356     0     True
34              Homo sapiens                      HG01678     0     True
35              Homo sapiens                      HG04026     1     True
36              Homo sapiens                      HG02303     1     True
37              Homo sapiens                      HG03086     1     True
38              Homo sapiens                      HG00475     0     True
39              Homo sapiens                      HG04210     0     True
40              Homo sapiens                      HG03162     1     True
41              Homo sapiens                      HG01670     1     True
42              Homo sapiens                      HG01183     1     True
43              Homo sapiens                      HG01878     1     True
44              Mus musculus                    C57BR_cdJ     0    False
45              Mus musculus                       KK_HiJ     0    False
46              Mus musculus                      PWK_PhJ     1    False
47              Mus musculus                      C3H_HeJ     1    False
48              Mus musculus                      SEA_GnJ     0    False
49              Mus musculus                        AKR_J     1    False
50              Mus musculus                       FVB_NJ     1    False
51              Mus musculus                        ST_bJ     0    False
52              Mus musculus                  129S1_SvImJ     1    False
53              Mus musculus                         RF_J     0    False

In [15]:
for split in ['train', 'valid', 'test']:
    metadata_df = pd.read_csv(f'mammals_gender_data/{split}_merged_metadata.csv')
    metadata_assembly_ids = metadata_df['assembly_accession/sample_id'].unique()

    with h5py.File(f'mammals_gender_data/merged_links_{split}.h5', 'r') as f:
        assembly_ids = list(f.keys())

        assert all([assembly_id in assembly_ids for assembly_id in metadata_assembly_ids])
        print(split, len(metadata_assembly_ids))

train 79
valid 30
test 54

## Checking chromosomes names

In [16]:
for split in ['train', 'valid', 'test']:
    with h5py.File(f'mammals_gender_data/merged_links_{split}.h5', 'r') as f:
        for assembly_id in f.keys():
            for chr in list(f[assembly_id].keys()):
                if "Y" in chr:
                   assert ('chromosome Y' in chr) or ('chrY' in chr)

                if "X" in chr:
                   assert ('chromosome X' in chr) or ('chrX' in chr)
            #    chr_name = re.findall(r'chromosome\s+([0-9]{1,2}|[A-Za-z]{1,2})', chr)[0]

## Checking dataset class

In [16]:
from mammals_gender_dataset import MultiSpeciesGenderDataChunkedDataset

for split in ['train']:
    dataset = MultiSpeciesGenderDataChunkedDataset(data_path='mammals_gender_data', split_name=split, max_n_samples=100, chunk_size=10, n_chunks=10, force_sampling_from_y=True)
    for elem in dataset:
        print(elem)

DEBUG:mammals_gender_dataset:Sample organism name: Papio anubis
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_008728515.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_044997.1 chromosome Y ', 'NC_044996.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_044976.1 chromosome 1 ', 'NC_044977.1 chromosome 2 ', 'NC_044978.1 chromosome 3 ', 'NC_044979.1 chromosome 4 ', 'NC_044980.1 chromosome 5 ', 'NC_044981.1 chromosome 6 ', 'NC_044982.1 chromosome 7 ', 'NC_044983.1 chromosome 8 ', 'NC_044984.1 chromosome 9 ', 'NC_044985.1 chromosome 10 ', 'NC_044986.1 chromosome 11 ', 'NC_044987.1 chromosome 12 ', 'NC_044988.1 chromosome 13 ', 'NC_044989.1 chromosome 14 ', 'NC_044990.1 chromosome 15 ', 'NC_044991.1 chromosome 16 ', 'NC_044992.1 chromosome 17 ', 'NC_044993.1 chromosome 18 ', 'NC_044994.1 chromosome 19 ', 'NC_044995.1 chromosome 20 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_044997.1 chromosome Y ': 8309886, 'NC_044996.1 chromosome X ': 142711496, 'NC_044976.1 chromosome 1 ': 436345764, 'NC_044977.1 chromosome 2 ': 387321500, 'NC_044978.1 chromosome 3 ': 369839030, 'NC_044979.1 chromosome 4 ': 364241804, 'NC_044980.1 chromosome 5 ': 347801522, 'NC_044981.1 chromosome 6 ': 334276494, 'NC_044982.1 chromosome 7 ': 323536936, 'NC_044983.1 chromosome 8 ': 280549772, 'NC_044984.1 chromosome 9 ': 255183638, 'NC_044985.1 chromosome 10 ': 252925378, 'NC_044986.1 chromosome 11 ': 251827392, 'NC_044987.1 chromosome 12 ': 246686900, 'NC_044988.1 chromosome 13 ': 213698002, 'NC_044989.1 chromosome 14 ': 213309948, 'NC_044990.1 chromosome 15 ': 183971550, 'NC_044991.1 chromosome 16 ': 182368386, 'NC_044992.1 chromosome 17 ': 149051852, 'NC_044993.1 chromosome 18 ': 145788816, 'NC_044994.1 chromosome 19 ': 144246688, 'NC_044995.1 chromosome 20 ': 100042216}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_044997.1 chromosome Y ': 0.0015578986727190504, 'NC_044996.1 chromosome X ': 0.0267548857108449, 'NC_044976.1 chromosome 1 ': 0.08180406886233818, 'NC_044977.1 chromosome 2 ': 0.07261322848057744, 'NC_044978.1 chromosome 3 ': 0.06933569653743758, 'NC_044979.1 chromosome 4 ': 0.06828635471056914, 'NC_044980.1 chromosome 5 ': 0.06520420731324901, 'NC_044981.1 chromosome 6 ': 0.06266859814006806, 'NC_044982.1 chromosome 7 ': 0.06065519589197594, 'NC_044983.1 chromosome 8 ': 0.052596162863176726, 'NC_044984.1 chromosome 9 ': 0.047840638360119335, 'NC_044985.1 chromosome 10 ': 0.047417270307097366, 'NC_044986.1 chromosome 11 ': 0.04721142501246106, 'NC_044987.1 chromosome 12 ': 0.04624770954585624, 'NC_044988.1 chromosome 13 ': 0.04006310479812996, 'NC_044989.1 chromosome 14 ': 0.03999035424396552, 'NC_044990.1 chromosome 15 ': 0.03449012821151414, 'NC_044991.1 chromosome 16 ': 0.034189574501421016, 'NC_044992.1 chromosome 17 ': 0.02794354608440072, 'NC_044993.1 chromosome 18 ': 0.02733180731284182, 'NC_044994.1 chromosome 19 ': 0.027042696347376965, 'NC_044995.1 chromosome 20 ': 0.01875544809185981}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Bos javanicus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_032452875.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_083897.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_083868.1 chromosome 1 ', 'NC_083869.1 chromosome 2 ', 'NC_083870.1 chromosome 3 ', 'NC_083871.1 chromosome 4 ', 'NC_083872.1 chromosome 5 ', 'NC_083873.1 chromosome 6 ', 'NC_083874.1 chromosome 7 ', 'NC_083875.1 chromosome 8 ', 'NC_083876.1 chromosome 9 ', 'NC_083877.1 chromosome 10 ', 'NC_083878.1 chromosome 11 ', 'NC_083879.1 chromosome 12 ', 'NC_083880.1 chromosome 13 ', 'NC_083881.1 chromosome 14 ', 'NC_083882.1 chromosome 15 ', 'NC_083883.1 chromosome 16 ', 'NC_083884.1 chromosome 17 ', 'NC_083885.1 chromosome 18 ', 'NC_083886.1 chromosome 19 ', 'NC_083887.1 chromosome 20 ', 'NC_083888.1 chromosome 21 ', 'NC_083889.1 chromosome 22 ', 'NC_083890.1 chromosome 23 ', 'NC_083891.1 chromosome 24 ', 'NC_083892.1 chromosome 25 ', 'NC_083893.1 chromosome 26 ', 'NC_083894.1 chromosome 27 ', 'NC_083895.1 chromosome 28 ', 'NC_083896.1 chromosome 29 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_083897.1 chromosome X ': 289614402, 'NC_083868.1 chromosome 1 ': 315079896, 'NC_083869.1 chromosome 2 ': 272587692, 'NC_083870.1 chromosome 3 ': 242213704, 'NC_083871.1 chromosome 4 ': 241174964, 'NC_083872.1 chromosome 5 ': 241365140, 'NC_083873.1 chromosome 6 ': 235909094, 'NC_083874.1 chromosome 7 ': 220434918, 'NC_083875.1 chromosome 8 ': 227311134, 'NC_083876.1 chromosome 9 ': 208316260, 'NC_083877.1 chromosome 10 ': 205664430, 'NC_083878.1 chromosome 11 ': 214037294, 'NC_083879.1 chromosome 12 ': 175098584, 'NC_083880.1 chromosome 13 ': 166853022, 'NC_083881.1 chromosome 14 ': 164560312, 'NC_083882.1 chromosome 15 ': 168946102, 'NC_083883.1 chromosome 16 ': 163440464, 'NC_083884.1 chromosome 17 ': 146750032, 'NC_083885.1 chromosome 18 ': 132675716, 'NC_083886.1 chromosome 19 ': 130085436, 'NC_083887.1 chromosome 20 ': 143142620, 'NC_083888.1 chromosome 21 ': 139484372, 'NC_083889.1 chromosome 22 ': 122030608, 'NC_083890.1 chromosome 23 ': 105840364, 'NC_083891.1 chromosome 24 ': 124459492, 'NC_083892.1 chromosome 25 ': 85127494, 'NC_083893.1 chromosome 26 ': 102967822, 'NC_083894.1 chromosome 27 ': 91091356, 'NC_083895.1 chromosome 28 ': 94834968, 'NC_083896.1 chromosome 29 ': 103161888}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_083897.1 chromosome X ': 0.05491091168478287, 'NC_083868.1 chromosome 1 ': 0.05973917119945773, 'NC_083869.1 chromosome 2 ': 0.05168264623031694, 'NC_083870.1 chromosome 3 ': 0.04592373589621465, 'NC_083871.1 chromosome 4 ': 0.04572679071666018, 'NC_083872.1 chromosome 5 ': 0.04576284810009294, 'NC_083873.1 chromosome 6 ': 0.044728381381638406, 'NC_083874.1 chromosome 7 ': 0.0417944764864986, 'NC_083875.1 chromosome 8 ': 0.04309820754025156, 'NC_083876.1 chromosome 9 ': 0.03949677804822796, 'NC_083877.1 chromosome 10 ': 0.03899399088734271, 'NC_083878.1 chromosome 11 ': 0.04058148651075683, 'NC_083879.1 chromosome 12 ': 0.033198704262485314, 'NC_083880.1 chromosome 13 ': 0.031635345107530716, 'NC_083881.1 chromosome 14 ': 0.031200647124766657, 'NC_083882.1 chromosome 15 ': 0.032032193227774355, 'NC_083883.1 chromosome 16 ': 0.03098832386251266, 'NC_083884.1 chromosome 17 ': 0.027823816741306465, 'NC_083885.1 chromosome 18 ': 0.025155325403987794, 'NC_083886.1 chromosome 19 ': 0.024664208127579492, 'NC_083887.1 chromosome 20 ': 0.02713985116371538, 'NC_083888.1 chromosome 21 ': 0.02644624707682666, 'NC_083889.1 chromosome 22 ': 0.023137012152898245, 'NC_083890.1 chromosome 23 ': 0.02006734071287405, 'NC_083891.1 chromosome 24 ': 0.023597528735967144, 'NC_083892.1 chromosome 25 ': 0.01614017905428917, 'NC_083893.1 chromosome 26 ': 0.019522706540734954, 'NC_083894.1 chromosome 27 ': 0.017270927723280545, 'NC_083895.1 chromosome 28 ': 0.01798071683077836, 'NC_083896.1 chromosome 29 ': 0.019559501468450667}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Rattus rattus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011064425.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_046173.1 chromosome Y ', 'NC_046172.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_046154.1 chromosome 1 ', 'NC_046155.1 chromosome 2 ', 'NC_046156.1 chromosome 3 ', 'NC_046157.1 chromosome 4 ', 'NC_046158.1 chromosome 5 ', 'NC_046159.1 chromosome 6 ', 'NC_046160.1 chromosome 7 ', 'NC_046161.1 chromosome 8 ', 'NC_046162.1 chromosome 9 ', 'NC_046163.1 chromosome 10 ', 'NC_046164.1 chromosome 11 ', 'NC_046165.1 chromosome 12 ', 'NC_046166.1 chromosome 13 ', 'NC_046167.1 chromosome 14 ', 'NC_046168.1 chromosome 15 ', 'NC_046169.1 chromosome 16 ', 'NC_046170.1 chromosome 17 ', 'NC_046171.1 chromosome 18 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_046173.1 chromosome Y ': 2293298, 'NC_046172.1 chromosome X ': 130373513, 'NC_046154.1 chromosome 1 ': 545899780, 'NC_046155.1 chromosome 2 ': 460490430, 'NC_046156.1 chromosome 3 ': 446780580, 'NC_046157.1 chromosome 4 ': 365650368, 'NC_046158.1 chromosome 5 ': 317649504, 'NC_046159.1 chromosome 6 ': 319153832, 'NC_046160.1 chromosome 7 ': 261677498, 'NC_046161.1 chromosome 8 ': 230657978, 'NC_046162.1 chromosome 9 ': 193419404, 'NC_046163.1 chromosome 10 ': 189950930, 'NC_046164.1 chromosome 11 ': 197229706, 'NC_046165.1 chromosome 12 ': 188176076, 'NC_046166.1 chromosome 13 ': 157637022, 'NC_046167.1 chromosome 14 ': 163988198, 'NC_046168.1 chromosome 15 ': 158636486, 'NC_046169.1 chromosome 16 ': 88862024, 'NC_046170.1 chromosome 17 ': 97008248, 'NC_046171.1 chromosome 18 ': 99693070}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_046173.1 chromosome Y ': 0.0004968981006635848, 'NC_046172.1 chromosome X ': 0.02824855338754021, 'NC_046154.1 chromosome 1 ': 0.11828230078893752, 'NC_046155.1 chromosome 2 ': 0.09977631343190352, 'NC_046156.1 chromosome 3 ': 0.09680574509521869, 'NC_046157.1 chromosome 4 ': 0.07922693577814172, 'NC_046158.1 chromosome 5 ': 0.06882639552920283, 'NC_046159.1 chromosome 6 ': 0.0691523443269496, 'NC_046160.1 chromosome 7 ': 0.05669871588541874, 'NC_046161.1 chromosome 8 ': 0.04997759173517918, 'NC_046162.1 chromosome 9 ': 0.04190896014346265, 'NC_046163.1 chromosome 10 ': 0.041157431932649646, 'NC_046164.1 chromosome 11 ': 0.042734553601772314, 'NC_046165.1 chromosome 12 ': 0.040772867178502925, 'NC_046166.1 chromosome 13 ': 0.034155847528783326, 'NC_046167.1 chromosome 14 ': 0.03553198237535806, 'NC_046168.1 chromosome 15 ': 0.03437240541322819, 'NC_046169.1 chromosome 16 ': 0.01925409211830381, 'NC_046170.1 chromosome 17 ': 0.021019167234219892, 'NC_046171.1 chromosome 18 ': 0.021600898414563575}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Canis lupus familiaris
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_014441545.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_051844.1 chromosome Y ', 'NW_024010443.1 chromosome Y unlocalized genomic scaffold', 'NW_024010444.1 chromosome Y unlocalized genomic scaffold', 'NC_051843.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_051805.1 chromosome 1 ', 'NC_051806.1 chromosome 2 ', 'NC_051807.1 chromosome 3 ', 'NC_051808.1 chromosome 4 ', 'NC_051809.1 chromosome 5 ', 'NC_051810.1 chromosome 6 ', 'NC_051811.1 chromosome 7 ', 'NC_051812.1 chromosome 8 ', 'NC_051813.1 chromosome 9 ', 'NC_051814.1 chromosome 10 ', 'NC_051815.1 chromosome 11 ', 'NC_051816.1 chromosome 12 ', 'NC_051817.1 chromosome 13 ', 'NC_051818.1 chromosome 14 ', 'NC_051819.1 chromosome 15 ', 'NC_051820.1 chromosome 16 ', 'NC_051821.1 chromosome 17 ', 'NC_051822.1 chromosome 18 ', 'NC_051823.1 chromosome 19 ', 'NC_051824.1 chromosome 20 ', 'NC_051825.1 chromosome 21 ', 'NC_051826.1 chromosome 22 ', 'NC_051827.1 chromosome 23 ', 'NC_051828.1 chromosome 24 ', 'NC_051829.1 chromosome 25 ', 'NC_051830.1 chromosome 26 ', 'NC_051831.1 chromosome 27 ', 'NC_051832.1 chromosome 28 ', 'NC_051833.1 chromosome 29 ', 'NC_051834.1 chromosome 30 ', 'NC_051835.1 chromosome 31 ', 'NC_051836.1 chromosome 32 ', 'NC_051837.1 chromosome 33 ', 'NC_051838.1 chromosome 34 ', 'NC_051839.1 chromosome 35 ', 'NC_051840.1 chromosome 36 ', 'NC_051841.1 chromosome 37 ', 'NC_051842.1 chromosome 38 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_051844.1 chromosome Y ': 3937623, 'NW_024010443.1 chromosome Y unlocalized genomic scaffold': 1569522, 'NW_024010444.1 chromosome Y unlocalized genomic scaffold': 1221461, 'NC_051843.1 chromosome X ': 127069619, 'NC_051805.1 chromosome 1 ': 246627878, 'NC_051806.1 chromosome 2 ': 172375622, 'NC_051807.1 chromosome 3 ': 185740474, 'NC_051808.1 chromosome 4 ': 178015330, 'NC_051809.1 chromosome 5 ': 179146810, 'NC_051810.1 chromosome 6 ': 156536352, 'NC_051811.1 chromosome 7 ': 162078904, 'NC_051812.1 chromosome 8 ': 150521048, 'NC_051813.1 chromosome 9 ': 124004586, 'NC_051814.1 chromosome 10 ': 140722000, 'NC_051815.1 chromosome 11 ': 151082694, 'NC_051816.1 chromosome 12 ': 146994588, 'NC_051817.1 chromosome 13 ': 128074554, 'NC_051818.1 chromosome 14 ': 122086128, 'NC_051819.1 chromosome 15 ': 130401200, 'NC_051820.1 chromosome 16 ': 124042426, 'NC_051821.1 chromosome 17 ': 130943096, 'NC_051822.1 chromosome 18 ': 113766814, 'NC_051823.1 chromosome 19 ': 110530482, 'NC_051824.1 chromosome 20 ': 117792922, 'NC_051825.1 chromosome 21 ': 104281432, 'NC_051826.1 chromosome 22 ': 124213958, 'NC_051827.1 chromosome 23 ': 106565846, 'NC_051828.1 chromosome 24 ': 97677994, 'NC_051829.1 chromosome 25 ': 103882002, 'NC_051830.1 chromosome 26 ': 81348702, 'NC_051831.1 chromosome 27 ': 92497604, 'NC_051832.1 chromosome 28 ': 83724424, 'NC_051833.1 chromosome 29 ': 84099704, 'NC_051834.1 chromosome 30 ': 80829806, 'NC_051835.1 chromosome 31 ': 79037866, 'NC_051836.1 chromosome 32 ': 78047464, 'NC_051837.1 chromosome 33 ': 63298168, 'NC_051838.1 chromosome 34 ': 84527742, 'NC_051839.1 chromosome 35 ': 53884536, 'NC_051840.1 chromosome 36 ': 62130370, 'NC_051841.1 chromosome 37 ': 61864816, 'NC_051842.1 chromosome 38 ': 48204096}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_051844.1 chromosome Y ': 0.0008568621111599954, 'NW_024010443.1 chromosome Y unlocalized genomic scaffold': 0.00034154207612868427, 'NW_024010444.1 chromosome Y unlocalized genomic scaffold': 0.0002658008781337368, 'NC_051843.1 chromosome X ': 0.02765148974410101, 'NC_051805.1 chromosome 1 ': 0.05366844012593125, 'NC_051806.1 chromosome 2 ': 0.03751048268954071, 'NC_051807.1 chromosome 3 ': 0.04041879445530926, 'NC_051808.1 chromosome 4 ': 0.038737733775590824, 'NC_051809.1 chromosome 5 ': 0.03898395398040355, 'NC_051810.1 chromosome 6 ': 0.034063715355178534, 'NC_051811.1 chromosome 7 ': 0.03526982442350073, 'NC_051812.1 chromosome 8 ': 0.03275473120796354, 'NC_051813.1 chromosome 9 ': 0.02698451104980878, 'NC_051814.1 chromosome 10 ': 0.030622370401294605, 'NC_051815.1 chromosome 11 ': 0.03287695041921981, 'NC_051816.1 chromosome 12 ': 0.031987341856438194, 'NC_051817.1 chromosome 13 ': 0.02787017262097332, 'NC_051818.1 chromosome 14 ': 0.02656703736783065, 'NC_051819.1 chromosome 15 ': 0.0283764716758808, 'NC_051820.1 chromosome 16 ': 0.0269927453734823, 'NC_051821.1 chromosome 17 ': 0.02849439310984976, 'NC_051822.1 chromosome 18 ': 0.024756679962501874, 'NC_051823.1 chromosome 19 ': 0.02405242506813168, 'NC_051824.1 chromosome 20 ': 0.025632797203953925, 'NC_051825.1 chromosome 21 ': 0.022692575693078667, 'NC_051826.1 chromosome 22 ': 0.027030072276451808, 'NC_051827.1 chromosome 23 ': 0.02318968468568752, 'NC_051828.1 chromosome 24 ': 0.02125560830803593, 'NC_051829.1 chromosome 25 ': 0.022605656139566145, 'NC_051830.1 chromosome 26 ': 0.017702207787755542, 'NC_051831.1 chromosome 27 ': 0.020128308941887333, 'NC_051832.1 chromosome 28 ': 0.018219186220797313, 'NC_051833.1 chromosome 29 ': 0.0183008505175256, 'NC_051834.1 chromosome 30 ': 0.01758929136024776, 'NC_051835.1 chromosome 31 ': 0.017199349130767677, 'NC_051836.1 chromosome 32 ': 0.016983828765151903, 'NC_051837.1 chromosome 33 ': 0.013774249557420825, 'NC_051838.1 chromosome 34 ': 0.01839399542863992, 'NC_051839.1 chromosome 35 ': 0.011725758732066724, 'NC_051840.1 chromosome 36 ': 0.013520126229796921, 'NC_051841.1 chromosome 37 ': 0.013462339295632075, 'NC_051842.1 chromosome 38 ': 0.01048964399718284}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0

DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Mesoplodon densirostris
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_025265405.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_082681.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_082661.1 chromosome 1 ', 'NC_082662.1 chromosome 2 ', 'NC_082663.1 chromosome 3 ', 'NC_082664.1 chromosome 4 ', 'NC_082665.1 chromosome 5 ', 'NC_082666.1 chromosome 6 ', 'NC_082667.1 chromosome 7 ', 'NC_082668.1 chromosome 8 ', 'NC_082669.1 chromosome 9 ', 'NC_082670.1 chromosome 10 ', 'NC_082671.1 chromosome 11 ', 'NC_082672.1 chromosome 12 ', 'NC_082673.1 chromosome 13 ', 'NC_082674.1 chromosome 14 ', 'NC_082675.1 chromosome 15 ', 'NC_082676.1 chromosome 16 ', 'NC_082677.1 chromosome 17 ', 'NC_082678.1 chromosome 18 ', 'NC_082679.1 chromosome 19 ', 'NC_082680.1 chromosome 20 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_082681.1 chromosome X ': 284260750, 'NC_082661.1 chromosome 1 ': 494568720, 'NC_082662.1 chromosome 2 ': 386830698, 'NC_082663.1 chromosome 3 ': 370973532, 'NC_082664.1 chromosome 4 ': 369816576, 'NC_082665.1 chromosome 5 ': 311038254, 'NC_082666.1 chromosome 6 ': 273731452, 'NC_082667.1 chromosome 7 ': 251611380, 'NC_082668.1 chromosome 8 ': 234670390, 'NC_082669.1 chromosome 9 ': 228226422, 'NC_082670.1 chromosome 10 ': 222585620, 'NC_082671.1 chromosome 11 ': 212261872, 'NC_082672.1 chromosome 12 ': 209401840, 'NC_082673.1 chromosome 13 ': 186724664, 'NC_082674.1 chromosome 14 ': 183971348, 'NC_082675.1 chromosome 15 ': 182393564, 'NC_082676.1 chromosome 16 ': 177466300, 'NC_082677.1 chromosome 17 ': 157194532, 'NC_082678.1 chromosome 18 ': 134099418, 'NC_082679.1 chromosome 19 ': 133134426, 'NC_082680.1 chromosome 20 ': 90065488}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_082681.1 chromosome X ': 0.055791801746137314, 'NC_082661.1 chromosome 1 ': 0.0970689058411367, 'NC_082662.1 chromosome 2 ': 0.07592318535758424, 'NC_082663.1 chromosome 3 ': 0.0728109024914918, 'NC_082664.1 chromosome 4 ': 0.07258382696389608, 'NC_082665.1 chromosome 5 ': 0.061047417213360274, 'NC_082666.1 chromosome 6 ': 0.053725218489243776, 'NC_082667.1 chromosome 7 ': 0.04938371628876663, 'NC_082668.1 chromosome 8 ': 0.046058711498399706, 'NC_082669.1 chromosome 9 ': 0.04479395516072575, 'NC_082670.1 chromosome 10 ': 0.04368683605661723, 'NC_082671.1 chromosome 11 ': 0.04166059605797837, 'NC_082672.1 chromosome 12 ': 0.0410992581373136, 'NC_082673.1 chromosome 13 ': 0.03664841324383371, 'NC_082674.1 chromosome 14 ': 0.036108020451594655, 'NC_082675.1 chromosome 15 ': 0.03579834909483426, 'NC_082676.1 chromosome 16 ': 0.034831275954279754, 'NC_082677.1 chromosome 17 ': 0.03085254001799699, 'NC_082678.1 chromosome 18 ': 0.02631966651508658, 'NC_082679.1 chromosome 19 ': 0.026130267724185592, 'NC_082680.1 chromosome 20 ': 0.017677135695536965}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Papio anubis
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_008728515.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_044996.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_044976.1 chromosome 1 ', 'NC_044977.1 chromosome 2 ', 'NC_044978.1 chromosome 3 ', 'NC_044979.1 chromosome 4 ', 'NC_044980.1 chromosome 5 ', 'NC_044981.1 chromosome 6 ', 'NC_044982.1 chromosome 7 ', 'NC_044983.1 chromosome 8 ', 'NC_044984.1 chromosome 9 ', 'NC_044985.1 chromosome 10 ', 'NC_044986.1 chromosome 11 ', 'NC_044987.1 chromosome 12 ', 'NC_044988.1 chromosome 13 ', 'NC_044989.1 chromosome 14 ', 'NC_044990.1 chromosome 15 ', 'NC_044991.1 chromosome 16 ', 'NC_044992.1 chromosome 17 ', 'NC_044993.1 chromosome 18 ', 'NC_044994.1 chromosome 19 ', 'NC_044995.1 chromosome 20 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_044996.1 chromosome X ': 285422992, 'NC_044976.1 chromosome 1 ': 436345764, 'NC_044977.1 chromosome 2 ': 387321500, 'NC_044978.1 chromosome 3 ': 369839030, 'NC_044979.1 chromosome 4 ': 364241804, 'NC_044980.1 chromosome 5 ': 347801522, 'NC_044981.1 chromosome 6 ': 334276494, 'NC_044982.1 chromosome 7 ': 323536936, 'NC_044983.1 chromosome 8 ': 280549772, 'NC_044984.1 chromosome 9 ': 255183638, 'NC_044985.1 chromosome 10 ': 252925378, 'NC_044986.1 chromosome 11 ': 251827392, 'NC_044987.1 chromosome 12 ': 246686900, 'NC_044988.1 chromosome 13 ': 213698002, 'NC_044989.1 chromosome 14 ': 213309948, 'NC_044990.1 chromosome 15 ': 183971550, 'NC_044991.1 chromosome 16 ': 182368386, 'NC_044992.1 chromosome 17 ': 149051852, 'NC_044993.1 chromosome 18 ': 145788816, 'NC_044994.1 chromosome 19 ': 144246688, 'NC_044995.1 chromosome 20 ': 100042216}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_044996.1 chromosome X ': 0.05219462415343583, 'NC_044976.1 chromosome 1 ': 0.07979351275570613, 'NC_044977.1 chromosome 2 ': 0.07082856211893747, 'NC_044978.1 chromosome 3 ': 0.06763158438238667, 'NC_044979.1 chromosome 4 ': 0.06660803296725808, 'NC_044980.1 chromosome 5 ': 0.06360163767319398, 'NC_044981.1 chromosome 6 ': 0.061128347949131745, 'NC_044982.1 chromosome 7 ': 0.05916443050346211, 'NC_044983.1 chromosome 8 ': 0.05130346999470917, 'NC_044984.1 chromosome 9 ': 0.0466648253603775, 'NC_044985.1 chromosome 10 ': 0.04625186272161174, 'NC_044986.1 chromosome 11 ': 0.04605107663148578, 'NC_044987.1 chromosome 12 ': 0.04511104707737143, 'NC_044988.1 chromosome 13 ': 0.03907844570815156, 'NC_044989.1 chromosome 14 ': 0.03900748319549863, 'NC_044990.1 chromosome 15 ': 0.033642440084767335, 'NC_044991.1 chromosome 16 ': 0.03334927329448886, 'NC_044992.1 chromosome 17 ': 0.02725675790867451, 'NC_044993.1 chromosome 18 ': 0.026660054270941185, 'NC_044994.1 chromosome 19 ': 0.026378048988912293, 'NC_044995.1 chromosome 20 ': 0.018294482259498014}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002

{'labels': 0, 'species': 'Papio anubis', 'sampled_chromosomes': ['NC_044978.1 chromosome 3 ', 'NC_044984.1 chromosome 9 ', 'NC_044983.1 chromosome 8 ', 'NC_044991.1 chromosome 16 ', 'NC_044983.1 chromosome 8 ', 'NC_044976.1 chromosome 1 ', 'NC_044976.1 chromosome 1 ', 'NC_044997.1 chromosome Y ', 'NC_044991.1 chromosome 16 ', 'NC_044993.1 chromosome 18 '], 'chunks': ['AGGAAGGAAG', 'CTACTAGAAT', 'AATAGACAGA', 'GATACTCCTA', 'TATTTTGTCA', 'TAAAACAAAC', 'AAGGAACAGT', 'CCATTTTGCT', 'TCCAGCCTGT', 'AATATAGCAT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Bos javanicus', 'sampled_chromosomes': ['NC_083868.1 chromosome 1 ', 'NC_083875.1 chromosome 8 ', 'NC_083872.1 chromosome 5 ', 'NC_083870.1 chromosome 3 ', 'NC_083894.1 chromosome 27 ', 'NC_083868.1 chromosome 1 ', 'NC_083896.1 chromosome 29 ', 'NC_083872.1 chromosome 5 ', 'NC_083883.1 chromosome 16 ', 'NC_083879.1 chromosome 12 '], 'chunks': ['GGATAAAAAA', 'GCCTGCCATG', 'CGATGCTTCT', 'AAAGTACAGA', 'AAACTATTTC', 'CAAGCATTTG', 'GCTTGCTAGT', 'ACAATTCTAC', 'TCGAATCTGC', 'CCCCTCCCCG'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Rattus rattus', 'sampled_chromosomes': ['NC_046168.1 chromosome 15 ', 'NC_046165.1 chromosome 12 ', 'NC_046164.1 chromosome 11 ', 'NC_046168.1 chromosome 15 ', 'NC_046159.1 chromosome 6 ', 'NC_046173.1 chromosome Y ', 'NC_046157.1 chromosome 4 ', 'NC_046159.1 chromosome 6 ', 'NC_046162.1 chromosome 9 ', 'NC_046157.1 chromosome 4 '], 'chunks': ['CCCTCCTAAA', 'AGCAGAGTTG', 'ATCTTAAATT', 'AAATCTTGTC', 'ATTGATAAAT', 'TTAATCTGAA', 'AAAATATAAT', 'TCACAGATTC', 'TTTATAAAGG', 'TGATTTCCTG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Canis lupus familiaris', 'sampled_chromosomes': ['NC_051819.1 chromosome 15 ', 'NC_051809.1 chromosome 5 ', 'NC_051819.1 chromosome 15 ', 'NC_051816.1 chromosome 12 ', 'NC_051831.1 chromosome 27 ', 'NC_051839.1 chromosome 35 ', 'NC_051812.1 chromosome 8 ', 'NC_051844.1 chromosome Y ', 'NC_051833.1 chromosome 29 ', 'NC_051816.1 chromosome 12 '], 'chunks': ['AGAACAATTA', 'ATACATTAAA', 'TTTAATAATC', 'TAACTTCAAA', 'AGTCCTCATA', 'GACACCTCTT', 'CAAGCTGTGC', 'CATTGAATCG', 'TTAGTACAGT', 'GAGAAGGTAG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Mesoplodon densirostris', 'sampled_chromosomes': ['NC_082671.1 chromosome 11 ', 'NC_082674.1 chromosome 14 ', 'NC_082681.1 chromosome X ', 'NC_082664.1 chromosome 4 ', 'NC_082664.1 chromosome 4 ', 'NC_082661.1 chromosome 1 ', 'NC_082678.1 chromosome 18 ', 'NC_082673.1 chromosome 13 ', 'NC_082673.1 chromosome 13 ', 'NC_082669.1 chromosome 9 '], 'chunks': ['TTCCTGCAGG', 'GCCCAGGATT', 'TCGGGCTCTA', 'TAACTACTGA', 'TTCTGAGAAT', 'CAATAAAGTA', 'GGAAGATCCC', 'CATTCGTGGA', 'AAGAACTGCA', 'AGTGTTCTCC'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}

DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Budorcas taxicolor
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_023091745.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_068935.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_068910.1 chromosome 1 ', 'NC_068911.1 chromosome 2 ', 'NC_068912.1 chromosome 3 ', 'NC_068913.1 chromosome 4 ', 'NC_068914.1 chromosome 5 ', 'NC_068915.1 chromosome 6 ', 'NC_068916.1 chromosome 7 ', 'NC_068917.1 chromosome 8 ', 'NC_068918.1 chromosome 9 ', 'NC_068919.1 chromosome 10 ', 'NC_068920.1 chromosome 11 ', 'NC_068921.1 chromosome 12 ', 'NC_068922.1 chromosome 13 ', 'NC_068923.1 chromosome 14 ', 'NC_068924.1 chromosome 15 ', 'NC_068925.1 chromosome 16 ', 'NC_068926.1 chromosome 17 ', 'NC_068927.1 chromosome 18 ', 'NC_068928.1 chromosome 19 ', 'NC_068929.1 chromosome 20 ', 'NC_068930.1 chromosome 21 ', 'NC_068931.1 chromosome 22 ', 'NC_068932.1 chromosome 23 ', 'NC_068933.1 chromosome 24 ', 'NC_068934.1 chromosome 25 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_068935.1 chromosome X ': 293495872, 'NC_068910.1 chromosome 1 ': 443363910, 'NC_068911.1 chromosome 2 ': 361581120, 'NC_068912.1 chromosome 3 ': 242514874, 'NC_068913.1 chromosome 4 ': 243786826, 'NC_068914.1 chromosome 5 ': 328459970, 'NC_068915.1 chromosome 6 ': 234941170, 'NC_068916.1 chromosome 7 ': 219495396, 'NC_068917.1 chromosome 8 ': 232665740, 'NC_068918.1 chromosome 9 ': 190522314, 'NC_068919.1 chromosome 10 ': 202531878, 'NC_068920.1 chromosome 11 ': 332203558, 'NC_068921.1 chromosome 12 ': 174640522, 'NC_068922.1 chromosome 13 ': 166773768, 'NC_068923.1 chromosome 14 ': 190390618, 'NC_068924.1 chromosome 15 ': 163768502, 'NC_068925.1 chromosome 16 ': 163692860, 'NC_068926.1 chromosome 17 ': 146250216, 'NC_068927.1 chromosome 18 ': 136107162, 'NC_068928.1 chromosome 19 ': 125218408, 'NC_068929.1 chromosome 20 ': 149592478, 'NC_068930.1 chromosome 21 ': 148734572, 'NC_068931.1 chromosome 22 ': 125252580, 'NC_068932.1 chromosome 23 ': 102628326, 'NC_068933.1 chromosome 24 ': 89805930, 'NC_068934.1 chromosome 25 ': 104042192}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_068935.1 chromosome X ': 0.05524668983898652, 'NC_068910.1 chromosome 1 ': 0.08345735241404123, 'NC_068911.1 chromosome 2 ': 0.06806283118105785, 'NC_068912.1 chromosome 3 ': 0.04565019580656622, 'NC_068913.1 chromosome 4 ': 0.04588962383379953, 'NC_068914.1 chromosome 5 ': 0.06182821572057006, 'NC_068915.1 chromosome 6 ': 0.044224546876756775, 'NC_068916.1 chromosome 7 ': 0.04131708559055142, 'NC_068917.1 chromosome 8 ': 0.04379622747790565, 'NC_068918.1 chromosome 9 ': 0.03586328869717118, 'NC_068919.1 chromosome 10 ': 0.038123929205973496, 'NC_068920.1 chromosome 11 ': 0.06253289631355963, 'NC_068921.1 chromosome 12 ': 0.0328737528282943, 'NC_068922.1 chromosome 13 ': 0.03139294113811283, 'NC_068923.1 chromosome 14 ': 0.03583849867877857, 'NC_068924.1 chromosome 15 ': 0.03082723983044451, 'NC_068925.1 chromosome 16 ': 0.030813001231160906, 'NC_068926.1 chromosome 17 ': 0.027529655756919076, 'NC_068927.1 chromosome 18 ': 0.025620360901971024, 'NC_068928.1 chromosome 19 ': 0.023570697951443995, 'NC_068929.1 chromosome 20 ': 0.028158792074293348, 'NC_068930.1 chromosome 21 ': 0.027997302693301286, 'NC_068931.1 chromosome 22 ': 0.023577130375424315, 'NC_068932.1 chromosome 23 ': 0.019318415814776422, 'NC_068933.1 chromosome 24 ': 0.016904770505296016, 'NC_068934.1 chromosome 25 ': 0.019584557262843836}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Mustela erminea
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_009829155.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_045636.1 chromosome Y ', 'NC_045635.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_045614.1 chromosome 1 ', 'NC_045615.1 chromosome 2 ', 'NC_045616.1 chromosome 3 ', 'NC_045617.1 chromosome 4 ', 'NC_045618.1 chromosome 5 ', 'NC_045619.1 chromosome 6 ', 'NC_045620.1 chromosome 7 ', 'NC_045621.1 chromosome 8 ', 'NC_045622.1 chromosome 9 ', 'NC_045623.1 chromosome 10 ', 'NC_045624.1 chromosome 11 ', 'NC_045625.1 chromosome 12 ', 'NC_045626.1 chromosome 13 ', 'NC_045627.1 chromosome 14 ', 'NC_045628.1 chromosome 15 ', 'NC_045629.1 chromosome 16 ', 'NC_045630.1 chromosome 17 ', 'NC_045631.1 chromosome 18 ', 'NC_045632.1 chromosome 19 ', 'NC_045633.1 chromosome 20 ', 'NC_045634.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_045636.1 chromosome Y ': 5451993, 'NC_045635.1 chromosome X ': 130149454, 'NC_045614.1 chromosome 1 ': 440707378, 'NC_045615.1 chromosome 2 ': 331357966, 'NC_045616.1 chromosome 3 ': 328770848, 'NC_045617.1 chromosome 4 ': 302680028, 'NC_045618.1 chromosome 5 ': 296174906, 'NC_045619.1 chromosome 6 ': 290223092, 'NC_045620.1 chromosome 7 ': 282916320, 'NC_045621.1 chromosome 8 ': 229450082, 'NC_045622.1 chromosome 9 ': 228192686, 'NC_045623.1 chromosome 10 ': 219496374, 'NC_045624.1 chromosome 11 ': 213757318, 'NC_045625.1 chromosome 12 ': 187231206, 'NC_045626.1 chromosome 13 ': 185798618, 'NC_045627.1 chromosome 14 ': 184280032, 'NC_045628.1 chromosome 15 ': 172274730, 'NC_045629.1 chromosome 16 ': 170932264, 'NC_045630.1 chromosome 17 ': 141640406, 'NC_045631.1 chromosome 18 ': 123844424, 'NC_045632.1 chromosome 19 ': 121449576, 'NC_045633.1 chromosome 20 ': 80416618, 'NC_045634.1 chromosome 21 ': 80414020}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_045636.1 chromosome Y ': 0.0011483657273247, 'NC_045635.1 chromosome X ': 0.02741367650391748, 'NC_045614.1 chromosome 1 ': 0.09282720074554965, 'NC_045615.1 chromosome 2 ': 0.0697946845548817, 'NC_045616.1 chromosome 3 ': 0.0692497539866024, 'NC_045617.1 chromosome 4 ': 0.06375418502937927, 'NC_045618.1 chromosome 5 ': 0.06238399633748881, 'NC_045619.1 chromosome 6 ': 0.061130352172316306, 'NC_045620.1 chromosome 7 ': 0.0595913101115184, 'NC_045621.1 chromosome 8 ': 0.04832959438881195, 'NC_045622.1 chromosome 9 ': 0.04806474619988816, 'NC_045623.1 chromosome 10 ': 0.04623302215788691, 'NC_045624.1 chromosome 11 ': 0.045024191695779356, 'NC_045625.1 chromosome 12 ': 0.03943693619123698, 'NC_045626.1 chromosome 13 ': 0.03913518691155584, 'NC_045627.1 chromosome 14 ': 0.03881532367688274, 'NC_045628.1 chromosome 15 ': 0.03628661951989232, 'NC_045629.1 chromosome 16 ': 0.03600385284273432, 'NC_045630.1 chromosome 17 ': 0.029834041946634155, 'NC_045631.1 chromosome 18 ': 0.02608563364660749, 'NC_045632.1 chromosome 19 ': 0.02558120134719843, 'NC_045633.1 chromosome 20 ': 0.016938335764290702, 'NC_045634.1 chromosome 21 ': 0.01693778854162193}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Bos javanicus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_032452875.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_083898.1 chromosome Y ', 'NC_083897.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_083868.1 chromosome 1 ', 'NC_083869.1 chromosome 2 ', 'NC_083870.1 chromosome 3 ', 'NC_083871.1 chromosome 4 ', 'NC_083872.1 chromosome 5 ', 'NC_083873.1 chromosome 6 ', 'NC_083874.1 chromosome 7 ', 'NC_083875.1 chromosome 8 ', 'NC_083876.1 chromosome 9 ', 'NC_083877.1 chromosome 10 ', 'NC_083878.1 chromosome 11 ', 'NC_083879.1 chromosome 12 ', 'NC_083880.1 chromosome 13 ', 'NC_083881.1 chromosome 14 ', 'NC_083882.1 chromosome 15 ', 'NC_083883.1 chromosome 16 ', 'NC_083884.1 chromosome 17 ', 'NC_083885.1 chromosome 18 ', 'NC_083886.1 chromosome 19 ', 'NC_083887.1 chromosome 20 ', 'NC_083888.1 chromosome 21 ', 'NC_083889.1 chromosome 22 ', 'NC_083890.1 chromosome 23 ', 'NC_083891.1 chromosome 24 ', 'NC_083892.1 chromosome 25 ', 'NC_083893.1 chromosome 26 ', 'NC_083894.1 chromosome 27 ', 'NC_083895.1 chromosome 28 ', 'NC_083896.1 chromosome 29 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_083898.1 chromosome Y ': 6354378, 'NC_083897.1 chromosome X ': 144807201, 'NC_083868.1 chromosome 1 ': 315079896, 'NC_083869.1 chromosome 2 ': 272587692, 'NC_083870.1 chromosome 3 ': 242213704, 'NC_083871.1 chromosome 4 ': 241174964, 'NC_083872.1 chromosome 5 ': 241365140, 'NC_083873.1 chromosome 6 ': 235909094, 'NC_083874.1 chromosome 7 ': 220434918, 'NC_083875.1 chromosome 8 ': 227311134, 'NC_083876.1 chromosome 9 ': 208316260, 'NC_083877.1 chromosome 10 ': 205664430, 'NC_083878.1 chromosome 11 ': 214037294, 'NC_083879.1 chromosome 12 ': 175098584, 'NC_083880.1 chromosome 13 ': 166853022, 'NC_083881.1 chromosome 14 ': 164560312, 'NC_083882.1 chromosome 15 ': 168946102, 'NC_083883.1 chromosome 16 ': 163440464, 'NC_083884.1 chromosome 17 ': 146750032, 'NC_083885.1 chromosome 18 ': 132675716, 'NC_083886.1 chromosome 19 ': 130085436, 'NC_083887.1 chromosome 20 ': 143142620, 'NC_083888.1 chromosome 21 ': 139484372, 'NC_083889.1 chromosome 22 ': 122030608, 'NC_083890.1 chromosome 23 ': 105840364, 'NC_083891.1 chromosome 24 ': 124459492, 'NC_083892.1 chromosome 25 ': 85127494, 'NC_083893.1 chromosome 26 ': 102967822, 'NC_083894.1 chromosome 27 ': 91091356, 'NC_083895.1 chromosome 28 ': 94834968, 'NC_083896.1 chromosome 29 ': 103161888}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_083898.1 chromosome Y ': 0.001237269683353859, 'NC_083897.1 chromosome X ': 0.028195609346599877, 'NC_083868.1 chromosome 1 ': 0.06134964006785351, 'NC_083869.1 chromosome 2 ': 0.053075924562089205, 'NC_083870.1 chromosome 3 ': 0.04716176356711001, 'NC_083871.1 chromosome 4 ': 0.046959509072510064, 'NC_083872.1 chromosome 5 ': 0.04699653850313278, 'NC_083873.1 chromosome 6 ': 0.045934184279511826, 'NC_083874.1 chromosome 7 ': 0.04292118617966918, 'NC_083875.1 chromosome 8 ': 0.04426006365799873, 'NC_083876.1 chromosome 9 ': 0.040561545606455925, 'NC_083877.1 chromosome 10 ': 0.04004520413850922, 'NC_083878.1 chromosome 11 ': 0.041675496008153255, 'NC_083879.1 chromosome 12 ': 0.034093686208373046, 'NC_083880.1 chromosome 13 ': 0.03248818148630354, 'NC_083881.1 chromosome 14 ': 0.0320417647676692, 'NC_083882.1 chromosome 15 ': 0.03289572797296742, 'NC_083883.1 chromosome 16 ': 0.03182371762279295, 'NC_083884.1 chromosome 17 ': 0.028573900643746514, 'NC_083885.1 chromosome 18 ': 0.02583347121056798, 'NC_083886.1 chromosome 19 ': 0.025329114227807772, 'NC_083887.1 chromosome 20 ': 0.027871496489796765, 'NC_083888.1 chromosome 21 ': 0.02715919398834188, 'NC_083889.1 chromosome 22 ': 0.023760747585308727, 'NC_083890.1 chromosome 23 ': 0.020608322899949797, 'NC_083891.1 chromosome 24 ': 0.024233678930844556, 'NC_083892.1 chromosome 25 ': 0.01657529148346031, 'NC_083893.1 chromosome 26 ': 0.020049006294805962, 'NC_083894.1 chromosome 27 ': 0.017736523259144113, 'NC_083895.1 chromosome 28 ': 0.018465447102491126, 'NC_083896.1 chromosome 29 ': 0.02008679315268092}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Homo sapiens
DEBUG:mammals_gender_dataset:Sample/assembly id: HG00371
DEBUG:mammals_gender_dataset:Diploid: True
DEBUG:mammals_gender_dataset:Label: 0.0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['chrY_with_SNPs', 'chrX']
DEBUG:mammals_gender_dataset:Autosomes: ['h1_chr1', 'h1_chr10', 'h1_chr11', 'h1_chr12', 'h1_chr13', 'h1_chr14', 'h1_chr15', 'h1_chr16', 'h1_chr17', 'h1_chr18', 'h1_chr19', 'h1_chr2', 'h1_chr20', 'h1_chr21', 'h1_chr22', 'h1_chr3', 'h1_chr4', 'h1_chr5', 'h1_chr6', 'h1_chr7', 'h1_chr8', 'h1_chr9', 'h2_chr1', 'h2_chr10', 'h2_chr11', 'h2_chr12', 'h2_chr13', 'h2_chr14', 'h2_chr15', 'h2_chr16', 'h2_chr17', 'h2_chr18', 'h2_chr19', 'h2_chr2', 'h2_chr20', 'h2_chr21', 'h2_chr22', 'h2_chr3', 'h2_chr4', 'h2_chr5', 'h2_chr6', 'h2_chr7', 'h2_chr8', 'h2_chr9']
DEBUG:mammals_gender_dataset:Chromosomes length: {'chrY_with_SNPs': 54105630, 'chrX': 156014097, 'h1_chr1': 248921254, 'h1_chr10': 133768818, 'h1_chr11': 135007373, 'h1_chr12': 133245125, 'h1_chr13': 98349318, 'h1_chr14': 90857038, 'h1_chr15': 84976214, 'h1_chr16': 90211765, 'h1_chr17': 83181026, 'h1_chr18': 80248134, 'h1_chr19': 58542169, 'h1_chr2': 242160515, 'h1_chr20': 64268172, 'h1_chr21': 41687310, 'h1_chr22': 40294413, 'h1_chr3': 198214654, 'h1_chr4': 190182179, 'h1_chr5': 181457687, 'h1_chr6': 170675524, 'h1_chr7': 159313080, 'h1_chr8': 145010492, 'h1_chr9': 138323523, 'h2_chr1': 248920688, 'h2_chr10': 133766585, 'h2_chr11': 135007194, 'h2_chr12': 133245437, 'h2_chr13': 98348327, 'h2_chr14': 90855534, 'h2_chr15': 84975820, 'h2_chr16': 90212851, 'h2_chr17': 83180806, 'h2_chr18': 80247686, 'h2_chr19': 58542291, 'h2_chr2': 242160198, 'h2_chr20': 64269285, 'h2_chr21': 41687489, 'h2_chr22': 40295776, 'h2_chr3': 198214260, 'h2_chr4': 190183173, 'h2_chr5': 181457473, 'h2_chr6': 170675341, 'h2_chr7': 159314128, 'h2_chr8': 145011134, 'h2_chr9': 138323808}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'chrY_with_SNPs': 0.009283880950220324, 'chrX': 0.02677015872662652, 'h1_chr1': 0.042711919039027074, 'h1_chr10': 0.02295313410385739, 'h1_chr11': 0.02316565537327612, 'h1_chr12': 0.022863274629594477, 'h1_chr13': 0.016875570247446722, 'h1_chr14': 0.015589984337704673, 'h1_chr15': 0.014580905062494338, 'h1_chr16': 0.01547926318516673, 'h1_chr17': 0.014272872207590622, 'h1_chr18': 0.013769622912316664, 'h1_chr19': 0.010045138141144994, 'h1_chr2': 0.04155185684195976, 'h1_chr20': 0.011027651978847362, 'h1_chr21': 0.007153045314783862, 'h1_chr22': 0.0069140407985455515, 'h1_chr3': 0.03401127110663184, 'h1_chr4': 0.03263299417619741, 'h1_chr5': 0.031135975380202432, 'h1_chr6': 0.029285884776361935, 'h1_chr7': 0.02733622487221619, 'h1_chr8': 0.024882071316069634, 'h1_chr9': 0.023734667171365766, 'h2_chr1': 0.042711821920176085, 'h2_chr10': 0.022952750947683776, 'h2_chr11': 0.023165624659010522, 'h2_chr12': 0.022863328165074175, 'h2_chr13': 0.016875400203663446, 'h2_chr14': 0.01558972626923843, 'h2_chr15': 0.01458083745679241, 'h2_chr16': 0.01547944952981722, 'h2_chr17': 0.014272834458213913, 'h2_chr18': 0.013769546040858635, 'h2_chr19': 0.01004515907489026, 'h2_chr2': 0.041551802448539676, 'h2_chr20': 0.011027842956375903, 'h2_chr21': 0.007153076029049459, 'h2_chr22': 0.006914274673093083, 'h2_chr3': 0.034011203500929905, 'h2_chr4': 0.03263316473474491, 'h2_chr5': 0.031135938660354176, 'h2_chr6': 0.029285853375744034, 'h2_chr7': 0.027336404696519795, 'h2_chr8': 0.0248821814756144, 'h2_chr9': 0.023734716073967415}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999

{'labels': 1, 'species': 'Papio anubis', 'sampled_chromosomes': ['NC_044988.1 chromosome 13 ', 'NC_044988.1 chromosome 13 ', 'NC_044987.1 chromosome 12 ', 'NC_044994.1 chromosome 19 ', 'NC_044987.1 chromosome 12 ', 'NC_044984.1 chromosome 9 ', 'NC_044978.1 chromosome 3 ', 'NC_044980.1 chromosome 5 ', 'NC_044986.1 chromosome 11 ', 'NC_044982.1 chromosome 7 '], 'chunks': ['GATATATAAA', 'CTGAAGACAG', 'CTTGGTACAA', 'TGAACCAATT', 'GTAAGATCAA', 'GTTTGTACAG', 'ACAGTTAACT', 'CAAAGATTTA', 'ACCTCTACAT', 'GGCCTCTGGA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Budorcas taxicolor', 'sampled_chromosomes': ['NC_068922.1 chromosome 13 ', 'NC_068917.1 chromosome 8 ', 'NC_068911.1 chromosome 2 ', 'NC_068917.1 chromosome 8 ', 'NC_068913.1 chromosome 4 ', 'NC_068920.1 chromosome 11 ', 'NC_068925.1 chromosome 16 ', 'NC_068911.1 chromosome 2 ', 'NC_068910.1 chromosome 1 ', 'NC_068919.1 chromosome 10 '], 'chunks': ['TTTTTTTTTT', 'GAATCCTTGA', 'TCCCTTTAAA', 'GTTGTACCTT', 'TCAAAACTTG', 'GAAGTATTAA', 'TGACCTAGCA', 'TGGGGTGATG', 'TGTGCTGTGT', 'GAATTCTTCT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Mustela erminea', 'sampled_chromosomes': ['NC_045629.1 chromosome 16 ', 'NC_045616.1 chromosome 3 ', 'NC_045614.1 chromosome 1 ', 'NC_045617.1 chromosome 4 ', 'NC_045615.1 chromosome 2 ', 'NC_045636.1 chromosome Y ', 'NC_045618.1 chromosome 5 ', 'NC_045625.1 chromosome 12 ', 'NC_045621.1 chromosome 8 ', 'NC_045625.1 chromosome 12 '], 'chunks': ['GCCTGTGGTC', 'AAGGTTTAGC', 'TTTATAGCTA', 'GCCTAAAATC', 'ACCTGGACAC', 'TGCCTCCATC', 'GTGCAATATT', 'TGAGCCTATA', 'GAGCAAGCAG', 'ATTTCTGCAA'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Bos javanicus', 'sampled_chromosomes': ['NC_083871.1 chromosome 4 ', 'NC_083869.1 chromosome 2 ', 'NC_083898.1 chromosome Y ', 'NC_083875.1 chromosome 8 ', 'NC_083879.1 chromosome 12 ', 'NC_083882.1 chromosome 15 ', 'NC_083870.1 chromosome 3 ', 'NC_083876.1 chromosome 9 ', 'NC_083884.1 chromosome 17 ', 'NC_083885.1 chromosome 18 '], 'chunks': ['TAAACAAGAA', 'TAGGGTTTAC', 'ATGTAAACCC', 'TCTGCACACA', 'AGAGACAATA', 'TAAAAGCTAT', 'CAGGCCCTGG', 'GTTTGCAGGG', 'CTGATGCCCC', 'GGCTCTGTAA'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Label: 0.0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Bos taurus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_002263795.3
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_082638.1 chromosome Y ', 'NC_037357.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_037328.1 chromosome 1 ', 'NC_037329.1 chromosome 2 ', 'NC_037330.1 chromosome 3 ', 'NC_037331.1 chromosome 4 ', 'NC_037332.1 chromosome 5 ', 'NC_037333.1 chromosome 6 ', 'NC_037334.1 chromosome 7 ', 'NC_037335.1 chromosome 8 ', 'NC_037336.1 chromosome 9 ', 'NC_037337.1 chromosome 10 ', 'NC_037338.1 chromosome 11 ', 'NC_037339.1 chromosome 12 ', 'NC_037340.1 chromosome 13 ', 'NC_037341.1 chromosome 14 ', 'NC_037342.1 chromosome 15 ', 'NC_037343.1 chromosome 16 ', 'NC_037344.1 chromosome 17 ', 'NC_037345.1 chromosome 18 ', 'NC_037346.1 chromosome 19 ', 'NC_037347.1 chromosome 20 ', 'NC_037348.1 chromosome 21 ', 'NC_037349.1 chromosome 22 ', 'NC_037350.1 chromosome 23 ', 'NC_037351.1 chromosome 24 ', 'NC_037352.1 chromosome 25 ', 'NC_037353.1 chromosome 26 ', 'NC_037354.1 chromosome 27 ', 'NC_037355.1 chromosome 28 ', 'NC_037356.1 chromosome 29 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_082638.1 chromosome Y ': 59476289, 'NC_037357.1 chromosome X ': 139009144, 'NC_037328.1 chromosome 1 ': 317068220, 'NC_037329.1 chromosome 2 ': 272462204, 'NC_037330.1 chromosome 3 ': 242010316, 'NC_037331.1 chromosome 4 ': 240001202, 'NC_037332.1 chromosome 5 ': 240178632, 'NC_037333.1 chromosome 6 ': 235612680, 'NC_037334.1 chromosome 7 ': 221365486, 'NC_037335.1 chromosome 8 ': 226639540, 'NC_037336.1 chromosome 9 ': 210908934, 'NC_037337.1 chromosome 10 ': 206617474, 'NC_037338.1 chromosome 11 ': 213964948, 'NC_037339.1 chromosome 12 ': 174432366, 'NC_037340.1 chromosome 13 ': 166944690, 'NC_037341.1 chromosome 14 ': 164806006, 'NC_037342.1 chromosome 15 ': 170015560, 'NC_037343.1 chromosome 16 ': 162027958, 'NC_037344.1 chromosome 17 ': 146334488, 'NC_037345.1 chromosome 18 ': 131641258, 'NC_037346.1 chromosome 19 ': 126899482, 'NC_037347.1 chromosome 20 ': 143949190, 'NC_037348.1 chromosome 21 ': 139725908, 'NC_037349.1 chromosome 22 ': 121546070, 'NC_037350.1 chromosome 23 ': 104997230, 'NC_037351.1 chromosome 24 ': 124634506, 'NC_037352.1 chromosome 25 ': 84700870, 'NC_037353.1 chromosome 26 ': 103984610, 'NC_037354.1 chromosome 27 ': 91224216, 'NC_037355.1 chromosome 28 ': 91880300, 'NC_037356.1 chromosome 29 ': 102197214}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_082638.1 chromosome Y ': 0.011487992406672478, 'NC_037357.1 chromosome X ': 0.026849960170346892, 'NC_037328.1 chromosome 1 ': 0.061242511343590364, 'NC_037329.1 chromosome 2 ': 0.05262674896642001, 'NC_037330.1 chromosome 3 ': 0.04674489143975353, 'NC_037331.1 chromosome 4 ': 0.046356826098687284, 'NC_037332.1 chromosome 5 ': 0.04639109714227435, 'NC_037333.1 chromosome 6 ': 0.04550917221408606, 'NC_037334.1 chromosome 7 ': 0.04275729143537121, 'NC_037335.1 chromosome 8 ': 0.043775988017203685, 'NC_037336.1 chromosome 9 ': 0.04073758253968042, 'NC_037337.1 chromosome 10 ': 0.039908676420579096, 'NC_037338.1 chromosome 11 ': 0.04132785920651626, 'NC_037339.1 chromosome 12 ': 0.033692043161702885, 'NC_037340.1 chromosome 13 ': 0.03224578001250701, 'NC_037341.1 chromosome 14 ': 0.03183268790529313, 'NC_037342.1 chromosome 15 ': 0.03283892615250708, 'NC_037343.1 chromosome 16 ': 0.03129610105924139, 'NC_037344.1 chromosome 17 ': 0.028264868492018806, 'NC_037345.1 chromosome 18 ': 0.02542683475609604, 'NC_037346.1 chromosome 19 ': 0.02451094898719506, 'NC_037347.1 chromosome 20 ': 0.027804142280407805, 'NC_037348.1 chromosome 21 ': 0.026988404910726984, 'NC_037349.1 chromosome 22 ': 0.023476924211274872, 'NC_037350.1 chromosome 23 ': 0.020280474811763115, 'NC_037351.1 chromosome 24 ': 0.02407346326764562, 'NC_037352.1 chromosome 25 ': 0.016360182650241556, 'NC_037353.1 chromosome 26 ': 0.02008488475282644, 'NC_037354.1 chromosome 27 ': 0.0176201830735043, 'NC_037355.1 chromosome 28 ': 0.017746907321719237, 'NC_037356.1 chromosome 29 ': 0.01973964479214704}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Pongo abelii
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_028885655.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_072008.2 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_071985.2 chromosome 1 ', 'NC_071988.2 chromosome 3 ', 'NC_071989.2 chromosome 4 ', 'NC_071990.2 chromosome 5 ', 'NC_071991.2 chromosome 6 ', 'NC_071992.2 chromosome 7 ', 'NC_071993.2 chromosome 8 ', 'NC_071994.2 chromosome 9 ', 'NC_071995.2 chromosome 10 ', 'NC_071996.2 chromosome 11 ', 'NC_071997.2 chromosome 12 ', 'NC_071998.2 chromosome 13 ', 'NC_071999.2 chromosome 14 ', 'NC_072000.2 chromosome 15 ', 'NC_072001.2 chromosome 16 ', 'NC_072002.2 chromosome 17 ', 'NC_072003.2 chromosome 18 ', 'NC_072004.2 chromosome 19 ', 'NC_072005.2 chromosome 20 ', 'NC_072006.2 chromosome 21 ', 'NC_072007.2 chromosome 22 ', 'NC_085928.1 chromosome 2 ', 'NC_085929.1 chromosome 23 ', 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_072008.2 chromosome X ': 325172642, 'NC_071985.2 chromosome 1 ': 467591038, 'NC_071988.2 chromosome 3 ': 425833550, 'NC_071989.2 chromosome 4 ': 380757808, 'NC_071990.2 chromosome 5 ': 345210726, 'NC_071991.2 chromosome 6 ': 313933982, 'NC_071992.2 chromosome 7 ': 323262792, 'NC_071993.2 chromosome 8 ': 281708270, 'NC_071994.2 chromosome 9 ': 276942042, 'NC_071995.2 chromosome 10 ': 264563434, 'NC_071996.2 chromosome 11 ': 292394356, 'NC_071997.2 chromosome 12 ': 266366248, 'NC_071998.2 chromosome 13 ': 259236340, 'NC_071999.2 chromosome 14 ': 241159696, 'NC_072000.2 chromosome 15 ': 223483318, 'NC_072001.2 chromosome 16 ': 210667690, 'NC_072002.2 chromosome 17 ': 190920258, 'NC_072003.2 chromosome 18 ': 179106226, 'NC_072004.2 chromosome 19 ': 197338576, 'NC_072005.2 chromosome 20 ': 130800294, 'NC_072006.2 chromosome 21 ': 137501336, 'NC_072007.2 chromosome 22 ': 114286206, 'NC_085928.1 chromosome 2 ': 419089974, 'NC_085929.1 chromosome 23 ': 115186842, 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold': 443016, 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold': 266400, 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold': 230424, 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold': 598924}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_072008.2 chromosome X ': 0.05093514608252884, 'NC_071985.2 chromosome 1 ': 0.07324360893623792, 'NC_071988.2 chromosome 3 ': 0.06670270273257443, 'NC_071989.2 chromosome 4 ': 0.05964202416679158, 'NC_071990.2 chromosome 5 ': 0.05407391793454087, 'NC_071991.2 chromosome 6 ': 0.04917471880503397, 'NC_071992.2 chromosome 7 ': 0.05063598657099245, 'NC_071993.2 chromosome 8 ': 0.04412687302613384, 'NC_071994.2 chromosome 9 ': 0.043380289556044005, 'NC_071995.2 chromosome 10 ': 0.04144130046120386, 'NC_071996.2 chromosome 11 ': 0.04580074493649113, 'NC_071997.2 chromosome 12 ': 0.04172369381965136, 'NC_071998.2 chromosome 13 ': 0.0406068627624587, 'NC_071999.2 chromosome 14 ': 0.0377753314959942, 'NC_072000.2 chromosome 15 ': 0.035006498023097056, 'NC_072001.2 chromosome 16 ': 0.03299905397643785, 'NC_072002.2 chromosome 17 ': 0.029905809946164215, 'NC_072003.2 chromosome 18 ': 0.028055256215559564, 'NC_072004.2 chromosome 19 ': 0.030911177319395213, 'NC_072005.2 chromosome 20 ': 0.020488599660631105, 'NC_072006.2 chromosome 21 ': 0.02153825301115855, 'NC_072007.2 chromosome 22 ': 0.01790182766306639, 'NC_085928.1 chromosome 2 ': 0.06564638684275663, 'NC_085929.1 chromosome 23 ': 0.018042903572604883, 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold': 6.939416716642969e-05, 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold': 4.1728980743668106e-05, 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold': 3.609368865945563e-05, 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold': 9.381564588183437e-05}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Pongo abelii
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_028885655.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_072009.2 chromosome Y ', 'NC_072008.2 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_071985.2 chromosome 1 ', 'NC_071988.2 chromosome 3 ', 'NC_071989.2 chromosome 4 ', 'NC_071990.2 chromosome 5 ', 'NC_071991.2 chromosome 6 ', 'NC_071992.2 chromosome 7 ', 'NC_071993.2 chromosome 8 ', 'NC_071994.2 chromosome 9 ', 'NC_071995.2 chromosome 10 ', 'NC_071996.2 chromosome 11 ', 'NC_071997.2 chromosome 12 ', 'NC_071998.2 chromosome 13 ', 'NC_071999.2 chromosome 14 ', 'NC_072000.2 chromosome 15 ', 'NC_072001.2 chromosome 16 ', 'NC_072002.2 chromosome 17 ', 'NC_072003.2 chromosome 18 ', 'NC_072004.2 chromosome 19 ', 'NC_072005.2 chromosome 20 ', 'NC_072006.2 chromosome 21 ', 'NC_072007.2 chromosome 22 ', 'NC_085928.1 chromosome 2 ', 'NC_085929.1 chromosome 23 ', 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_072009.2 chromosome Y ': 67827326, 'NC_072008.2 chromosome X ': 162586321, 'NC_071985.2 chromosome 1 ': 467591038, 'NC_071988.2 chromosome 3 ': 425833550, 'NC_071989.2 chromosome 4 ': 380757808, 'NC_071990.2 chromosome 5 ': 345210726, 'NC_071991.2 chromosome 6 ': 313933982, 'NC_071992.2 chromosome 7 ': 323262792, 'NC_071993.2 chromosome 8 ': 281708270, 'NC_071994.2 chromosome 9 ': 276942042, 'NC_071995.2 chromosome 10 ': 264563434, 'NC_071996.2 chromosome 11 ': 292394356, 'NC_071997.2 chromosome 12 ': 266366248, 'NC_071998.2 chromosome 13 ': 259236340, 'NC_071999.2 chromosome 14 ': 241159696, 'NC_072000.2 chromosome 15 ': 223483318, 'NC_072001.2 chromosome 16 ': 210667690, 'NC_072002.2 chromosome 17 ': 190920258, 'NC_072003.2 chromosome 18 ': 179106226, 'NC_072004.2 chromosome 19 ': 197338576, 'NC_072005.2 chromosome 20 ': 130800294, 'NC_072006.2 chromosome 21 ': 137501336, 'NC_072007.2 chromosome 22 ': 114286206, 'NC_085928.1 chromosome 2 ': 419089974, 'NC_085929.1 chromosome 23 ': 115186842, 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold': 443016, 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold': 266400, 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold': 230424, 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold': 598924}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_072009.2 chromosome Y ': 0.010784570148977402, 'NC_072008.2 chromosome X ': 0.025851285720576066, 'NC_071985.2 chromosome 1 ': 0.07434714955951761, 'NC_071988.2 chromosome 3 ': 0.06770769338250303, 'NC_071989.2 chromosome 4 ': 0.06054063358102704, 'NC_071990.2 chromosome 5 ': 0.05488863427590256, 'NC_071991.2 chromosome 6 ': 0.04991562030658276, 'NC_071992.2 chromosome 7 ': 0.05139890457834488, 'NC_071993.2 chromosome 8 ': 0.04479172007108265, 'NC_071994.2 chromosome 9 ': 0.04403388804019852, 'NC_071995.2 chromosome 10 ': 0.042065684748169976, 'NC_071996.2 chromosome 11 ': 0.04649081173341658, 'NC_071997.2 chromosome 12 ': 0.042352332847028516, 'NC_071998.2 chromosome 13 ': 0.04121867481395561, 'NC_071999.2 chromosome 14 ': 0.038344481671267194, 'NC_072000.2 chromosome 15 ': 0.03553393097196879, 'NC_072001.2 chromosome 16 ': 0.03349624133683267, 'NC_072002.2 chromosome 17 ': 0.030356392278561357, 'NC_072003.2 chromosome 18 ': 0.028477956781247725, 'NC_072004.2 chromosome 19 ': 0.03137690723604979, 'NC_072005.2 chromosome 20 ': 0.020797295564178187, 'NC_072006.2 chromosome 21 ': 0.021862763743186804, 'NC_072007.2 chromosome 22 ': 0.018171549408677587, 'NC_085928.1 chromosome 2 ': 0.06663546228161958, 'NC_085929.1 chromosome 23 ': 0.0183147508688191, 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold': 7.043970934545426e-05, 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold': 4.235769942762567e-05, 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold': 3.663750200041748e-05, 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold': 9.52291395345018e-05}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Apodemus sylvaticus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_947179515.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_067496.1 chromosome Y ', 'NW_026262995.1 chromosome Y unlocalized genomic scaffold', 'NW_026262996.1 chromosome Y unlocalized genomic scaffold', 'NW_026262997.1 chromosome Y unlocalized genomic scaffold', 'NW_026262998.1 chromosome Y unlocalized genomic scaffold', 'NW_026262999.1 chromosome Y unlocalized genomic scaffold', 'NW_026263000.1 chromosome Y unlocalized genomic scaffold', 'NW_026263001.1 chromosome Y unlocalized genomic scaffold', 'NW_026263002.1 chromosome Y unlocalized genomic scaffold', 'NW_026263003.1 chromosome Y unlocalized genomic scaffold', 'NC_067495.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_067472.1 chromosome 1 ', 'NC_067473.1 chromosome 2 ', 'NC_067474.1 chromosome 3 ', 'NC_067475.1 chromosome 4 ', 'NC_067476.1 chromosome 5 ', 'NC_067477.1 chromosome 6 ', 'NC_067478.1 chromosome 7 ', 'NC_067479.1 chromosome 8 ', 'NC_067480.1 chromosome 9 ', 'NC_067481.1 chromosome 10 ', 'NC_067482.1 chromosome 11 ', 'NC_067483.1 chromosome 12 ', 'NC_067484.1 chromosome 13 ', 'NC_067485.1 chromosome 14 ', 'NC_067486.1 chromosome 15 ', 'NC_067487.1 chromosome 16 ', 'NC_067488.1 chromosome 17 ', 'NC_067489.1 chromosome 18 ', 'NC_067490.1 chromosome 19 ', 'NC_067491.1 chromosome 20 ', 'NC_067492.1 chromosome 21 ', 'NC_067493.1 chromosome 22 ', 'NC_067494.1 chromosome 23 ', 'NW_026262993.1 chromosome 5 unlocalized genomic scaffold', 'NW_026262994.1 chromosome 15 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_067496.1 chromosome Y ': 3454884, 'NW_026262995.1 chromosome Y unlocalized genomic scaffold': 2319465, 'NW_026262996.1 chromosome Y unlocalized genomic scaffold': 2307501, 'NW_026262997.1 chromosome Y unlocalized genomic scaffold': 1800492, 'NW_026262998.1 chromosome Y unlocalized genomic scaffold': 1756322, 'NW_026262999.1 chromosome Y unlocalized genomic scaffold': 1504898, 'NW_026263000.1 chromosome Y unlocalized genomic scaffold': 974588, 'NW_026263001.1 chromosome Y unlocalized genomic scaffold': 855225, 'NW_026263002.1 chromosome Y unlocalized genomic scaffold': 354000, 'NW_026263003.1 chromosome Y unlocalized genomic scaffold': 333444, 'NC_067495.1 chromosome X ': 151773995, 'NC_067472.1 chromosome 1 ': 423528672, 'NC_067473.1 chromosome 2 ': 376121598, 'NC_067474.1 chromosome 3 ': 343320724, 'NC_067475.1 chromosome 4 ': 340525048, 'NC_067476.1 chromosome 5 ': 330219786, 'NC_067477.1 chromosome 6 ': 295131364, 'NC_067478.1 chromosome 7 ': 265624236, 'NC_067479.1 chromosome 8 ': 241876502, 'NC_067480.1 chromosome 9 ': 229934912, 'NC_067481.1 chromosome 10 ': 222463898, 'NC_067482.1 chromosome 11 ': 216648076, 'NC_067483.1 chromosome 12 ': 208942418, 'NC_067484.1 chromosome 13 ': 204787724, 'NC_067485.1 chromosome 14 ': 183482302, 'NC_067486.1 chromosome 15 ': 178861258, 'NC_067487.1 chromosome 16 ': 179680142, 'NC_067488.1 chromosome 17 ': 165585976, 'NC_067489.1 chromosome 18 ': 143008274, 'NC_067490.1 chromosome 19 ': 137700132, 'NC_067491.1 chromosome 20 ': 135996420, 'NC_067492.1 chromosome 21 ': 127553474, 'NC_067493.1 chromosome 22 ': 118583046, 'NC_067494.1 chromosome 23 ': 115249044, 'NW_026262993.1 chromosome 5 unlocalized genomic scaffold': 1312222, 'NW_026262994.1 chromosome 15 unlocalized genomic scaffold': 3911922}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_067496.1 chromosome Y ': 0.0006448706165651507, 'NW_026262995.1 chromosome Y unlocalized genomic scaffold': 0.0004329392317227691, 'NW_026262996.1 chromosome Y unlocalized genomic scaffold': 0.0004307060939223146, 'NW_026262997.1 chromosome Y unlocalized genomic scaffold': 0.00033607044003810876, 'NW_026262998.1 chromosome Y unlocalized genomic scaffold': 0.0003278258983592325, 'NW_026262999.1 chromosome Y unlocalized genomic scaffold': 0.0002808964066890993, 'NW_026263000.1 chromosome Y unlocalized genomic scaffold': 0.0001819115097517014, 'NW_026263001.1 chromosome Y unlocalized genomic scaffold': 0.00015963183512150654, 'NW_026263002.1 chromosome Y unlocalized genomic scaffold': 6.607579249088054e-05, 'NW_026263003.1 chromosome Y unlocalized genomic scaffold': 6.223891681166433e-05, 'NC_067495.1 chromosome X ': 0.028329341805457462, 'NC_067472.1 chromosome 1 ': 0.07905365153957687, 'NC_067473.1 chromosome 2 ': 0.07020489452199546, 'NC_067474.1 chromosome 3 ': 0.06408245456735275, 'NC_067475.1 chromosome 4 ': 0.06356062827569248, 'NC_067476.1 chromosome 5 ': 0.06163710185344345, 'NC_067477.1 chromosome 6 ': 0.05508768012772467, 'NC_067478.1 chromosome 7 ': 0.04958003361153865, 'NC_067479.1 chromosome 8 ': 0.04514740552138998, 'NC_067480.1 chromosome 9 ': 0.042918450654578756, 'NC_067481.1 chromosome 10 ': 0.04152395017220457, 'NC_067482.1 chromosome 11 ': 0.04043839919018225, 'NC_067483.1 chromosome 12 ': 0.03900010128336391, 'NC_067484.1 chromosome 13 ': 0.03822460778447378, 'NC_067485.1 chromosome 14 ': 0.03424784890593525, 'NC_067486.1 chromosome 15 ': 0.033385308949903526, 'NC_067487.1 chromosome 16 ': 0.03353815756362698, 'NC_067488.1 chromosome 17 ': 0.03090741409484725, 'NC_067489.1 chromosome 18 ': 0.026693178071477367, 'NC_067490.1 chromosome 19 ': 0.025702387988697346, 'NC_067491.1 chromosome 20 ': 0.02538438199836903, 'NC_067492.1 chromosome 21 ': 0.023808465761341602, 'NC_067493.1 chromosome 22 ': 0.02213409248709758, 'NC_067494.1 chromosome 23 ': 0.021511785073775033, 'NW_026262993.1 chromosome 5 unlocalized genomic scaffold': 0.0002449325100959555, 'NW_026262994.1 chromosome 15 unlocalized genomic scaffold': 0.0007301789443856226}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Arvicanthis niloticus

{'labels': 0.0, 'species': 'Homo sapiens', 'sampled_chromosomes': ['h2_chr7', 'h2_chr16', 'h1_chr16', 'h1_chr13', 'h2_chr1', 'chrY_with_SNPs', 'chrX', 'h2_chr7', 'h1_chr3', 'h2_chr14'], 'chunks': ['TCAGGATATT', 'NNNNNNNNNN', 'AGGCGTGTGC', 'CCATCAGCTG', 'TGCTCTTTTT', 'NNNNNNNNNN', 'AGTGGATCAC', 'ATCTTCCAGT', 'CTCTTGCACG', 'TGATCTCAGT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': True}
{'labels': 0, 'species': 'Bos taurus', 'sampled_chromosomes': ['NC_037328.1 chromosome 1 ', 'NC_037332.1 chromosome 5 ', 'NC_037347.1 chromosome 20 ', 'NC_037351.1 chromosome 24 ', 'NC_082638.1 chromosome Y ', 'NC_037331.1 chromosome 4 ', 'NC_037335.1 chromosome 8 ', 'NC_037330.1 chromosome 3 ', 'NC_037342.1 chromosome 15 ', 'NC_037328.1 chromosome 1 '], 'chunks': ['CCCTGGAGTG', 'TGATTCACAT', 'TCTTTGGAAG', 'CTTAATTCAG', 'CGACTCACTG', 'ATTGTCCTTA', 'CCAGTCACAT', 'GCACCGAAGA', 'ATAAGATATT', 'ATATACAGCC'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Pongo abelii', 'sampled_chromosomes': ['NC_071988.2 chromosome 3 ', 'NC_071989.2 chromosome 4 ', 'NC_071992.2 chromosome 7 ', 'NC_071989.2 chromosome 4 ', 'NC_072008.2 chromosome X ', 'NC_071998.2 chromosome 13 ', 'NC_071989.2 chromosome 4 ', 'NC_071991.2 chromosome 6 ', 'NC_071991.2 chromosome 6 ', 'NC_085929.1 chromosome 23 '], 'chunks': ['AATGCCTTCC', 'TTCACATTAC', 'CTTTAGCCAA', 'GTCCACTGGC', 'CATATGGTAC', 'ATAAAATGAA', 'TCGGTGTGAG', 'GGTAAAGTGA', 'GAACAGATAC', 'CAGTAAGCCC'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 0, 'species': 'Pongo abelii', 'sampled_chromosomes': ['NC_072006.2 chromosome 21 ', 'NC_071999.2 chromosome 14 ', 'NC_071989.2 chromosome 4 ', 'NC_072002.2 chromosome 17 ', 'NC_085928.1 chromosome 2 ', 'NC_072009.2 chromosome Y ', 'NC_072005.2 chromosome 20 ', 'NC_072003.2 chromosome 18 ', 'NC_071999.2 chromosome 14 ', 'NC_071991.2 chromosome 6 '], 'chunks': ['ATTTGGAGCG', 'AGTGAGTTTG', 'AAATTATTTG', 'NNNNNNNNNN', 'CATGAGCTCT', 'TCCCCTCAAT', 'TTTAATGTAG', 'CCGAGATGGT', 'TTTGCAAGCA', 'TTGAGGTCAG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Apodemus sylvaticus', 'sampled_chromosomes': ['NC_067479.1 chromosome 8 ', 'NC_067472.1 chromosome 1 ', 'NC_067477.1 chromosome 6 ', 'NC_067479.1 chromosome 8 ', 'NC_067472.1 chromosome 1 ', 'NW_026263000.1 chromosome Y unlocalized genomic scaffold', 'NW_026262995.1 chromosome Y unlocalized genomic scaffold', 'NC_067476.1 chromosome 5 ', 'NC_067475.1 chromosome 4 ', 'NC_067478.1 chromosome 7 '], 'chunks': ['GGTCCTGGAA', 'AGCAGGCTAG', 'CATGAAGGCC', 'TTTATTTAAA', 'GAGAGGCTCT', 'TACACGTAAC', 'ATTTAGCTGT', 'GGTTTAGAAG', 'TGGGGAGTGC', 'CAGAACTATC'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Arvicanthis niloticus', 'sampled_chromosomes': ['NC_047673.1 chromosome 16 ', 'NC_047660.1 chromosome 3 ', 'NC_047679.1 chromosome X ', 'NC_047659.1 chromosome 2 ', 'NC_047677.1 chromosome 20 ', 'NC_047660.1 chromosome 3 ', 'NC_047662.1 chromosome 5 ', 'NC_047677.1 chromosome 20 ', 'NC_047663.1 chromosome 6 ', 'NC_047665.1 chromosome 8 '], 'chunks': ['TGAAAGTTTT', 'ATTGAGCGTG', 'ATTTTAAAGA', 'CTTACAAGCA', 'CCAACATGTT', 'GGGCAGGGAA', 'ACATTAACAC', 'AGACAGGCAC', 'GAACCATGAA', 'TCAAAAAAGG'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}

DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_044996.1 chromosome X ': 285422992, 'NC_044976.1 chromosome 1 ': 436345764, 'NC_044977.1 chromosome 2 ': 387321500, 'NC_044978.1 chromosome 3 ': 369839030, 'NC_044979.1 chromosome 4 ': 364241804, 'NC_044980.1 chromosome 5 ': 347801522, 'NC_044981.1 chromosome 6 ': 334276494, 'NC_044982.1 chromosome 7 ': 323536936, 'NC_044983.1 chromosome 8 ': 280549772, 'NC_044984.1 chromosome 9 ': 255183638, 'NC_044985.1 chromosome 10 ': 252925378, 'NC_044986.1 chromosome 11 ': 251827392, 'NC_044987.1 chromosome 12 ': 246686900, 'NC_044988.1 chromosome 13 ': 213698002, 'NC_044989.1 chromosome 14 ': 213309948, 'NC_044990.1 chromosome 15 ': 183971550, 'NC_044991.1 chromosome 16 ': 182368386, 'NC_044992.1 chromosome 17 ': 149051852, 'NC_044993.1 chromosome 18 ': 145788816, 'NC_044994.1 chromosome 19 ': 144246688, 'NC_044995.1 chromosome 20 ': 100042216}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_044996.1 chromosome X ': 0.05219462415343583, 'NC_044976.1 chromosome 1 ': 0.07979351275570613, 'NC_044977.1 chromosome 2 ': 0.07082856211893747, 'NC_044978.1 chromosome 3 ': 0.06763158438238667, 'NC_044979.1 chromosome 4 ': 0.06660803296725808, 'NC_044980.1 chromosome 5 ': 0.06360163767319398, 'NC_044981.1 chromosome 6 ': 0.061128347949131745, 'NC_044982.1 chromosome 7 ': 0.05916443050346211, 'NC_044983.1 chromosome 8 ': 0.05130346999470917, 'NC_044984.1 chromosome 9 ': 0.0466648253603775, 'NC_044985.1 chromosome 10 ': 0.04625186272161174, 'NC_044986.1 chromosome 11 ': 0.04605107663148578, 'NC_044987.1 chromosome 12 ': 0.04511104707737143, 'NC_044988.1 chromosome 13 ': 0.03907844570815156, 'NC_044989.1 chromosome 14 ': 0.03900748319549863, 'NC_044990.1 chromosome 15 ': 0.033642440084767335, 'NC_044991.1 chromosome 16 ': 0.03334927329448886, 'NC_044992.1 chromosome 17 ': 0.02725675790867451, 'NC_044993.1 chromosome 18 ': 0.026660054270941185, 'NC_044994.1 chromosome 19 ': 0.026378048988912293, 'NC_044995.1 chromosome 20 ': 0.018294482259498014}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Ovis aries
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_016772045.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_056080.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_056054.1 chromosome 1 ', 'NC_056055.1 chromosome 2 ', 'NC_056056.1 chromosome 3 ', 'NC_056057.1 chromosome 4 ', 'NC_056058.1 chromosome 5 ', 'NC_056059.1 chromosome 6 ', 'NC_056060.1 chromosome 7 ', 'NC_056061.1 chromosome 8 ', 'NC_056062.1 chromosome 9 ', 'NC_056063.1 chromosome 10 ', 'NC_056064.1 chromosome 11 ', 'NC_056065.1 chromosome 12 ', 'NC_056066.1 chromosome 13 ', 'NC_056067.1 chromosome 14 ', 'NC_056068.1 chromosome 15 ', 'NC_056069.1 chromosome 16 ', 'NC_056070.1 chromosome 17 ', 'NC_056071.1 chromosome 18 ', 'NC_056072.1 chromosome 19 ', 'NC_056073.1 chromosome 20 ', 'NC_056074.1 chromosome 21 ', 'NC_056075.1 chromosome 22 ', 'NC_056076.1 chromosome 23 ', 'NC_056077.1 chromosome 24 ', 'NC_056078.1 chromosome 25 ', 'NC_056079.1 chromosome 26 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_056080.1 chromosome X ': 286343450, 'NC_056054.1 chromosome 1 ': 557234404, 'NC_056055.1 chromosome 2 ': 500404116, 'NC_056056.1 chromosome 3 ': 452178200, 'NC_056057.1 chromosome 4 ': 243156198, 'NC_056058.1 chromosome 5 ': 216441576, 'NC_056059.1 chromosome 6 ': 236939394, 'NC_056060.1 chromosome 7 ': 202548836, 'NC_056061.1 chromosome 8 ': 183585742, 'NC_056062.1 chromosome 9 ': 190359316, 'NC_056063.1 chromosome 10 ': 172918942, 'NC_056064.1 chromosome 11 ': 125094994, 'NC_056065.1 chromosome 12 ': 160807310, 'NC_056066.1 chromosome 13 ': 167023670, 'NC_056067.1 chromosome 14 ': 133033314, 'NC_056068.1 chromosome 15 ': 165077274, 'NC_056069.1 chromosome 16 ': 143794728, 'NC_056070.1 chromosome 17 ': 146334446, 'NC_056071.1 chromosome 18 ': 135968920, 'NC_056072.1 chromosome 19 ': 121123100, 'NC_056073.1 chromosome 20 ': 102903434, 'NC_056074.1 chromosome 21 ': 95028388, 'NC_056075.1 chromosome 22 ': 103024982, 'NC_056076.1 chromosome 23 ': 124881288, 'NC_056077.1 chromosome 24 ': 85260472, 'NC_056078.1 chromosome 25 ': 89727508, 'NC_056079.1 chromosome 26 ': 90104718}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_056080.1 chromosome X ': 0.05473658938750108, 'NC_056054.1 chromosome 1 ': 0.10651932413448567, 'NC_056055.1 chromosome 2 ': 0.09565580992094445, 'NC_056056.1 chromosome 3 ': 0.08643708268297857, 'NC_056057.1 chromosome 4 ': 0.046481038651143974, 'NC_056058.1 chromosome 5 ': 0.04137434843330835, 'NC_056059.1 chromosome 6 ': 0.045292652299542165, 'NC_056060.1 chromosome 7 ': 0.03871865225849691, 'NC_056061.1 chromosome 8 ': 0.03509372181292679, 'NC_056062.1 chromosome 9 ': 0.036388538714531675, 'NC_056063.1 chromosome 10 ': 0.033054687039550286, 'NC_056064.1 chromosome 11 ': 0.023912798847013653, 'NC_056065.1 chromosome 12 ': 0.030739462341389672, 'NC_056066.1 chromosome 13 ': 0.03192776381922996, 'NC_056067.1 chromosome 14 ': 0.02543026524013907, 'NC_056068.1 chromosome 15 ': 0.031555696364439306, 'NC_056069.1 chromosome 16 ': 0.02748738615331835, 'NC_056070.1 chromosome 17 ': 0.027972871333182058, 'NC_056071.1 chromosome 18 ': 0.025991427230139134, 'NC_056072.1 chromosome 19 ': 0.02315354302688339, 'NC_056073.1 chromosome 20 ': 0.01967072413712211, 'NC_056074.1 chromosome 21 ': 0.018165353019641745, 'NC_056075.1 chromosome 22 ': 0.019693958902809512, 'NC_056076.1 chromosome 23 ': 0.023871947423411522, 'NC_056077.1 chromosome 24 ': 0.016298146323404754, 'NC_056078.1 chromosome 25 ': 0.017152052062513457, 'NC_056079.1 chromosome 26 ': 0.017224158439952363}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Mus musculus
DEBUG:mammals_gender_dataset:Sample/assembly id: C3H_HeH
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1.0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['HeH_chrX']
DEBUG:mammals_gender_dataset:Autosomes: ['HeH_chr1', 'HeH_chr10', 'HeH_chr11', 'HeH_chr12', 'HeH_chr13', 'HeH_chr14', 'HeH_chr15', 'HeH_chr16', 'HeH_chr17', 'HeH_chr18', 'HeH_chr19', 'HeH_chr2', 'HeH_chr3', 'HeH_chr4', 'HeH_chr5', 'HeH_chr6', 'HeH_chr7', 'HeH_chr8', 'HeH_chr9']
DEBUG:mammals_gender_dataset:Chromosomes length: {'HeH_chrX': 335662598, 'HeH_chr1': 384743942, 'HeH_chr10': 254989986, 'HeH_chr11': 237765086, 'HeH_chr12': 234058044, 'HeH_chr13': 234643278, 'HeH_chr14': 243604488, 'HeH_chr15': 201787370, 'HeH_chr16': 190215536, 'HeH_chr17': 183774542, 'HeH_chr18': 175205278, 'HeH_chr19': 116663132, 'HeH_chr2': 357926448, 'HeH_chr3': 313879360, 'HeH_chr4': 306616232, 'HeH_chr5': 297469368, 'HeH_chr6': 293073092, 'HeH_chr7': 284682918, 'HeH_chr8': 252602426, 'HeH_chr9': 242990220}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'HeH_chrX': 0.06527412169987205, 'HeH_chr1': 0.07481865135714796, 'HeH_chr10': 0.04958624367917414, 'HeH_chr11': 0.04623662943687442, 'HeH_chr12': 0.04551574509618139, 'HeH_chr13': 0.04562955174478185, 'HeH_chr14': 0.04737217995419025, 'HeH_chr15': 0.03924027706797738, 'HeH_chr16': 0.036989977793326835, 'HeH_chr17': 0.035737439593571424, 'HeH_chr18': 0.03407103057288473, 'HeH_chr19': 0.02268672030017547, 'HeH_chr2': 0.06960362776657923, 'HeH_chr3': 0.061038077122068726, 'HeH_chr4': 0.05962566387192237, 'HeH_chr5': 0.05784693273695041, 'HeH_chr6': 0.05699201754425376, 'HeH_chr7': 0.055360434990754305, 'HeH_chr8': 0.049121950418815875, 'HeH_chr9': 0.04725272725249741}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0

{'labels': 1, 'species': 'Papio anubis', 'sampled_chromosomes': ['NC_044990.1 chromosome 15 ', 'NC_044978.1 chromosome 3 ', 'NC_044983.1 chromosome 8 ', 'NC_044977.1 chromosome 2 ', 'NC_044985.1 chromosome 10 ', 'NC_044996.1 chromosome X ', 'NC_044984.1 chromosome 9 ', 'NC_044982.1 chromosome 7 ', 'NC_044996.1 chromosome X ', 'NC_044978.1 chromosome 3 '], 'chunks': ['TGCCTCGATT', 'ATATCAGTCA', 'ACATTCATAC', 'AATAACAGAC', 'TTTATCCAAC', 'ATAGGAAATT', 'TTTAAAGCTT', 'TATTAGTTGG', 'TTTCTGTGCT', 'TAATAATATT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Ovis aries', 'sampled_chromosomes': ['NC_056073.1 chromosome 20 ', 'NC_056078.1 chromosome 25 ', 'NC_056076.1 chromosome 23 ', 'NC_056054.1 chromosome 1 ', 'NC_056065.1 chromosome 12 ', 'NC_056064.1 chromosome 11 ', 'NC_056060.1 chromosome 7 ', 'NC_056063.1 chromosome 10 ', 'NC_056076.1 chromosome 23 ', 'NC_056060.1 chromosome 7 '], 'chunks': ['AGGCTCCCAG', 'TACTGTTCAA', 'AGATCTGGGT', 'CATGATAAAG', 'CACATTCTGT', 'CAGTTAAATT', 'TTCACATCAT', 'AGATCATTTC', 'GGACATTCCA', 'GTGTGAGTGA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Label: 1.0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Arvicanthis niloticus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011762505.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_047679.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_047658.1 chromosome 1 ', 'NC_047659.1 chromosome 2 ', 'NC_047660.1 chromosome 3 ', 'NC_047661.1 chromosome 4 ', 'NC_047662.1 chromosome 5 ', 'NC_047663.1 chromosome 6 ', 'NC_047664.1 chromosome 7 ', 'NC_047665.1 chromosome 8 ', 'NC_047666.1 chromosome 9 ', 'NC_047667.1 chromosome 10 ', 'NC_047668.1 chromosome 11 ', 'NC_047669.1 chromosome 12 ', 'NC_047670.1 chromosome 13 ', 'NC_047671.1 chromosome 14 ', 'NC_047672.1 chromosome 15 ', 'NC_047673.1 chromosome 16 ', 'NC_047674.1 chromosome 17 ', 'NC_047675.1 chromosome 18 ', 'NC_047676.1 chromosome 19 ', 'NC_047677.1 chromosome 20 ', 'NC_047678.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_047679.1 chromosome X ': 260706670, 'NC_047658.1 chromosome 1 ': 334233126, 'NC_047659.1 chromosome 2 ': 298647216, 'NC_047660.1 chromosome 3 ': 278543182, 'NC_047661.1 chromosome 4 ': 270236198, 'NC_047662.1 chromosome 5 ': 217382080, 'NC_047663.1 chromosome 6 ': 217296002, 'NC_047664.1 chromosome 7 ': 182853410, 'NC_047665.1 chromosome 8 ': 176469402, 'NC_047666.1 chromosome 9 ': 172772988, 'NC_047667.1 chromosome 10 ': 165378234, 'NC_047668.1 chromosome 11 ': 161882470, 'NC_047669.1 chromosome 12 ': 159107368, 'NC_047670.1 chromosome 13 ': 156082964, 'NC_047671.1 chromosome 14 ': 152795984, 'NC_047672.1 chromosome 15 ': 147790464, 'NC_047673.1 chromosome 16 ': 146846972, 'NC_047674.1 chromosome 17 ': 128083624, 'NC_047675.1 chromosome 18 ': 109678282, 'NC_047676.1 chromosome 19 ': 106271352, 'NC_047677.1 chromosome 20 ': 104862384, 'NC_047678.1 chromosome 21 ': 104166660}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_047679.1 chromosome X ': 0.06433886240378264, 'NC_047658.1 chromosome 1 ': 0.08248419230892769, 'NC_047659.1 chromosome 2 ': 0.07370207343562309, 'NC_047660.1 chromosome 3 ': 0.06874067111597025, 'NC_047661.1 chromosome 4 ': 0.0666906203805348, 'NC_047662.1 chromosome 5 ': 0.05364694249735947, 'NC_047663.1 chromosome 6 ': 0.053625699617006646, 'NC_047664.1 chromosome 7 ': 0.0451257360851276, 'NC_047665.1 chromosome 8 ': 0.04355024968772685, 'NC_047666.1 chromosome 9 ': 0.04263802495740669, 'NC_047667.1 chromosome 10 ': 0.04081310018614625, 'NC_047668.1 chromosome 11 ': 0.03995039314841646, 'NC_047669.1 chromosome 12 ': 0.03926553569642085, 'NC_047670.1 chromosome 13 ': 0.038519153899555236, 'NC_047671.1 chromosome 14 ': 0.0377079719150514, 'NC_047672.1 chromosome 15 ': 0.03647267761844065, 'NC_047673.1 chromosome 16 ': 0.036239836617606, 'NC_047674.1 chromosome 17 ': 0.031609297378980876, 'NC_047675.1 chromosome 18 ': 0.02706710915482627, 'NC_047676.1 chromosome 19 ': 0.026226325140787352, 'NC_047677.1 chromosome 20 ': 0.025878610990308068, 'NC_047678.1 chromosome 21 ': 0.025706915763994875}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Delphinus delphis
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_949987515.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_082704.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_082683.1 chromosome 1 ', 'NC_082684.1 chromosome 2 ', 'NC_082685.1 chromosome 3 ', 'NC_082686.1 chromosome 4 ', 'NC_082687.1 chromosome 5 ', 'NC_082688.1 chromosome 6 ', 'NC_082689.1 chromosome 7 ', 'NC_082690.1 chromosome 8 ', 'NC_082691.1 chromosome 9 ', 'NC_082692.1 chromosome 10 ', 'NC_082693.1 chromosome 11 ', 'NC_082694.1 chromosome 12 ', 'NC_082695.1 chromosome 13 ', 'NC_082696.1 chromosome 14 ', 'NC_082697.1 chromosome 15 ', 'NC_082698.1 chromosome 16 ', 'NC_082699.1 chromosome 17 ', 'NC_082700.1 chromosome 18 ', 'NC_082701.1 chromosome 19 ', 'NC_082702.1 chromosome 20 ', 'NC_082703.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_082704.1 chromosome X ': 252958184, 'NC_082683.1 chromosome 1 ': 369735110, 'NC_082684.1 chromosome 2 ': 356731664, 'NC_082685.1 chromosome 3 ': 346114934, 'NC_082686.1 chromosome 4 ': 289038024, 'NC_082687.1 chromosome 5 ': 278427586, 'NC_082688.1 chromosome 6 ': 233193856, 'NC_082689.1 chromosome 7 ': 231072564, 'NC_082690.1 chromosome 8 ': 221068098, 'NC_082691.1 chromosome 9 ': 214161966, 'NC_082692.1 chromosome 10 ': 209825618, 'NC_082693.1 chromosome 11 ': 204893786, 'NC_082694.1 chromosome 12 ': 179785098, 'NC_082695.1 chromosome 13 ': 179611866, 'NC_082696.1 chromosome 14 ': 177695210, 'NC_082697.1 chromosome 15 ': 176080914, 'NC_082698.1 chromosome 16 ': 170657774, 'NC_082699.1 chromosome 17 ': 161332118, 'NC_082700.1 chromosome 18 ': 157641024, 'NC_082701.1 chromosome 19 ': 120427388, 'NC_082702.1 chromosome 20 ': 118940318, 'NC_082703.1 chromosome 21 ': 71183194}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_082704.1 chromosome X ': 0.053586292911210386, 'NC_082683.1 chromosome 1 ': 0.07832414666614855, 'NC_082684.1 chromosome 2 ': 0.0755695156232126, 'NC_082685.1 chromosome 3 ': 0.07332048301812702, 'NC_082686.1 chromosome 4 ': 0.06122939361606683, 'NC_082687.1 chromosome 5 ': 0.05898169389908816, 'NC_082688.1 chromosome 6 ': 0.04939944648207396, 'NC_082689.1 chromosome 7 ': 0.048950075077422314, 'NC_082690.1 chromosome 8 ': 0.046830743585478, 'NC_082691.1 chromosome 9 ': 0.04536775865103728, 'NC_082692.1 chromosome 10 ': 0.044449153012672396, 'NC_082693.1 chromosome 11 ': 0.04340440091190273, 'NC_082694.1 chromosome 12 ': 0.038085413051900566, 'NC_082695.1 chromosome 13 ': 0.038048715837575235, 'NC_082696.1 chromosome 14 ': 0.037642694224825086, 'NC_082697.1 chromosome 15 ': 0.03730072411366475, 'NC_082698.1 chromosome 16 ': 0.03615189404245227, 'NC_082699.1 chromosome 17 ': 0.03417636067127189, 'NC_082700.1 chromosome 18 ': 0.03339444469955218, 'NC_082701.1 chromosome 19 ': 0.0255111623030152, 'NC_082702.1 chromosome 20 ': 0.02519614356221228, 'NC_082703.1 chromosome 21 ': 0.015079344039090326}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Bos taurus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_002263795.3
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_037357.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_037328.1 chromosome 1 ', 'NC_037329.1 chromosome 2 ', 'NC_037330.1 chromosome 3 ', 'NC_037331.1 chromosome 4 ', 'NC_037332.1 chromosome 5 ', 'NC_037333.1 chromosome 6 ', 'NC_037334.1 chromosome 7 ', 'NC_037335.1 chromosome 8 ', 'NC_037336.1 chromosome 9 ', 'NC_037337.1 chromosome 10 ', 'NC_037338.1 chromosome 11 ', 'NC_037339.1 chromosome 12 ', 'NC_037340.1 chromosome 13 ', 'NC_037341.1 chromosome 14 ', 'NC_037342.1 chromosome 15 ', 'NC_037343.1 chromosome 16 ', 'NC_037344.1 chromosome 17 ', 'NC_037345.1 chromosome 18 ', 'NC_037346.1 chromosome 19 ', 'NC_037347.1 chromosome 20 ', 'NC_037348.1 chromosome 21 ', 'NC_037349.1 chromosome 22 ', 'NC_037350.1 chromosome 23 ', 'NC_037351.1 chromosome 24 ', 'NC_037352.1 chromosome 25 ', 'NC_037353.1 chromosome 26 ', 'NC_037354.1 chromosome 27 ', 'NC_037355.1 chromosome 28 ', 'NC_037356.1 chromosome 29 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_037357.1 chromosome X ': 278018288, 'NC_037328.1 chromosome 1 ': 317068220, 'NC_037329.1 chromosome 2 ': 272462204, 'NC_037330.1 chromosome 3 ': 242010316, 'NC_037331.1 chromosome 4 ': 240001202, 'NC_037332.1 chromosome 5 ': 240178632, 'NC_037333.1 chromosome 6 ': 235612680, 'NC_037334.1 chromosome 7 ': 221365486, 'NC_037335.1 chromosome 8 ': 226639540, 'NC_037336.1 chromosome 9 ': 210908934, 'NC_037337.1 chromosome 10 ': 206617474, 'NC_037338.1 chromosome 11 ': 213964948, 'NC_037339.1 chromosome 12 ': 174432366, 'NC_037340.1 chromosome 13 ': 166944690, 'NC_037341.1 chromosome 14 ': 164806006, 'NC_037342.1 chromosome 15 ': 170015560, 'NC_037343.1 chromosome 16 ': 162027958, 'NC_037344.1 chromosome 17 ': 146334488, 'NC_037345.1 chromosome 18 ': 131641258, 'NC_037346.1 chromosome 19 ': 126899482, 'NC_037347.1 chromosome 20 ': 143949190, 'NC_037348.1 chromosome 21 ': 139725908, 'NC_037349.1 chromosome 22 ': 121546070, 'NC_037350.1 chromosome 23 ': 104997230, 'NC_037351.1 chromosome 24 ': 124634506, 'NC_037352.1 chromosome 25 ': 84700870, 'NC_037353.1 chromosome 26 ': 103984610, 'NC_037354.1 chromosome 27 ': 91224216, 'NC_037355.1 chromosome 28 ': 91880300, 'NC_037356.1 chromosome 29 ': 102197214}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_037357.1 chromosome X ': 0.052887464811162244, 'NC_037328.1 chromosome 1 ': 0.060315939820433144, 'NC_037329.1 chromosome 2 ': 0.051830530034850476, 'NC_037330.1 chromosome 3 ': 0.046037662354745004, 'NC_037331.1 chromosome 4 ': 0.045655468266935166, 'NC_037332.1 chromosome 5 ': 0.04568922080511871, 'NC_037333.1 chromosome 6 ': 0.04482063900258112, 'NC_037334.1 chromosome 7 ': 0.042110392936564045, 'NC_037335.1 chromosome 8 ': 0.04311367709942879, 'NC_037336.1 chromosome 9 ': 0.04012124132382522, 'NC_037337.1 chromosome 10 ': 0.03930487617975056, 'NC_037338.1 chromosome 11 ': 0.04070258737141839, 'NC_037339.1 chromosome 12 ': 0.033182297772989575, 'NC_037340.1 chromosome 13 ': 0.03175791593172241, 'NC_037341.1 chromosome 14 ': 0.03135107372142797, 'NC_037342.1 chromosome 15 ': 0.03234208803864746, 'NC_037343.1 chromosome 16 ': 0.030822605191891096, 'NC_037344.1 chromosome 17 ': 0.027837233803696553, 'NC_037345.1 chromosome 18 ': 0.02504213823578444, 'NC_037346.1 chromosome 19 ': 0.024140109404708357, 'NC_037347.1 chromosome 20 ': 0.027383478171480246, 'NC_037348.1 chromosome 21 ': 0.026580082539597875, 'NC_037349.1 chromosome 22 ': 0.023121728956406146, 'NC_037350.1 chromosome 23 ': 0.019973640391938923, 'NC_037351.1 chromosome 24 ': 0.023709242646410333, 'NC_037352.1 chromosome 25 ': 0.016112660479370437, 'NC_037353.1 chromosome 26 ': 0.019781009522213264, 'NC_037354.1 chromosome 27 ': 0.017353597665581855, 'NC_037355.1 chromosome 28 ': 0.017478404633183807, 'NC_037356.1 chromosome 29 ': 0.019440992886136387}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Pan paniscus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_029289425.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_073273.2 chromosome Y ', 'NC_073272.2 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_073249.2 chromosome 1 ', 'NC_073252.2 chromosome 3 ', 'NC_073253.2 chromosome 4 ', 'NC_073254.2 chromosome 5 ', 'NC_073255.2 chromosome 6 ', 'NC_073256.2 chromosome 7 ', 'NC_073257.2 chromosome 8 ', 'NC_073258.2 chromosome 9 ', 'NC_073259.2 chromosome 10 ', 'NC_073260.2 chromosome 11 ', 'NC_073261.2 chromosome 12 ', 'NC_073262.2 chromosome 13 ', 'NC_073263.2 chromosome 14 ', 'NC_073264.2 chromosome 15 ', 'NC_073265.2 chromosome 16 ', 'NC_073266.2 chromosome 17 ', 'NC_073267.2 chromosome 18 ', 'NC_073268.2 chromosome 19 ', 'NC_073269.2 chromosome 20 ', 'NC_073270.2 chromosome 21 ', 'NC_073271.2 chromosome 22 ', 'NC_085926.1 chromosome 2 ', 'NC_085927.1 chromosome 23 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_073273.2 chromosome Y ': 46954669, 'NC_073272.2 chromosome X ': 160241051, 'NC_073249.2 chromosome 1 ': 455410104, 'NC_073252.2 chromosome 3 ': 377228750, 'NC_073253.2 chromosome 4 ': 353102666, 'NC_073254.2 chromosome 5 ': 382303424, 'NC_073255.2 chromosome 6 ': 392619714, 'NC_073256.2 chromosome 7 ': 325587904, 'NC_073257.2 chromosome 8 ': 294056814, 'NC_073258.2 chromosome 9 ': 271500796, 'NC_073259.2 chromosome 10 ': 283630350, 'NC_073260.2 chromosome 11 ': 249517922, 'NC_073261.2 chromosome 12 ': 253102938, 'NC_073262.2 chromosome 13 ': 289744536, 'NC_073263.2 chromosome 14 ': 232252860, 'NC_073264.2 chromosome 15 ': 216905492, 'NC_073265.2 chromosome 16 ': 183719858, 'NC_073266.2 chromosome 17 ': 196540932, 'NC_073267.2 chromosome 18 ': 200854384, 'NC_073268.2 chromosome 19 ': 201584824, 'NC_073269.2 chromosome 20 ': 141442586, 'NC_073270.2 chromosome 21 ': 153582654, 'NC_073271.2 chromosome 22 ': 96966552, 'NC_085926.1 chromosome 2 ': 392863782, 'NC_085927.1 chromosome 23 ': 130104760}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_073273.2 chromosome Y ': 0.007474691505511036, 'NC_073272.2 chromosome X ': 0.025508696967789523, 'NC_073249.2 chromosome 1 ': 0.07249651862933369, 'NC_073252.2 chromosome 3 ': 0.060050865937518294, 'NC_073253.2 chromosome 4 ': 0.05621024605931096, 'NC_073254.2 chromosome 5 ': 0.060858700886605846, 'NC_073255.2 chromosome 6 ': 0.06250094620264435, 'NC_073256.2 chromosome 7 ': 0.05183018413623452, 'NC_073257.2 chromosome 8 ': 0.04681076486224275, 'NC_073258.2 chromosome 9 ': 0.04322008304649501, 'NC_073259.2 chromosome 10 ': 0.04515098099935753, 'NC_073260.2 chromosome 11 ': 0.03972063975248479, 'NC_073261.2 chromosome 12 ': 0.040291336750526055, 'NC_073262.2 chromosome 13 ': 0.04612429537108304, 'NC_073263.2 chromosome 14 ': 0.03697222271490496, 'NC_073264.2 chromosome 15 ': 0.03452908247635804, 'NC_073265.2 chromosome 16 ': 0.0292462771271222, 'NC_073266.2 chromosome 17 ': 0.031287257821061884, 'NC_073267.2 chromosome 18 ': 0.031973914200725206, 'NC_073268.2 chromosome 19 ': 0.03209019259815754, 'NC_073269.2 chromosome 20 ': 0.022516178233344893, 'NC_073270.2 chromosome 21 ': 0.024448749904884656, 'NC_073271.2 chromosome 22 ': 0.015436059458817484, 'NC_085926.1 chromosome 2 ': 0.06253979927189646, 'NC_085927.1 chromosome 23 ': 0.020711315085589294}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Rattus rattus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011064425.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_046172.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_046154.1 chromosome 1 ', 'NC_046155.1 chromosome 2 ', 'NC_046156.1 chromosome 3 ', 'NC_046157.1 chromosome 4 ', 'NC_046158.1 chromosome 5 ', 'NC_046159.1 chromosome 6 ', 'NC_046160.1 chromosome 7 ', 'NC_046161.1 chromosome 8 ', 'NC_046162.1 chromosome 9 ', 'NC_046163.1 chromosome 10 ', 'NC_046164.1 chromosome 11 ', 'NC_046165.1 chromosome 12 ', 'NC_046166.1 chromosome 13 ', 'NC_046167.1 chromosome 14 ', 'NC_046168.1 chromosome 15 ', 'NC_046169.1 chromosome 16 ', 'NC_046170.1 chromosome 17 ', 'NC_046171.1 chromosome 18 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_046172.1 chromosome X ': 260747026, 'NC_046154.1 chromosome 1 ': 545899780, 'NC_046155.1 chromosome 2 ': 460490430, 'NC_046156.1 chromosome 3 ': 446780580, 'NC_046157.1 chromosome 4 ': 365650368, 'NC_046158.1 chromosome 5 ': 317649504, 'NC_046159.1 chromosome 6 ': 319153832, 'NC_046160.1 chromosome 7 ': 261677498, 'NC_046161.1 chromosome 8 ': 230657978, 'NC_046162.1 chromosome 9 ': 193419404, 'NC_046163.1 chromosome 10 ': 189950930, 'NC_046164.1 chromosome 11 ': 197229706, 'NC_046165.1 chromosome 12 ': 188176076, 'NC_046166.1 chromosome 13 ': 157637022, 'NC_046167.1 chromosome 14 ': 163988198, 'NC_046168.1 chromosome 15 ': 158636486, 'NC_046169.1 chromosome 16 ': 88862024, 'NC_046170.1 chromosome 17 ': 97008248, 'NC_046171.1 chromosome 18 ': 99693070}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_046172.1 chromosome X ': 0.05497155512662285, 'NC_046154.1 chromosome 1 ': 0.11508840699061812, 'NC_046155.1 chromosome 2 ': 0.09708212379775047, 'NC_046156.1 chromosome 3 ': 0.09419176762911394, 'NC_046157.1 chromosome 4 ': 0.07708762653953312, 'NC_046158.1 chromosome 5 ': 0.0669679247658242, 'NC_046159.1 chromosome 6 ': 0.06728507219737542, 'NC_046160.1 chromosome 7 ': 0.055167720327915615, 'NC_046161.1 chromosome 8 ': 0.04862808196716445, 'NC_046162.1 chromosome 9 ': 0.040777321960882254, 'NC_046163.1 chromosome 10 ': 0.04004608673791078, 'NC_046164.1 chromosome 11 ': 0.04158062249955103, 'NC_046165.1 chromosome 12 ': 0.03967190611541461, 'NC_046166.1 chromosome 13 ': 0.03323356119455667, 'NC_046167.1 chromosome 14 ': 0.03457253723949489, 'NC_046168.1 chromosome 15 ': 0.03344427151871997, 'NC_046169.1 chromosome 16 ': 0.01873418740729677, 'NC_046170.1 chromosome 17 ': 0.020451601440965625, 'NC_046171.1 chromosome 18 ': 0.021017624543289214}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Bos javanicus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_032452875.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_083898.1 chromosome Y ', 'NC_083897.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_083868.1 chromosome 1 ', 'NC_083869.1 chromosome 2 ', 'NC_083870.1 chromosome 3 ', 'NC_083871.1 chromosome 4 ', 'NC_083872.1 chromosome 5 ', 'NC_083873.1 chromosome 6 ', 'NC_083874.1 chromosome 7 ', 'NC_083875.1 chromosome 8 ', 'NC_083876.1 chromosome 9 ', 'NC_083877.1 chromosome 10 ', 'NC_083878.1 chromosome 11 ', 'NC_083879.1 chromosome 12 ', 'NC_083880.1 chromosome 13 ', 'NC_083881.1 chromosome 14 ', 'NC_083882.1 chromosome 15 ', 'NC_083883.1 chromosome 16 ', 'NC_083884.1 chromosome 17 ', 'NC_083885.1 chromosome 18 ', 'NC_083886.1 chromosome 19 ', 'NC_083887.1 chromosome 20 ', 'NC_083888.1 chromosome 21 ', 'NC_083889.1 chromosome 22 ', 'NC_083890.1 chromosome 23 ', 'NC_083891.1 chromosome 24 ', 'NC_083892.1 chromosome 25 ', 'NC_083893.1 chromosome 26 ', 'NC_083894.1 chromosome 27 ', 'NC_083895.1 chromosome 28 ', 'NC_083896.1 chromosome 29 ']

{'labels': 1.0, 'species': 'Mus musculus', 'sampled_chromosomes': ['HeH_chr10', 'HeH_chr16', 'HeH_chr11', 'HeH_chr14', 'HeH_chr14', 'HeH_chr5', 'HeH_chr4', 'HeH_chr12', 'HeH_chr16', 'HeH_chr8'], 'chunks': ['AAGGACCACA', 'GGTGAAAAGC', 'ACACATCCCT', 'CTTTCGTCAC', 'AAACAGACTA', 'TACCCAAAAG', 'ATAATCTACA', 'ATATCCACGC', 'TGGGGATCAC', 'ACGTGTGCTT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Arvicanthis niloticus', 'sampled_chromosomes': ['NC_047662.1 chromosome 5 ', 'NC_047659.1 chromosome 2 ', 'NC_047662.1 chromosome 5 ', 'NC_047675.1 chromosome 18 ', 'NC_047668.1 chromosome 11 ', 'NC_047660.1 chromosome 3 ', 'NC_047658.1 chromosome 1 ', 'NC_047663.1 chromosome 6 ', 'NC_047658.1 chromosome 1 ', 'NC_047662.1 chromosome 5 '], 'chunks': ['TGTGTTTCCT', 'ACACGGCAGT', 'TGCAAGGCAA', 'CTGCTGCTGC', 'GATTCCCAAA', 'GGTGCTGGAG', 'TGTATTGTAT', 'AGTCATCATA', 'GGAAAAACAT', 'TCTGGTTGGT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Delphinus delphis', 'sampled_chromosomes': ['NC_082704.1 chromosome X ', 'NC_082685.1 chromosome 3 ', 'NC_082704.1 chromosome X ', 'NC_082696.1 chromosome 14 ', 'NC_082697.1 chromosome 15 ', 'NC_082694.1 chromosome 12 ', 'NC_082697.1 chromosome 15 ', 'NC_082687.1 chromosome 5 ', 'NC_082703.1 chromosome 21 ', 'NC_082690.1 chromosome 8 '], 'chunks': ['GCCCAGAAAT', 'AAAGTGTTTT', 'TGAACCTGCA', 'TCTTTGGGTA', 'GTAGTTTTCT', 'GCAACCAGAT', 'TTTTTGTGCA', 'CTAGGAATAG', 'ACTTCGGGGA', 'GTGCAAGGAG'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Bos taurus', 'sampled_chromosomes': ['NC_037349.1 chromosome 22 ', 'NC_037334.1 chromosome 7 ', 'NC_037338.1 chromosome 11 ', 'NC_037344.1 chromosome 17 ', 'NC_037343.1 chromosome 16 ', 'NC_037331.1 chromosome 4 ', 'NC_037334.1 chromosome 7 ', 'NC_037343.1 chromosome 16 ', 'NC_037331.1 chromosome 4 ', 'NC_037330.1 chromosome 3 '], 'chunks': ['ACCTATCAAT', 'CAGGGACTGG', 'CCTTGAATAT', 'CTCTCAAGAG', 'TCCCGCATTG', 'TTAGTCTATT', 'AGAGAATATA', 'AGCATTTTTA', 'TGGTATTGTT', 'CAAATAGAAA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Pan paniscus', 'sampled_chromosomes': ['NC_073253.2 chromosome 4 ', 'NC_073273.2 chromosome Y ', 'NC_073260.2 chromosome 11 ', 'NC_073260.2 chromosome 11 ', 'NC_073252.2 chromosome 3 ', 'NC_073252.2 chromosome 3 ', 'NC_073260.2 chromosome 11 ', 'NC_073258.2 chromosome 9 ', 'NC_073257.2 chromosome 8 ', 'NC_073253.2 chromosome 4 '], 'chunks': ['TTTTCACCAG', 'TTCTGTTTTT', 'TTACATTCCA', 'ATCAATAAAA', 'TGTGTTTCGT', 'AAAGCTTTGT', 'GACTCCATTC', 'GTTGGCCAGG', 'TTTAATCTTT', 'CACGAGGTCA'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Rattus rattus', 'sampled_chromosomes': ['NC_046154.1 chromosome 1 ', 'NC_046157.1 chromosome 4 ', 'NC_046154.1 chromosome 1 ', 'NC_046154.1 chromosome 1 ', 'NC_046172.1 chromosome X ', 'NC_046172.1 chromosome X ', 'NC_046157.1 chromosome 4 ', 'NC_046166.1 chromosome 13 ', 'NC_046163.1 chromosome 10 ', 'NC_046167.1 chromosome 14 '], 'chunks': ['AGAGAGAGAG', 'TTGCATAAAC', 'CTACAGCTTC', 'ACTCCAACTC', 'AATACCTTTG', 'AAGGACCAGT', 'AAACTCTTTC', 'TTGCATTTGC', 'AAAACACCAT', 'GCCAGCCTCA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}

DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Arvicanthis niloticus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011762505.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_047679.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_047658.1 chromosome 1 ', 'NC_047659.1 chromosome 2 ', 'NC_047660.1 chromosome 3 ', 'NC_047661.1 chromosome 4 ', 'NC_047662.1 chromosome 5 ', 'NC_047663.1 chromosome 6 ', 'NC_047664.1 chromosome 7 ', 'NC_047665.1 chromosome 8 ', 'NC_047666.1 chromosome 9 ', 'NC_047667.1 chromosome 10 ', 'NC_047668.1 chromosome 11 ', 'NC_047669.1 chromosome 12 ', 'NC_047670.1 chromosome 13 ', 'NC_047671.1 chromosome 14 ', 'NC_047672.1 chromosome 15 ', 'NC_047673.1 chromosome 16 ', 'NC_047674.1 chromosome 17 ', 'NC_047675.1 chromosome 18 ', 'NC_047676.1 chromosome 19 ', 'NC_047677.1 chromosome 20 ', 'NC_047678.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_047679.1 chromosome X ': 260706670, 'NC_047658.1 chromosome 1 ': 334233126, 'NC_047659.1 chromosome 2 ': 298647216, 'NC_047660.1 chromosome 3 ': 278543182, 'NC_047661.1 chromosome 4 ': 270236198, 'NC_047662.1 chromosome 5 ': 217382080, 'NC_047663.1 chromosome 6 ': 217296002, 'NC_047664.1 chromosome 7 ': 182853410, 'NC_047665.1 chromosome 8 ': 176469402, 'NC_047666.1 chromosome 9 ': 172772988, 'NC_047667.1 chromosome 10 ': 165378234, 'NC_047668.1 chromosome 11 ': 161882470, 'NC_047669.1 chromosome 12 ': 159107368, 'NC_047670.1 chromosome 13 ': 156082964, 'NC_047671.1 chromosome 14 ': 152795984, 'NC_047672.1 chromosome 15 ': 147790464, 'NC_047673.1 chromosome 16 ': 146846972, 'NC_047674.1 chromosome 17 ': 128083624, 'NC_047675.1 chromosome 18 ': 109678282, 'NC_047676.1 chromosome 19 ': 106271352, 'NC_047677.1 chromosome 20 ': 104862384, 'NC_047678.1 chromosome 21 ': 104166660}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_047679.1 chromosome X ': 0.06433886240378264, 'NC_047658.1 chromosome 1 ': 0.08248419230892769, 'NC_047659.1 chromosome 2 ': 0.07370207343562309, 'NC_047660.1 chromosome 3 ': 0.06874067111597025, 'NC_047661.1 chromosome 4 ': 0.0666906203805348, 'NC_047662.1 chromosome 5 ': 0.05364694249735947, 'NC_047663.1 chromosome 6 ': 0.053625699617006646, 'NC_047664.1 chromosome 7 ': 0.0451257360851276, 'NC_047665.1 chromosome 8 ': 0.04355024968772685, 'NC_047666.1 chromosome 9 ': 0.04263802495740669, 'NC_047667.1 chromosome 10 ': 0.04081310018614625, 'NC_047668.1 chromosome 11 ': 0.03995039314841646, 'NC_047669.1 chromosome 12 ': 0.03926553569642085, 'NC_047670.1 chromosome 13 ': 0.038519153899555236, 'NC_047671.1 chromosome 14 ': 0.0377079719150514, 'NC_047672.1 chromosome 15 ': 0.03647267761844065, 'NC_047673.1 chromosome 16 ': 0.036239836617606, 'NC_047674.1 chromosome 17 ': 0.031609297378980876, 'NC_047675.1 chromosome 18 ': 0.02706710915482627, 'NC_047676.1 chromosome 19 ': 0.026226325140787352, 'NC_047677.1 chromosome 20 ': 0.025878610990308068, 'NC_047678.1 chromosome 21 ': 0.025706915763994875}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Mustela lutreola
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_030435805.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_081309.1 chromosome Y ', 'NW_026709260.1 chromosome Y unlocalized genomic scaffold', 'NC_081308.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_081290.1 chromosome 1 ', 'NC_081291.1 chromosome 2 ', 'NC_081292.1 chromosome 3 ', 'NC_081293.1 chromosome 4 ', 'NC_081294.1 chromosome 5 ', 'NC_081295.1 chromosome 6 ', 'NC_081296.1 chromosome 7 ', 'NC_081297.1 chromosome 8 ', 'NC_081298.1 chromosome 9 ', 'NC_081299.1 chromosome 10 ', 'NC_081300.1 chromosome 11 ', 'NC_081301.1 chromosome 12 ', 'NC_081302.1 chromosome 13 ', 'NC_081303.1 chromosome 14 ', 'NC_081304.1 chromosome 15 ', 'NC_081305.1 chromosome 16 ', 'NC_081306.1 chromosome 17 ', 'NC_081307.1 chromosome 18 ', 'NW_026709257.1 chromosome 4 unlocalized genomic scaffold', 'NW_026709258.1 chromosome 5 unlocalized genomic scaffold', 'NW_026709259.1 chromosome 16 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_081309.1 chromosome Y ': 6758561, 'NW_026709260.1 chromosome Y unlocalized genomic scaffold': 1017074, 'NC_081308.1 chromosome X ': 133082756, 'NC_081290.1 chromosome 1 ': 580209788, 'NC_081291.1 chromosome 2 ': 450360622, 'NC_081292.1 chromosome 3 ': 422582014, 'NC_081293.1 chromosome 4 ': 405148736, 'NC_081294.1 chromosome 5 ': 354945442, 'NC_081295.1 chromosome 6 ': 320021132, 'NC_081296.1 chromosome 7 ': 308157286, 'NC_081297.1 chromosome 8 ': 303022374, 'NC_081298.1 chromosome 9 ': 292543060, 'NC_081299.1 chromosome 10 ': 247627348, 'NC_081300.1 chromosome 11 ': 209097952, 'NC_081301.1 chromosome 12 ': 201223108, 'NC_081302.1 chromosome 13 ': 184206380, 'NC_081303.1 chromosome 14 ': 151745266, 'NC_081304.1 chromosome 15 ': 141844742, 'NC_081305.1 chromosome 16 ': 128067692, 'NC_081306.1 chromosome 17 ': 98796040, 'NC_081307.1 chromosome 18 ': 84746544, 'NW_026709257.1 chromosome 4 unlocalized genomic scaffold': 1395006, 'NW_026709258.1 chromosome 5 unlocalized genomic scaffold': 2109010, 'NW_026709259.1 chromosome 16 unlocalized genomic scaffold': 2893842}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_081309.1 chromosome Y ': 0.0013432225565982911, 'NW_026709260.1 chromosome Y unlocalized genomic scaffold': 0.00020213722100453785, 'NC_081308.1 chromosome X ': 0.026449381718011658, 'NC_081290.1 chromosome 1 ': 0.11531313763398933, 'NC_081291.1 chromosome 2 ': 0.08950641210074699, 'NC_081292.1 chromosome 3 ': 0.0839855840936458, 'NC_081293.1 chromosome 4 ': 0.08052082698853885, 'NC_081294.1 chromosome 5 ': 0.07054323014265174, 'NC_081295.1 chromosome 6 ': 0.06360223767907387, 'NC_081296.1 chromosome 7 ': 0.061244371033317715, 'NC_081297.1 chromosome 8 ': 0.060223838759576716, 'NC_081298.1 chromosome 9 ': 0.05814113935914573, 'NC_081299.1 chromosome 10 ': 0.04921441701335754, 'NC_081300.1 chromosome 11 ': 0.04155693581294994, 'NC_081301.1 chromosome 12 ': 0.03999185885492697, 'NC_081302.1 chromosome 13 ': 0.03660988850811827, 'NC_081303.1 chromosome 14 ': 0.030158441145712492, 'NC_081304.1 chromosome 15 ': 0.028190772708756348, 'NC_081305.1 chromosome 16 ': 0.02545266849938656, 'NC_081306.1 chromosome 17 ': 0.01963510715233421, 'NC_081307.1 chromosome 18 ': 0.0168428559710491, 'NW_026709257.1 chromosome 4 unlocalized genomic scaffold': 0.0002772488886006882, 'NW_026709258.1 chromosome 5 unlocalized genomic scaffold': 0.0004191528054701825, 'NW_026709259.1 chromosome 16 unlocalized genomic scaffold': 0.0005751333530364692}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Piliocolobus tephrosceles
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_002776525.5
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_045456.1 chromosome Y ', 'NC_045455.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_045434.1 chromosome 1 ', 'NC_045435.1 chromosome 2 ', 'NC_045436.1 chromosome 3 ', 'NC_045437.1 chromosome 4 ', 'NC_045438.1 chromosome 5 ', 'NC_045439.1 chromosome 6 ', 'NC_045440.1 chromosome 7 ', 'NC_045441.1 chromosome 8 ', 'NC_045442.1 chromosome 9 ', 'NC_045443.1 chromosome 10 ', 'NC_045444.1 chromosome 11 ', 'NC_045445.1 chromosome 12 ', 'NC_045446.1 chromosome 13 ', 'NC_045447.1 chromosome 14 ', 'NC_045448.1 chromosome 15 ', 'NC_045449.1 chromosome 16 ', 'NC_045450.1 chromosome 17 ', 'NC_045451.1 chromosome 18 ', 'NC_045452.1 chromosome 19 ', 'NC_045453.1 chromosome 20 ', 'NC_045454.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_045456.1 chromosome Y ': 26487807, 'NC_045455.1 chromosome X ': 95246109, 'NC_045434.1 chromosome 1 ': 442090666, 'NC_045435.1 chromosome 2 ': 387364770, 'NC_045436.1 chromosome 3 ': 369293928, 'NC_045437.1 chromosome 4 ': 357735212, 'NC_045438.1 chromosome 5 ': 336804120, 'NC_045439.1 chromosome 6 ': 326826152, 'NC_045440.1 chromosome 7 ': 297312896, 'NC_045441.1 chromosome 8 ': 295585868, 'NC_045442.1 chromosome 9 ': 262566228, 'NC_045443.1 chromosome 10 ': 261620716, 'NC_045444.1 chromosome 11 ': 256363946, 'NC_045445.1 chromosome 12 ': 249569366, 'NC_045446.1 chromosome 13 ': 248118162, 'NC_045447.1 chromosome 14 ': 222884816, 'NC_045448.1 chromosome 15 ': 216416848, 'NC_045449.1 chromosome 16 ': 154195728, 'NC_045450.1 chromosome 17 ': 149826520, 'NC_045451.1 chromosome 18 ': 147851294, 'NC_045452.1 chromosome 19 ': 138641668, 'NC_045453.1 chromosome 20 ': 116473160, 'NC_045454.1 chromosome 21 ': 105352426}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_045456.1 chromosome Y ': 0.004847137816528783, 'NC_045455.1 chromosome X ': 0.017429567378345907, 'NC_045434.1 chromosome 1 ': 0.08090040770468447, 'NC_045435.1 chromosome 2 ': 0.07088583911299165, 'NC_045436.1 chromosome 3 ': 0.06757896430698311, 'NC_045437.1 chromosome 4 ': 0.06546377638545695, 'NC_045438.1 chromosome 5 ': 0.061633489960671264, 'NC_045439.1 chromosome 6 ': 0.059807571113372426, 'NC_045440.1 chromosome 7 ': 0.05440679107724127, 'NC_045441.1 chromosome 8 ': 0.054090753485718346, 'NC_045442.1 chromosome 9 ': 0.04804832250107072, 'NC_045443.1 chromosome 10 ': 0.047875298476424896, 'NC_045444.1 chromosome 11 ': 0.046913335537786975, 'NC_045445.1 chromosome 12 ': 0.04566996096678417, 'NC_045446.1 chromosome 13 ': 0.04540439780453756, 'NC_045447.1 chromosome 14 ': 0.040786820153275026, 'NC_045448.1 chromosome 15 ': 0.039603213964627626, 'NC_045449.1 chromosome 16 ': 0.02821705641150232, 'NC_045450.1 chromosome 17 ': 0.027417512933815395, 'NC_045451.1 chromosome 18 ': 0.027056056334528376, 'NC_045452.1 chromosome 19 ': 0.025370740277193517, 'NC_045453.1 chromosome 20 ': 0.021314012837929826, 'NC_045454.1 chromosome 21 ': 0.01927897345852943}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Tursiops truncatus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011762595.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NW_022983135.1 chromosome Y unlocalized genomic scaffold', 'NW_022983136.1 chromosome Y unlocalized genomic scaffold', 'NW_022983137.1 chromosome Y unlocalized genomic scaffold', 'NW_022983138.1 chromosome Y unlocalized genomic scaffold', 'NC_047055.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_047034.1 chromosome 1 ', 'NC_047035.1 chromosome 2 ', 'NC_047036.1 chromosome 3 ', 'NC_047037.1 chromosome 4 ', 'NC_047038.1 chromosome 5 ', 'NC_047039.1 chromosome 6 ', 'NC_047040.1 chromosome 7 ', 'NC_047041.1 chromosome 8 ', 'NC_047042.1 chromosome 9 ', 'NC_047043.1 chromosome 10 ', 'NC_047044.1 chromosome 11 ', 'NC_047045.1 chromosome 12 ', 'NC_047046.1 chromosome 13 ', 'NC_047047.1 chromosome 14 ', 'NC_047048.1 chromosome 15 ', 'NC_047049.1 chromosome 16 ', 'NC_047050.1 chromosome 17 ', 'NC_047051.1 chromosome 18 ', 'NC_047052.1 chromosome 19 ', 'NC_047053.1 chromosome 20 ', 'NC_047054.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NW_022983135.1 chromosome Y unlocalized genomic scaffold': 7055931, 'NW_022983136.1 chromosome Y unlocalized genomic scaffold': 4926226, 'NW_022983137.1 chromosome Y unlocalized genomic scaffold': 596945, 'NW_022983138.1 chromosome Y unlocalized genomic scaffold': 124658, 'NC_047055.1 chromosome X ': 128693445, 'NC_047034.1 chromosome 1 ': 367485760, 'NC_047035.1 chromosome 2 ': 352945496, 'NC_047036.1 chromosome 3 ': 342843538, 'NC_047037.1 chromosome 4 ': 288366400, 'NC_047038.1 chromosome 5 ': 274975098, 'NC_047039.1 chromosome 6 ': 231199232, 'NC_047040.1 chromosome 7 ': 228030614, 'NC_047041.1 chromosome 8 ': 216860270, 'NC_047042.1 chromosome 9 ': 210670356, 'NC_047043.1 chromosome 10 ': 205625018, 'NC_047044.1 chromosome 11 ': 204335466, 'NC_047045.1 chromosome 12 ': 178661934, 'NC_047046.1 chromosome 13 ': 176970138, 'NC_047047.1 chromosome 14 ': 176966308, 'NC_047048.1 chromosome 15 ': 172587980, 'NC_047049.1 chromosome 16 ': 167017088, 'NC_047050.1 chromosome 17 ': 156885544, 'NC_047051.1 chromosome 18 ': 156303926, 'NC_047052.1 chromosome 19 ': 117272254, 'NC_047053.1 chromosome 20 ': 116934582, 'NC_047054.1 chromosome 21 ': 71364496}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NW_022983135.1 chromosome Y unlocalized genomic scaffold': 0.0015488142346537443, 'NW_022983136.1 chromosome Y unlocalized genomic scaffold': 0.001081332704631235, 'NW_022983137.1 chromosome Y unlocalized genomic scaffold': 0.00013103258993113443, 'NW_022983138.1 chromosome Y unlocalized genomic scaffold': 2.7363091399769418e-05, 'NC_047055.1 chromosome X ': 0.028248892955816705, 'NC_047034.1 chromosome 1 ': 0.08066507114660695, 'NC_047035.1 chromosome 2 ': 0.07747340616875734, 'NC_047036.1 chromosome 3 ': 0.07525597287068876, 'NC_047037.1 chromosome 4 ': 0.0632979524765556, 'NC_047038.1 chromosome 5 ': 0.060358490744553524, 'NC_047039.1 chromosome 6 ': 0.0507494562464703, 'NC_047040.1 chromosome 7 ': 0.05005392780910604, 'NC_047041.1 chromosome 8 ': 0.04760197812405682, 'NC_047042.1 chromosome 9 ': 0.046243259208794955, 'NC_047043.1 chromosome 10 ': 0.04513578078914496, 'NC_047044.1 chromosome 11 ': 0.04485271729349481, 'NC_047045.1 chromosome 12 ': 0.039217241009013235, 'NC_047046.1 chromosome 13 ': 0.03884588282439801, 'NC_047047.1 chromosome 14 ': 0.03884504211910785, 'NC_047048.1 chromosome 15 ': 0.037883975928071814, 'NC_047049.1 chromosome 16 ': 0.03666113562119826, 'NC_047050.1 chromosome 17 ': 0.03443720803939215, 'NC_047051.1 chromosome 18 ': 0.03430953980715875, 'NC_047052.1 chromosome 19 ': 0.025741881025357176, 'NC_047053.1 chromosome 20 ': 0.025667760232474707, 'NC_047054.1 chromosome 21 ': 0.01566488493916539}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Neomonachus schauinslandi
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_002201575.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_058419.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_058403.1 chromosome 1 ', 'NC_058404.1 chromosome 2 ', 'NC_058405.1 chromosome 3 ', 'NC_058406.1 chromosome 4 ', 'NC_058407.1 chromosome 5 ', 'NC_058408.1 chromosome 6 ', 'NC_058409.1 chromosome 7 ', 'NC_058410.1 chromosome 8 ', 'NC_058411.1 chromosome 9 ', 'NC_058412.1 chromosome 10 ', 'NC_058413.1 chromosome 11 ', 'NC_058414.1 chromosome 12 ', 'NC_058415.1 chromosome 13 ', 'NC_058416.1 chromosome 14 ', 'NC_058417.1 chromosome 15 ', 'NC_058418.1 chromosome 16 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_058419.1 chromosome X ': 252989786, 'NC_058403.1 chromosome 1 ': 429366354, 'NC_058404.1 chromosome 2 ': 407736248, 'NC_058405.1 chromosome 3 ': 385675150, 'NC_058406.1 chromosome 4 ': 376368364, 'NC_058407.1 chromosome 5 ': 352990000, 'NC_058408.1 chromosome 6 ': 309600356, 'NC_058409.1 chromosome 7 ': 301621650, 'NC_058410.1 chromosome 8 ': 291868190, 'NC_058411.1 chromosome 9 ': 287733078, 'NC_058412.1 chromosome 10 ': 276814350, 'NC_058413.1 chromosome 11 ': 222157914, 'NC_058414.1 chromosome 12 ': 211869670, 'NC_058415.1 chromosome 13 ': 187349136, 'NC_058416.1 chromosome 14 ': 184857912, 'NC_058417.1 chromosome 15 ': 120033060, 'NC_058418.1 chromosome 16 ': 118930010}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_058419.1 chromosome X ': 0.05362269289085391, 'NC_058403.1 chromosome 1 ': 0.09100675763332068, 'NC_058404.1 chromosome 2 ': 0.08642212775725676, 'NC_058405.1 chromosome 3 ': 0.08174614655820144, 'NC_058406.1 chromosome 4 ': 0.07977351779966768, 'NC_058407.1 chromosome 5 ': 0.07481833422137653, 'NC_058408.1 chromosome 6 ': 0.06562164058547028, 'NC_058409.1 chromosome 7 ': 0.06393050629792077, 'NC_058410.1 chromosome 8 ': 0.061863202323035285, 'NC_058411.1 chromosome 9 ': 0.06098674069052778, 'NC_058412.1 chromosome 10 ': 0.058672451218371904, 'NC_058413.1 chromosome 11 ': 0.04708769387114599, 'NC_058414.1 chromosome 12 ': 0.04490703924029789, 'NC_058415.1 chromosome 13 ': 0.039709765923493935, 'NC_058416.1 chromosome 14 ': 0.039181736149697756, 'NC_058417.1 chromosome 15 ': 0.025441722430365, 'NC_058418.1 chromosome 16 ': 0.025207924408996437}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002

{'labels': 0, 'species': 'Bos javanicus', 'sampled_chromosomes': ['NC_083875.1 chromosome 8 ', 'NC_083871.1 chromosome 4 ', 'NC_083896.1 chromosome 29 ', 'NC_083875.1 chromosome 8 ', 'NC_083868.1 chromosome 1 ', 'NC_083868.1 chromosome 1 ', 'NC_083878.1 chromosome 11 ', 'NC_083891.1 chromosome 24 ', 'NC_083898.1 chromosome Y ', 'NC_083878.1 chromosome 11 '], 'chunks': ['CATGGAACAA', 'CCCAAAGCCA', 'TCTTTGCCAG', 'AATCTCATTT', 'AATCCTAGGA', 'AAGAATTGGG', 'GTGGTTCGGA', 'GAACGGGATG', 'GTTATCACTT', 'AAAAGGTGGA'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Arvicanthis niloticus', 'sampled_chromosomes': ['NC_047668.1 chromosome 11 ', 'NC_047676.1 chromosome 19 ', 'NC_047665.1 chromosome 8 ', 'NC_047675.1 chromosome 18 ', 'NC_047668.1 chromosome 11 ', 'NC_047660.1 chromosome 3 ', 'NC_047658.1 chromosome 1 ', 'NC_047670.1 chromosome 13 ', 'NC_047662.1 chromosome 5 ', 'NC_047679.1 chromosome X '], 'chunks': ['CAACCTAAGA', 'AAACACACCT', 'CTTTTTTTTA', 'ACAACTCTCT', 'ATGTTTACGA', 'AAGTGCTGCC', 'TTAGGAAAGG', 'ATGGTCCCTC', 'GGTGCCCTTG', 'GACATTGTGC'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 0, 'species': 'Mustela lutreola', 'sampled_chromosomes': ['NC_081294.1 chromosome 5 ', 'NC_081295.1 chromosome 6 ', 'NC_081290.1 chromosome 1 ', 'NC_081309.1 chromosome Y ', 'NC_081296.1 chromosome 7 ', 'NC_081298.1 chromosome 9 ', 'NC_081290.1 chromosome 1 ', 'NC_081290.1 chromosome 1 ', 'NC_081292.1 chromosome 3 ', 'NC_081303.1 chromosome 14 '], 'chunks': ['GTCCAGGGAA', 'CAATTTATAT', 'GAGCATCGAA', 'ATGTAATACA', 'TGCTGTTGCC', 'TTGGATTTGG', 'GAAAGAAACC', 'AGATAAATCC', 'ATAACCTGCT', 'ATACCTTAGT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Piliocolobus tephrosceles', 'sampled_chromosomes': ['NC_045442.1 chromosome 9 ', 'NC_045456.1 chromosome Y ', 'NC_045436.1 chromosome 3 ', 'NC_045434.1 chromosome 1 ', 'NC_045439.1 chromosome 6 ', 'NC_045438.1 chromosome 5 ', 'NC_045438.1 chromosome 5 ', 'NC_045450.1 chromosome 17 ', 'NC_045446.1 chromosome 13 ', 'NC_045438.1 chromosome 5 '], 'chunks': ['CAAAGGAGGA', 'CACTTCTGGT', 'CCTGTCTTAC', 'TGCTCTTAAT', 'CATTGTTTTT', 'TGTTGAATAT', 'TTGTTTTTTT', 'AGACTTTTGT', 'TTATAGGGAT', 'GAATAACCTT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Tursiops truncatus', 'sampled_chromosomes': ['NC_047041.1 chromosome 8 ', 'NC_047035.1 chromosome 2 ', 'NW_022983137.1 chromosome Y unlocalized genomic scaffold', 'NC_047046.1 chromosome 13 ', 'NC_047038.1 chromosome 5 ', 'NC_047048.1 chromosome 15 ', 'NC_047040.1 chromosome 7 ', 'NC_047037.1 chromosome 4 ', 'NC_047039.1 chromosome 6 ', 'NC_047044.1 chromosome 11 '], 'chunks': ['TGGACACATG', 'TAACATAATT', 'GCAGATTTCA', 'GGAACATTTG', 'ACCACAACGA', 'CCTCATATCT', 'AGAGGAAATC', 'ATGTATCCAT', 'GTGAAATTTA', 'GAAGTCAGTC'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Pan paniscus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_029289425.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_073272.2 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_073249.2 chromosome 1 ', 'NC_073252.2 chromosome 3 ', 'NC_073253.2 chromosome 4 ', 'NC_073254.2 chromosome 5 ', 'NC_073255.2 chromosome 6 ', 'NC_073256.2 chromosome 7 ', 'NC_073257.2 chromosome 8 ', 'NC_073258.2 chromosome 9 ', 'NC_073259.2 chromosome 10 ', 'NC_073260.2 chromosome 11 ', 'NC_073261.2 chromosome 12 ', 'NC_073262.2 chromosome 13 ', 'NC_073263.2 chromosome 14 ', 'NC_073264.2 chromosome 15 ', 'NC_073265.2 chromosome 16 ', 'NC_073266.2 chromosome 17 ', 'NC_073267.2 chromosome 18 ', 'NC_073268.2 chromosome 19 ', 'NC_073269.2 chromosome 20 ', 'NC_073270.2 chromosome 21 ', 'NC_073271.2 chromosome 22 ', 'NC_085926.1 chromosome 2 ', 'NC_085927.1 chromosome 23 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_073272.2 chromosome X ': 320482102, 'NC_073249.2 chromosome 1 ': 455410104, 'NC_073252.2 chromosome 3 ': 377228750, 'NC_073253.2 chromosome 4 ': 353102666, 'NC_073254.2 chromosome 5 ': 382303424, 'NC_073255.2 chromosome 6 ': 392619714, 'NC_073256.2 chromosome 7 ': 325587904, 'NC_073257.2 chromosome 8 ': 294056814, 'NC_073258.2 chromosome 9 ': 271500796, 'NC_073259.2 chromosome 10 ': 283630350, 'NC_073260.2 chromosome 11 ': 249517922, 'NC_073261.2 chromosome 12 ': 253102938, 'NC_073262.2 chromosome 13 ': 289744536, 'NC_073263.2 chromosome 14 ': 232252860, 'NC_073264.2 chromosome 15 ': 216905492, 'NC_073265.2 chromosome 16 ': 183719858, 'NC_073266.2 chromosome 17 ': 196540932, 'NC_073267.2 chromosome 18 ': 200854384, 'NC_073268.2 chromosome 19 ': 201584824, 'NC_073269.2 chromosome 20 ': 141442586, 'NC_073270.2 chromosome 21 ': 153582654, 'NC_073271.2 chromosome 22 ': 96966552, 'NC_085926.1 chromosome 2 ': 392863782, 'NC_085927.1 chromosome 23 ': 130104760}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_073272.2 chromosome X ': 0.050113644202300085, 'NC_073249.2 chromosome 1 ': 0.07121227605399467, 'NC_073252.2 chromosome 3 ': 0.05898709239113268, 'NC_073253.2 chromosome 4 ': 0.05521450733248, 'NC_073254.2 chromosome 5 ': 0.05978061691462905, 'NC_073255.2 chromosome 6 ': 0.06139377060814715, 'NC_073256.2 chromosome 7 ': 0.05091203619735568, 'NC_073257.2 chromosome 8 ': 0.04598153363353169, 'NC_073258.2 chromosome 9 ': 0.04245445909920192, 'NC_073259.2 chromosome 10 ': 0.044351152080479815, 'NC_073260.2 chromosome 11 ': 0.039017006838045716, 'NC_073261.2 chromosome 12 ': 0.03957759420052986, 'NC_073262.2 chromosome 13 ': 0.045307224634543015, 'NC_073263.2 chromosome 14 ': 0.03631727674766254, 'NC_073264.2 chromosome 15 ': 0.03391741561783955, 'NC_073265.2 chromosome 16 ': 0.028728192742286416, 'NC_073266.2 chromosome 17 ': 0.03073301839937525, 'NC_073267.2 chromosome 18 ': 0.03140751097622342, 'NC_073268.2 chromosome 19 ': 0.03152172955517898, 'NC_073269.2 chromosome 20 ': 0.022117314463499217, 'NC_073270.2 chromosome 21 ': 0.02401565151429567, 'NC_073271.2 chromosome 22 ': 0.015162616745604813, 'NC_085926.1 chromosome 2 ': 0.061431935413098306, 'NC_085927.1 chromosome 23 ': 0.020344423638564514}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Tursiops truncatus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011762595.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_047055.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_047034.1 chromosome 1 ', 'NC_047035.1 chromosome 2 ', 'NC_047036.1 chromosome 3 ', 'NC_047037.1 chromosome 4 ', 'NC_047038.1 chromosome 5 ', 'NC_047039.1 chromosome 6 ', 'NC_047040.1 chromosome 7 ', 'NC_047041.1 chromosome 8 ', 'NC_047042.1 chromosome 9 ', 'NC_047043.1 chromosome 10 ', 'NC_047044.1 chromosome 11 ', 'NC_047045.1 chromosome 12 ', 'NC_047046.1 chromosome 13 ', 'NC_047047.1 chromosome 14 ', 'NC_047048.1 chromosome 15 ', 'NC_047049.1 chromosome 16 ', 'NC_047050.1 chromosome 17 ', 'NC_047051.1 chromosome 18 ', 'NC_047052.1 chromosome 19 ', 'NC_047053.1 chromosome 20 ', 'NC_047054.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_047055.1 chromosome X ': 257386890, 'NC_047034.1 chromosome 1 ': 367485760, 'NC_047035.1 chromosome 2 ': 352945496, 'NC_047036.1 chromosome 3 ': 342843538, 'NC_047037.1 chromosome 4 ': 288366400, 'NC_047038.1 chromosome 5 ': 274975098, 'NC_047039.1 chromosome 6 ': 231199232, 'NC_047040.1 chromosome 7 ': 228030614, 'NC_047041.1 chromosome 8 ': 216860270, 'NC_047042.1 chromosome 9 ': 210670356, 'NC_047043.1 chromosome 10 ': 205625018, 'NC_047044.1 chromosome 11 ': 204335466, 'NC_047045.1 chromosome 12 ': 178661934, 'NC_047046.1 chromosome 13 ': 176970138, 'NC_047047.1 chromosome 14 ': 176966308, 'NC_047048.1 chromosome 15 ': 172587980, 'NC_047049.1 chromosome 16 ': 167017088, 'NC_047050.1 chromosome 17 ': 156885544, 'NC_047051.1 chromosome 18 ': 156303926, 'NC_047052.1 chromosome 19 ': 117272254, 'NC_047053.1 chromosome 20 ': 116934582, 'NC_047054.1 chromosome 21 ': 71364496}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_047055.1 chromosome X ': 0.055095046720397826, 'NC_047034.1 chromosome 1 ': 0.07866230139491916, 'NC_047035.1 chromosome 2 ': 0.0755498797622287, 'NC_047036.1 chromosome 3 ': 0.0733875013754449, 'NC_047037.1 chromosome 4 ': 0.06172637728593297, 'NC_047038.1 chromosome 5 ': 0.05885989714260882, 'NC_047039.1 chromosome 6 ': 0.049489437821639226, 'NC_047040.1 chromosome 7 ': 0.048811178114048476, 'NC_047041.1 chromosome 8 ': 0.04642010596362576, 'NC_047042.1 chromosome 9 ': 0.045095121614091696, 'NC_047043.1 chromosome 10 ': 0.044015139907058375, 'NC_047044.1 chromosome 11 ': 0.04373910437281503, 'NC_047045.1 chromosome 12 ': 0.03824354690670777, 'NC_047046.1 chromosome 13 ': 0.037881408883044705, 'NC_047047.1 chromosome 14 ': 0.03788058905096647, 'NC_047048.1 chromosome 15 ': 0.03694338441821604, 'NC_047049.1 chromosome 16 ': 0.0357509050537298, 'NC_047050.1 chromosome 17 ': 0.03358219362468317, 'NC_047051.1 chromosome 18 ': 0.03345769516680358, 'NC_047052.1 chromosome 19 ': 0.02510275606164852, 'NC_047053.1 chromosome 20 ': 0.025030475555768168, 'NC_047054.1 chromosome 21 ': 0.01527595380362086}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Delphinus delphis
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_949987515.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_082705.1 chromosome Y ', 'NC_082704.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_082683.1 chromosome 1 ', 'NC_082684.1 chromosome 2 ', 'NC_082685.1 chromosome 3 ', 'NC_082686.1 chromosome 4 ', 'NC_082687.1 chromosome 5 ', 'NC_082688.1 chromosome 6 ', 'NC_082689.1 chromosome 7 ', 'NC_082690.1 chromosome 8 ', 'NC_082691.1 chromosome 9 ', 'NC_082692.1 chromosome 10 ', 'NC_082693.1 chromosome 11 ', 'NC_082694.1 chromosome 12 ', 'NC_082695.1 chromosome 13 ', 'NC_082696.1 chromosome 14 ', 'NC_082697.1 chromosome 15 ', 'NC_082698.1 chromosome 16 ', 'NC_082699.1 chromosome 17 ', 'NC_082700.1 chromosome 18 ', 'NC_082701.1 chromosome 19 ', 'NC_082702.1 chromosome 20 ', 'NC_082703.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_082705.1 chromosome Y ': 4078762, 'NC_082704.1 chromosome X ': 126479092, 'NC_082683.1 chromosome 1 ': 369735110, 'NC_082684.1 chromosome 2 ': 356731664, 'NC_082685.1 chromosome 3 ': 346114934, 'NC_082686.1 chromosome 4 ': 289038024, 'NC_082687.1 chromosome 5 ': 278427586, 'NC_082688.1 chromosome 6 ': 233193856, 'NC_082689.1 chromosome 7 ': 231072564, 'NC_082690.1 chromosome 8 ': 221068098, 'NC_082691.1 chromosome 9 ': 214161966, 'NC_082692.1 chromosome 10 ': 209825618, 'NC_082693.1 chromosome 11 ': 204893786, 'NC_082694.1 chromosome 12 ': 179785098, 'NC_082695.1 chromosome 13 ': 179611866, 'NC_082696.1 chromosome 14 ': 177695210, 'NC_082697.1 chromosome 15 ': 176080914, 'NC_082698.1 chromosome 16 ': 170657774, 'NC_082699.1 chromosome 17 ': 161332118, 'NC_082700.1 chromosome 18 ': 157641024, 'NC_082701.1 chromosome 19 ': 120427388, 'NC_082702.1 chromosome 20 ': 118940318, 'NC_082703.1 chromosome 21 ': 71183194}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_082705.1 chromosome Y ': 0.0008870391285443203, 'NC_082704.1 chromosome X ': 0.027506361868321054, 'NC_082683.1 chromosome 1 ': 0.08040908240457237, 'NC_082684.1 chromosome 2 ': 0.0775811249488755, 'NC_082685.1 chromosome 3 ': 0.07527222461902286, 'NC_082686.1 chromosome 4 ': 0.06285927860589373, 'NC_082687.1 chromosome 5 ': 0.060551746644726706, 'NC_082688.1 chromosome 6 ': 0.05071442629114661, 'NC_082689.1 chromosome 7 ': 0.05025309292404452, 'NC_082690.1 chromosome 8 ': 0.048077346263123565, 'NC_082691.1 chromosome 9 ': 0.04657541766054954, 'NC_082692.1 chromosome 10 ': 0.04563235936222644, 'NC_082693.1 chromosome 11 ': 0.04455979666810333, 'NC_082694.1 chromosome 12 ': 0.03909922095360681, 'NC_082695.1 chromosome 13 ': 0.0390615468842897, 'NC_082696.1 chromosome 14 ': 0.03864471725119043, 'NC_082697.1 chromosome 15 ': 0.03829364412727377, 'NC_082698.1 chromosome 16 ': 0.037114232977622515, 'NC_082699.1 chromosome 17 ': 0.03508611224605149, 'NC_082700.1 chromosome 18 ': 0.034283382200725195, 'NC_082701.1 chromosome 19 ': 0.02619025216582599, 'NC_082702.1 chromosome 20 ': 0.025866847839492557, 'NC_082703.1 chromosome 21 ': 0.015480745964771}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Pan paniscus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_029289425.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_073273.2 chromosome Y ', 'NC_073272.2 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_073249.2 chromosome 1 ', 'NC_073252.2 chromosome 3 ', 'NC_073253.2 chromosome 4 ', 'NC_073254.2 chromosome 5 ', 'NC_073255.2 chromosome 6 ', 'NC_073256.2 chromosome 7 ', 'NC_073257.2 chromosome 8 ', 'NC_073258.2 chromosome 9 ', 'NC_073259.2 chromosome 10 ', 'NC_073260.2 chromosome 11 ', 'NC_073261.2 chromosome 12 ', 'NC_073262.2 chromosome 13 ', 'NC_073263.2 chromosome 14 ', 'NC_073264.2 chromosome 15 ', 'NC_073265.2 chromosome 16 ', 'NC_073266.2 chromosome 17 ', 'NC_073267.2 chromosome 18 ', 'NC_073268.2 chromosome 19 ', 'NC_073269.2 chromosome 20 ', 'NC_073270.2 chromosome 21 ', 'NC_073271.2 chromosome 22 ', 'NC_085926.1 chromosome 2 ', 'NC_085927.1 chromosome 23 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_073273.2 chromosome Y ': 46954669, 'NC_073272.2 chromosome X ': 160241051, 'NC_073249.2 chromosome 1 ': 455410104, 'NC_073252.2 chromosome 3 ': 377228750, 'NC_073253.2 chromosome 4 ': 353102666, 'NC_073254.2 chromosome 5 ': 382303424, 'NC_073255.2 chromosome 6 ': 392619714, 'NC_073256.2 chromosome 7 ': 325587904, 'NC_073257.2 chromosome 8 ': 294056814, 'NC_073258.2 chromosome 9 ': 271500796, 'NC_073259.2 chromosome 10 ': 283630350, 'NC_073260.2 chromosome 11 ': 249517922, 'NC_073261.2 chromosome 12 ': 253102938, 'NC_073262.2 chromosome 13 ': 289744536, 'NC_073263.2 chromosome 14 ': 232252860, 'NC_073264.2 chromosome 15 ': 216905492, 'NC_073265.2 chromosome 16 ': 183719858, 'NC_073266.2 chromosome 17 ': 196540932, 'NC_073267.2 chromosome 18 ': 200854384, 'NC_073268.2 chromosome 19 ': 201584824, 'NC_073269.2 chromosome 20 ': 141442586, 'NC_073270.2 chromosome 21 ': 153582654, 'NC_073271.2 chromosome 22 ': 96966552, 'NC_085926.1 chromosome 2 ': 392863782, 'NC_085927.1 chromosome 23 ': 130104760}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_073273.2 chromosome Y ': 0.007474691505511036, 'NC_073272.2 chromosome X ': 0.025508696967789523, 'NC_073249.2 chromosome 1 ': 0.07249651862933369, 'NC_073252.2 chromosome 3 ': 0.060050865937518294, 'NC_073253.2 chromosome 4 ': 0.05621024605931096, 'NC_073254.2 chromosome 5 ': 0.060858700886605846, 'NC_073255.2 chromosome 6 ': 0.06250094620264435, 'NC_073256.2 chromosome 7 ': 0.05183018413623452, 'NC_073257.2 chromosome 8 ': 0.04681076486224275, 'NC_073258.2 chromosome 9 ': 0.04322008304649501, 'NC_073259.2 chromosome 10 ': 0.04515098099935753, 'NC_073260.2 chromosome 11 ': 0.03972063975248479, 'NC_073261.2 chromosome 12 ': 0.040291336750526055, 'NC_073262.2 chromosome 13 ': 0.04612429537108304, 'NC_073263.2 chromosome 14 ': 0.03697222271490496, 'NC_073264.2 chromosome 15 ': 0.03452908247635804, 'NC_073265.2 chromosome 16 ': 0.0292462771271222, 'NC_073266.2 chromosome 17 ': 0.031287257821061884, 'NC_073267.2 chromosome 18 ': 0.031973914200725206, 'NC_073268.2 chromosome 19 ': 0.03209019259815754, 'NC_073269.2 chromosome 20 ': 0.022516178233344893, 'NC_073270.2 chromosome 21 ': 0.024448749904884656, 'NC_073271.2 chromosome 22 ': 0.015436059458817484, 'NC_085926.1 chromosome 2 ': 0.06253979927189646, 'NC_085927.1 chromosome 23 ': 0.020711315085589294}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Pan paniscus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_029289425.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_073272.2 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_073249.2 chromosome 1 ', 'NC_073252.2 chromosome 3 ', 'NC_073253.2 chromosome 4 ', 'NC_073254.2 chromosome 5 ', 'NC_073255.2 chromosome 6 ', 'NC_073256.2 chromosome 7 ', 'NC_073257.2 chromosome 8 ', 'NC_073258.2 chromosome 9 ', 'NC_073259.2 chromosome 10 ', 'NC_073260.2 chromosome 11 ', 'NC_073261.2 chromosome 12 ', 'NC_073262.2 chromosome 13 ', 'NC_073263.2 chromosome 14 ', 'NC_073264.2 chromosome 15 ', 'NC_073265.2 chromosome 16 ', 'NC_073266.2 chromosome 17 ', 'NC_073267.2 chromosome 18 ', 'NC_073268.2 chromosome 19 ', 'NC_073269.2 chromosome 20 ', 'NC_073270.2 chromosome 21 ', 'NC_073271.2 chromosome 22 ', 'NC_085926.1 chromosome 2 ', 'NC_085927.1 chromosome 23 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_073272.2 chromosome X ': 320482102, 'NC_073249.2 chromosome 1 ': 455410104, 'NC_073252.2 chromosome 3 ': 377228750, 'NC_073253.2 chromosome 4 ': 353102666, 'NC_073254.2 chromosome 5 ': 382303424, 'NC_073255.2 chromosome 6 ': 392619714, 'NC_073256.2 chromosome 7 ': 325587904, 'NC_073257.2 chromosome 8 ': 294056814, 'NC_073258.2 chromosome 9 ': 271500796, 'NC_073259.2 chromosome 10 ': 283630350, 'NC_073260.2 chromosome 11 ': 249517922, 'NC_073261.2 chromosome 12 ': 253102938, 'NC_073262.2 chromosome 13 ': 289744536, 'NC_073263.2 chromosome 14 ': 232252860, 'NC_073264.2 chromosome 15 ': 216905492, 'NC_073265.2 chromosome 16 ': 183719858, 'NC_073266.2 chromosome 17 ': 196540932, 'NC_073267.2 chromosome 18 ': 200854384, 'NC_073268.2 chromosome 19 ': 201584824, 'NC_073269.2 chromosome 20 ': 141442586, 'NC_073270.2 chromosome 21 ': 153582654, 'NC_073271.2 chromosome 22 ': 96966552, 'NC_085926.1 chromosome 2 ': 392863782, 'NC_085927.1 chromosome 23 ': 130104760}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_073272.2 chromosome X ': 0.050113644202300085, 'NC_073249.2 chromosome 1 ': 0.07121227605399467, 'NC_073252.2 chromosome 3 ': 0.05898709239113268, 'NC_073253.2 chromosome 4 ': 0.05521450733248, 'NC_073254.2 chromosome 5 ': 0.05978061691462905, 'NC_073255.2 chromosome 6 ': 0.06139377060814715, 'NC_073256.2 chromosome 7 ': 0.05091203619735568, 'NC_073257.2 chromosome 8 ': 0.04598153363353169, 'NC_073258.2 chromosome 9 ': 0.04245445909920192, 'NC_073259.2 chromosome 10 ': 0.044351152080479815, 'NC_073260.2 chromosome 11 ': 0.039017006838045716, 'NC_073261.2 chromosome 12 ': 0.03957759420052986, 'NC_073262.2 chromosome 13 ': 0.045307224634543015, 'NC_073263.2 chromosome 14 ': 0.03631727674766254, 'NC_073264.2 chromosome 15 ': 0.03391741561783955, 'NC_073265.2 chromosome 16 ': 0.028728192742286416, 'NC_073266.2 chromosome 17 ': 0.03073301839937525, 'NC_073267.2 chromosome 18 ': 0.03140751097622342, 'NC_073268.2 chromosome 19 ': 0.03152172955517898, 'NC_073269.2 chromosome 20 ': 0.022117314463499217, 'NC_073270.2 chromosome 21 ': 0.02401565151429567, 'NC_073271.2 chromosome 22 ': 0.015162616745604813, 'NC_085926.1 chromosome 2 ': 0.061431935413098306, 'NC_085927.1 chromosome 23 ': 0.020344423638564514}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0

{'labels': 1, 'species': 'Neomonachus schauinslandi', 'sampled_chromosomes': ['NC_058411.1 chromosome 9 ', 'NC_058404.1 chromosome 2 ', 'NC_058403.1 chromosome 1 ', 'NC_058419.1 chromosome X ', 'NC_058419.1 chromosome X ', 'NC_058410.1 chromosome 8 ', 'NC_058403.1 chromosome 1 ', 'NC_058404.1 chromosome 2 ', 'NC_058404.1 chromosome 2 ', 'NC_058419.1 chromosome X '], 'chunks': ['AGCAAAGACA', 'CAGACAGTGC', 'AGCCGCACTC', 'TCATCTTTTC', 'CTCACGCCGA', 'TTTCTGAGAC', 'GCGATAATAG', 'TTGTTATTAT', 'AAACTCTCAA', 'GGTTGACCCT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Pan paniscus', 'sampled_chromosomes': ['NC_073272.2 chromosome X ', 'NC_073258.2 chromosome 9 ', 'NC_073262.2 chromosome 13 ', 'NC_073266.2 chromosome 17 ', 'NC_073266.2 chromosome 17 ', 'NC_073253.2 chromosome 4 ', 'NC_073260.2 chromosome 11 ', 'NC_073253.2 chromosome 4 ', 'NC_073265.2 chromosome 16 ', 'NC_073258.2 chromosome 9 '], 'chunks': ['TACAGGCGTG', 'AAAGGCAAAG', 'TATCTTACTT', 'TTCACAATTG', 'ATTTTAGATG', 'TACCACCTAC', 'TTTTTTTTTT', 'GTCAAGCTGG', 'CCCTTAAGCA', 'ATCTCTTCTC'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Tursiops truncatus', 'sampled_chromosomes': ['NC_047053.1 chromosome 20 ', 'NC_047051.1 chromosome 18 ', 'NC_047049.1 chromosome 16 ', 'NC_047034.1 chromosome 1 ', 'NC_047052.1 chromosome 19 ', 'NC_047036.1 chromosome 3 ', 'NC_047052.1 chromosome 19 ', 'NC_047039.1 chromosome 6 ', 'NC_047036.1 chromosome 3 ', 'NC_047055.1 chromosome X '], 'chunks': ['TCCTTTAGGG', 'TACTGGTGGT', 'CCTACATAAG', 'TCTGATTAAT', 'TGGTGGGTGT', 'CCATATTTTT', 'GCATCGGCAG', 'AGCCCGGAGG', 'GTAGTAAAGC', 'NNNNNNNNNN'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 0, 'species': 'Delphinus delphis', 'sampled_chromosomes': ['NC_082691.1 chromosome 9 ', 'NC_082691.1 chromosome 9 ', 'NC_082688.1 chromosome 6 ', 'NC_082687.1 chromosome 5 ', 'NC_082699.1 chromosome 17 ', 'NC_082685.1 chromosome 3 ', 'NC_082692.1 chromosome 10 ', 'NC_082705.1 chromosome Y ', 'NC_082687.1 chromosome 5 ', 'NC_082693.1 chromosome 11 '], 'chunks': ['GCTCTGCGTG', 'TCCTCAGGTC', 'GGGGGCTTGT', 'ACAATATGAA', 'TAATACAGTG', 'AAAACAACAG', 'CTGAGTTAAT', 'TGCCTGCCAG', 'ATATATTTTT', 'CCAGGACCCT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Pan paniscus', 'sampled_chromosomes': ['NC_073264.2 chromosome 15 ', 'NC_073255.2 chromosome 6 ', 'NC_073264.2 chromosome 15 ', 'NC_073270.2 chromosome 21 ', 'NC_073256.2 chromosome 7 ', 'NC_073259.2 chromosome 10 ', 'NC_073269.2 chromosome 20 ', 'NC_073273.2 chromosome Y ', 'NC_073262.2 chromosome 13 ', 'NC_073262.2 chromosome 13 '], 'chunks': ['CTAGTGCAGA', 'TAGTTGAAAA', 'AAAAAAAAAA', 'GAGGCCAAGG', 'TACAACCTGG', 'TACTCATCTG', 'TTCCTTTAGA', 'CAGATCCAAG', 'GAGATACACA', 'ATAACACATT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Macaca thibetana thibetana
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_024542745.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_065599.1 chromosome Y ', 'NC_065598.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_065578.1 chromosome 1 ', 'NC_065579.1 chromosome 2 ', 'NC_065580.1 chromosome 3 ', 'NC_065581.1 chromosome 4 ', 'NC_065582.1 chromosome 5 ', 'NC_065583.1 chromosome 6 ', 'NC_065584.1 chromosome 7 ', 'NC_065585.1 chromosome 8 ', 'NC_065586.1 chromosome 9 ', 'NC_065587.1 chromosome 10 ', 'NC_065588.1 chromosome 11 ', 'NC_065589.1 chromosome 12 ', 'NC_065590.1 chromosome 13 ', 'NC_065591.1 chromosome 14 ', 'NC_065592.1 chromosome 15 ', 'NC_065593.1 chromosome 16 ', 'NC_065594.1 chromosome 17 ', 'NC_065595.1 chromosome 18 ', 'NC_065596.1 chromosome 19 ', 'NC_065597.1 chromosome 20 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_065599.1 chromosome Y ': 13980984, 'NC_065598.1 chromosome X ': 150623419, 'NC_065578.1 chromosome 1 ': 440717450, 'NC_065579.1 chromosome 2 ': 388858296, 'NC_065580.1 chromosome 3 ': 370244344, 'NC_065581.1 chromosome 4 ': 337606734, 'NC_065582.1 chromosome 5 ': 371886000, 'NC_065583.1 chromosome 6 ': 353442578, 'NC_065584.1 chromosome 7 ': 334985354, 'NC_065585.1 chromosome 8 ': 284152360, 'NC_065586.1 chromosome 9 ': 259633458, 'NC_065587.1 chromosome 10 ': 193506794, 'NC_065588.1 chromosome 11 ': 259204282, 'NC_065589.1 chromosome 12 ': 256822080, 'NC_065590.1 chromosome 13 ': 214157138, 'NC_065591.1 chromosome 14 ': 252576470, 'NC_065592.1 chromosome 15 ': 220636000, 'NC_065593.1 chromosome 16 ': 155906002, 'NC_065594.1 chromosome 17 ': 187118888, 'NC_065595.1 chromosome 18 ': 145543466, 'NC_065596.1 chromosome 19 ': 113358026, 'NC_065597.1 chromosome 20 ': 151433910}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_065599.1 chromosome Y ': 0.0025623120169554663, 'NC_065598.1 chromosome X ': 0.027604938002834298, 'NC_065578.1 chromosome 1 ': 0.08077082544525978, 'NC_065579.1 chromosome 2 ': 0.07126653494014625, 'NC_065580.1 chromosome 3 ': 0.06785513321816214, 'NC_065581.1 chromosome 4 ': 0.06187359856311169, 'NC_065582.1 chromosome 5 ': 0.06815600151874149, 'NC_065583.1 chromosome 6 ': 0.06477585303817812, 'NC_065584.1 chromosome 7 ': 0.061393175048214114, 'NC_065585.1 chromosome 8 ': 0.05207695013986539, 'NC_065586.1 chromosome 9 ': 0.04758334101784984, 'NC_065587.1 chromosome 10 ': 0.035464226525738524, 'NC_065588.1 chromosome 11 ': 0.0475046854080452, 'NC_065589.1 chromosome 12 ': 0.04706809633738927, 'NC_065590.1 chromosome 13 ': 0.03924884029723445, 'NC_065591.1 chromosome 14 ': 0.04628999820622009, 'NC_065592.1 chromosome 15 ': 0.04043622925060112, 'NC_065593.1 chromosome 16 ': 0.028573083442487518, 'NC_065594.1 chromosome 17 ': 0.03429350718960439, 'NC_065595.1 chromosome 18 ': 0.02667392881081541, 'NC_065596.1 chromosome 19 ': 0.02077526390403924, 'NC_065597.1 chromosome 20 ': 0.027753477678506215}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Macaca mulatta
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_003339765.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_027914.1 chromosome Y ', 'NC_041774.1 chromosome X ', 'NW_021160381.1 chromosome X unlocalized genomic scaffold', 'NW_021160382.1 chromosome X unlocalized genomic scaffold', 'NW_021160383.1 chromosome X unlocalized genomic scaffold', 'NW_021160384.1 chromosome X unlocalized genomic scaffold']

{'labels': 1, 'species': 'Pan paniscus', 'sampled_chromosomes': ['NC_085926.1 chromosome 2 ', 'NC_085927.1 chromosome 23 ', 'NC_073255.2 chromosome 6 ', 'NC_073259.2 chromosome 10 ', 'NC_073254.2 chromosome 5 ', 'NC_073263.2 chromosome 14 ', 'NC_073260.2 chromosome 11 ', 'NC_073256.2 chromosome 7 ', 'NC_073249.2 chromosome 1 ', 'NC_073256.2 chromosome 7 '], 'chunks': ['GTTATAGGAA', 'CTGTTTCCCT', 'GCTGTTCTGC', 'GGAGTGCACG', 'AAGAGACAAA', 'TCAGAAGATA', 'CAGCCCTAGT', 'TTTGGGGAAC', 'TGCTGTCTCT', 'TTTTATATGG'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Macaca thibetana thibetana', 'sampled_chromosomes': ['NC_065593.1 chromosome 16 ', 'NC_065597.1 chromosome 20 ', 'NC_065583.1 chromosome 6 ', 'NC_065597.1 chromosome 20 ', 'NC_065580.1 chromosome 3 ', 'NC_065589.1 chromosome 12 ', 'NC_065599.1 chromosome Y ', 'NC_065587.1 chromosome 10 ', 'NC_065582.1 chromosome 5 ', 'NC_065584.1 chromosome 7 '], 'chunks': ['TTAGTAGAGA', 'GGATTACAGG', 'ATAATGAGCA', 'AGAAAGTTTC', 'CATAGAGTAT', 'CTCACGTGCA', 'GTTTGATGTT', 'CCATTCTTTG', 'ATTTATATTT', 'CCTTAGGAAG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Macaca mulatta', 'sampled_chromosomes': ['NC_027914.1 chromosome Y ', 'NC_041755.1 chromosome 2 ', 'NC_041759.1 chromosome 6 ', 'NC_041763.1 chromosome 10 ', 'NC_041765.1 chromosome 12 ', 'NC_041764.1 chromosome 11 ', 'NC_041758.1 chromosome 5 ', 'NC_041760.1 chromosome 7 ', 'NC_041757.1 chromosome 4 ', 'NC_041769.1 chromosome 16 '], 'chunks': ['ATGGCAAGTA', 'CTGCCTCAGC', 'TTTTCCCTGG', 'TGCCTTTCTT', 'TTCCCACATA', 'ATAACATCTT', 'AAGAATTAAG', 'TTTTTTGTAT', 'TGAGCGATCT', 'ATCAGGAGTT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Tursiops truncatus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011762595.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NW_022983135.1 chromosome Y unlocalized genomic scaffold', 'NW_022983136.1 chromosome Y unlocalized genomic scaffold', 'NW_022983137.1 chromosome Y unlocalized genomic scaffold', 'NW_022983138.1 chromosome Y unlocalized genomic scaffold', 'NC_047055.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_047034.1 chromosome 1 ', 'NC_047035.1 chromosome 2 ', 'NC_047036.1 chromosome 3 ', 'NC_047037.1 chromosome 4 ', 'NC_047038.1 chromosome 5 ', 'NC_047039.1 chromosome 6 ', 'NC_047040.1 chromosome 7 ', 'NC_047041.1 chromosome 8 ', 'NC_047042.1 chromosome 9 ', 'NC_047043.1 chromosome 10 ', 'NC_047044.1 chromosome 11 ', 'NC_047045.1 chromosome 12 ', 'NC_047046.1 chromosome 13 ', 'NC_047047.1 chromosome 14 ', 'NC_047048.1 chromosome 15 ', 'NC_047049.1 chromosome 16 ', 'NC_047050.1 chromosome 17 ', 'NC_047051.1 chromosome 18 ', 'NC_047052.1 chromosome 19 ', 'NC_047053.1 chromosome 20 ', 'NC_047054.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NW_022983135.1 chromosome Y unlocalized genomic scaffold': 7055931, 'NW_022983136.1 chromosome Y unlocalized genomic scaffold': 4926226, 'NW_022983137.1 chromosome Y unlocalized genomic scaffold': 596945, 'NW_022983138.1 chromosome Y unlocalized genomic scaffold': 124658, 'NC_047055.1 chromosome X ': 128693445, 'NC_047034.1 chromosome 1 ': 367485760, 'NC_047035.1 chromosome 2 ': 352945496, 'NC_047036.1 chromosome 3 ': 342843538, 'NC_047037.1 chromosome 4 ': 288366400, 'NC_047038.1 chromosome 5 ': 274975098, 'NC_047039.1 chromosome 6 ': 231199232, 'NC_047040.1 chromosome 7 ': 228030614, 'NC_047041.1 chromosome 8 ': 216860270, 'NC_047042.1 chromosome 9 ': 210670356, 'NC_047043.1 chromosome 10 ': 205625018, 'NC_047044.1 chromosome 11 ': 204335466, 'NC_047045.1 chromosome 12 ': 178661934, 'NC_047046.1 chromosome 13 ': 176970138, 'NC_047047.1 chromosome 14 ': 176966308, 'NC_047048.1 chromosome 15 ': 172587980, 'NC_047049.1 chromosome 16 ': 167017088, 'NC_047050.1 chromosome 17 ': 156885544, 'NC_047051.1 chromosome 18 ': 156303926, 'NC_047052.1 chromosome 19 ': 117272254, 'NC_047053.1 chromosome 20 ': 116934582, 'NC_047054.1 chromosome 21 ': 71364496}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NW_022983135.1 chromosome Y unlocalized genomic scaffold': 0.0015488142346537443, 'NW_022983136.1 chromosome Y unlocalized genomic scaffold': 0.001081332704631235, 'NW_022983137.1 chromosome Y unlocalized genomic scaffold': 0.00013103258993113443, 'NW_022983138.1 chromosome Y unlocalized genomic scaffold': 2.7363091399769418e-05, 'NC_047055.1 chromosome X ': 0.028248892955816705, 'NC_047034.1 chromosome 1 ': 0.08066507114660695, 'NC_047035.1 chromosome 2 ': 0.07747340616875734, 'NC_047036.1 chromosome 3 ': 0.07525597287068876, 'NC_047037.1 chromosome 4 ': 0.0632979524765556, 'NC_047038.1 chromosome 5 ': 0.060358490744553524, 'NC_047039.1 chromosome 6 ': 0.0507494562464703, 'NC_047040.1 chromosome 7 ': 0.05005392780910604, 'NC_047041.1 chromosome 8 ': 0.04760197812405682, 'NC_047042.1 chromosome 9 ': 0.046243259208794955, 'NC_047043.1 chromosome 10 ': 0.04513578078914496, 'NC_047044.1 chromosome 11 ': 0.04485271729349481, 'NC_047045.1 chromosome 12 ': 0.039217241009013235, 'NC_047046.1 chromosome 13 ': 0.03884588282439801, 'NC_047047.1 chromosome 14 ': 0.03884504211910785, 'NC_047048.1 chromosome 15 ': 0.037883975928071814, 'NC_047049.1 chromosome 16 ': 0.03666113562119826, 'NC_047050.1 chromosome 17 ': 0.03443720803939215, 'NC_047051.1 chromosome 18 ': 0.03430953980715875, 'NC_047052.1 chromosome 19 ': 0.025741881025357176, 'NC_047053.1 chromosome 20 ': 0.025667760232474707, 'NC_047054.1 chromosome 21 ': 0.01566488493916539}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Macaca thibetana thibetana
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_024542745.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_065599.1 chromosome Y ', 'NC_065598.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_065578.1 chromosome 1 ', 'NC_065579.1 chromosome 2 ', 'NC_065580.1 chromosome 3 ', 'NC_065581.1 chromosome 4 ', 'NC_065582.1 chromosome 5 ', 'NC_065583.1 chromosome 6 ', 'NC_065584.1 chromosome 7 ', 'NC_065585.1 chromosome 8 ', 'NC_065586.1 chromosome 9 ', 'NC_065587.1 chromosome 10 ', 'NC_065588.1 chromosome 11 ', 'NC_065589.1 chromosome 12 ', 'NC_065590.1 chromosome 13 ', 'NC_065591.1 chromosome 14 ', 'NC_065592.1 chromosome 15 ', 'NC_065593.1 chromosome 16 ', 'NC_065594.1 chromosome 17 ', 'NC_065595.1 chromosome 18 ', 'NC_065596.1 chromosome 19 ', 'NC_065597.1 chromosome 20 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_065599.1 chromosome Y ': 13980984, 'NC_065598.1 chromosome X ': 150623419, 'NC_065578.1 chromosome 1 ': 440717450, 'NC_065579.1 chromosome 2 ': 388858296, 'NC_065580.1 chromosome 3 ': 370244344, 'NC_065581.1 chromosome 4 ': 337606734, 'NC_065582.1 chromosome 5 ': 371886000, 'NC_065583.1 chromosome 6 ': 353442578, 'NC_065584.1 chromosome 7 ': 334985354, 'NC_065585.1 chromosome 8 ': 284152360, 'NC_065586.1 chromosome 9 ': 259633458, 'NC_065587.1 chromosome 10 ': 193506794, 'NC_065588.1 chromosome 11 ': 259204282, 'NC_065589.1 chromosome 12 ': 256822080, 'NC_065590.1 chromosome 13 ': 214157138, 'NC_065591.1 chromosome 14 ': 252576470, 'NC_065592.1 chromosome 15 ': 220636000, 'NC_065593.1 chromosome 16 ': 155906002, 'NC_065594.1 chromosome 17 ': 187118888, 'NC_065595.1 chromosome 18 ': 145543466, 'NC_065596.1 chromosome 19 ': 113358026, 'NC_065597.1 chromosome 20 ': 151433910}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_065599.1 chromosome Y ': 0.0025623120169554663, 'NC_065598.1 chromosome X ': 0.027604938002834298, 'NC_065578.1 chromosome 1 ': 0.08077082544525978, 'NC_065579.1 chromosome 2 ': 0.07126653494014625, 'NC_065580.1 chromosome 3 ': 0.06785513321816214, 'NC_065581.1 chromosome 4 ': 0.06187359856311169, 'NC_065582.1 chromosome 5 ': 0.06815600151874149, 'NC_065583.1 chromosome 6 ': 0.06477585303817812, 'NC_065584.1 chromosome 7 ': 0.061393175048214114, 'NC_065585.1 chromosome 8 ': 0.05207695013986539, 'NC_065586.1 chromosome 9 ': 0.04758334101784984, 'NC_065587.1 chromosome 10 ': 0.035464226525738524, 'NC_065588.1 chromosome 11 ': 0.0475046854080452, 'NC_065589.1 chromosome 12 ': 0.04706809633738927, 'NC_065590.1 chromosome 13 ': 0.03924884029723445, 'NC_065591.1 chromosome 14 ': 0.04628999820622009, 'NC_065592.1 chromosome 15 ': 0.04043622925060112, 'NC_065593.1 chromosome 16 ': 0.028573083442487518, 'NC_065594.1 chromosome 17 ': 0.03429350718960439, 'NC_065595.1 chromosome 18 ': 0.02667392881081541, 'NC_065596.1 chromosome 19 ': 0.02077526390403924, 'NC_065597.1 chromosome 20 ': 0.027753477678506215}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Mustela lutreola
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_030435805.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_081308.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_081290.1 chromosome 1 ', 'NC_081291.1 chromosome 2 ', 'NC_081292.1 chromosome 3 ', 'NC_081293.1 chromosome 4 ', 'NC_081294.1 chromosome 5 ', 'NC_081295.1 chromosome 6 ', 'NC_081296.1 chromosome 7 ', 'NC_081297.1 chromosome 8 ', 'NC_081298.1 chromosome 9 ', 'NC_081299.1 chromosome 10 ', 'NC_081300.1 chromosome 11 ', 'NC_081301.1 chromosome 12 ', 'NC_081302.1 chromosome 13 ', 'NC_081303.1 chromosome 14 ', 'NC_081304.1 chromosome 15 ', 'NC_081305.1 chromosome 16 ', 'NC_081306.1 chromosome 17 ', 'NC_081307.1 chromosome 18 ', 'NW_026709257.1 chromosome 4 unlocalized genomic scaffold', 'NW_026709258.1 chromosome 5 unlocalized genomic scaffold', 'NW_026709259.1 chromosome 16 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_081308.1 chromosome X ': 266165512, 'NC_081290.1 chromosome 1 ': 580209788, 'NC_081291.1 chromosome 2 ': 450360622, 'NC_081292.1 chromosome 3 ': 422582014, 'NC_081293.1 chromosome 4 ': 405148736, 'NC_081294.1 chromosome 5 ': 354945442, 'NC_081295.1 chromosome 6 ': 320021132, 'NC_081296.1 chromosome 7 ': 308157286, 'NC_081297.1 chromosome 8 ': 303022374, 'NC_081298.1 chromosome 9 ': 292543060, 'NC_081299.1 chromosome 10 ': 247627348, 'NC_081300.1 chromosome 11 ': 209097952, 'NC_081301.1 chromosome 12 ': 201223108, 'NC_081302.1 chromosome 13 ': 184206380, 'NC_081303.1 chromosome 14 ': 151745266, 'NC_081304.1 chromosome 15 ': 141844742, 'NC_081305.1 chromosome 16 ': 128067692, 'NC_081306.1 chromosome 17 ': 98796040, 'NC_081307.1 chromosome 18 ': 84746544, 'NW_026709257.1 chromosome 4 unlocalized genomic scaffold': 1395006, 'NW_026709258.1 chromosome 5 unlocalized genomic scaffold': 2109010, 'NW_026709259.1 chromosome 16 unlocalized genomic scaffold': 2893842}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_081308.1 chromosome X ': 0.051613382622767205, 'NC_081290.1 chromosome 1 ': 0.11251115730395095, 'NC_081291.1 chromosome 2 ': 0.08733150635050506, 'NC_081292.1 chromosome 3 ': 0.0819448282919598, 'NC_081293.1 chromosome 4 ': 0.07856426091107738, 'NC_081294.1 chromosome 5 ': 0.06882910851407835, 'NC_081295.1 chromosome 6 ': 0.06205677440767416, 'NC_081296.1 chromosome 7 ': 0.05975620128542988, 'NC_081297.1 chromosome 8 ': 0.058760466805035445, 'NC_081298.1 chromosome 9 ': 0.05672837467167851, 'NC_081299.1 chromosome 10 ': 0.048018561699252484, 'NC_081300.1 chromosome 11 ': 0.04054714873132403, 'NC_081301.1 chromosome 12 ': 0.039020101393701254, 'NC_081302.1 chromosome 13 ': 0.035720309145442, 'NC_081303.1 chromosome 14 ': 0.029425624741538967, 'NC_081304.1 chromosome 15 ': 0.02750576844784345, 'NC_081305.1 chromosome 16 ': 0.024834197109694294, 'NC_081306.1 chromosome 17 ': 0.019157995999625275, 'NC_081307.1 chromosome 18 ': 0.016433593400444667, 'NW_026709257.1 chromosome 4 unlocalized genomic scaffold': 0.00027051205055843595, 'NW_026709258.1 chromosome 5 unlocalized genomic scaffold': 0.00040896786088966423, 'NW_026709259.1 chromosome 16 unlocalized genomic scaffold': 0.00056115825552874}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Canis lupus familiaris
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_014441545.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_051843.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_051805.1 chromosome 1 ', 'NC_051806.1 chromosome 2 ', 'NC_051807.1 chromosome 3 ', 'NC_051808.1 chromosome 4 ', 'NC_051809.1 chromosome 5 ', 'NC_051810.1 chromosome 6 ', 'NC_051811.1 chromosome 7 ', 'NC_051812.1 chromosome 8 ', 'NC_051813.1 chromosome 9 ', 'NC_051814.1 chromosome 10 ', 'NC_051815.1 chromosome 11 ', 'NC_051816.1 chromosome 12 ', 'NC_051817.1 chromosome 13 ', 'NC_051818.1 chromosome 14 ', 'NC_051819.1 chromosome 15 ', 'NC_051820.1 chromosome 16 ', 'NC_051821.1 chromosome 17 ', 'NC_051822.1 chromosome 18 ', 'NC_051823.1 chromosome 19 ', 'NC_051824.1 chromosome 20 ', 'NC_051825.1 chromosome 21 ', 'NC_051826.1 chromosome 22 ', 'NC_051827.1 chromosome 23 ', 'NC_051828.1 chromosome 24 ', 'NC_051829.1 chromosome 25 ', 'NC_051830.1 chromosome 26 ', 'NC_051831.1 chromosome 27 ', 'NC_051832.1 chromosome 28 ', 'NC_051833.1 chromosome 29 ', 'NC_051834.1 chromosome 30 ', 'NC_051835.1 chromosome 31 ', 'NC_051836.1 chromosome 32 ', 'NC_051837.1 chromosome 33 ', 'NC_051838.1 chromosome 34 ', 'NC_051839.1 chromosome 35 ', 'NC_051840.1 chromosome 36 ', 'NC_051841.1 chromosome 37 ', 'NC_051842.1 chromosome 38 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_051843.1 chromosome X ': 254139238, 'NC_051805.1 chromosome 1 ': 246627878, 'NC_051806.1 chromosome 2 ': 172375622, 'NC_051807.1 chromosome 3 ': 185740474, 'NC_051808.1 chromosome 4 ': 178015330, 'NC_051809.1 chromosome 5 ': 179146810, 'NC_051810.1 chromosome 6 ': 156536352, 'NC_051811.1 chromosome 7 ': 162078904, 'NC_051812.1 chromosome 8 ': 150521048, 'NC_051813.1 chromosome 9 ': 124004586, 'NC_051814.1 chromosome 10 ': 140722000, 'NC_051815.1 chromosome 11 ': 151082694, 'NC_051816.1 chromosome 12 ': 146994588, 'NC_051817.1 chromosome 13 ': 128074554, 'NC_051818.1 chromosome 14 ': 122086128, 'NC_051819.1 chromosome 15 ': 130401200, 'NC_051820.1 chromosome 16 ': 124042426, 'NC_051821.1 chromosome 17 ': 130943096, 'NC_051822.1 chromosome 18 ': 113766814, 'NC_051823.1 chromosome 19 ': 110530482, 'NC_051824.1 chromosome 20 ': 117792922, 'NC_051825.1 chromosome 21 ': 104281432, 'NC_051826.1 chromosome 22 ': 124213958, 'NC_051827.1 chromosome 23 ': 106565846, 'NC_051828.1 chromosome 24 ': 97677994, 'NC_051829.1 chromosome 25 ': 103882002, 'NC_051830.1 chromosome 26 ': 81348702, 'NC_051831.1 chromosome 27 ': 92497604, 'NC_051832.1 chromosome 28 ': 83724424, 'NC_051833.1 chromosome 29 ': 84099704, 'NC_051834.1 chromosome 30 ': 80829806, 'NC_051835.1 chromosome 31 ': 79037866, 'NC_051836.1 chromosome 32 ': 78047464, 'NC_051837.1 chromosome 33 ': 63298168, 'NC_051838.1 chromosome 34 ': 84527742, 'NC_051839.1 chromosome 35 ': 53884536, 'NC_051840.1 chromosome 36 ': 62130370, 'NC_051841.1 chromosome 37 ': 61864816, 'NC_051842.1 chromosome 38 ': 48204096}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_051843.1 chromosome X ': 0.05389170214238094, 'NC_051805.1 chromosome 1 ': 0.052298874608192006, 'NC_051806.1 chromosome 2 ': 0.03655325226650615, 'NC_051807.1 chromosome 3 ': 0.03938734679212602, 'NC_051808.1 chromosome 4 ': 0.037749185118504405, 'NC_051809.1 chromosome 5 ': 0.03798912202718461, 'NC_051810.1 chromosome 6 ': 0.033194443025908876, 'NC_051811.1 chromosome 7 ': 0.03436977338356368, 'NC_051812.1 chromosome 8 ': 0.03191886285963848, 'NC_051813.1 chromosome 9 ': 0.026295893013582032, 'NC_051814.1 chromosome 10 ': 0.029840917792002392, 'NC_051815.1 chromosome 11 ': 0.032037963157489614, 'NC_051816.1 chromosome 12 ': 0.031171056525470513, 'NC_051817.1 chromosome 13 ': 0.027158953377306828, 'NC_051818.1 chromosome 14 ': 0.025889072847116168, 'NC_051819.1 chromosome 15 ': 0.027652332181026865, 'NC_051820.1 chromosome 16 ': 0.026303917205458566, 'NC_051821.1 chromosome 17 ': 0.027767244376616856, 'NC_051822.1 chromosome 18 ': 0.024124913972456523, 'NC_051823.1 chromosome 19 ': 0.0234386309665326, 'NC_051824.1 chromosome 20 ': 0.02497867356832443, 'NC_051825.1 chromosome 21 ': 0.022113483602736513, 'NC_051826.1 chromosome 22 ': 0.026340291562777944, 'NC_051827.1 chromosome 23 ': 0.022597906865459465, 'NC_051828.1 chromosome 24 ': 0.02071318620430141, 'NC_051829.1 chromosome 25 ': 0.022028782150272368, 'NC_051830.1 chromosome 26 ': 0.017250464951237908, 'NC_051831.1 chromosome 27 ': 0.01961465440315794, 'NC_051832.1 chromosome 28 ': 0.017754250605923397, 'NC_051833.1 chromosome 29 ': 0.017833830910559362, 'NC_051834.1 chromosome 30 ': 0.0171404300392938, 'NC_051835.1 chromosome 31 ': 0.016760438749884886, 'NC_051836.1 chromosome 32 ': 0.016550418250865298, 'NC_051837.1 chromosome 33 ': 0.013422744330469695, 'NC_051838.1 chromosome 34 ': 0.017924598855655748, 'NC_051839.1 chromosome 35 ': 0.011426528965166736, 'NC_051840.1 chromosome 36 ': 0.013175105978856837, 'NC_051841.1 chromosome 37 ': 0.013118793710104704, 'NC_051842.1 chromosome 38 ': 0.010221958655887433}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Bos indicus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_000247795.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_032679.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_032650.1 chromosome 1 ', 'NC_032651.1 chromosome 2 ', 'NC_032652.1 chromosome 3 ', 'NC_032653.1 chromosome 4 ', 'NC_032654.1 chromosome 5 ', 'NC_032655.1 chromosome 6 ', 'NC_032656.1 chromosome 7 ', 'NC_032657.1 chromosome 8 ', 'NC_032658.1 chromosome 9 ', 'NC_032659.1 chromosome 10 ', 'NC_032660.1 chromosome 11 ', 'NC_032661.1 chromosome 12 ', 'NC_032662.1 chromosome 13 ', 'NC_032663.1 chromosome 14 ', 'NC_032664.1 chromosome 15 ', 'NC_032665.1 chromosome 16 ', 'NC_032666.1 chromosome 17 ', 'NC_032667.1 chromosome 18 ', 'NC_032668.1 chromosome 19 ', 'NC_032669.1 chromosome 20 ', 'NC_032670.1 chromosome 21 ', 'NC_032671.1 chromosome 22 ', 'NC_032672.1 chromosome 23 ', 'NC_032673.1 chromosome 24 ', 'NC_032674.1 chromosome 25 ', 'NC_032675.1 chromosome 26 ', 'NC_032676.1 chromosome 27 ', 'NC_032677.1 chromosome 28 ', 'NC_032678.1 chromosome 29 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_032679.1 chromosome X ': 177033304, 'NC_032650.1 chromosome 1 ': 322216984, 'NC_032651.1 chromosome 2 ': 281361770, 'NC_032652.1 chromosome 3 ': 255730136, 'NC_032653.1 chromosome 4 ': 248859830, 'NC_032654.1 chromosome 5 ': 251285472, 'NC_032655.1 chromosome 6 ': 245293224, 'NC_032656.1 chromosome 7 ': 223897714, 'NC_032657.1 chromosome 8 ': 233882624, 'NC_032658.1 chromosome 9 ': 216200410, 'NC_032659.1 chromosome 10 ': 212621306, 'NC_032660.1 chromosome 11 ': 220513268, 'NC_032661.1 chromosome 12 ': 170885336, 'NC_032662.1 chromosome 13 ': 168866216, 'NC_032663.1 chromosome 14 ': 162818060, 'NC_032664.1 chromosome 15 ': 169600158, 'NC_032665.1 chromosome 16 ': 155812094, 'NC_032666.1 chromosome 17 ': 153038054, 'NC_032667.1 chromosome 18 ': 131897584, 'NC_032668.1 chromosome 19 ': 130635662, 'NC_032669.1 chromosome 20 ': 151725208, 'NC_032670.1 chromosome 21 ': 138614818, 'NC_032671.1 chromosome 22 ': 123785068, 'NC_032672.1 chromosome 23 ': 106662320, 'NC_032673.1 chromosome 24 ': 130035316, 'NC_032674.1 chromosome 25 ': 88088598, 'NC_032675.1 chromosome 26 ': 103722348, 'NC_032676.1 chromosome 27 ': 97498662, 'NC_032677.1 chromosome 28 ': 92211346, 'NC_032678.1 chromosome 29 ': 104263186}

{'labels': 0, 'species': 'Zalophus californianus', 'sampled_chromosomes': ['NC_045613.1 chromosome Y ', 'NC_045600.1 chromosome 6 ', 'NC_045596.1 chromosome 2 ', 'NC_045604.1 chromosome 10 ', 'NC_045610.1 chromosome 16 ', 'NC_045612.1 chromosome X ', 'NC_045599.1 chromosome 5 ', 'NC_045605.1 chromosome 11 ', 'NC_045601.1 chromosome 7 ', 'NC_045606.1 chromosome 12 '], 'chunks': ['TGCCAACTAG', 'ACCTGAGTCT', 'TAAAAAAGAA', 'CTTTCTCACT', 'ATTTCCCATT', 'CAGATTTTTG', 'AGTAAGCAGA', 'GCAGGTAGGG', 'TATGTACAAG', 'ACAGAGACAC'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': True}
{'labels': 0, 'species': 'Tursiops truncatus', 'sampled_chromosomes': ['NW_022983136.1 chromosome Y unlocalized genomic scaffold', 'NC_047041.1 chromosome 8 ', 'NC_047039.1 chromosome 6 ', 'NC_047035.1 chromosome 2 ', 'NC_047035.1 chromosome 2 ', 'NC_047049.1 chromosome 16 ', 'NC_047052.1 chromosome 19 ', 'NC_047036.1 chromosome 3 ', 'NC_047038.1 chromosome 5 ', 'NC_047047.1 chromosome 14 '], 'chunks': ['ACAAGAAAAA', 'TTAGTGGTGA', 'GTTCCAACCC', 'AAAGCAGTGG', 'AAATGCATAG', 'CTTACAACTT', 'CTTCACCTGT', 'CACCATTCTG', 'GATTCGTAGT', 'TTTCCTATTG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Macaca thibetana thibetana', 'sampled_chromosomes': ['NC_065583.1 chromosome 6 ', 'NC_065582.1 chromosome 5 ', 'NC_065584.1 chromosome 7 ', 'NC_065578.1 chromosome 1 ', 'NC_065596.1 chromosome 19 ', 'NC_065578.1 chromosome 1 ', 'NC_065579.1 chromosome 2 ', 'NC_065580.1 chromosome 3 ', 'NC_065585.1 chromosome 8 ', 'NC_065599.1 chromosome Y '], 'chunks': ['GCGATTCTCC', 'ATATAAACTC', 'ACACAGTTTG', 'ACCTCTGAGC', 'TTAATTGTGG', 'TAACTTTTTC', 'CTGAAAATTA', 'CCAAGATGTT', 'ACAGAAAGAG', 'TAGTGCCCTG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Mustela lutreola', 'sampled_chromosomes': ['NC_081290.1 chromosome 1 ', 'NC_081290.1 chromosome 1 ', 'NC_081290.1 chromosome 1 ', 'NC_081295.1 chromosome 6 ', 'NC_081290.1 chromosome 1 ', 'NC_081299.1 chromosome 10 ', 'NC_081303.1 chromosome 14 ', 'NC_081290.1 chromosome 1 ', 'NC_081292.1 chromosome 3 ', 'NC_081305.1 chromosome 16 '], 'chunks': ['CCCACAGACC', 'TCTTTGAGTT', 'TTGTTTAAGC', 'TTCTGTTTCT', 'TAACAATGTA', 'ACCTGCCACT', 'AAGATGAAGA', 'AACTGATCTT', 'TCATGGAAGT', 'ACAGTTTTAA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Canis lupus familiaris', 'sampled_chromosomes': ['NC_051817.1 chromosome 13 ', 'NC_051830.1 chromosome 26 ', 'NC_051808.1 chromosome 4 ', 'NC_051837.1 chromosome 33 ', 'NC_051815.1 chromosome 11 ', 'NC_051819.1 chromosome 15 ', 'NC_051809.1 chromosome 5 ', 'NC_051836.1 chromosome 32 ', 'NC_051809.1 chromosome 5 ', 'NC_051831.1 chromosome 27 '], 'chunks': ['ATTTTTTCTA', 'CCAAAAAGCT', 'ATCTAGAAAA', 'AAAAGCAAGG', 'GAAATCTCTA', 'TGTCTAGTGG', 'AAGAAAGACA', 'GGGAAAAGCT', 'TGTGGACCAA', 'TGGGGGCATC'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Canis lupus familiaris
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_014441545.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_051843.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_051805.1 chromosome 1 ', 'NC_051806.1 chromosome 2 ', 'NC_051807.1 chromosome 3 ', 'NC_051808.1 chromosome 4 ', 'NC_051809.1 chromosome 5 ', 'NC_051810.1 chromosome 6 ', 'NC_051811.1 chromosome 7 ', 'NC_051812.1 chromosome 8 ', 'NC_051813.1 chromosome 9 ', 'NC_051814.1 chromosome 10 ', 'NC_051815.1 chromosome 11 ', 'NC_051816.1 chromosome 12 ', 'NC_051817.1 chromosome 13 ', 'NC_051818.1 chromosome 14 ', 'NC_051819.1 chromosome 15 ', 'NC_051820.1 chromosome 16 ', 'NC_051821.1 chromosome 17 ', 'NC_051822.1 chromosome 18 ', 'NC_051823.1 chromosome 19 ', 'NC_051824.1 chromosome 20 ', 'NC_051825.1 chromosome 21 ', 'NC_051826.1 chromosome 22 ', 'NC_051827.1 chromosome 23 ', 'NC_051828.1 chromosome 24 ', 'NC_051829.1 chromosome 25 ', 'NC_051830.1 chromosome 26 ', 'NC_051831.1 chromosome 27 ', 'NC_051832.1 chromosome 28 ', 'NC_051833.1 chromosome 29 ', 'NC_051834.1 chromosome 30 ', 'NC_051835.1 chromosome 31 ', 'NC_051836.1 chromosome 32 ', 'NC_051837.1 chromosome 33 ', 'NC_051838.1 chromosome 34 ', 'NC_051839.1 chromosome 35 ', 'NC_051840.1 chromosome 36 ', 'NC_051841.1 chromosome 37 ', 'NC_051842.1 chromosome 38 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_051843.1 chromosome X ': 254139238, 'NC_051805.1 chromosome 1 ': 246627878, 'NC_051806.1 chromosome 2 ': 172375622, 'NC_051807.1 chromosome 3 ': 185740474, 'NC_051808.1 chromosome 4 ': 178015330, 'NC_051809.1 chromosome 5 ': 179146810, 'NC_051810.1 chromosome 6 ': 156536352, 'NC_051811.1 chromosome 7 ': 162078904, 'NC_051812.1 chromosome 8 ': 150521048, 'NC_051813.1 chromosome 9 ': 124004586, 'NC_051814.1 chromosome 10 ': 140722000, 'NC_051815.1 chromosome 11 ': 151082694, 'NC_051816.1 chromosome 12 ': 146994588, 'NC_051817.1 chromosome 13 ': 128074554, 'NC_051818.1 chromosome 14 ': 122086128, 'NC_051819.1 chromosome 15 ': 130401200, 'NC_051820.1 chromosome 16 ': 124042426, 'NC_051821.1 chromosome 17 ': 130943096, 'NC_051822.1 chromosome 18 ': 113766814, 'NC_051823.1 chromosome 19 ': 110530482, 'NC_051824.1 chromosome 20 ': 117792922, 'NC_051825.1 chromosome 21 ': 104281432, 'NC_051826.1 chromosome 22 ': 124213958, 'NC_051827.1 chromosome 23 ': 106565846, 'NC_051828.1 chromosome 24 ': 97677994, 'NC_051829.1 chromosome 25 ': 103882002, 'NC_051830.1 chromosome 26 ': 81348702, 'NC_051831.1 chromosome 27 ': 92497604, 'NC_051832.1 chromosome 28 ': 83724424, 'NC_051833.1 chromosome 29 ': 84099704, 'NC_051834.1 chromosome 30 ': 80829806, 'NC_051835.1 chromosome 31 ': 79037866, 'NC_051836.1 chromosome 32 ': 78047464, 'NC_051837.1 chromosome 33 ': 63298168, 'NC_051838.1 chromosome 34 ': 84527742, 'NC_051839.1 chromosome 35 ': 53884536, 'NC_051840.1 chromosome 36 ': 62130370, 'NC_051841.1 chromosome 37 ': 61864816, 'NC_051842.1 chromosome 38 ': 48204096}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_051843.1 chromosome X ': 0.05389170214238094, 'NC_051805.1 chromosome 1 ': 0.052298874608192006, 'NC_051806.1 chromosome 2 ': 0.03655325226650615, 'NC_051807.1 chromosome 3 ': 0.03938734679212602, 'NC_051808.1 chromosome 4 ': 0.037749185118504405, 'NC_051809.1 chromosome 5 ': 0.03798912202718461, 'NC_051810.1 chromosome 6 ': 0.033194443025908876, 'NC_051811.1 chromosome 7 ': 0.03436977338356368, 'NC_051812.1 chromosome 8 ': 0.03191886285963848, 'NC_051813.1 chromosome 9 ': 0.026295893013582032, 'NC_051814.1 chromosome 10 ': 0.029840917792002392, 'NC_051815.1 chromosome 11 ': 0.032037963157489614, 'NC_051816.1 chromosome 12 ': 0.031171056525470513, 'NC_051817.1 chromosome 13 ': 0.027158953377306828, 'NC_051818.1 chromosome 14 ': 0.025889072847116168, 'NC_051819.1 chromosome 15 ': 0.027652332181026865, 'NC_051820.1 chromosome 16 ': 0.026303917205458566, 'NC_051821.1 chromosome 17 ': 0.027767244376616856, 'NC_051822.1 chromosome 18 ': 0.024124913972456523, 'NC_051823.1 chromosome 19 ': 0.0234386309665326, 'NC_051824.1 chromosome 20 ': 0.02497867356832443, 'NC_051825.1 chromosome 21 ': 0.022113483602736513, 'NC_051826.1 chromosome 22 ': 0.026340291562777944, 'NC_051827.1 chromosome 23 ': 0.022597906865459465, 'NC_051828.1 chromosome 24 ': 0.02071318620430141, 'NC_051829.1 chromosome 25 ': 0.022028782150272368, 'NC_051830.1 chromosome 26 ': 0.017250464951237908, 'NC_051831.1 chromosome 27 ': 0.01961465440315794, 'NC_051832.1 chromosome 28 ': 0.017754250605923397, 'NC_051833.1 chromosome 29 ': 0.017833830910559362, 'NC_051834.1 chromosome 30 ': 0.0171404300392938, 'NC_051835.1 chromosome 31 ': 0.016760438749884886, 'NC_051836.1 chromosome 32 ': 0.016550418250865298, 'NC_051837.1 chromosome 33 ': 0.013422744330469695, 'NC_051838.1 chromosome 34 ': 0.017924598855655748, 'NC_051839.1 chromosome 35 ': 0.011426528965166736, 'NC_051840.1 chromosome 36 ': 0.013175105978856837, 'NC_051841.1 chromosome 37 ': 0.013118793710104704, 'NC_051842.1 chromosome 38 ': 0.010221958655887433}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Mus musculus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_000001635.27
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_000086.8 chromosome X ', 'NT_165789.3 chromosome X unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_000067.7 chromosome 1 ', 'NC_000068.8 chromosome 2 ', 'NC_000069.7 chromosome 3 ', 'NC_000070.7 chromosome 4 ', 'NC_000071.7 chromosome 5 ', 'NC_000072.7 chromosome 6 ', 'NC_000073.7 chromosome 7 ', 'NC_000074.7 chromosome 8 ', 'NC_000075.7 chromosome 9 ', 'NC_000076.7 chromosome 10 ', 'NC_000077.7 chromosome 11 ', 'NC_000078.7 chromosome 12 ', 'NC_000079.7 chromosome 13 ', 'NC_000080.7 chromosome 14 ', 'NC_000081.7 chromosome 15 ', 'NC_000082.7 chromosome 16 ', 'NC_000083.7 chromosome 17 ', 'NC_000084.7 chromosome 18 ', 'NC_000085.7 chromosome 19 ', 'NT_162750.1 chromosome 1 unlocalized genomic scaffold', 'NT_166280.1 chromosome 1 unlocalized genomic scaffold', 'NT_166281.1 chromosome 1 unlocalized genomic scaffold', 'NT_166282.1 chromosome 1 unlocalized genomic scaffold', 'NT_166307.1 chromosome 7 unlocalized genomic scaffold', 'NT_166338.1 chromosome 1 unlocalized genomic scaffold', 'NT_166438.1 chromosome 5 unlocalized genomic scaffold', 'NT_187055.1 chromosome 4 unlocalized genomic scaffold', 'NT_187056.1 chromosome 5 unlocalized genomic scaffold', 'NT_187057.1 chromosome 5 unlocalized genomic scaffold', 'NT_187058.1 chromosome 5 unlocalized genomic scaffold', 'NT_187059.1 chromosome 5 unlocalized genomic scaffold', 'NW_023337852.1 chromosome 1 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_000086.8 chromosome X ': 332553184, 'NT_165789.3 chromosome X unlocalized genomic scaffold': 1118206, 'NC_000067.7 chromosome 1 ': 384008558, 'NC_000068.8 chromosome 2 ': 357210034, 'NC_000069.7 chromosome 3 ': 313290632, 'NC_000070.7 chromosome 4 ': 307321372, 'NC_000071.7 chromosome 5 ': 297216298, 'NC_000072.7 chromosome 6 ': 292876088, 'NC_000073.7 chromosome 7 ': 283690392, 'NC_000074.7 chromosome 8 ': 253955388, 'NC_000075.7 chromosome 9 ': 242519400, 'NC_000076.7 chromosome 10 ': 254761724, 'NC_000077.7 chromosome 11 ': 237646738, 'NC_000078.7 chromosome 12 ': 233885514, 'NC_000079.7 chromosome 13 ': 235466350, 'NC_000080.7 chromosome 14 ': 243979312, 'NC_000081.7 chromosome 15 ': 201847902, 'NC_000082.7 chromosome 16 ': 189717936, 'NC_000083.7 chromosome 17 ': 184289398, 'NC_000084.7 chromosome 18 ': 175241526, 'NC_000085.7 chromosome 19 ': 116540008, 'NT_162750.1 chromosome 1 unlocalized genomic scaffold': 413922, 'NT_166280.1 chromosome 1 unlocalized genomic scaffold': 339450, 'NT_166281.1 chromosome 1 unlocalized genomic scaffold': 483470, 'NT_166282.1 chromosome 1 unlocalized genomic scaffold': 307236, 'NT_166307.1 chromosome 7 unlocalized genomic scaffold': 351936, 'NT_166338.1 chromosome 1 unlocalized genomic scaffold': 80112, 'NT_166438.1 chromosome 5 unlocalized genomic scaffold': 391986, 'NT_187055.1 chromosome 4 unlocalized genomic scaffold': 3952, 'NT_187056.1 chromosome 5 unlocalized genomic scaffold': 398736, 'NT_187057.1 chromosome 5 unlocalized genomic scaffold': 411552, 'NT_187058.1 chromosome 5 unlocalized genomic scaffold': 368378, 'NT_187059.1 chromosome 5 unlocalized genomic scaffold': 1906024, 'NW_023337852.1 chromosome 1 unlocalized genomic scaffold': 16824}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_000086.8 chromosome X ': 0.0646410930788116, 'NT_165789.3 chromosome X unlocalized genomic scaffold': 0.00021735488218114796, 'NC_000067.7 chromosome 1 ': 0.07464289664037084, 'NC_000068.8 chromosome 2 ': 0.06943384747890269, 'NC_000069.7 chromosome 3 ': 0.06089687267535444, 'NC_000070.7 chromosome 4 ': 0.05973657859357644, 'NC_000071.7 chromosome 5 ': 0.05777237238407499, 'NC_000072.7 chromosome 6 ': 0.05692873012746803, 'NC_000073.7 chromosome 7 ': 0.05514323096914493, 'NC_000074.7 chromosome 8 ': 0.04936339407766343, 'NC_000075.7 chromosome 9 ': 0.04714048718540474, 'NC_000076.7 chromosome 10 ': 0.04952012822707635, 'NC_000077.7 chromosome 11 ': 0.046193347861417426, 'NC_000078.7 chromosome 12 ': 0.04546224786787696, 'NC_000079.7 chromosome 13 ': 0.045769527941966814, 'NC_000080.7 chromosome 14 ': 0.04742426226866744, 'NC_000081.7 chromosome 15 ': 0.03923483415195581, 'NC_000082.7 chromosome 16 ': 0.03687703305735309, 'NC_000083.7 chromosome 17 ': 0.03582184355076317, 'NC_000084.7 chromosome 18 ': 0.034063134375038745, 'NC_000085.7 chromosome 19 ': 0.022652838303702575, 'NT_162750.1 chromosome 1 unlocalized genomic scaffold': 8.045741799112608e-05, 'NT_166280.1 chromosome 1 unlocalized genomic scaffold': 6.598168383678023e-05, 'NT_166281.1 chromosome 1 unlocalized genomic scaffold': 9.397603383287122e-05, 'NT_166282.1 chromosome 1 unlocalized genomic scaffold': 5.971998413691857e-05, 'NT_166307.1 chromosome 7 unlocalized genomic scaffold': 6.840869018347646e-05, 'NT_166338.1 chromosome 1 unlocalized genomic scaffold': 1.557202726626053e-05, 'NT_166438.1 chromosome 5 unlocalized genomic scaffold': 7.619353754733873e-05, 'NT_187055.1 chromosome 4 unlocalized genomic scaffold': 7.681826911856104e-07, 'NT_187056.1 chromosome 5 unlocalized genomic scaffold': 7.750559047383238e-05, 'NT_187057.1 chromosome 5 unlocalized genomic scaffold': 7.99967416302683e-05, 'NT_187058.1 chromosome 5 unlocalized genomic scaffold': 7.160465673420364e-05, 'NT_187059.1 chromosome 5 unlocalized genomic scaffold': 0.0003704895358766098, 'NW_023337852.1 chromosome 1 unlocalized genomic scaffold': 3.2702190274561515e-06}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999997
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Macaca thibetana thibetana
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_024542745.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_065599.1 chromosome Y ', 'NC_065598.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_065578.1 chromosome 1 ', 'NC_065579.1 chromosome 2 ', 'NC_065580.1 chromosome 3 ', 'NC_065581.1 chromosome 4 ', 'NC_065582.1 chromosome 5 ', 'NC_065583.1 chromosome 6 ', 'NC_065584.1 chromosome 7 ', 'NC_065585.1 chromosome 8 ', 'NC_065586.1 chromosome 9 ', 'NC_065587.1 chromosome 10 ', 'NC_065588.1 chromosome 11 ', 'NC_065589.1 chromosome 12 ', 'NC_065590.1 chromosome 13 ', 'NC_065591.1 chromosome 14 ', 'NC_065592.1 chromosome 15 ', 'NC_065593.1 chromosome 16 ', 'NC_065594.1 chromosome 17 ', 'NC_065595.1 chromosome 18 ', 'NC_065596.1 chromosome 19 ', 'NC_065597.1 chromosome 20 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_065599.1 chromosome Y ': 13980984, 'NC_065598.1 chromosome X ': 150623419, 'NC_065578.1 chromosome 1 ': 440717450, 'NC_065579.1 chromosome 2 ': 388858296, 'NC_065580.1 chromosome 3 ': 370244344, 'NC_065581.1 chromosome 4 ': 337606734, 'NC_065582.1 chromosome 5 ': 371886000, 'NC_065583.1 chromosome 6 ': 353442578, 'NC_065584.1 chromosome 7 ': 334985354, 'NC_065585.1 chromosome 8 ': 284152360, 'NC_065586.1 chromosome 9 ': 259633458, 'NC_065587.1 chromosome 10 ': 193506794, 'NC_065588.1 chromosome 11 ': 259204282, 'NC_065589.1 chromosome 12 ': 256822080, 'NC_065590.1 chromosome 13 ': 214157138, 'NC_065591.1 chromosome 14 ': 252576470, 'NC_065592.1 chromosome 15 ': 220636000, 'NC_065593.1 chromosome 16 ': 155906002, 'NC_065594.1 chromosome 17 ': 187118888, 'NC_065595.1 chromosome 18 ': 145543466, 'NC_065596.1 chromosome 19 ': 113358026, 'NC_065597.1 chromosome 20 ': 151433910}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_065599.1 chromosome Y ': 0.0025623120169554663, 'NC_065598.1 chromosome X ': 0.027604938002834298, 'NC_065578.1 chromosome 1 ': 0.08077082544525978, 'NC_065579.1 chromosome 2 ': 0.07126653494014625, 'NC_065580.1 chromosome 3 ': 0.06785513321816214, 'NC_065581.1 chromosome 4 ': 0.06187359856311169, 'NC_065582.1 chromosome 5 ': 0.06815600151874149, 'NC_065583.1 chromosome 6 ': 0.06477585303817812, 'NC_065584.1 chromosome 7 ': 0.061393175048214114, 'NC_065585.1 chromosome 8 ': 0.05207695013986539, 'NC_065586.1 chromosome 9 ': 0.04758334101784984, 'NC_065587.1 chromosome 10 ': 0.035464226525738524, 'NC_065588.1 chromosome 11 ': 0.0475046854080452, 'NC_065589.1 chromosome 12 ': 0.04706809633738927, 'NC_065590.1 chromosome 13 ': 0.03924884029723445, 'NC_065591.1 chromosome 14 ': 0.04628999820622009, 'NC_065592.1 chromosome 15 ': 0.04043622925060112, 'NC_065593.1 chromosome 16 ': 0.028573083442487518, 'NC_065594.1 chromosome 17 ': 0.03429350718960439, 'NC_065595.1 chromosome 18 ': 0.02667392881081541, 'NC_065596.1 chromosome 19 ': 0.02077526390403924, 'NC_065597.1 chromosome 20 ': 0.027753477678506215}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Rattus rattus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011064425.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_046172.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_046154.1 chromosome 1 ', 'NC_046155.1 chromosome 2 ', 'NC_046156.1 chromosome 3 ', 'NC_046157.1 chromosome 4 ', 'NC_046158.1 chromosome 5 ', 'NC_046159.1 chromosome 6 ', 'NC_046160.1 chromosome 7 ', 'NC_046161.1 chromosome 8 ', 'NC_046162.1 chromosome 9 ', 'NC_046163.1 chromosome 10 ', 'NC_046164.1 chromosome 11 ', 'NC_046165.1 chromosome 12 ', 'NC_046166.1 chromosome 13 ', 'NC_046167.1 chromosome 14 ', 'NC_046168.1 chromosome 15 ', 'NC_046169.1 chromosome 16 ', 'NC_046170.1 chromosome 17 ', 'NC_046171.1 chromosome 18 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_046172.1 chromosome X ': 260747026, 'NC_046154.1 chromosome 1 ': 545899780, 'NC_046155.1 chromosome 2 ': 460490430, 'NC_046156.1 chromosome 3 ': 446780580, 'NC_046157.1 chromosome 4 ': 365650368, 'NC_046158.1 chromosome 5 ': 317649504, 'NC_046159.1 chromosome 6 ': 319153832, 'NC_046160.1 chromosome 7 ': 261677498, 'NC_046161.1 chromosome 8 ': 230657978, 'NC_046162.1 chromosome 9 ': 193419404, 'NC_046163.1 chromosome 10 ': 189950930, 'NC_046164.1 chromosome 11 ': 197229706, 'NC_046165.1 chromosome 12 ': 188176076, 'NC_046166.1 chromosome 13 ': 157637022, 'NC_046167.1 chromosome 14 ': 163988198, 'NC_046168.1 chromosome 15 ': 158636486, 'NC_046169.1 chromosome 16 ': 88862024, 'NC_046170.1 chromosome 17 ': 97008248, 'NC_046171.1 chromosome 18 ': 99693070}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_046172.1 chromosome X ': 0.05497155512662285, 'NC_046154.1 chromosome 1 ': 0.11508840699061812, 'NC_046155.1 chromosome 2 ': 0.09708212379775047, 'NC_046156.1 chromosome 3 ': 0.09419176762911394, 'NC_046157.1 chromosome 4 ': 0.07708762653953312, 'NC_046158.1 chromosome 5 ': 0.0669679247658242, 'NC_046159.1 chromosome 6 ': 0.06728507219737542, 'NC_046160.1 chromosome 7 ': 0.055167720327915615, 'NC_046161.1 chromosome 8 ': 0.04862808196716445, 'NC_046162.1 chromosome 9 ': 0.040777321960882254, 'NC_046163.1 chromosome 10 ': 0.04004608673791078, 'NC_046164.1 chromosome 11 ': 0.04158062249955103, 'NC_046165.1 chromosome 12 ': 0.03967190611541461, 'NC_046166.1 chromosome 13 ': 0.03323356119455667, 'NC_046167.1 chromosome 14 ': 0.03457253723949489, 'NC_046168.1 chromosome 15 ': 0.03344427151871997, 'NC_046169.1 chromosome 16 ': 0.01873418740729677, 'NC_046170.1 chromosome 17 ': 0.020451601440965625, 'NC_046171.1 chromosome 18 ': 0.021017624543289214}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Mus musculus
DEBUG:mammals_gender_dataset:Sample/assembly id: CAST_EiJ
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1.0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['EiJ_chrX']
DEBUG:mammals_gender_dataset:Autosomes: ['EiJ_chr1', 'EiJ_chr10', 'EiJ_chr11', 'EiJ_chr12', 'EiJ_chr13', 'EiJ_chr14', 'EiJ_chr15', 'EiJ_chr16', 'EiJ_chr17', 'EiJ_chr18', 'EiJ_chr19', 'EiJ_chr2', 'EiJ_chr3', 'EiJ_chr4', 'EiJ_chr5', 'EiJ_chr6', 'EiJ_chr7', 'EiJ_chr8', 'EiJ_chr9']
DEBUG:mammals_gender_dataset:Chromosomes length: {'EiJ_chrX': 335662598, 'EiJ_chr1': 384743942, 'EiJ_chr10': 254989986, 'EiJ_chr11': 237765086, 'EiJ_chr12': 234058044, 'EiJ_chr13': 234643278, 'EiJ_chr14': 243604488, 'EiJ_chr15': 201787370, 'EiJ_chr16': 190215536, 'EiJ_chr17': 183774542, 'EiJ_chr18': 175205278, 'EiJ_chr19': 116663132, 'EiJ_chr2': 357926448, 'EiJ_chr3': 313879360, 'EiJ_chr4': 306616232, 'EiJ_chr5': 297469368, 'EiJ_chr6': 293073092, 'EiJ_chr7': 284682918, 'EiJ_chr8': 252602426, 'EiJ_chr9': 242990220}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'EiJ_chrX': 0.06527412169987205, 'EiJ_chr1': 0.07481865135714796, 'EiJ_chr10': 0.04958624367917414, 'EiJ_chr11': 0.04623662943687442, 'EiJ_chr12': 0.04551574509618139, 'EiJ_chr13': 0.04562955174478185, 'EiJ_chr14': 0.04737217995419025, 'EiJ_chr15': 0.03924027706797738, 'EiJ_chr16': 0.036989977793326835, 'EiJ_chr17': 0.035737439593571424, 'EiJ_chr18': 0.03407103057288473, 'EiJ_chr19': 0.02268672030017547, 'EiJ_chr2': 0.06960362776657923, 'EiJ_chr3': 0.061038077122068726, 'EiJ_chr4': 0.05962566387192237, 'EiJ_chr5': 0.05784693273695041, 'EiJ_chr6': 0.05699201754425376, 'EiJ_chr7': 0.055360434990754305, 'EiJ_chr8': 0.049121950418815875, 'EiJ_chr9': 0.04725272725249741}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0

{'labels': 1, 'species': 'Bos indicus', 'sampled_chromosomes': ['NC_032656.1 chromosome 7 ', 'NC_032657.1 chromosome 8 ', 'NC_032653.1 chromosome 4 ', 'NC_032668.1 chromosome 19 ', 'NC_032650.1 chromosome 1 ', 'NC_032669.1 chromosome 20 ', 'NC_032651.1 chromosome 2 ', 'NC_032677.1 chromosome 28 ', 'NC_032656.1 chromosome 7 ', 'NC_032663.1 chromosome 14 '], 'chunks': ['GCGTCCCAAC', 'CAGGCGCACG', 'TTGATGCTTT', 'TTAAAGGCGT', 'AAATCCCATG', 'GATTGAAGGT', 'AATTTTATAT', 'GCCACCCCGG', 'TTTTTTTTTT', 'CTGTGAAGAT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Canis lupus familiaris', 'sampled_chromosomes': ['NC_051805.1 chromosome 1 ', 'NC_051812.1 chromosome 8 ', 'NC_051814.1 chromosome 10 ', 'NC_051843.1 chromosome X ', 'NC_051818.1 chromosome 14 ', 'NC_051817.1 chromosome 13 ', 'NC_051843.1 chromosome X ', 'NC_051811.1 chromosome 7 ', 'NC_051825.1 chromosome 21 ', 'NC_051814.1 chromosome 10 '], 'chunks': ['TTCTACAGAA', 'TAATAACTGA', 'AAAAATATTC', 'CCCAGAGATG', 'AACACAATCT', 'GGCACCTGCC', 'TCTGGAATCT', 'TTTATTTAAA', 'TATTTCCCCC', 'CTGAGCCTCT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Mus musculus', 'sampled_chromosomes': ['NC_000085.7 chromosome 19 ', 'NC_000080.7 chromosome 14 ', 'NC_000074.7 chromosome 8 ', 'NC_000084.7 chromosome 18 ', 'NC_000079.7 chromosome 13 ', 'NC_000081.7 chromosome 15 ', 'NC_000075.7 chromosome 9 ', 'NC_000084.7 chromosome 18 ', 'NC_000086.8 chromosome X ', 'NC_000078.7 chromosome 12 '], 'chunks': ['ACTCAGTCCT', 'GAGCTTTGAA', 'AAATAGATAT', 'TGAGTCTGTT', 'TAACCCCCCT', 'GTGGGGATAC', 'GAAGTTTAAC', 'CCACATGAAC', 'TCTCTGGTTT', 'ATTTAGTGTT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 0, 'species': 'Macaca thibetana thibetana', 'sampled_chromosomes': ['NC_065584.1 chromosome 7 ', 'NC_065578.1 chromosome 1 ', 'NC_065580.1 chromosome 3 ', 'NC_065582.1 chromosome 5 ', 'NC_065599.1 chromosome Y ', 'NC_065578.1 chromosome 1 ', 'NC_065581.1 chromosome 4 ', 'NC_065581.1 chromosome 4 ', 'NC_065589.1 chromosome 12 ', 'NC_065590.1 chromosome 13 '], 'chunks': ['ATAATGAATT', 'TTGGCCAGGC', 'CACGATCTTG', 'GGTGATTTCA', 'CAATTCACTA', 'AATTACCAGC', 'GTAGGCAGCA', 'GAGGATCCAG', 'AAGCCATTTT', 'CCCATCTCTA'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Rattus rattus', 'sampled_chromosomes': ['NC_046160.1 chromosome 7 ', 'NC_046157.1 chromosome 4 ', 'NC_046172.1 chromosome X ', 'NC_046170.1 chromosome 17 ', 'NC_046157.1 chromosome 4 ', 'NC_046169.1 chromosome 16 ', 'NC_046154.1 chromosome 1 ', 'NC_046156.1 chromosome 3 ', 'NC_046159.1 chromosome 6 ', 'NC_046164.1 chromosome 11 '], 'chunks': ['TCTATTTCAA', 'GAACGTTGAA', 'ATAAGAATGG', 'AAATCAGGAG', 'AGACAGCACT', 'CTTAGACAGA', 'ACTTTACTTA', 'ACAACCATCA', 'GGGAAAATGG', 'TCTACATAAA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}

DEBUG:mammals_gender_dataset:Label: 1.0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Arvicanthis niloticus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011762505.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_047679.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_047658.1 chromosome 1 ', 'NC_047659.1 chromosome 2 ', 'NC_047660.1 chromosome 3 ', 'NC_047661.1 chromosome 4 ', 'NC_047662.1 chromosome 5 ', 'NC_047663.1 chromosome 6 ', 'NC_047664.1 chromosome 7 ', 'NC_047665.1 chromosome 8 ', 'NC_047666.1 chromosome 9 ', 'NC_047667.1 chromosome 10 ', 'NC_047668.1 chromosome 11 ', 'NC_047669.1 chromosome 12 ', 'NC_047670.1 chromosome 13 ', 'NC_047671.1 chromosome 14 ', 'NC_047672.1 chromosome 15 ', 'NC_047673.1 chromosome 16 ', 'NC_047674.1 chromosome 17 ', 'NC_047675.1 chromosome 18 ', 'NC_047676.1 chromosome 19 ', 'NC_047677.1 chromosome 20 ', 'NC_047678.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_047679.1 chromosome X ': 260706670, 'NC_047658.1 chromosome 1 ': 334233126, 'NC_047659.1 chromosome 2 ': 298647216, 'NC_047660.1 chromosome 3 ': 278543182, 'NC_047661.1 chromosome 4 ': 270236198, 'NC_047662.1 chromosome 5 ': 217382080, 'NC_047663.1 chromosome 6 ': 217296002, 'NC_047664.1 chromosome 7 ': 182853410, 'NC_047665.1 chromosome 8 ': 176469402, 'NC_047666.1 chromosome 9 ': 172772988, 'NC_047667.1 chromosome 10 ': 165378234, 'NC_047668.1 chromosome 11 ': 161882470, 'NC_047669.1 chromosome 12 ': 159107368, 'NC_047670.1 chromosome 13 ': 156082964, 'NC_047671.1 chromosome 14 ': 152795984, 'NC_047672.1 chromosome 15 ': 147790464, 'NC_047673.1 chromosome 16 ': 146846972, 'NC_047674.1 chromosome 17 ': 128083624, 'NC_047675.1 chromosome 18 ': 109678282, 'NC_047676.1 chromosome 19 ': 106271352, 'NC_047677.1 chromosome 20 ': 104862384, 'NC_047678.1 chromosome 21 ': 104166660}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_047679.1 chromosome X ': 0.06433886240378264, 'NC_047658.1 chromosome 1 ': 0.08248419230892769, 'NC_047659.1 chromosome 2 ': 0.07370207343562309, 'NC_047660.1 chromosome 3 ': 0.06874067111597025, 'NC_047661.1 chromosome 4 ': 0.0666906203805348, 'NC_047662.1 chromosome 5 ': 0.05364694249735947, 'NC_047663.1 chromosome 6 ': 0.053625699617006646, 'NC_047664.1 chromosome 7 ': 0.0451257360851276, 'NC_047665.1 chromosome 8 ': 0.04355024968772685, 'NC_047666.1 chromosome 9 ': 0.04263802495740669, 'NC_047667.1 chromosome 10 ': 0.04081310018614625, 'NC_047668.1 chromosome 11 ': 0.03995039314841646, 'NC_047669.1 chromosome 12 ': 0.03926553569642085, 'NC_047670.1 chromosome 13 ': 0.038519153899555236, 'NC_047671.1 chromosome 14 ': 0.0377079719150514, 'NC_047672.1 chromosome 15 ': 0.03647267761844065, 'NC_047673.1 chromosome 16 ': 0.036239836617606, 'NC_047674.1 chromosome 17 ': 0.031609297378980876, 'NC_047675.1 chromosome 18 ': 0.02706710915482627, 'NC_047676.1 chromosome 19 ': 0.026226325140787352, 'NC_047677.1 chromosome 20 ': 0.025878610990308068, 'NC_047678.1 chromosome 21 ': 0.025706915763994875}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Papio anubis
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_008728515.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_044996.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_044976.1 chromosome 1 ', 'NC_044977.1 chromosome 2 ', 'NC_044978.1 chromosome 3 ', 'NC_044979.1 chromosome 4 ', 'NC_044980.1 chromosome 5 ', 'NC_044981.1 chromosome 6 ', 'NC_044982.1 chromosome 7 ', 'NC_044983.1 chromosome 8 ', 'NC_044984.1 chromosome 9 ', 'NC_044985.1 chromosome 10 ', 'NC_044986.1 chromosome 11 ', 'NC_044987.1 chromosome 12 ', 'NC_044988.1 chromosome 13 ', 'NC_044989.1 chromosome 14 ', 'NC_044990.1 chromosome 15 ', 'NC_044991.1 chromosome 16 ', 'NC_044992.1 chromosome 17 ', 'NC_044993.1 chromosome 18 ', 'NC_044994.1 chromosome 19 ', 'NC_044995.1 chromosome 20 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_044996.1 chromosome X ': 285422992, 'NC_044976.1 chromosome 1 ': 436345764, 'NC_044977.1 chromosome 2 ': 387321500, 'NC_044978.1 chromosome 3 ': 369839030, 'NC_044979.1 chromosome 4 ': 364241804, 'NC_044980.1 chromosome 5 ': 347801522, 'NC_044981.1 chromosome 6 ': 334276494, 'NC_044982.1 chromosome 7 ': 323536936, 'NC_044983.1 chromosome 8 ': 280549772, 'NC_044984.1 chromosome 9 ': 255183638, 'NC_044985.1 chromosome 10 ': 252925378, 'NC_044986.1 chromosome 11 ': 251827392, 'NC_044987.1 chromosome 12 ': 246686900, 'NC_044988.1 chromosome 13 ': 213698002, 'NC_044989.1 chromosome 14 ': 213309948, 'NC_044990.1 chromosome 15 ': 183971550, 'NC_044991.1 chromosome 16 ': 182368386, 'NC_044992.1 chromosome 17 ': 149051852, 'NC_044993.1 chromosome 18 ': 145788816, 'NC_044994.1 chromosome 19 ': 144246688, 'NC_044995.1 chromosome 20 ': 100042216}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_044996.1 chromosome X ': 0.05219462415343583, 'NC_044976.1 chromosome 1 ': 0.07979351275570613, 'NC_044977.1 chromosome 2 ': 0.07082856211893747, 'NC_044978.1 chromosome 3 ': 0.06763158438238667, 'NC_044979.1 chromosome 4 ': 0.06660803296725808, 'NC_044980.1 chromosome 5 ': 0.06360163767319398, 'NC_044981.1 chromosome 6 ': 0.061128347949131745, 'NC_044982.1 chromosome 7 ': 0.05916443050346211, 'NC_044983.1 chromosome 8 ': 0.05130346999470917, 'NC_044984.1 chromosome 9 ': 0.0466648253603775, 'NC_044985.1 chromosome 10 ': 0.04625186272161174, 'NC_044986.1 chromosome 11 ': 0.04605107663148578, 'NC_044987.1 chromosome 12 ': 0.04511104707737143, 'NC_044988.1 chromosome 13 ': 0.03907844570815156, 'NC_044989.1 chromosome 14 ': 0.03900748319549863, 'NC_044990.1 chromosome 15 ': 0.033642440084767335, 'NC_044991.1 chromosome 16 ': 0.03334927329448886, 'NC_044992.1 chromosome 17 ': 0.02725675790867451, 'NC_044993.1 chromosome 18 ': 0.026660054270941185, 'NC_044994.1 chromosome 19 ': 0.026378048988912293, 'NC_044995.1 chromosome 20 ': 0.018294482259498014}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Mustela lutreola
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_030435805.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_081308.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_081290.1 chromosome 1 ', 'NC_081291.1 chromosome 2 ', 'NC_081292.1 chromosome 3 ', 'NC_081293.1 chromosome 4 ', 'NC_081294.1 chromosome 5 ', 'NC_081295.1 chromosome 6 ', 'NC_081296.1 chromosome 7 ', 'NC_081297.1 chromosome 8 ', 'NC_081298.1 chromosome 9 ', 'NC_081299.1 chromosome 10 ', 'NC_081300.1 chromosome 11 ', 'NC_081301.1 chromosome 12 ', 'NC_081302.1 chromosome 13 ', 'NC_081303.1 chromosome 14 ', 'NC_081304.1 chromosome 15 ', 'NC_081305.1 chromosome 16 ', 'NC_081306.1 chromosome 17 ', 'NC_081307.1 chromosome 18 ', 'NW_026709257.1 chromosome 4 unlocalized genomic scaffold', 'NW_026709258.1 chromosome 5 unlocalized genomic scaffold', 'NW_026709259.1 chromosome 16 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_081308.1 chromosome X ': 266165512, 'NC_081290.1 chromosome 1 ': 580209788, 'NC_081291.1 chromosome 2 ': 450360622, 'NC_081292.1 chromosome 3 ': 422582014, 'NC_081293.1 chromosome 4 ': 405148736, 'NC_081294.1 chromosome 5 ': 354945442, 'NC_081295.1 chromosome 6 ': 320021132, 'NC_081296.1 chromosome 7 ': 308157286, 'NC_081297.1 chromosome 8 ': 303022374, 'NC_081298.1 chromosome 9 ': 292543060, 'NC_081299.1 chromosome 10 ': 247627348, 'NC_081300.1 chromosome 11 ': 209097952, 'NC_081301.1 chromosome 12 ': 201223108, 'NC_081302.1 chromosome 13 ': 184206380, 'NC_081303.1 chromosome 14 ': 151745266, 'NC_081304.1 chromosome 15 ': 141844742, 'NC_081305.1 chromosome 16 ': 128067692, 'NC_081306.1 chromosome 17 ': 98796040, 'NC_081307.1 chromosome 18 ': 84746544, 'NW_026709257.1 chromosome 4 unlocalized genomic scaffold': 1395006, 'NW_026709258.1 chromosome 5 unlocalized genomic scaffold': 2109010, 'NW_026709259.1 chromosome 16 unlocalized genomic scaffold': 2893842}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_081308.1 chromosome X ': 0.051613382622767205, 'NC_081290.1 chromosome 1 ': 0.11251115730395095, 'NC_081291.1 chromosome 2 ': 0.08733150635050506, 'NC_081292.1 chromosome 3 ': 0.0819448282919598, 'NC_081293.1 chromosome 4 ': 0.07856426091107738, 'NC_081294.1 chromosome 5 ': 0.06882910851407835, 'NC_081295.1 chromosome 6 ': 0.06205677440767416, 'NC_081296.1 chromosome 7 ': 0.05975620128542988, 'NC_081297.1 chromosome 8 ': 0.058760466805035445, 'NC_081298.1 chromosome 9 ': 0.05672837467167851, 'NC_081299.1 chromosome 10 ': 0.048018561699252484, 'NC_081300.1 chromosome 11 ': 0.04054714873132403, 'NC_081301.1 chromosome 12 ': 0.039020101393701254, 'NC_081302.1 chromosome 13 ': 0.035720309145442, 'NC_081303.1 chromosome 14 ': 0.029425624741538967, 'NC_081304.1 chromosome 15 ': 0.02750576844784345, 'NC_081305.1 chromosome 16 ': 0.024834197109694294, 'NC_081306.1 chromosome 17 ': 0.019157995999625275, 'NC_081307.1 chromosome 18 ': 0.016433593400444667, 'NW_026709257.1 chromosome 4 unlocalized genomic scaffold': 0.00027051205055843595, 'NW_026709258.1 chromosome 5 unlocalized genomic scaffold': 0.00040896786088966423, 'NW_026709259.1 chromosome 16 unlocalized genomic scaffold': 0.00056115825552874}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Meles meles
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_922984935.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_060088.1 chromosome Y ', 'NC_060087.1 chromosome X ', 'NW_025721105.1 chromosome X unlocalized genomic scaffold', 'NW_025721106.1 chromosome X unlocalized genomic scaffold', 'NW_025721107.1 chromosome X unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_060066.1 chromosome 1 ', 'NC_060067.1 chromosome 2 ', 'NC_060068.1 chromosome 3 ', 'NC_060069.1 chromosome 4 ', 'NC_060070.1 chromosome 5 ', 'NC_060071.1 chromosome 6 ', 'NC_060072.1 chromosome 7 ', 'NC_060073.1 chromosome 8 ', 'NC_060074.1 chromosome 9 ', 'NC_060075.1 chromosome 10 ', 'NC_060076.1 chromosome 11 ', 'NC_060077.1 chromosome 12 ', 'NC_060078.1 chromosome 13 ', 'NC_060079.1 chromosome 14 ', 'NC_060080.1 chromosome 15 ', 'NC_060081.1 chromosome 16 ', 'NC_060082.1 chromosome 17 ', 'NC_060083.1 chromosome 18 ', 'NC_060084.1 chromosome 19 ', 'NC_060085.1 chromosome 20 ', 'NC_060086.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_060088.1 chromosome Y ': 44745037, 'NC_060087.1 chromosome X ': 132955750, 'NW_025721105.1 chromosome X unlocalized genomic scaffold': 88411, 'NW_025721106.1 chromosome X unlocalized genomic scaffold': 23696, 'NW_025721107.1 chromosome X unlocalized genomic scaffold': 19779, 'NC_060066.1 chromosome 1 ': 433931002, 'NC_060067.1 chromosome 2 ': 421458882, 'NC_060068.1 chromosome 3 ': 368596490, 'NC_060069.1 chromosome 4 ': 329533118, 'NC_060070.1 chromosome 5 ': 316065892, 'NC_060071.1 chromosome 6 ': 307541514, 'NC_060072.1 chromosome 7 ': 302275162, 'NC_060073.1 chromosome 8 ': 240260840, 'NC_060074.1 chromosome 9 ': 237412256, 'NC_060075.1 chromosome 10 ': 219946646, 'NC_060076.1 chromosome 11 ': 197097284, 'NC_060077.1 chromosome 12 ': 192867276, 'NC_060078.1 chromosome 13 ': 175700910, 'NC_060079.1 chromosome 14 ': 173070976, 'NC_060080.1 chromosome 15 ': 169968488, 'NC_060081.1 chromosome 16 ': 165907548, 'NC_060082.1 chromosome 17 ': 138477822, 'NC_060083.1 chromosome 18 ': 129040510, 'NC_060084.1 chromosome 19 ': 124339868, 'NC_060085.1 chromosome 20 ': 122973998, 'NC_060086.1 chromosome 21 ': 90235732}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_060088.1 chromosome Y ': 0.008887620803967228, 'NC_060087.1 chromosome X ': 0.026408745392412253, 'NW_025721105.1 chromosome X unlocalized genomic scaffold': 1.7560907210771703e-05, 'NW_025721106.1 chromosome X unlocalized genomic scaffold': 4.706690991691603e-06, 'NW_025721107.1 chromosome X unlocalized genomic scaffold': 3.928664801007267e-06, 'NC_060066.1 chromosome 1 ': 0.08619088192644796, 'NC_060067.1 chromosome 2 ': 0.08371356867310153, 'NC_060068.1 chromosome 3 ': 0.07321361322806144, 'NC_060069.1 chromosome 4 ': 0.06545453063616838, 'NC_060070.1 chromosome 5 ': 0.06277956138830904, 'NC_060071.1 chromosome 6 ': 0.06108638055009271, 'NC_060072.1 chromosome 7 ': 0.060040335161948, 'NC_060073.1 chromosome 8 ': 0.04772254942961924, 'NC_060074.1 chromosome 9 ': 0.047156740658017414, 'NC_060075.1 chromosome 10 ': 0.0436875800717835, 'NC_060076.1 chromosome 11 ': 0.03914905516077319, 'NC_060077.1 chromosome 12 ': 0.03830885679191838, 'NC_060078.1 chromosome 13 ': 0.034899134466957166, 'NC_060079.1 chromosome 14 ': 0.034376755725121264, 'NC_060080.1 chromosome 15 ': 0.033760514489409275, 'NC_060081.1 chromosome 16 ': 0.03295389777284108, 'NC_060082.1 chromosome 17 ': 0.027505583953261022, 'NC_060083.1 chromosome 18 ': 0.025631068787149314, 'NC_060084.1 chromosome 19 ': 0.02469738929033267, 'NC_060085.1 chromosome 20 ': 0.02442608915424127, 'NC_060086.1 chromosome 21 ': 0.017923350225063205}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Budorcas taxicolor
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_023091745.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_068936.1 chromosome Y ', 'NC_068935.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_068910.1 chromosome 1 ', 'NC_068911.1 chromosome 2 ', 'NC_068912.1 chromosome 3 ', 'NC_068913.1 chromosome 4 ', 'NC_068914.1 chromosome 5 ', 'NC_068915.1 chromosome 6 ', 'NC_068916.1 chromosome 7 ', 'NC_068917.1 chromosome 8 ', 'NC_068918.1 chromosome 9 ', 'NC_068919.1 chromosome 10 ', 'NC_068920.1 chromosome 11 ', 'NC_068921.1 chromosome 12 ', 'NC_068922.1 chromosome 13 ', 'NC_068923.1 chromosome 14 ', 'NC_068924.1 chromosome 15 ', 'NC_068925.1 chromosome 16 ', 'NC_068926.1 chromosome 17 ', 'NC_068927.1 chromosome 18 ', 'NC_068928.1 chromosome 19 ', 'NC_068929.1 chromosome 20 ', 'NC_068930.1 chromosome 21 ', 'NC_068931.1 chromosome 22 ', 'NC_068932.1 chromosome 23 ', 'NC_068933.1 chromosome 24 ', 'NC_068934.1 chromosome 25 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_068936.1 chromosome Y ': 11293021, 'NC_068935.1 chromosome X ': 146747936, 'NC_068910.1 chromosome 1 ': 443363910, 'NC_068911.1 chromosome 2 ': 361581120, 'NC_068912.1 chromosome 3 ': 242514874, 'NC_068913.1 chromosome 4 ': 243786826, 'NC_068914.1 chromosome 5 ': 328459970, 'NC_068915.1 chromosome 6 ': 234941170, 'NC_068916.1 chromosome 7 ': 219495396, 'NC_068917.1 chromosome 8 ': 232665740, 'NC_068918.1 chromosome 9 ': 190522314, 'NC_068919.1 chromosome 10 ': 202531878, 'NC_068920.1 chromosome 11 ': 332203558, 'NC_068921.1 chromosome 12 ': 174640522, 'NC_068922.1 chromosome 13 ': 166773768, 'NC_068923.1 chromosome 14 ': 190390618, 'NC_068924.1 chromosome 15 ': 163768502, 'NC_068925.1 chromosome 16 ': 163692860, 'NC_068926.1 chromosome 17 ': 146250216, 'NC_068927.1 chromosome 18 ': 136107162, 'NC_068928.1 chromosome 19 ': 125218408, 'NC_068929.1 chromosome 20 ': 149592478, 'NC_068930.1 chromosome 21 ': 148734572, 'NC_068931.1 chromosome 22 ': 125252580, 'NC_068932.1 chromosome 23 ': 102628326, 'NC_068933.1 chromosome 24 ': 89805930, 'NC_068934.1 chromosome 25 ': 104042192}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_068936.1 chromosome Y ': 0.002181380769840958, 'NC_068935.1 chromosome X ': 0.028346102039857324, 'NC_068910.1 chromosome 1 ': 0.08564099077788814, 'NC_068911.1 chromosome 2 ': 0.06984367618775841, 'NC_068912.1 chromosome 3 ': 0.0468446204557667, 'NC_068913.1 chromosome 4 ': 0.04709031305059679, 'NC_068914.1 chromosome 5 ': 0.06344593375152122, 'NC_068915.1 chromosome 6 ': 0.04538166981907989, 'NC_068916.1 chromosome 7 ': 0.0423981356187176, 'NC_068917.1 chromosome 8 ': 0.04494214356254329, 'NC_068918.1 chromosome 9 ': 0.03680164164975879, 'NC_068919.1 chromosome 10 ': 0.03912143118736563, 'NC_068920.1 chromosome 11 ': 0.06416905211581075, 'NC_068921.1 chromosome 12 ': 0.033733885408146036, 'NC_068922.1 chromosome 13 ': 0.03221432869283758, 'NC_068923.1 chromosome 14 ': 0.03677620300744466, 'NC_068924.1 chromosome 15 ': 0.03163382596813204, 'NC_068925.1 chromosome 16 ': 0.0316192148198669, 'NC_068926.1 chromosome 17 ': 0.028249961526458364, 'NC_068927.1 chromosome 18 ': 0.026290710503808323, 'NC_068928.1 chromosome 19 ': 0.024187418693483273, 'NC_068929.1 chromosome 20 ': 0.02889555902021758, 'NC_068930.1 chromosome 21 ': 0.028729844314583794, 'NC_068931.1 chromosome 22 ': 0.02419401942004413, 'NC_068932.1 chromosome 23 ': 0.019823876779948322, 'NC_068933.1 chromosome 24 ': 0.01734707911370068, 'NC_068934.1 chromosome 25 ': 0.02009698174482282}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Globicephala melas
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_963455315.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_083335.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_083314.1 chromosome 1 ', 'NC_083315.1 chromosome 2 ', 'NC_083316.1 chromosome 3 ', 'NC_083317.1 chromosome 4 ', 'NC_083318.1 chromosome 5 ', 'NC_083319.1 chromosome 6 ', 'NC_083320.1 chromosome 7 ', 'NC_083321.1 chromosome 8 ', 'NC_083322.1 chromosome 9 ', 'NC_083323.1 chromosome 10 ', 'NC_083324.1 chromosome 11 ', 'NC_083325.1 chromosome 12 ', 'NC_083326.1 chromosome 13 ', 'NC_083327.1 chromosome 14 ', 'NC_083328.1 chromosome 15 ', 'NC_083329.1 chromosome 16 ', 'NC_083330.1 chromosome 17 ', 'NC_083331.1 chromosome 18 ', 'NC_083332.1 chromosome 19 ', 'NC_083333.1 chromosome 20 ', 'NC_083334.1 chromosome 21 ']

{'labels': 1.0, 'species': 'Mus musculus', 'sampled_chromosomes': ['EiJ_chrX', 'EiJ_chr1', 'EiJ_chr1', 'EiJ_chr18', 'EiJ_chr5', 'EiJ_chr8', 'EiJ_chrX', 'EiJ_chr8', 'EiJ_chr5', 'EiJ_chr2'], 'chunks': ['TGAGCTTATG', 'GTAGACCAGG', 'CAGACATTTG', 'AAATATAAGT', 'GATGTAATCA', 'AGGTGCTCAC', 'AAAAGAAAAA', 'GTTAATAGTC', 'ATTGAACCTG', 'AGTCTTATAT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Arvicanthis niloticus', 'sampled_chromosomes': ['NC_047667.1 chromosome 10 ', 'NC_047658.1 chromosome 1 ', 'NC_047672.1 chromosome 15 ', 'NC_047658.1 chromosome 1 ', 'NC_047668.1 chromosome 11 ', 'NC_047669.1 chromosome 12 ', 'NC_047663.1 chromosome 6 ', 'NC_047658.1 chromosome 1 ', 'NC_047663.1 chromosome 6 ', 'NC_047662.1 chromosome 5 '], 'chunks': ['GACAAGACCA', 'TACATTTAGG', 'GTTAATGTTG', 'AGAGTCTGAA', 'TCATTTCTCC', 'AAACACACCC', 'AAAAAGAACA', 'GGCACAACTT', 'CCACAGCTCC', 'CACATATATA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Papio anubis', 'sampled_chromosomes': ['NC_044991.1 chromosome 16 ', 'NC_044984.1 chromosome 9 ', 'NC_044996.1 chromosome X ', 'NC_044993.1 chromosome 18 ', 'NC_044982.1 chromosome 7 ', 'NC_044996.1 chromosome X ', 'NC_044977.1 chromosome 2 ', 'NC_044990.1 chromosome 15 ', 'NC_044980.1 chromosome 5 ', 'NC_044987.1 chromosome 12 '], 'chunks': ['TATTTTACTT', 'ACACAAAAAC', 'TCCAGCTTTT', 'TGATGACATT', 'GTGGTTTTTA', 'CATCCTTAGG', 'TGGTAACTCG', 'ATAATTGGTG', 'CATTGACATC', 'TGGAAGAAGT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Mustela lutreola', 'sampled_chromosomes': ['NC_081291.1 chromosome 2 ', 'NC_081296.1 chromosome 7 ', 'NC_081291.1 chromosome 2 ', 'NC_081305.1 chromosome 16 ', 'NC_081301.1 chromosome 12 ', 'NC_081301.1 chromosome 12 ', 'NC_081308.1 chromosome X ', 'NC_081292.1 chromosome 3 ', 'NC_081294.1 chromosome 5 ', 'NC_081308.1 chromosome X '], 'chunks': ['GTACTCTGAT', 'AAGGGTTGAA', 'TGGTCCTGTC', 'TTGATAGGAA', 'ACTTAATATC', 'CCTGAGATCA', 'GAAGTGGGAC', 'ATATTTTATG', 'CTTCCGTGGT', 'ACTATTTTAA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 0, 'species': 'Meles meles', 'sampled_chromosomes': ['NC_060069.1 chromosome 4 ', 'NC_060082.1 chromosome 17 ', 'NC_060067.1 chromosome 2 ', 'NC_060079.1 chromosome 14 ', 'NC_060088.1 chromosome Y ', 'NC_060072.1 chromosome 7 ', 'NC_060072.1 chromosome 7 ', 'NC_060072.1 chromosome 7 ', 'NC_060074.1 chromosome 9 ', 'NC_060079.1 chromosome 14 '], 'chunks': ['AGTCCTTCAG', 'TTAATTCTGG', 'CCAGAGCACT', 'TCAATTCTAT', 'CCTGATATGC', 'CATGGGGTAA', 'AAAATTAAGA', 'TGCGTGAAAC', 'TAACATAGCT', 'TTTATTCTGC'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Budorcas taxicolor', 'sampled_chromosomes': ['NC_068932.1 chromosome 23 ', 'NC_068917.1 chromosome 8 ', 'NC_068916.1 chromosome 7 ', 'NC_068929.1 chromosome 20 ', 'NC_068936.1 chromosome Y ', 'NC_068920.1 chromosome 11 ', 'NC_068914.1 chromosome 5 ', 'NC_068927.1 chromosome 18 ', 'NC_068912.1 chromosome 3 ', 'NC_068910.1 chromosome 1 '], 'chunks': ['GTGCAAGGCG', 'CTTTTCTTTG', 'CTGGTGGTCT', 'GGGCCATCCA', 'GGACTTTAGG', 'CTTCTAACTC', 'TGTTGCTGAA', 'TTGTACAAGA', 'TCTAGTCAAG', 'CAATAAGAAG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_083335.1 chromosome X ': 251608796, 'NC_083314.1 chromosome 1 ': 376211502, 'NC_083315.1 chromosome 2 ': 357645432, 'NC_083316.1 chromosome 3 ': 342643638, 'NC_083317.1 chromosome 4 ': 292965586, 'NC_083318.1 chromosome 5 ': 280431184, 'NC_083319.1 chromosome 6 ': 230873462, 'NC_083320.1 chromosome 7 ': 230368126, 'NC_083321.1 chromosome 8 ': 216244426, 'NC_083322.1 chromosome 9 ': 210175864, 'NC_083323.1 chromosome 10 ': 206087028, 'NC_083324.1 chromosome 11 ': 205404662, 'NC_083325.1 chromosome 12 ': 181484796, 'NC_083326.1 chromosome 13 ': 179702716, 'NC_083327.1 chromosome 14 ': 177336390, 'NC_083328.1 chromosome 15 ': 173456714, 'NC_083329.1 chromosome 16 ': 167907120, 'NC_083330.1 chromosome 17 ': 159897700, 'NC_083331.1 chromosome 18 ': 159396420, 'NC_083332.1 chromosome 19 ': 125846918, 'NC_083333.1 chromosome 20 ': 117568280, 'NC_083334.1 chromosome 21 ': 71197884}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_083335.1 chromosome X ': 0.05336965036246937, 'NC_083314.1 chromosome 1 ': 0.07979958031387521, 'NC_083315.1 chromosome 2 ': 0.07586146415793156, 'NC_083316.1 chromosome 3 ': 0.07267937945613206, 'NC_083317.1 chromosome 4 ': 0.06214198844247063, 'NC_083318.1 chromosome 5 ': 0.059483271168362946, 'NC_083319.1 chromosome 6 ': 0.0489714037855531, 'NC_083320.1 chromosome 7 ': 0.04886421514165701, 'NC_083321.1 chromosome 8 ': 0.045868386129286516, 'NC_083322.1 chromosome 9 ': 0.04458116152787406, 'NC_083323.1 chromosome 10 ': 0.04371386375776956, 'NC_083324.1 chromosome 11 ': 0.04356912464125935, 'NC_083325.1 chromosome 12 ': 0.038495395481420606, 'NC_083326.1 chromosome 13 ': 0.03811739205693799, 'NC_083327.1 chromosome 14 ': 0.03761546210348906, 'NC_083328.1 chromosome 15 ': 0.036792530016330774, 'NC_083329.1 chromosome 16 ': 0.03561538559156409, 'NC_083330.1 chromosome 17 ': 0.03391647859068893, 'NC_083331.1 chromosome 18 ': 0.0338101502796004, 'NC_083332.1 chromosome 19 ': 0.02669384425198852, 'NC_083333.1 chromosome 20 ': 0.024937832448897773, 'NC_083334.1 chromosome 21 ': 0.01510204029444047}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Bos taurus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_002263795.3
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_082638.1 chromosome Y ', 'NC_037357.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_037328.1 chromosome 1 ', 'NC_037329.1 chromosome 2 ', 'NC_037330.1 chromosome 3 ', 'NC_037331.1 chromosome 4 ', 'NC_037332.1 chromosome 5 ', 'NC_037333.1 chromosome 6 ', 'NC_037334.1 chromosome 7 ', 'NC_037335.1 chromosome 8 ', 'NC_037336.1 chromosome 9 ', 'NC_037337.1 chromosome 10 ', 'NC_037338.1 chromosome 11 ', 'NC_037339.1 chromosome 12 ', 'NC_037340.1 chromosome 13 ', 'NC_037341.1 chromosome 14 ', 'NC_037342.1 chromosome 15 ', 'NC_037343.1 chromosome 16 ', 'NC_037344.1 chromosome 17 ', 'NC_037345.1 chromosome 18 ', 'NC_037346.1 chromosome 19 ', 'NC_037347.1 chromosome 20 ', 'NC_037348.1 chromosome 21 ', 'NC_037349.1 chromosome 22 ', 'NC_037350.1 chromosome 23 ', 'NC_037351.1 chromosome 24 ', 'NC_037352.1 chromosome 25 ', 'NC_037353.1 chromosome 26 ', 'NC_037354.1 chromosome 27 ', 'NC_037355.1 chromosome 28 ', 'NC_037356.1 chromosome 29 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_082638.1 chromosome Y ': 59476289, 'NC_037357.1 chromosome X ': 139009144, 'NC_037328.1 chromosome 1 ': 317068220, 'NC_037329.1 chromosome 2 ': 272462204, 'NC_037330.1 chromosome 3 ': 242010316, 'NC_037331.1 chromosome 4 ': 240001202, 'NC_037332.1 chromosome 5 ': 240178632, 'NC_037333.1 chromosome 6 ': 235612680, 'NC_037334.1 chromosome 7 ': 221365486, 'NC_037335.1 chromosome 8 ': 226639540, 'NC_037336.1 chromosome 9 ': 210908934, 'NC_037337.1 chromosome 10 ': 206617474, 'NC_037338.1 chromosome 11 ': 213964948, 'NC_037339.1 chromosome 12 ': 174432366, 'NC_037340.1 chromosome 13 ': 166944690, 'NC_037341.1 chromosome 14 ': 164806006, 'NC_037342.1 chromosome 15 ': 170015560, 'NC_037343.1 chromosome 16 ': 162027958, 'NC_037344.1 chromosome 17 ': 146334488, 'NC_037345.1 chromosome 18 ': 131641258, 'NC_037346.1 chromosome 19 ': 126899482, 'NC_037347.1 chromosome 20 ': 143949190, 'NC_037348.1 chromosome 21 ': 139725908, 'NC_037349.1 chromosome 22 ': 121546070, 'NC_037350.1 chromosome 23 ': 104997230, 'NC_037351.1 chromosome 24 ': 124634506, 'NC_037352.1 chromosome 25 ': 84700870, 'NC_037353.1 chromosome 26 ': 103984610, 'NC_037354.1 chromosome 27 ': 91224216, 'NC_037355.1 chromosome 28 ': 91880300, 'NC_037356.1 chromosome 29 ': 102197214}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_082638.1 chromosome Y ': 0.011487992406672478, 'NC_037357.1 chromosome X ': 0.026849960170346892, 'NC_037328.1 chromosome 1 ': 0.061242511343590364, 'NC_037329.1 chromosome 2 ': 0.05262674896642001, 'NC_037330.1 chromosome 3 ': 0.04674489143975353, 'NC_037331.1 chromosome 4 ': 0.046356826098687284, 'NC_037332.1 chromosome 5 ': 0.04639109714227435, 'NC_037333.1 chromosome 6 ': 0.04550917221408606, 'NC_037334.1 chromosome 7 ': 0.04275729143537121, 'NC_037335.1 chromosome 8 ': 0.043775988017203685, 'NC_037336.1 chromosome 9 ': 0.04073758253968042, 'NC_037337.1 chromosome 10 ': 0.039908676420579096, 'NC_037338.1 chromosome 11 ': 0.04132785920651626, 'NC_037339.1 chromosome 12 ': 0.033692043161702885, 'NC_037340.1 chromosome 13 ': 0.03224578001250701, 'NC_037341.1 chromosome 14 ': 0.03183268790529313, 'NC_037342.1 chromosome 15 ': 0.03283892615250708, 'NC_037343.1 chromosome 16 ': 0.03129610105924139, 'NC_037344.1 chromosome 17 ': 0.028264868492018806, 'NC_037345.1 chromosome 18 ': 0.02542683475609604, 'NC_037346.1 chromosome 19 ': 0.02451094898719506, 'NC_037347.1 chromosome 20 ': 0.027804142280407805, 'NC_037348.1 chromosome 21 ': 0.026988404910726984, 'NC_037349.1 chromosome 22 ': 0.023476924211274872, 'NC_037350.1 chromosome 23 ': 0.020280474811763115, 'NC_037351.1 chromosome 24 ': 0.02407346326764562, 'NC_037352.1 chromosome 25 ': 0.016360182650241556, 'NC_037353.1 chromosome 26 ': 0.02008488475282644, 'NC_037354.1 chromosome 27 ': 0.0176201830735043, 'NC_037355.1 chromosome 28 ': 0.017746907321719237, 'NC_037356.1 chromosome 29 ': 0.01973964479214704}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Mus musculus
DEBUG:mammals_gender_dataset:Sample/assembly id: CAST_EiJ
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1.0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['EiJ_chrX']
DEBUG:mammals_gender_dataset:Autosomes: ['EiJ_chr1', 'EiJ_chr10', 'EiJ_chr11', 'EiJ_chr12', 'EiJ_chr13', 'EiJ_chr14', 'EiJ_chr15', 'EiJ_chr16', 'EiJ_chr17', 'EiJ_chr18', 'EiJ_chr19', 'EiJ_chr2', 'EiJ_chr3', 'EiJ_chr4', 'EiJ_chr5', 'EiJ_chr6', 'EiJ_chr7', 'EiJ_chr8', 'EiJ_chr9']
DEBUG:mammals_gender_dataset:Chromosomes length: {'EiJ_chrX': 335662598, 'EiJ_chr1': 384743942, 'EiJ_chr10': 254989986, 'EiJ_chr11': 237765086, 'EiJ_chr12': 234058044, 'EiJ_chr13': 234643278, 'EiJ_chr14': 243604488, 'EiJ_chr15': 201787370, 'EiJ_chr16': 190215536, 'EiJ_chr17': 183774542, 'EiJ_chr18': 175205278, 'EiJ_chr19': 116663132, 'EiJ_chr2': 357926448, 'EiJ_chr3': 313879360, 'EiJ_chr4': 306616232, 'EiJ_chr5': 297469368, 'EiJ_chr6': 293073092, 'EiJ_chr7': 284682918, 'EiJ_chr8': 252602426, 'EiJ_chr9': 242990220}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'EiJ_chrX': 0.06527412169987205, 'EiJ_chr1': 0.07481865135714796, 'EiJ_chr10': 0.04958624367917414, 'EiJ_chr11': 0.04623662943687442, 'EiJ_chr12': 0.04551574509618139, 'EiJ_chr13': 0.04562955174478185, 'EiJ_chr14': 0.04737217995419025, 'EiJ_chr15': 0.03924027706797738, 'EiJ_chr16': 0.036989977793326835, 'EiJ_chr17': 0.035737439593571424, 'EiJ_chr18': 0.03407103057288473, 'EiJ_chr19': 0.02268672030017547, 'EiJ_chr2': 0.06960362776657923, 'EiJ_chr3': 0.061038077122068726, 'EiJ_chr4': 0.05962566387192237, 'EiJ_chr5': 0.05784693273695041, 'EiJ_chr6': 0.05699201754425376, 'EiJ_chr7': 0.055360434990754305, 'EiJ_chr8': 0.049121950418815875, 'EiJ_chr9': 0.04725272725249741}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0

{'labels': 1, 'species': 'Globicephala melas', 'sampled_chromosomes': ['NC_083332.1 chromosome 19 ', 'NC_083316.1 chromosome 3 ', 'NC_083324.1 chromosome 11 ', 'NC_083318.1 chromosome 5 ', 'NC_083317.1 chromosome 4 ', 'NC_083323.1 chromosome 10 ', 'NC_083329.1 chromosome 16 ', 'NC_083325.1 chromosome 12 ', 'NC_083327.1 chromosome 14 ', 'NC_083328.1 chromosome 15 '], 'chunks': ['CAAAGGCAGT', 'TTTTTTCAGT', 'TCTTAGTTTT', 'CTTCCTTCAT', 'CCAATTTCTT', 'GGGCAGTGAA', 'CAGGGGCAGG', 'CGAAAACGCT', 'AGTGTGTTTT', 'GTAGCAGGTG'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Bos taurus', 'sampled_chromosomes': ['NC_037343.1 chromosome 16 ', 'NC_082638.1 chromosome Y ', 'NC_037341.1 chromosome 14 ', 'NC_037348.1 chromosome 21 ', 'NC_037354.1 chromosome 27 ', 'NC_037350.1 chromosome 23 ', 'NC_037330.1 chromosome 3 ', 'NC_037348.1 chromosome 21 ', 'NC_037341.1 chromosome 14 ', 'NC_037339.1 chromosome 12 '], 'chunks': ['CGCCTCCCAT', 'GAGACTTACT', 'TATATCCTGA', 'TTGACATGAA', 'GGAGGTGAGG', 'CCGGAGGTCG', 'TTCAGAGGAG', 'TCCAGGGGAT', 'AGTGAGAGGC', 'CCAGGCTCCT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Label: 1.0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Macaca mulatta
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_003339765.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_041774.1 chromosome X ', 'NW_021160381.1 chromosome X unlocalized genomic scaffold', 'NW_021160382.1 chromosome X unlocalized genomic scaffold', 'NW_021160383.1 chromosome X unlocalized genomic scaffold', 'NW_021160384.1 chromosome X unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_041754.1 chromosome 1 ', 'NC_041755.1 chromosome 2 ', 'NC_041756.1 chromosome 3 ', 'NC_041757.1 chromosome 4 ', 'NC_041758.1 chromosome 5 ', 'NC_041759.1 chromosome 6 ', 'NC_041760.1 chromosome 7 ', 'NC_041761.1 chromosome 8 ', 'NC_041762.1 chromosome 9 ', 'NC_041763.1 chromosome 10 ', 'NC_041764.1 chromosome 11 ', 'NC_041765.1 chromosome 12 ', 'NC_041766.1 chromosome 13 ', 'NC_041767.1 chromosome 14 ', 'NC_041768.1 chromosome 15 ', 'NC_041769.1 chromosome 16 ', 'NC_041770.1 chromosome 17 ', 'NC_041771.1 chromosome 18 ', 'NC_041772.1 chromosome 19 ', 'NC_041773.1 chromosome 20 ', 'NW_021160094.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160095.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160096.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160097.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160098.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160099.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160100.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160101.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160102.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160103.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160104.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160105.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160106.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160107.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160108.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160109.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160110.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160111.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160112.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160113.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160114.1 chromosome 1 unlocalized genomic scaffold', 'NW_021160115.1 chromosome 2 unlocalized genomic scaffold', 'NW_021160116.1 chromosome 2 unlocalized genomic scaffold', 'NW_021160117.1 chromosome 2 unlocalized genomic scaffold', 'NW_021160118.1 chromosome 2 unlocalized genomic scaffold', 'NW_021160119.1 chromosome 2 unlocalized genomic scaffold', 'NW_021160120.1 chromosome 2 unlocalized genomic scaffold', 'NW_021160121.1 chromosome 2 unlocalized genomic scaffold', 'NW_021160122.1 chromosome 2 unlocalized genomic scaffold', 'NW_021160123.1 chromosome 2 unlocalized genomic scaffold', 'NW_021160124.1 chromosome 2 unlocalized genomic scaffold', 'NW_021160125.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160126.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160127.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160128.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160129.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160130.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160131.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160132.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160133.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160134.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160135.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160136.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160137.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160138.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160139.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160140.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160141.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160142.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160143.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160144.1 chromosome 3 unlocalized genomic scaffold', 'NW_021160145.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160146.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160147.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160148.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160149.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160150.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160151.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160152.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160153.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160154.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160155.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160156.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160157.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160158.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160159.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160160.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160161.1 chromosome 4 unlocalized genomic scaffold', 'NW_021160162.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160163.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160164.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160165.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160166.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160167.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160168.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160169.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160170.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160171.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160172.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160173.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160174.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160175.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160176.1 chromosome 5 unlocalized genomic scaffold', 'NW_021160177.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160178.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160179.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160180.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160181.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160182.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160183.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160184.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160185.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160186.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160187.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160188.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160189.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160190.1 chromosome 6 unlocalized genomic scaffold', 'NW_021160191.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160192.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160193.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160194.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160195.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160196.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160197.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160198.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160199.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160200.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160201.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160202.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160203.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160204.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160205.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160206.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160207.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160208.1 chromosome 7 unlocalized genomic scaffold', 'NW_021160209.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160210.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160211.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160212.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160213.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160214.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160215.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160216.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160217.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160218.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160219.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160220.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160221.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160222.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160223.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160224.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160225.1 chromosome 8 unlocalized genomic scaffold', 'NW_021160226.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160227.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160228.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160229.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160230.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160231.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160232.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160233.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160234.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160235.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160236.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160237.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160238.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160239.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160240.1 chromosome 9 unlocalized genomic scaffold', 'NW_021160241.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160242.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160243.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160244.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160245.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160246.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160247.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160248.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160249.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160250.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160251.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160252.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160253.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160254.1 chromosome 10 unlocalized genomic scaffold', 'NW_021160255.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160256.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160257.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160258.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160259.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160260.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160261.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160262.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160263.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160264.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160265.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160266.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160267.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160268.1 chromosome 11 unlocalized genomic scaffold', 'NW_021160269.1 chromosome 12 unlocalized genomic scaffold', 'NW_021160270.1 chromosome 12 unlocalized genomic scaffold', 'NW_021160271.1 chromosome 12 unlocalized genomic scaffold', 'NW_021160272.1 chromosome 12 unlocalized genomic scaffold', 'NW_021160273.1 chromosome 12 unlocalized genomic scaffold', 'NW_021160274.1 chromosome 12 unlocalized genomic scaffold', 'NW_021160275.1 chromosome 12 unlocalized genomic scaffold', 'NW_021160276.1 chromosome 13 unlocalized genomic scaffold', 'NW_021160277.1 chromosome 13 unlocalized genomic scaffold', 'NW_021160278.1 chromosome 13 unlocalized genomic scaffold', 'NW_021160279.1 chromosome 13 unlocalized genomic scaffold', 'NW_021160280.1 chromosome 13 unlocalized genomic scaffold', 'NW_021160281.1 chromosome 13 unlocalized genomic scaffold', 'NW_021160282.1 chromosome 13 unlocalized genomic scaffold', 'NW_021160283.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160284.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160285.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160286.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160287.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160288.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160289.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160290.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160291.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160292.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160293.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160294.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160295.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160296.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160297.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160298.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160299.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160300.1 chromosome 14 unlocalized genomic scaffold', 'NW_021160301.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160302.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160303.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160304.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160305.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160306.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160307.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160308.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160309.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160310.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160311.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160312.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160313.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160314.1 chromosome 15 unlocalized genomic scaffold', 'NW_021160315.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160316.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160317.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160318.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160319.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160320.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160321.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160322.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160323.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160324.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160325.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160326.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160327.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160328.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160329.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160330.1 chromosome 16 unlocalized genomic scaffold', 'NW_021160331.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160332.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160333.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160334.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160335.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160336.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160337.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160338.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160339.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160340.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160341.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160342.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160343.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160344.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160345.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160346.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160347.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160348.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160349.1 chromosome 17 unlocalized genomic scaffold', 'NW_021160350.1 chromosome 18 unlocalized genomic scaffold', 'NW_021160351.1 chromosome 18 unlocalized genomic scaffold', 'NW_021160352.1 chromosome 18 unlocalized genomic scaffold', 'NW_021160353.1 chromosome 18 unlocalized genomic scaffold', 'NW_021160354.1 chromosome 18 unlocalized genomic scaffold', 'NW_021160355.1 chromosome 18 unlocalized genomic scaffold', 'NW_021160356.1 chromosome 18 unlocalized genomic scaffold', 'NW_021160357.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160358.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160359.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160360.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160361.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160362.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160363.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160364.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160365.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160366.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160367.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160368.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160369.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160370.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160371.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160372.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160373.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160374.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160375.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160376.1 chromosome 19 unlocalized genomic scaffold', 'NW_021160377.1 chromosome 20 unlocalized genomic scaffold', 'NW_021160378.1 chromosome 20 unlocalized genomic scaffold', 'NW_021160379.1 chromosome 20 unlocalized genomic scaffold', 'NW_021160380.1 chromosome 20 unlocalized genomic scaffold']

{'labels': 1.0, 'species': 'Mus musculus', 'sampled_chromosomes': ['EiJ_chr11', 'EiJ_chr4', 'EiJ_chr18', 'EiJ_chr10', 'EiJ_chr4', 'EiJ_chr6', 'EiJ_chr13', 'EiJ_chr3', 'EiJ_chr17', 'EiJ_chr2'], 'chunks': ['TGGAGACATA', 'TAAGCAGAGT', 'AGCCAGTTTG', 'GGCTAAGCAG', 'TGGGCTCCTC', 'AAAAGGGACA', 'CTCCTCATTT', 'GTCTGTTCAA', 'GAGACAAAGT', 'ATGTCTTGTG'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Macaca mulatta', 'sampled_chromosomes': ['NC_041756.1 chromosome 3 ', 'NC_041771.1 chromosome 18 ', 'NC_041755.1 chromosome 2 ', 'NC_041758.1 chromosome 5 ', 'NC_041772.1 chromosome 19 ', 'NC_041769.1 chromosome 16 ', 'NC_041763.1 chromosome 10 ', 'NC_041756.1 chromosome 3 ', 'NC_041758.1 chromosome 5 ', 'NC_041770.1 chromosome 17 '], 'chunks': ['TCTGATGTTA', 'CTACATCAGC', 'TAGTGGCTCC', 'TCTTTTTATT', 'CTGCTGGCTG', 'CAATAATTAA', 'GGATAACCTG', 'TTGCGGTGGT', 'TTTGGAGGAA', 'CTCAAATCCA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Arvicanthis niloticus', 'sampled_chromosomes': ['NC_047664.1 chromosome 7 ', 'NC_047662.1 chromosome 5 ', 'NC_047661.1 chromosome 4 ', 'NC_047676.1 chromosome 19 ', 'NC_047662.1 chromosome 5 ', 'NC_047658.1 chromosome 1 ', 'NC_047659.1 chromosome 2 ', 'NW_023044977.1 chromosome Y unlocalized genomic scaffold', 'NC_047670.1 chromosome 13 ', 'NC_047672.1 chromosome 15 '], 'chunks': ['ATTGATAGAA', 'TTCAGGACCT', 'AAAAGAAGAG', 'ATCAGATCTT', 'CAGCTTTACA', 'GCATTTTAAC', 'CCTATATTTA', 'CTTCATTCAA', 'AATCGTGAAT', 'GGTTCGCCCT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Globicephala melas', 'sampled_chromosomes': ['NC_083319.1 chromosome 6 ', 'NC_083326.1 chromosome 13 ', 'NC_083320.1 chromosome 7 ', 'NC_083316.1 chromosome 3 ', 'NC_083324.1 chromosome 11 ', 'NC_083319.1 chromosome 6 ', 'NC_083315.1 chromosome 2 ', 'NC_083328.1 chromosome 15 ', 'NC_083314.1 chromosome 1 ', 'NC_083319.1 chromosome 6 '], 'chunks': ['GAATTTCAGA', 'TAATATTGCA', 'TGTACCTCTT', 'GTTGCCCCCT', 'TGATGGGGTA', 'TGAGTACTGT', 'CATGAAAGAA', 'TTTTTTTTGC', 'GGGAAGGGGC', 'AGTTTGCATT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_058419.1 chromosome X ': 0.05362269289085391, 'NC_058403.1 chromosome 1 ': 0.09100675763332068, 'NC_058404.1 chromosome 2 ': 0.08642212775725676, 'NC_058405.1 chromosome 3 ': 0.08174614655820144, 'NC_058406.1 chromosome 4 ': 0.07977351779966768, 'NC_058407.1 chromosome 5 ': 0.07481833422137653, 'NC_058408.1 chromosome 6 ': 0.06562164058547028, 'NC_058409.1 chromosome 7 ': 0.06393050629792077, 'NC_058410.1 chromosome 8 ': 0.061863202323035285, 'NC_058411.1 chromosome 9 ': 0.06098674069052778, 'NC_058412.1 chromosome 10 ': 0.058672451218371904, 'NC_058413.1 chromosome 11 ': 0.04708769387114599, 'NC_058414.1 chromosome 12 ': 0.04490703924029789, 'NC_058415.1 chromosome 13 ': 0.039709765923493935, 'NC_058416.1 chromosome 14 ': 0.039181736149697756, 'NC_058417.1 chromosome 15 ': 0.025441722430365, 'NC_058418.1 chromosome 16 ': 0.025207924408996437}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Bos javanicus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_032452875.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_083897.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_083868.1 chromosome 1 ', 'NC_083869.1 chromosome 2 ', 'NC_083870.1 chromosome 3 ', 'NC_083871.1 chromosome 4 ', 'NC_083872.1 chromosome 5 ', 'NC_083873.1 chromosome 6 ', 'NC_083874.1 chromosome 7 ', 'NC_083875.1 chromosome 8 ', 'NC_083876.1 chromosome 9 ', 'NC_083877.1 chromosome 10 ', 'NC_083878.1 chromosome 11 ', 'NC_083879.1 chromosome 12 ', 'NC_083880.1 chromosome 13 ', 'NC_083881.1 chromosome 14 ', 'NC_083882.1 chromosome 15 ', 'NC_083883.1 chromosome 16 ', 'NC_083884.1 chromosome 17 ', 'NC_083885.1 chromosome 18 ', 'NC_083886.1 chromosome 19 ', 'NC_083887.1 chromosome 20 ', 'NC_083888.1 chromosome 21 ', 'NC_083889.1 chromosome 22 ', 'NC_083890.1 chromosome 23 ', 'NC_083891.1 chromosome 24 ', 'NC_083892.1 chromosome 25 ', 'NC_083893.1 chromosome 26 ', 'NC_083894.1 chromosome 27 ', 'NC_083895.1 chromosome 28 ', 'NC_083896.1 chromosome 29 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_083897.1 chromosome X ': 289614402, 'NC_083868.1 chromosome 1 ': 315079896, 'NC_083869.1 chromosome 2 ': 272587692, 'NC_083870.1 chromosome 3 ': 242213704, 'NC_083871.1 chromosome 4 ': 241174964, 'NC_083872.1 chromosome 5 ': 241365140, 'NC_083873.1 chromosome 6 ': 235909094, 'NC_083874.1 chromosome 7 ': 220434918, 'NC_083875.1 chromosome 8 ': 227311134, 'NC_083876.1 chromosome 9 ': 208316260, 'NC_083877.1 chromosome 10 ': 205664430, 'NC_083878.1 chromosome 11 ': 214037294, 'NC_083879.1 chromosome 12 ': 175098584, 'NC_083880.1 chromosome 13 ': 166853022, 'NC_083881.1 chromosome 14 ': 164560312, 'NC_083882.1 chromosome 15 ': 168946102, 'NC_083883.1 chromosome 16 ': 163440464, 'NC_083884.1 chromosome 17 ': 146750032, 'NC_083885.1 chromosome 18 ': 132675716, 'NC_083886.1 chromosome 19 ': 130085436, 'NC_083887.1 chromosome 20 ': 143142620, 'NC_083888.1 chromosome 21 ': 139484372, 'NC_083889.1 chromosome 22 ': 122030608, 'NC_083890.1 chromosome 23 ': 105840364, 'NC_083891.1 chromosome 24 ': 124459492, 'NC_083892.1 chromosome 25 ': 85127494, 'NC_083893.1 chromosome 26 ': 102967822, 'NC_083894.1 chromosome 27 ': 91091356, 'NC_083895.1 chromosome 28 ': 94834968, 'NC_083896.1 chromosome 29 ': 103161888}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_083897.1 chromosome X ': 0.05491091168478287, 'NC_083868.1 chromosome 1 ': 0.05973917119945773, 'NC_083869.1 chromosome 2 ': 0.05168264623031694, 'NC_083870.1 chromosome 3 ': 0.04592373589621465, 'NC_083871.1 chromosome 4 ': 0.04572679071666018, 'NC_083872.1 chromosome 5 ': 0.04576284810009294, 'NC_083873.1 chromosome 6 ': 0.044728381381638406, 'NC_083874.1 chromosome 7 ': 0.0417944764864986, 'NC_083875.1 chromosome 8 ': 0.04309820754025156, 'NC_083876.1 chromosome 9 ': 0.03949677804822796, 'NC_083877.1 chromosome 10 ': 0.03899399088734271, 'NC_083878.1 chromosome 11 ': 0.04058148651075683, 'NC_083879.1 chromosome 12 ': 0.033198704262485314, 'NC_083880.1 chromosome 13 ': 0.031635345107530716, 'NC_083881.1 chromosome 14 ': 0.031200647124766657, 'NC_083882.1 chromosome 15 ': 0.032032193227774355, 'NC_083883.1 chromosome 16 ': 0.03098832386251266, 'NC_083884.1 chromosome 17 ': 0.027823816741306465, 'NC_083885.1 chromosome 18 ': 0.025155325403987794, 'NC_083886.1 chromosome 19 ': 0.024664208127579492, 'NC_083887.1 chromosome 20 ': 0.02713985116371538, 'NC_083888.1 chromosome 21 ': 0.02644624707682666, 'NC_083889.1 chromosome 22 ': 0.023137012152898245, 'NC_083890.1 chromosome 23 ': 0.02006734071287405, 'NC_083891.1 chromosome 24 ': 0.023597528735967144, 'NC_083892.1 chromosome 25 ': 0.01614017905428917, 'NC_083893.1 chromosome 26 ': 0.019522706540734954, 'NC_083894.1 chromosome 27 ': 0.017270927723280545, 'NC_083895.1 chromosome 28 ': 0.01798071683077836, 'NC_083896.1 chromosome 29 ': 0.019559501468450667}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Papio anubis
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_008728515.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_044997.1 chromosome Y ', 'NC_044996.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_044976.1 chromosome 1 ', 'NC_044977.1 chromosome 2 ', 'NC_044978.1 chromosome 3 ', 'NC_044979.1 chromosome 4 ', 'NC_044980.1 chromosome 5 ', 'NC_044981.1 chromosome 6 ', 'NC_044982.1 chromosome 7 ', 'NC_044983.1 chromosome 8 ', 'NC_044984.1 chromosome 9 ', 'NC_044985.1 chromosome 10 ', 'NC_044986.1 chromosome 11 ', 'NC_044987.1 chromosome 12 ', 'NC_044988.1 chromosome 13 ', 'NC_044989.1 chromosome 14 ', 'NC_044990.1 chromosome 15 ', 'NC_044991.1 chromosome 16 ', 'NC_044992.1 chromosome 17 ', 'NC_044993.1 chromosome 18 ', 'NC_044994.1 chromosome 19 ', 'NC_044995.1 chromosome 20 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_044997.1 chromosome Y ': 8309886, 'NC_044996.1 chromosome X ': 142711496, 'NC_044976.1 chromosome 1 ': 436345764, 'NC_044977.1 chromosome 2 ': 387321500, 'NC_044978.1 chromosome 3 ': 369839030, 'NC_044979.1 chromosome 4 ': 364241804, 'NC_044980.1 chromosome 5 ': 347801522, 'NC_044981.1 chromosome 6 ': 334276494, 'NC_044982.1 chromosome 7 ': 323536936, 'NC_044983.1 chromosome 8 ': 280549772, 'NC_044984.1 chromosome 9 ': 255183638, 'NC_044985.1 chromosome 10 ': 252925378, 'NC_044986.1 chromosome 11 ': 251827392, 'NC_044987.1 chromosome 12 ': 246686900, 'NC_044988.1 chromosome 13 ': 213698002, 'NC_044989.1 chromosome 14 ': 213309948, 'NC_044990.1 chromosome 15 ': 183971550, 'NC_044991.1 chromosome 16 ': 182368386, 'NC_044992.1 chromosome 17 ': 149051852, 'NC_044993.1 chromosome 18 ': 145788816, 'NC_044994.1 chromosome 19 ': 144246688, 'NC_044995.1 chromosome 20 ': 100042216}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_044997.1 chromosome Y ': 0.0015578986727190504, 'NC_044996.1 chromosome X ': 0.0267548857108449, 'NC_044976.1 chromosome 1 ': 0.08180406886233818, 'NC_044977.1 chromosome 2 ': 0.07261322848057744, 'NC_044978.1 chromosome 3 ': 0.06933569653743758, 'NC_044979.1 chromosome 4 ': 0.06828635471056914, 'NC_044980.1 chromosome 5 ': 0.06520420731324901, 'NC_044981.1 chromosome 6 ': 0.06266859814006806, 'NC_044982.1 chromosome 7 ': 0.06065519589197594, 'NC_044983.1 chromosome 8 ': 0.052596162863176726, 'NC_044984.1 chromosome 9 ': 0.047840638360119335, 'NC_044985.1 chromosome 10 ': 0.047417270307097366, 'NC_044986.1 chromosome 11 ': 0.04721142501246106, 'NC_044987.1 chromosome 12 ': 0.04624770954585624, 'NC_044988.1 chromosome 13 ': 0.04006310479812996, 'NC_044989.1 chromosome 14 ': 0.03999035424396552, 'NC_044990.1 chromosome 15 ': 0.03449012821151414, 'NC_044991.1 chromosome 16 ': 0.034189574501421016, 'NC_044992.1 chromosome 17 ': 0.02794354608440072, 'NC_044993.1 chromosome 18 ': 0.02733180731284182, 'NC_044994.1 chromosome 19 ': 0.027042696347376965, 'NC_044995.1 chromosome 20 ': 0.01875544809185981}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Budorcas taxicolor
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_023091745.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_068935.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_068910.1 chromosome 1 ', 'NC_068911.1 chromosome 2 ', 'NC_068912.1 chromosome 3 ', 'NC_068913.1 chromosome 4 ', 'NC_068914.1 chromosome 5 ', 'NC_068915.1 chromosome 6 ', 'NC_068916.1 chromosome 7 ', 'NC_068917.1 chromosome 8 ', 'NC_068918.1 chromosome 9 ', 'NC_068919.1 chromosome 10 ', 'NC_068920.1 chromosome 11 ', 'NC_068921.1 chromosome 12 ', 'NC_068922.1 chromosome 13 ', 'NC_068923.1 chromosome 14 ', 'NC_068924.1 chromosome 15 ', 'NC_068925.1 chromosome 16 ', 'NC_068926.1 chromosome 17 ', 'NC_068927.1 chromosome 18 ', 'NC_068928.1 chromosome 19 ', 'NC_068929.1 chromosome 20 ', 'NC_068930.1 chromosome 21 ', 'NC_068931.1 chromosome 22 ', 'NC_068932.1 chromosome 23 ', 'NC_068933.1 chromosome 24 ', 'NC_068934.1 chromosome 25 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_068935.1 chromosome X ': 293495872, 'NC_068910.1 chromosome 1 ': 443363910, 'NC_068911.1 chromosome 2 ': 361581120, 'NC_068912.1 chromosome 3 ': 242514874, 'NC_068913.1 chromosome 4 ': 243786826, 'NC_068914.1 chromosome 5 ': 328459970, 'NC_068915.1 chromosome 6 ': 234941170, 'NC_068916.1 chromosome 7 ': 219495396, 'NC_068917.1 chromosome 8 ': 232665740, 'NC_068918.1 chromosome 9 ': 190522314, 'NC_068919.1 chromosome 10 ': 202531878, 'NC_068920.1 chromosome 11 ': 332203558, 'NC_068921.1 chromosome 12 ': 174640522, 'NC_068922.1 chromosome 13 ': 166773768, 'NC_068923.1 chromosome 14 ': 190390618, 'NC_068924.1 chromosome 15 ': 163768502, 'NC_068925.1 chromosome 16 ': 163692860, 'NC_068926.1 chromosome 17 ': 146250216, 'NC_068927.1 chromosome 18 ': 136107162, 'NC_068928.1 chromosome 19 ': 125218408, 'NC_068929.1 chromosome 20 ': 149592478, 'NC_068930.1 chromosome 21 ': 148734572, 'NC_068931.1 chromosome 22 ': 125252580, 'NC_068932.1 chromosome 23 ': 102628326, 'NC_068933.1 chromosome 24 ': 89805930, 'NC_068934.1 chromosome 25 ': 104042192}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_068935.1 chromosome X ': 0.05524668983898652, 'NC_068910.1 chromosome 1 ': 0.08345735241404123, 'NC_068911.1 chromosome 2 ': 0.06806283118105785, 'NC_068912.1 chromosome 3 ': 0.04565019580656622, 'NC_068913.1 chromosome 4 ': 0.04588962383379953, 'NC_068914.1 chromosome 5 ': 0.06182821572057006, 'NC_068915.1 chromosome 6 ': 0.044224546876756775, 'NC_068916.1 chromosome 7 ': 0.04131708559055142, 'NC_068917.1 chromosome 8 ': 0.04379622747790565, 'NC_068918.1 chromosome 9 ': 0.03586328869717118, 'NC_068919.1 chromosome 10 ': 0.038123929205973496, 'NC_068920.1 chromosome 11 ': 0.06253289631355963, 'NC_068921.1 chromosome 12 ': 0.0328737528282943, 'NC_068922.1 chromosome 13 ': 0.03139294113811283, 'NC_068923.1 chromosome 14 ': 0.03583849867877857, 'NC_068924.1 chromosome 15 ': 0.03082723983044451, 'NC_068925.1 chromosome 16 ': 0.030813001231160906, 'NC_068926.1 chromosome 17 ': 0.027529655756919076, 'NC_068927.1 chromosome 18 ': 0.025620360901971024, 'NC_068928.1 chromosome 19 ': 0.023570697951443995, 'NC_068929.1 chromosome 20 ': 0.028158792074293348, 'NC_068930.1 chromosome 21 ': 0.027997302693301286, 'NC_068931.1 chromosome 22 ': 0.023577130375424315, 'NC_068932.1 chromosome 23 ': 0.019318415814776422, 'NC_068933.1 chromosome 24 ': 0.016904770505296016, 'NC_068934.1 chromosome 25 ': 0.019584557262843836}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Arvicanthis niloticus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011762505.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_047679.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_047658.1 chromosome 1 ', 'NC_047659.1 chromosome 2 ', 'NC_047660.1 chromosome 3 ', 'NC_047661.1 chromosome 4 ', 'NC_047662.1 chromosome 5 ', 'NC_047663.1 chromosome 6 ', 'NC_047664.1 chromosome 7 ', 'NC_047665.1 chromosome 8 ', 'NC_047666.1 chromosome 9 ', 'NC_047667.1 chromosome 10 ', 'NC_047668.1 chromosome 11 ', 'NC_047669.1 chromosome 12 ', 'NC_047670.1 chromosome 13 ', 'NC_047671.1 chromosome 14 ', 'NC_047672.1 chromosome 15 ', 'NC_047673.1 chromosome 16 ', 'NC_047674.1 chromosome 17 ', 'NC_047675.1 chromosome 18 ', 'NC_047676.1 chromosome 19 ', 'NC_047677.1 chromosome 20 ', 'NC_047678.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_047679.1 chromosome X ': 260706670, 'NC_047658.1 chromosome 1 ': 334233126, 'NC_047659.1 chromosome 2 ': 298647216, 'NC_047660.1 chromosome 3 ': 278543182, 'NC_047661.1 chromosome 4 ': 270236198, 'NC_047662.1 chromosome 5 ': 217382080, 'NC_047663.1 chromosome 6 ': 217296002, 'NC_047664.1 chromosome 7 ': 182853410, 'NC_047665.1 chromosome 8 ': 176469402, 'NC_047666.1 chromosome 9 ': 172772988, 'NC_047667.1 chromosome 10 ': 165378234, 'NC_047668.1 chromosome 11 ': 161882470, 'NC_047669.1 chromosome 12 ': 159107368, 'NC_047670.1 chromosome 13 ': 156082964, 'NC_047671.1 chromosome 14 ': 152795984, 'NC_047672.1 chromosome 15 ': 147790464, 'NC_047673.1 chromosome 16 ': 146846972, 'NC_047674.1 chromosome 17 ': 128083624, 'NC_047675.1 chromosome 18 ': 109678282, 'NC_047676.1 chromosome 19 ': 106271352, 'NC_047677.1 chromosome 20 ': 104862384, 'NC_047678.1 chromosome 21 ': 104166660}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_047679.1 chromosome X ': 0.06433886240378264, 'NC_047658.1 chromosome 1 ': 0.08248419230892769, 'NC_047659.1 chromosome 2 ': 0.07370207343562309, 'NC_047660.1 chromosome 3 ': 0.06874067111597025, 'NC_047661.1 chromosome 4 ': 0.0666906203805348, 'NC_047662.1 chromosome 5 ': 0.05364694249735947, 'NC_047663.1 chromosome 6 ': 0.053625699617006646, 'NC_047664.1 chromosome 7 ': 0.0451257360851276, 'NC_047665.1 chromosome 8 ': 0.04355024968772685, 'NC_047666.1 chromosome 9 ': 0.04263802495740669, 'NC_047667.1 chromosome 10 ': 0.04081310018614625, 'NC_047668.1 chromosome 11 ': 0.03995039314841646, 'NC_047669.1 chromosome 12 ': 0.03926553569642085, 'NC_047670.1 chromosome 13 ': 0.038519153899555236, 'NC_047671.1 chromosome 14 ': 0.0377079719150514, 'NC_047672.1 chromosome 15 ': 0.03647267761844065, 'NC_047673.1 chromosome 16 ': 0.036239836617606, 'NC_047674.1 chromosome 17 ': 0.031609297378980876, 'NC_047675.1 chromosome 18 ': 0.02706710915482627, 'NC_047676.1 chromosome 19 ': 0.026226325140787352, 'NC_047677.1 chromosome 20 ': 0.025878610990308068, 'NC_047678.1 chromosome 21 ': 0.025706915763994875}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Lutra lutra
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_902655055.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_062296.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_062278.1 chromosome 1 ', 'NC_062279.1 chromosome 2 ', 'NC_062280.1 chromosome 3 ', 'NC_062281.1 chromosome 4 ', 'NC_062282.1 chromosome 5 ', 'NC_062283.1 chromosome 6 ', 'NC_062284.1 chromosome 7 ', 'NC_062285.1 chromosome 8 ', 'NC_062286.1 chromosome 9 ', 'NC_062287.1 chromosome 10 ', 'NC_062288.1 chromosome 11 ', 'NC_062289.1 chromosome 12 ', 'NC_062290.1 chromosome 13 ', 'NC_062291.1 chromosome 14 ', 'NC_062292.1 chromosome 15 ', 'NC_062293.1 chromosome 16 ', 'NC_062294.1 chromosome 17 ', 'NC_062295.1 chromosome 18 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_062296.1 chromosome X ': 199378900, 'NC_062278.1 chromosome 1 ': 446898406, 'NC_062279.1 chromosome 2 ': 421290874, 'NC_062280.1 chromosome 3 ': 402637996, 'NC_062281.1 chromosome 4 ': 395416572, 'NC_062282.1 chromosome 5 ': 331611490, 'NC_062283.1 chromosome 6 ': 308851022, 'NC_062284.1 chromosome 7 ': 298009614, 'NC_062285.1 chromosome 8 ': 289491188, 'NC_062286.1 chromosome 9 ': 288170928, 'NC_062287.1 chromosome 10 ': 229324098, 'NC_062288.1 chromosome 11 ': 217575542, 'NC_062289.1 chromosome 12 ': 192891470, 'NC_062290.1 chromosome 13 ': 191452028, 'NC_062291.1 chromosome 14 ': 178161560, 'NC_062292.1 chromosome 15 ': 139984142, 'NC_062293.1 chromosome 16 ': 122966058, 'NC_062294.1 chromosome 17 ': 120697022, 'NC_062295.1 chromosome 18 ': 80856246}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_062296.1 chromosome X ': 0.0410610891802606, 'NC_062278.1 chromosome 1 ': 0.09203649585428704, 'NC_062279.1 chromosome 2 ': 0.08676275246851062, 'NC_062280.1 chromosome 3 ': 0.08292128535726404, 'NC_062281.1 chromosome 4 ': 0.08143406913291695, 'NC_062282.1 chromosome 5 ': 0.06829373100207242, 'NC_062283.1 chromosome 6 ': 0.06360632623490564, 'NC_062284.1 chromosome 7 ': 0.061373592376269694, 'NC_062285.1 chromosome 8 ': 0.059619265064495726, 'NC_062286.1 chromosome 9 ': 0.05934736410806989, 'NC_062287.1 chromosome 10 ': 0.04722815322564635, 'NC_062288.1 chromosome 11 ': 0.0448085967647807, 'NC_062289.1 chromosome 12 ': 0.03972503535620651, 'NC_062290.1 chromosome 13 ': 0.039428589461822434, 'NC_062291.1 chromosome 14 ': 0.036691483921590246, 'NC_062292.1 chromosome 15 ': 0.028829035261425676, 'NC_062293.1 chromosome 16 ': 0.02532424581379021, 'NC_062294.1 chromosome 17 ': 0.02485694917633649, 'NC_062295.1 chromosome 18 ': 0.016651940239348746}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0

{'labels': 1, 'species': 'Neomonachus schauinslandi', 'sampled_chromosomes': ['NC_058405.1 chromosome 3 ', 'NC_058404.1 chromosome 2 ', 'NC_058418.1 chromosome 16 ', 'NC_058408.1 chromosome 6 ', 'NC_058404.1 chromosome 2 ', 'NC_058412.1 chromosome 10 ', 'NC_058409.1 chromosome 7 ', 'NC_058405.1 chromosome 3 ', 'NC_058419.1 chromosome X ', 'NC_058405.1 chromosome 3 '], 'chunks': ['ATTGAAAAAT', 'TTTTTATCTT', 'AAGCACAAGG', 'AACGTGAGGC', 'AACACAAATG', 'ATGATGCGAT', 'ACCTCCACAT', 'ATTTGGATGA', 'TTCTAGTAAG', 'TGAAGGGTCT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Bos javanicus', 'sampled_chromosomes': ['NC_083878.1 chromosome 11 ', 'NC_083894.1 chromosome 27 ', 'NC_083875.1 chromosome 8 ', 'NC_083895.1 chromosome 28 ', 'NC_083897.1 chromosome X ', 'NC_083891.1 chromosome 24 ', 'NC_083869.1 chromosome 2 ', 'NC_083896.1 chromosome 29 ', 'NC_083875.1 chromosome 8 ', 'NC_083875.1 chromosome 8 '], 'chunks': ['GGGTCTCGCT', 'GGCTGTATAT', 'AGAATACTTG', 'CTCCCTGAGG', 'AGAAGTCTTG', 'TTCCTTTTCT', 'TAAAAGGTAG', 'TCCCAGGCAA', 'TGCAAACTAT', 'ATGTGAATTT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 0, 'species': 'Papio anubis', 'sampled_chromosomes': ['NC_044981.1 chromosome 6 ', 'NC_044984.1 chromosome 9 ', 'NC_044981.1 chromosome 6 ', 'NC_044977.1 chromosome 2 ', 'NC_044983.1 chromosome 8 ', 'NC_044996.1 chromosome X ', 'NC_044986.1 chromosome 11 ', 'NC_044995.1 chromosome 20 ', 'NC_044997.1 chromosome Y ', 'NC_044984.1 chromosome 9 '], 'chunks': ['GATTTTCAAA', 'AAAGCTCCCC', 'TTTGAAAATT', 'TATGGAAACA', 'GCTAGGGATC', 'TTCATTTCAT', 'CACACACACA', 'CAATGCTATC', 'AGTGCTTCCA', 'AGGTGAGAGA'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Budorcas taxicolor', 'sampled_chromosomes': ['NC_068914.1 chromosome 5 ', 'NC_068925.1 chromosome 16 ', 'NC_068912.1 chromosome 3 ', 'NC_068916.1 chromosome 7 ', 'NC_068916.1 chromosome 7 ', 'NC_068911.1 chromosome 2 ', 'NC_068918.1 chromosome 9 ', 'NC_068928.1 chromosome 19 ', 'NC_068935.1 chromosome X ', 'NC_068931.1 chromosome 22 '], 'chunks': ['GAACAGTGAG', 'ATGTAGGTTA', 'GAAGCCCACT', 'TTTGGTACCA', 'CTAAAGAAAA', 'AGGTTTGTAA', 'CTTTTATTTC', 'TTACCCAGAC', 'TACATCTGCA', 'CAACAAGGAT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Arvicanthis niloticus', 'sampled_chromosomes': ['NC_047661.1 chromosome 4 ', 'NC_047664.1 chromosome 7 ', 'NC_047662.1 chromosome 5 ', 'NC_047658.1 chromosome 1 ', 'NC_047661.1 chromosome 4 ', 'NC_047673.1 chromosome 16 ', 'NC_047658.1 chromosome 1 ', 'NC_047661.1 chromosome 4 ', 'NC_047669.1 chromosome 12 ', 'NC_047674.1 chromosome 17 '], 'chunks': ['TTCTTTAAGG', 'ATTTTTTATC', 'TTTCCAATTT', 'TCTCTGAAGA', 'AAATATGGTT', 'TGCTGAACTG', 'GGCCAAGCAG', 'AGATACATGC', 'AGCACGTTAC', 'ATTTTGCATG'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Zalophus californianus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_009762305.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_045613.1 chromosome Y ', 'NC_045612.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_045595.1 chromosome 1 ', 'NC_045596.1 chromosome 2 ', 'NC_045597.1 chromosome 3 ', 'NC_045598.1 chromosome 4 ', 'NC_045599.1 chromosome 5 ', 'NC_045600.1 chromosome 6 ', 'NC_045601.1 chromosome 7 ', 'NC_045602.1 chromosome 8 ', 'NC_045603.1 chromosome 9 ', 'NC_045604.1 chromosome 10 ', 'NC_045605.1 chromosome 11 ', 'NC_045606.1 chromosome 12 ', 'NC_045607.1 chromosome 13 ', 'NC_045608.1 chromosome 14 ', 'NC_045609.1 chromosome 15 ', 'NC_045610.1 chromosome 16 ', 'NC_045611.1 chromosome 17 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_045613.1 chromosome Y ': 3986568, 'NC_045612.1 chromosome X ': 129409743, 'NC_045595.1 chromosome 1 ': 432242772, 'NC_045596.1 chromosome 2 ': 406811418, 'NC_045597.1 chromosome 3 ': 391786922, 'NC_045598.1 chromosome 4 ': 383201330, 'NC_045599.1 chromosome 5 ': 308863016, 'NC_045600.1 chromosome 6 ': 295920112, 'NC_045601.1 chromosome 7 ': 294248304, 'NC_045602.1 chromosome 8 ': 281159526, 'NC_045603.1 chromosome 9 ': 280774536, 'NC_045604.1 chromosome 10 ': 228512180, 'NC_045605.1 chromosome 11 ': 227173286, 'NC_045606.1 chromosome 12 ': 214390358, 'NC_045607.1 chromosome 13 ': 190927330, 'NC_045608.1 chromosome 14 ': 188511412, 'NC_045609.1 chromosome 15 ': 178310118, 'NC_045610.1 chromosome 16 ': 125573166, 'NC_045611.1 chromosome 17 ': 120776634}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_045613.1 chromosome Y ': 0.0008513616596786272, 'NC_045612.1 chromosome X ': 0.027636426515003535, 'NC_045595.1 chromosome 1 ': 0.09230870356507413, 'NC_045596.1 chromosome 2 ': 0.08687764613690166, 'NC_045597.1 chromosome 3 ': 0.0836690517142316, 'NC_045598.1 chromosome 4 ': 0.08183553379745619, 'NC_045599.1 chromosome 5 ': 0.06596002624691373, 'NC_045600.1 chromosome 6 ': 0.06319597149342623, 'NC_045601.1 chromosome 7 ': 0.06283894428768334, 'NC_045602.1 chromosome 8 ': 0.060043737041439185, 'NC_045603.1 chromosome 9 ': 0.059961519523674615, 'NC_045604.1 chromosome 10 ': 0.048800499281984204, 'NC_045605.1 chromosome 11 ': 0.04851456837149334, 'NC_045606.1 chromosome 12 ': 0.0457846776992077, 'NC_045607.1 chromosome 13 ': 0.0407739711317627, 'NC_045608.1 chromosome 14 ': 0.04025803362408003, 'NC_045609.1 chromosome 15 ': 0.03807947036096509, 'NC_045610.1 chromosome 16 ': 0.02681709656447846, 'NC_045611.1 chromosome 17 ': 0.025792760984545634}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Neomonachus schauinslandi
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_002201575.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_058420.1 chromosome Y ', 'NC_058419.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_058403.1 chromosome 1 ', 'NC_058404.1 chromosome 2 ', 'NC_058405.1 chromosome 3 ', 'NC_058406.1 chromosome 4 ', 'NC_058407.1 chromosome 5 ', 'NC_058408.1 chromosome 6 ', 'NC_058409.1 chromosome 7 ', 'NC_058410.1 chromosome 8 ', 'NC_058411.1 chromosome 9 ', 'NC_058412.1 chromosome 10 ', 'NC_058413.1 chromosome 11 ', 'NC_058414.1 chromosome 12 ', 'NC_058415.1 chromosome 13 ', 'NC_058416.1 chromosome 14 ', 'NC_058417.1 chromosome 15 ', 'NC_058418.1 chromosome 16 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_058420.1 chromosome Y ': 5277812, 'NC_058419.1 chromosome X ': 126494893, 'NC_058403.1 chromosome 1 ': 429366354, 'NC_058404.1 chromosome 2 ': 407736248, 'NC_058405.1 chromosome 3 ': 385675150, 'NC_058406.1 chromosome 4 ': 376368364, 'NC_058407.1 chromosome 5 ': 352990000, 'NC_058408.1 chromosome 6 ': 309600356, 'NC_058409.1 chromosome 7 ': 301621650, 'NC_058410.1 chromosome 8 ': 291868190, 'NC_058411.1 chromosome 9 ': 287733078, 'NC_058412.1 chromosome 10 ': 276814350, 'NC_058413.1 chromosome 11 ': 222157914, 'NC_058414.1 chromosome 12 ': 211869670, 'NC_058415.1 chromosome 13 ': 187349136, 'NC_058416.1 chromosome 14 ': 184857912, 'NC_058417.1 chromosome 15 ': 120033060, 'NC_058418.1 chromosome 16 ': 118930010}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_058420.1 chromosome Y ': 0.0011481630978840728, 'NC_058419.1 chromosome X ': 0.02751836712133633, 'NC_058403.1 chromosome 1 ': 0.09340662439962422, 'NC_058404.1 chromosome 2 ': 0.08870109689835648, 'NC_058405.1 chromosome 3 ': 0.08390180912107223, 'NC_058406.1 chromosome 4 ': 0.08187716173971342, 'NC_058407.1 chromosome 5 ': 0.07679130895948906, 'NC_058408.1 chromosome 6 ': 0.06735209663606279, 'NC_058409.1 chromosome 7 ': 0.06561636679231954, 'NC_058410.1 chromosome 8 ': 0.06349454758983783, 'NC_058411.1 chromosome 9 ': 0.06259497348526237, 'NC_058412.1 chromosome 10 ': 0.06021965572755642, 'NC_058413.1 chromosome 11 ': 0.04832940596552197, 'NC_058414.1 chromosome 12 ': 0.04609124702715372, 'NC_058415.1 chromosome 13 ': 0.04075692055262, 'NC_058416.1 chromosome 14 ': 0.04021496652595836, 'NC_058417.1 chromosome 15 ': 0.026112625841561765, 'NC_058418.1 chromosome 16 ': 0.025872662518669435}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Rattus rattus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011064425.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_046173.1 chromosome Y ', 'NC_046172.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_046154.1 chromosome 1 ', 'NC_046155.1 chromosome 2 ', 'NC_046156.1 chromosome 3 ', 'NC_046157.1 chromosome 4 ', 'NC_046158.1 chromosome 5 ', 'NC_046159.1 chromosome 6 ', 'NC_046160.1 chromosome 7 ', 'NC_046161.1 chromosome 8 ', 'NC_046162.1 chromosome 9 ', 'NC_046163.1 chromosome 10 ', 'NC_046164.1 chromosome 11 ', 'NC_046165.1 chromosome 12 ', 'NC_046166.1 chromosome 13 ', 'NC_046167.1 chromosome 14 ', 'NC_046168.1 chromosome 15 ', 'NC_046169.1 chromosome 16 ', 'NC_046170.1 chromosome 17 ', 'NC_046171.1 chromosome 18 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_046173.1 chromosome Y ': 2293298, 'NC_046172.1 chromosome X ': 130373513, 'NC_046154.1 chromosome 1 ': 545899780, 'NC_046155.1 chromosome 2 ': 460490430, 'NC_046156.1 chromosome 3 ': 446780580, 'NC_046157.1 chromosome 4 ': 365650368, 'NC_046158.1 chromosome 5 ': 317649504, 'NC_046159.1 chromosome 6 ': 319153832, 'NC_046160.1 chromosome 7 ': 261677498, 'NC_046161.1 chromosome 8 ': 230657978, 'NC_046162.1 chromosome 9 ': 193419404, 'NC_046163.1 chromosome 10 ': 189950930, 'NC_046164.1 chromosome 11 ': 197229706, 'NC_046165.1 chromosome 12 ': 188176076, 'NC_046166.1 chromosome 13 ': 157637022, 'NC_046167.1 chromosome 14 ': 163988198, 'NC_046168.1 chromosome 15 ': 158636486, 'NC_046169.1 chromosome 16 ': 88862024, 'NC_046170.1 chromosome 17 ': 97008248, 'NC_046171.1 chromosome 18 ': 99693070}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_046173.1 chromosome Y ': 0.0004968981006635848, 'NC_046172.1 chromosome X ': 0.02824855338754021, 'NC_046154.1 chromosome 1 ': 0.11828230078893752, 'NC_046155.1 chromosome 2 ': 0.09977631343190352, 'NC_046156.1 chromosome 3 ': 0.09680574509521869, 'NC_046157.1 chromosome 4 ': 0.07922693577814172, 'NC_046158.1 chromosome 5 ': 0.06882639552920283, 'NC_046159.1 chromosome 6 ': 0.0691523443269496, 'NC_046160.1 chromosome 7 ': 0.05669871588541874, 'NC_046161.1 chromosome 8 ': 0.04997759173517918, 'NC_046162.1 chromosome 9 ': 0.04190896014346265, 'NC_046163.1 chromosome 10 ': 0.041157431932649646, 'NC_046164.1 chromosome 11 ': 0.042734553601772314, 'NC_046165.1 chromosome 12 ': 0.040772867178502925, 'NC_046166.1 chromosome 13 ': 0.034155847528783326, 'NC_046167.1 chromosome 14 ': 0.03553198237535806, 'NC_046168.1 chromosome 15 ': 0.03437240541322819, 'NC_046169.1 chromosome 16 ': 0.01925409211830381, 'NC_046170.1 chromosome 17 ': 0.021019167234219892, 'NC_046171.1 chromosome 18 ': 0.021600898414563575}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0

{'labels': 1, 'species': 'Lutra lutra', 'sampled_chromosomes': ['NC_062287.1 chromosome 10 ', 'NC_062291.1 chromosome 14 ', 'NC_062283.1 chromosome 6 ', 'NC_062278.1 chromosome 1 ', 'NC_062296.1 chromosome X ', 'NC_062289.1 chromosome 12 ', 'NC_062292.1 chromosome 15 ', 'NC_062293.1 chromosome 16 ', 'NC_062285.1 chromosome 8 ', 'NC_062295.1 chromosome 18 '], 'chunks': ['TGTATGTGAT', 'ACCCCAGAAC', 'AAAATTGCTG', 'CAAATCTCCT', 'AATTAACTGC', 'AGTGGAAAAG', 'GTCTTGAAAT', 'GTGGGGAGAT', 'CAGTGCTGCA', 'GACCATTGAG'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 0, 'species': 'Zalophus californianus', 'sampled_chromosomes': ['NC_045596.1 chromosome 2 ', 'NC_045599.1 chromosome 5 ', 'NC_045613.1 chromosome Y ', 'NC_045608.1 chromosome 14 ', 'NC_045604.1 chromosome 10 ', 'NC_045599.1 chromosome 5 ', 'NC_045596.1 chromosome 2 ', 'NC_045607.1 chromosome 13 ', 'NC_045608.1 chromosome 14 ', 'NC_045600.1 chromosome 6 '], 'chunks': ['CCTAGCCAAC', 'ATAAGTTCCC', 'AATTCTGCAC', 'GATGCCAATT', 'CTGCCACAGT', 'CCCTTCTTGA', 'AGAGTCACCT', 'TCTCCCCCGT', 'CATTCTAGAG', 'CAGCTATTTA'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Neomonachus schauinslandi', 'sampled_chromosomes': ['NC_058404.1 chromosome 2 ', 'NC_058408.1 chromosome 6 ', 'NC_058414.1 chromosome 12 ', 'NC_058411.1 chromosome 9 ', 'NC_058412.1 chromosome 10 ', 'NC_058410.1 chromosome 8 ', 'NC_058403.1 chromosome 1 ', 'NC_058420.1 chromosome Y ', 'NC_058409.1 chromosome 7 ', 'NC_058412.1 chromosome 10 '], 'chunks': ['TGATTTAATC', 'AGAAAGGGAG', 'GATTCTTCAG', 'CACACCCCGG', 'AATTTAAATT', 'GATATTAATT', 'ATAAATCTAA', 'AGTAATATTC', 'ACAAAAACAG', 'TATAAGGGCC'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Mesoplodon densirostris
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_025265405.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_082682.1 chromosome Y ', 'NW_026778236.1 chromosome Y unlocalized genomic scaffold', 'NW_026778237.1 chromosome Y unlocalized genomic scaffold', 'NC_082681.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_082661.1 chromosome 1 ', 'NC_082662.1 chromosome 2 ', 'NC_082663.1 chromosome 3 ', 'NC_082664.1 chromosome 4 ', 'NC_082665.1 chromosome 5 ', 'NC_082666.1 chromosome 6 ', 'NC_082667.1 chromosome 7 ', 'NC_082668.1 chromosome 8 ', 'NC_082669.1 chromosome 9 ', 'NC_082670.1 chromosome 10 ', 'NC_082671.1 chromosome 11 ', 'NC_082672.1 chromosome 12 ', 'NC_082673.1 chromosome 13 ', 'NC_082674.1 chromosome 14 ', 'NC_082675.1 chromosome 15 ', 'NC_082676.1 chromosome 16 ', 'NC_082677.1 chromosome 17 ', 'NC_082678.1 chromosome 18 ', 'NC_082679.1 chromosome 19 ', 'NC_082680.1 chromosome 20 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_082682.1 chromosome Y ': 12710753, 'NW_026778236.1 chromosome Y unlocalized genomic scaffold': 6823000, 'NW_026778237.1 chromosome Y unlocalized genomic scaffold': 2935457, 'NC_082681.1 chromosome X ': 142130375, 'NC_082661.1 chromosome 1 ': 494568720, 'NC_082662.1 chromosome 2 ': 386830698, 'NC_082663.1 chromosome 3 ': 370973532, 'NC_082664.1 chromosome 4 ': 369816576, 'NC_082665.1 chromosome 5 ': 311038254, 'NC_082666.1 chromosome 6 ': 273731452, 'NC_082667.1 chromosome 7 ': 251611380, 'NC_082668.1 chromosome 8 ': 234670390, 'NC_082669.1 chromosome 9 ': 228226422, 'NC_082670.1 chromosome 10 ': 222585620, 'NC_082671.1 chromosome 11 ': 212261872, 'NC_082672.1 chromosome 12 ': 209401840, 'NC_082673.1 chromosome 13 ': 186724664, 'NC_082674.1 chromosome 14 ': 183971348, 'NC_082675.1 chromosome 15 ': 182393564, 'NC_082676.1 chromosome 16 ': 177466300, 'NC_082677.1 chromosome 17 ': 157194532, 'NC_082678.1 chromosome 18 ': 134099418, 'NC_082679.1 chromosome 19 ': 133134426, 'NC_082680.1 chromosome 20 ': 90065488}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_082682.1 chromosome Y ': 0.0025547372380376205, 'NW_026778236.1 chromosome Y unlocalized genomic scaffold': 0.0013713563763791715, 'NW_026778237.1 chromosome Y unlocalized genomic scaffold': 0.0005899981935419718, 'NC_082681.1 chromosome X ': 0.028566817533843294, 'NC_082661.1 chromosome 1 ': 0.09940348347203358, 'NC_082662.1 chromosome 2 ': 0.077749193064855, 'NC_082663.1 chromosome 3 ': 0.0745620575371688, 'NC_082664.1 chromosome 4 ': 0.07432952067833981, 'NC_082665.1 chromosome 5 ': 0.06251565190103245, 'NC_082666.1 chromosome 6 ': 0.0550173489836918, 'NC_082667.1 chromosome 7 ': 0.05057143050455266, 'NC_082668.1 chromosome 8 ': 0.047166456935935366, 'NC_082669.1 chromosome 9 ': 0.045871282290473936, 'NC_082670.1 chromosome 10 ': 0.04473753616844662, 'NC_082671.1 chromosome 11 ': 0.042662563627345676, 'NC_082672.1 chromosome 12 ': 0.04208772512231146, 'NC_082673.1 chromosome 13 ': 0.03752983417905003, 'NC_082674.1 chromosome 14 ': 0.03697644454798059, 'NC_082675.1 chromosome 15 ': 0.03665932537035359, 'NC_082676.1 chromosome 16 ': 0.035668993418938734, 'NC_082677.1 chromosome 17 ': 0.031594565995916715, 'NC_082678.1 chromosome 18 ': 0.026952673595637675, 'NC_082679.1 chromosome 19 ': 0.026758719626363912, 'NC_082680.1 chromosome 20 ': 0.018102283637769567}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Pongo abelii
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_028885655.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_072009.2 chromosome Y ', 'NC_072008.2 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_071985.2 chromosome 1 ', 'NC_071988.2 chromosome 3 ', 'NC_071989.2 chromosome 4 ', 'NC_071990.2 chromosome 5 ', 'NC_071991.2 chromosome 6 ', 'NC_071992.2 chromosome 7 ', 'NC_071993.2 chromosome 8 ', 'NC_071994.2 chromosome 9 ', 'NC_071995.2 chromosome 10 ', 'NC_071996.2 chromosome 11 ', 'NC_071997.2 chromosome 12 ', 'NC_071998.2 chromosome 13 ', 'NC_071999.2 chromosome 14 ', 'NC_072000.2 chromosome 15 ', 'NC_072001.2 chromosome 16 ', 'NC_072002.2 chromosome 17 ', 'NC_072003.2 chromosome 18 ', 'NC_072004.2 chromosome 19 ', 'NC_072005.2 chromosome 20 ', 'NC_072006.2 chromosome 21 ', 'NC_072007.2 chromosome 22 ', 'NC_085928.1 chromosome 2 ', 'NC_085929.1 chromosome 23 ', 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_072009.2 chromosome Y ': 67827326, 'NC_072008.2 chromosome X ': 162586321, 'NC_071985.2 chromosome 1 ': 467591038, 'NC_071988.2 chromosome 3 ': 425833550, 'NC_071989.2 chromosome 4 ': 380757808, 'NC_071990.2 chromosome 5 ': 345210726, 'NC_071991.2 chromosome 6 ': 313933982, 'NC_071992.2 chromosome 7 ': 323262792, 'NC_071993.2 chromosome 8 ': 281708270, 'NC_071994.2 chromosome 9 ': 276942042, 'NC_071995.2 chromosome 10 ': 264563434, 'NC_071996.2 chromosome 11 ': 292394356, 'NC_071997.2 chromosome 12 ': 266366248, 'NC_071998.2 chromosome 13 ': 259236340, 'NC_071999.2 chromosome 14 ': 241159696, 'NC_072000.2 chromosome 15 ': 223483318, 'NC_072001.2 chromosome 16 ': 210667690, 'NC_072002.2 chromosome 17 ': 190920258, 'NC_072003.2 chromosome 18 ': 179106226, 'NC_072004.2 chromosome 19 ': 197338576, 'NC_072005.2 chromosome 20 ': 130800294, 'NC_072006.2 chromosome 21 ': 137501336, 'NC_072007.2 chromosome 22 ': 114286206, 'NC_085928.1 chromosome 2 ': 419089974, 'NC_085929.1 chromosome 23 ': 115186842, 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold': 443016, 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold': 266400, 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold': 230424, 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold': 598924}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_072009.2 chromosome Y ': 0.010784570148977402, 'NC_072008.2 chromosome X ': 0.025851285720576066, 'NC_071985.2 chromosome 1 ': 0.07434714955951761, 'NC_071988.2 chromosome 3 ': 0.06770769338250303, 'NC_071989.2 chromosome 4 ': 0.06054063358102704, 'NC_071990.2 chromosome 5 ': 0.05488863427590256, 'NC_071991.2 chromosome 6 ': 0.04991562030658276, 'NC_071992.2 chromosome 7 ': 0.05139890457834488, 'NC_071993.2 chromosome 8 ': 0.04479172007108265, 'NC_071994.2 chromosome 9 ': 0.04403388804019852, 'NC_071995.2 chromosome 10 ': 0.042065684748169976, 'NC_071996.2 chromosome 11 ': 0.04649081173341658, 'NC_071997.2 chromosome 12 ': 0.042352332847028516, 'NC_071998.2 chromosome 13 ': 0.04121867481395561, 'NC_071999.2 chromosome 14 ': 0.038344481671267194, 'NC_072000.2 chromosome 15 ': 0.03553393097196879, 'NC_072001.2 chromosome 16 ': 0.03349624133683267, 'NC_072002.2 chromosome 17 ': 0.030356392278561357, 'NC_072003.2 chromosome 18 ': 0.028477956781247725, 'NC_072004.2 chromosome 19 ': 0.03137690723604979, 'NC_072005.2 chromosome 20 ': 0.020797295564178187, 'NC_072006.2 chromosome 21 ': 0.021862763743186804, 'NC_072007.2 chromosome 22 ': 0.018171549408677587, 'NC_085928.1 chromosome 2 ': 0.06663546228161958, 'NC_085929.1 chromosome 23 ': 0.0183147508688191, 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold': 7.043970934545426e-05, 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold': 4.235769942762567e-05, 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold': 3.663750200041748e-05, 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold': 9.52291395345018e-05}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Lutra lutra
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_902655055.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_062297.1 chromosome Y ', 'NC_062296.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_062278.1 chromosome 1 ', 'NC_062279.1 chromosome 2 ', 'NC_062280.1 chromosome 3 ', 'NC_062281.1 chromosome 4 ', 'NC_062282.1 chromosome 5 ', 'NC_062283.1 chromosome 6 ', 'NC_062284.1 chromosome 7 ', 'NC_062285.1 chromosome 8 ', 'NC_062286.1 chromosome 9 ', 'NC_062287.1 chromosome 10 ', 'NC_062288.1 chromosome 11 ', 'NC_062289.1 chromosome 12 ', 'NC_062290.1 chromosome 13 ', 'NC_062291.1 chromosome 14 ', 'NC_062292.1 chromosome 15 ', 'NC_062293.1 chromosome 16 ', 'NC_062294.1 chromosome 17 ', 'NC_062295.1 chromosome 18 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_062297.1 chromosome Y ': 2249909, 'NC_062296.1 chromosome X ': 99689450, 'NC_062278.1 chromosome 1 ': 446898406, 'NC_062279.1 chromosome 2 ': 421290874, 'NC_062280.1 chromosome 3 ': 402637996, 'NC_062281.1 chromosome 4 ': 395416572, 'NC_062282.1 chromosome 5 ': 331611490, 'NC_062283.1 chromosome 6 ': 308851022, 'NC_062284.1 chromosome 7 ': 298009614, 'NC_062285.1 chromosome 8 ': 289491188, 'NC_062286.1 chromosome 9 ': 288170928, 'NC_062287.1 chromosome 10 ': 229324098, 'NC_062288.1 chromosome 11 ': 217575542, 'NC_062289.1 chromosome 12 ': 192891470, 'NC_062290.1 chromosome 13 ': 191452028, 'NC_062291.1 chromosome 14 ': 178161560, 'NC_062292.1 chromosome 15 ': 139984142, 'NC_062293.1 chromosome 16 ': 122966058, 'NC_062294.1 chromosome 17 ': 120697022, 'NC_062295.1 chromosome 18 ': 80856246}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_062297.1 chromosome Y ': 0.0004728462208490717, 'NC_062296.1 chromosome X ': 0.020950971657530366, 'NC_062278.1 chromosome 1 ': 0.09392123076114373, 'NC_062279.1 chromosome 2 ': 0.08853949099679251, 'NC_062280.1 chromosome 3 ': 0.08461935784018093, 'NC_062281.1 chromosome 4 ': 0.0831016862154402, 'NC_062282.1 chromosome 5 ': 0.06969225859207183, 'NC_062283.1 chromosome 6 ': 0.06490886456211051, 'NC_062284.1 chromosome 7 ': 0.06263040849945069, 'NC_062285.1 chromosome 8 ': 0.06084015585292922, 'NC_062286.1 chromosome 9 ': 0.060562686874611346, 'NC_062287.1 chromosome 10 ': 0.048195297271543945, 'NC_062288.1 chromosome 11 ': 0.045726192829971556, 'NC_062289.1 chromosome 12 ': 0.04053852961320751, 'NC_062290.1 chromosome 13 ': 0.04023601306261305, 'NC_062291.1 chromosome 14 ': 0.037442856731794545, 'NC_062292.1 chromosome 15 ': 0.029419399861727657, 'NC_062293.1 chromosome 16 ': 0.02584283889615436, 'NC_062294.1 chromosome 17 ': 0.025365972899542722, 'NC_062295.1 chromosome 18 ': 0.01699294076033425}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Neomonachus schauinslandi
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_002201575.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_058420.1 chromosome Y ', 'NC_058419.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_058403.1 chromosome 1 ', 'NC_058404.1 chromosome 2 ', 'NC_058405.1 chromosome 3 ', 'NC_058406.1 chromosome 4 ', 'NC_058407.1 chromosome 5 ', 'NC_058408.1 chromosome 6 ', 'NC_058409.1 chromosome 7 ', 'NC_058410.1 chromosome 8 ', 'NC_058411.1 chromosome 9 ', 'NC_058412.1 chromosome 10 ', 'NC_058413.1 chromosome 11 ', 'NC_058414.1 chromosome 12 ', 'NC_058415.1 chromosome 13 ', 'NC_058416.1 chromosome 14 ', 'NC_058417.1 chromosome 15 ', 'NC_058418.1 chromosome 16 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_058420.1 chromosome Y ': 5277812, 'NC_058419.1 chromosome X ': 126494893, 'NC_058403.1 chromosome 1 ': 429366354, 'NC_058404.1 chromosome 2 ': 407736248, 'NC_058405.1 chromosome 3 ': 385675150, 'NC_058406.1 chromosome 4 ': 376368364, 'NC_058407.1 chromosome 5 ': 352990000, 'NC_058408.1 chromosome 6 ': 309600356, 'NC_058409.1 chromosome 7 ': 301621650, 'NC_058410.1 chromosome 8 ': 291868190, 'NC_058411.1 chromosome 9 ': 287733078, 'NC_058412.1 chromosome 10 ': 276814350, 'NC_058413.1 chromosome 11 ': 222157914, 'NC_058414.1 chromosome 12 ': 211869670, 'NC_058415.1 chromosome 13 ': 187349136, 'NC_058416.1 chromosome 14 ': 184857912, 'NC_058417.1 chromosome 15 ': 120033060, 'NC_058418.1 chromosome 16 ': 118930010}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_058420.1 chromosome Y ': 0.0011481630978840728, 'NC_058419.1 chromosome X ': 0.02751836712133633, 'NC_058403.1 chromosome 1 ': 0.09340662439962422, 'NC_058404.1 chromosome 2 ': 0.08870109689835648, 'NC_058405.1 chromosome 3 ': 0.08390180912107223, 'NC_058406.1 chromosome 4 ': 0.08187716173971342, 'NC_058407.1 chromosome 5 ': 0.07679130895948906, 'NC_058408.1 chromosome 6 ': 0.06735209663606279, 'NC_058409.1 chromosome 7 ': 0.06561636679231954, 'NC_058410.1 chromosome 8 ': 0.06349454758983783, 'NC_058411.1 chromosome 9 ': 0.06259497348526237, 'NC_058412.1 chromosome 10 ': 0.06021965572755642, 'NC_058413.1 chromosome 11 ': 0.04832940596552197, 'NC_058414.1 chromosome 12 ': 0.04609124702715372, 'NC_058415.1 chromosome 13 ': 0.04075692055262, 'NC_058416.1 chromosome 14 ': 0.04021496652595836, 'NC_058417.1 chromosome 15 ': 0.026112625841561765, 'NC_058418.1 chromosome 16 ': 0.025872662518669435}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999

{'labels': 0, 'species': 'Rattus rattus', 'sampled_chromosomes': ['NC_046158.1 chromosome 5 ', 'NC_046161.1 chromosome 8 ', 'NC_046171.1 chromosome 18 ', 'NC_046157.1 chromosome 4 ', 'NC_046173.1 chromosome Y ', 'NC_046158.1 chromosome 5 ', 'NC_046166.1 chromosome 13 ', 'NC_046160.1 chromosome 7 ', 'NC_046157.1 chromosome 4 ', 'NC_046156.1 chromosome 3 '], 'chunks': ['CCCTCACCCC', 'GATGGAAGGA', 'TCTTATCTTT', 'CTTCTCAGCT', 'CCTCATCCAA', 'AAGACTGTTG', 'TGCATTACTG', 'TCCTTTGGTC', 'TTGAGATTTT', 'ACTGAACATT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Mesoplodon densirostris', 'sampled_chromosomes': ['NC_082676.1 chromosome 16 ', 'NC_082673.1 chromosome 13 ', 'NC_082662.1 chromosome 2 ', 'NC_082661.1 chromosome 1 ', 'NC_082676.1 chromosome 16 ', 'NC_082670.1 chromosome 10 ', 'NC_082661.1 chromosome 1 ', 'NC_082667.1 chromosome 7 ', 'NC_082664.1 chromosome 4 ', 'NW_026778236.1 chromosome Y unlocalized genomic scaffold'], 'chunks': ['CTTTACAGAC', 'AATTTGCCAC', 'GGTTAAAAGC', 'GTAGTTCTAC', 'TGAGTCTAGC', 'ACAGATGAAT', 'AGGCCCCTGA', 'ACAGTTGTTT', 'CTCTTGGCCA', 'CAGACCACGG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Pongo abelii', 'sampled_chromosomes': ['NC_072000.2 chromosome 15 ', 'NC_071998.2 chromosome 13 ', 'NC_071989.2 chromosome 4 ', 'NC_071996.2 chromosome 11 ', 'NC_071997.2 chromosome 12 ', 'NC_072004.2 chromosome 19 ', 'NC_071990.2 chromosome 5 ', 'NC_071988.2 chromosome 3 ', 'NC_072001.2 chromosome 16 ', 'NC_072009.2 chromosome Y '], 'chunks': ['AGCTTCTAGG', 'CAAGAGAAAA', 'TAAAATAAAA', 'ACCTGAAACA', 'ACCCCATCAC', 'GAAGTGGTAA', 'CAATCGAATT', 'TTTCTCTAAC', 'TAATTTATTC', 'CCAGGAAAAG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Lutra lutra', 'sampled_chromosomes': ['NC_062293.1 chromosome 16 ', 'NC_062281.1 chromosome 4 ', 'NC_062297.1 chromosome Y ', 'NC_062279.1 chromosome 2 ', 'NC_062292.1 chromosome 15 ', 'NC_062281.1 chromosome 4 ', 'NC_062289.1 chromosome 12 ', 'NC_062282.1 chromosome 5 ', 'NC_062285.1 chromosome 8 ', 'NC_062289.1 chromosome 12 '], 'chunks': ['AAGAATGGCA', 'GCTGAGTGGT', 'GGAGGGCCCA', 'GGATTTTCTT', 'AGACGGAGAG', 'TGATTCTGTG', 'AACTTTTAAA', 'AACAGTTGGT', 'AAGAGTCAGA', 'TGTGTGTGTG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Pongo abelii
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_028885655.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_072008.2 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_071985.2 chromosome 1 ', 'NC_071988.2 chromosome 3 ', 'NC_071989.2 chromosome 4 ', 'NC_071990.2 chromosome 5 ', 'NC_071991.2 chromosome 6 ', 'NC_071992.2 chromosome 7 ', 'NC_071993.2 chromosome 8 ', 'NC_071994.2 chromosome 9 ', 'NC_071995.2 chromosome 10 ', 'NC_071996.2 chromosome 11 ', 'NC_071997.2 chromosome 12 ', 'NC_071998.2 chromosome 13 ', 'NC_071999.2 chromosome 14 ', 'NC_072000.2 chromosome 15 ', 'NC_072001.2 chromosome 16 ', 'NC_072002.2 chromosome 17 ', 'NC_072003.2 chromosome 18 ', 'NC_072004.2 chromosome 19 ', 'NC_072005.2 chromosome 20 ', 'NC_072006.2 chromosome 21 ', 'NC_072007.2 chromosome 22 ', 'NC_085928.1 chromosome 2 ', 'NC_085929.1 chromosome 23 ', 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_072008.2 chromosome X ': 325172642, 'NC_071985.2 chromosome 1 ': 467591038, 'NC_071988.2 chromosome 3 ': 425833550, 'NC_071989.2 chromosome 4 ': 380757808, 'NC_071990.2 chromosome 5 ': 345210726, 'NC_071991.2 chromosome 6 ': 313933982, 'NC_071992.2 chromosome 7 ': 323262792, 'NC_071993.2 chromosome 8 ': 281708270, 'NC_071994.2 chromosome 9 ': 276942042, 'NC_071995.2 chromosome 10 ': 264563434, 'NC_071996.2 chromosome 11 ': 292394356, 'NC_071997.2 chromosome 12 ': 266366248, 'NC_071998.2 chromosome 13 ': 259236340, 'NC_071999.2 chromosome 14 ': 241159696, 'NC_072000.2 chromosome 15 ': 223483318, 'NC_072001.2 chromosome 16 ': 210667690, 'NC_072002.2 chromosome 17 ': 190920258, 'NC_072003.2 chromosome 18 ': 179106226, 'NC_072004.2 chromosome 19 ': 197338576, 'NC_072005.2 chromosome 20 ': 130800294, 'NC_072006.2 chromosome 21 ': 137501336, 'NC_072007.2 chromosome 22 ': 114286206, 'NC_085928.1 chromosome 2 ': 419089974, 'NC_085929.1 chromosome 23 ': 115186842, 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold': 443016, 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold': 266400, 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold': 230424, 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold': 598924}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_072008.2 chromosome X ': 0.05093514608252884, 'NC_071985.2 chromosome 1 ': 0.07324360893623792, 'NC_071988.2 chromosome 3 ': 0.06670270273257443, 'NC_071989.2 chromosome 4 ': 0.05964202416679158, 'NC_071990.2 chromosome 5 ': 0.05407391793454087, 'NC_071991.2 chromosome 6 ': 0.04917471880503397, 'NC_071992.2 chromosome 7 ': 0.05063598657099245, 'NC_071993.2 chromosome 8 ': 0.04412687302613384, 'NC_071994.2 chromosome 9 ': 0.043380289556044005, 'NC_071995.2 chromosome 10 ': 0.04144130046120386, 'NC_071996.2 chromosome 11 ': 0.04580074493649113, 'NC_071997.2 chromosome 12 ': 0.04172369381965136, 'NC_071998.2 chromosome 13 ': 0.0406068627624587, 'NC_071999.2 chromosome 14 ': 0.0377753314959942, 'NC_072000.2 chromosome 15 ': 0.035006498023097056, 'NC_072001.2 chromosome 16 ': 0.03299905397643785, 'NC_072002.2 chromosome 17 ': 0.029905809946164215, 'NC_072003.2 chromosome 18 ': 0.028055256215559564, 'NC_072004.2 chromosome 19 ': 0.030911177319395213, 'NC_072005.2 chromosome 20 ': 0.020488599660631105, 'NC_072006.2 chromosome 21 ': 0.02153825301115855, 'NC_072007.2 chromosome 22 ': 0.01790182766306639, 'NC_085928.1 chromosome 2 ': 0.06564638684275663, 'NC_085929.1 chromosome 23 ': 0.018042903572604883, 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold': 6.939416716642969e-05, 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold': 4.1728980743668106e-05, 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold': 3.609368865945563e-05, 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold': 9.381564588183437e-05}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Ovis aries
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_016772045.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_082741.1 chromosome Y ', 'NC_056080.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_056054.1 chromosome 1 ', 'NC_056055.1 chromosome 2 ', 'NC_056056.1 chromosome 3 ', 'NC_056057.1 chromosome 4 ', 'NC_056058.1 chromosome 5 ', 'NC_056059.1 chromosome 6 ', 'NC_056060.1 chromosome 7 ', 'NC_056061.1 chromosome 8 ', 'NC_056062.1 chromosome 9 ', 'NC_056063.1 chromosome 10 ', 'NC_056064.1 chromosome 11 ', 'NC_056065.1 chromosome 12 ', 'NC_056066.1 chromosome 13 ', 'NC_056067.1 chromosome 14 ', 'NC_056068.1 chromosome 15 ', 'NC_056069.1 chromosome 16 ', 'NC_056070.1 chromosome 17 ', 'NC_056071.1 chromosome 18 ', 'NC_056072.1 chromosome 19 ', 'NC_056073.1 chromosome 20 ', 'NC_056074.1 chromosome 21 ', 'NC_056075.1 chromosome 22 ', 'NC_056076.1 chromosome 23 ', 'NC_056077.1 chromosome 24 ', 'NC_056078.1 chromosome 25 ', 'NC_056079.1 chromosome 26 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_082741.1 chromosome Y ': 25917078, 'NC_056080.1 chromosome X ': 143171725, 'NC_056054.1 chromosome 1 ': 557234404, 'NC_056055.1 chromosome 2 ': 500404116, 'NC_056056.1 chromosome 3 ': 452178200, 'NC_056057.1 chromosome 4 ': 243156198, 'NC_056058.1 chromosome 5 ': 216441576, 'NC_056059.1 chromosome 6 ': 236939394, 'NC_056060.1 chromosome 7 ': 202548836, 'NC_056061.1 chromosome 8 ': 183585742, 'NC_056062.1 chromosome 9 ': 190359316, 'NC_056063.1 chromosome 10 ': 172918942, 'NC_056064.1 chromosome 11 ': 125094994, 'NC_056065.1 chromosome 12 ': 160807310, 'NC_056066.1 chromosome 13 ': 167023670, 'NC_056067.1 chromosome 14 ': 133033314, 'NC_056068.1 chromosome 15 ': 165077274, 'NC_056069.1 chromosome 16 ': 143794728, 'NC_056070.1 chromosome 17 ': 146334446, 'NC_056071.1 chromosome 18 ': 135968920, 'NC_056072.1 chromosome 19 ': 121123100, 'NC_056073.1 chromosome 20 ': 102903434, 'NC_056074.1 chromosome 21 ': 95028388, 'NC_056075.1 chromosome 22 ': 103024982, 'NC_056076.1 chromosome 23 ': 124881288, 'NC_056077.1 chromosome 24 ': 85260472, 'NC_056078.1 chromosome 25 ': 89727508, 'NC_056079.1 chromosome 26 ': 90104718}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_082741.1 chromosome Y ': 0.0050678245298728, 'NC_056080.1 chromosome X ': 0.02799579412228503, 'NC_056054.1 chromosome 1 ': 0.10896159595924546, 'NC_056055.1 chromosome 2 ': 0.09784900342214943, 'NC_056056.1 chromosome 3 ': 0.08841890948639074, 'NC_056057.1 chromosome 4 ': 0.04754675449196114, 'NC_056058.1 chromosome 5 ': 0.042322978236093114, 'NC_056059.1 chromosome 6 ': 0.04633112085422577, 'NC_056060.1 chromosome 7 ': 0.039606392340138914, 'NC_056061.1 chromosome 8 ': 0.03589834959953815, 'NC_056062.1 chromosome 9 ': 0.03722285402369077, 'NC_056063.1 chromosome 10 ': 0.0338125638988798, 'NC_056064.1 chromosome 11 ': 0.024461070771847452, 'NC_056065.1 chromosome 12 ': 0.03144425579924016, 'NC_056066.1 chromosome 13 ': 0.03265980261723098, 'NC_056067.1 chromosome 14 ': 0.026013329588291955, 'NC_056068.1 chromosome 15 ': 0.032279204411150564, 'NC_056069.1 chromosome 16 ': 0.028117616107216525, 'NC_056070.1 chromosome 17 ': 0.028614232476521718, 'NC_056071.1 chromosome 18 ': 0.02658735788333516, 'NC_056072.1 chromosome 19 ': 0.02368440675736038, 'NC_056073.1 chromosome 20 ': 0.020121733901998777, 'NC_056074.1 chromosome 21 ': 0.018581847681311527, 'NC_056075.1 chromosome 22 ': 0.020145501393687343, 'NC_056076.1 chromosome 23 ': 0.024419282708047167, 'NC_056077.1 chromosome 24 ': 0.016671829726720464, 'NC_056078.1 chromosome 25 ': 0.017545313790650236, 'NC_056079.1 chromosome 26 ': 0.017619073420918483}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Mustela lutreola
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_030435805.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_081308.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_081290.1 chromosome 1 ', 'NC_081291.1 chromosome 2 ', 'NC_081292.1 chromosome 3 ', 'NC_081293.1 chromosome 4 ', 'NC_081294.1 chromosome 5 ', 'NC_081295.1 chromosome 6 ', 'NC_081296.1 chromosome 7 ', 'NC_081297.1 chromosome 8 ', 'NC_081298.1 chromosome 9 ', 'NC_081299.1 chromosome 10 ', 'NC_081300.1 chromosome 11 ', 'NC_081301.1 chromosome 12 ', 'NC_081302.1 chromosome 13 ', 'NC_081303.1 chromosome 14 ', 'NC_081304.1 chromosome 15 ', 'NC_081305.1 chromosome 16 ', 'NC_081306.1 chromosome 17 ', 'NC_081307.1 chromosome 18 ', 'NW_026709257.1 chromosome 4 unlocalized genomic scaffold', 'NW_026709258.1 chromosome 5 unlocalized genomic scaffold', 'NW_026709259.1 chromosome 16 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_081308.1 chromosome X ': 266165512, 'NC_081290.1 chromosome 1 ': 580209788, 'NC_081291.1 chromosome 2 ': 450360622, 'NC_081292.1 chromosome 3 ': 422582014, 'NC_081293.1 chromosome 4 ': 405148736, 'NC_081294.1 chromosome 5 ': 354945442, 'NC_081295.1 chromosome 6 ': 320021132, 'NC_081296.1 chromosome 7 ': 308157286, 'NC_081297.1 chromosome 8 ': 303022374, 'NC_081298.1 chromosome 9 ': 292543060, 'NC_081299.1 chromosome 10 ': 247627348, 'NC_081300.1 chromosome 11 ': 209097952, 'NC_081301.1 chromosome 12 ': 201223108, 'NC_081302.1 chromosome 13 ': 184206380, 'NC_081303.1 chromosome 14 ': 151745266, 'NC_081304.1 chromosome 15 ': 141844742, 'NC_081305.1 chromosome 16 ': 128067692, 'NC_081306.1 chromosome 17 ': 98796040, 'NC_081307.1 chromosome 18 ': 84746544, 'NW_026709257.1 chromosome 4 unlocalized genomic scaffold': 1395006, 'NW_026709258.1 chromosome 5 unlocalized genomic scaffold': 2109010, 'NW_026709259.1 chromosome 16 unlocalized genomic scaffold': 2893842}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_081308.1 chromosome X ': 0.051613382622767205, 'NC_081290.1 chromosome 1 ': 0.11251115730395095, 'NC_081291.1 chromosome 2 ': 0.08733150635050506, 'NC_081292.1 chromosome 3 ': 0.0819448282919598, 'NC_081293.1 chromosome 4 ': 0.07856426091107738, 'NC_081294.1 chromosome 5 ': 0.06882910851407835, 'NC_081295.1 chromosome 6 ': 0.06205677440767416, 'NC_081296.1 chromosome 7 ': 0.05975620128542988, 'NC_081297.1 chromosome 8 ': 0.058760466805035445, 'NC_081298.1 chromosome 9 ': 0.05672837467167851, 'NC_081299.1 chromosome 10 ': 0.048018561699252484, 'NC_081300.1 chromosome 11 ': 0.04054714873132403, 'NC_081301.1 chromosome 12 ': 0.039020101393701254, 'NC_081302.1 chromosome 13 ': 0.035720309145442, 'NC_081303.1 chromosome 14 ': 0.029425624741538967, 'NC_081304.1 chromosome 15 ': 0.02750576844784345, 'NC_081305.1 chromosome 16 ': 0.024834197109694294, 'NC_081306.1 chromosome 17 ': 0.019157995999625275, 'NC_081307.1 chromosome 18 ': 0.016433593400444667, 'NW_026709257.1 chromosome 4 unlocalized genomic scaffold': 0.00027051205055843595, 'NW_026709258.1 chromosome 5 unlocalized genomic scaffold': 0.00040896786088966423, 'NW_026709259.1 chromosome 16 unlocalized genomic scaffold': 0.00056115825552874}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Pan paniscus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_029289425.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_073273.2 chromosome Y ', 'NC_073272.2 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_073249.2 chromosome 1 ', 'NC_073252.2 chromosome 3 ', 'NC_073253.2 chromosome 4 ', 'NC_073254.2 chromosome 5 ', 'NC_073255.2 chromosome 6 ', 'NC_073256.2 chromosome 7 ', 'NC_073257.2 chromosome 8 ', 'NC_073258.2 chromosome 9 ', 'NC_073259.2 chromosome 10 ', 'NC_073260.2 chromosome 11 ', 'NC_073261.2 chromosome 12 ', 'NC_073262.2 chromosome 13 ', 'NC_073263.2 chromosome 14 ', 'NC_073264.2 chromosome 15 ', 'NC_073265.2 chromosome 16 ', 'NC_073266.2 chromosome 17 ', 'NC_073267.2 chromosome 18 ', 'NC_073268.2 chromosome 19 ', 'NC_073269.2 chromosome 20 ', 'NC_073270.2 chromosome 21 ', 'NC_073271.2 chromosome 22 ', 'NC_085926.1 chromosome 2 ', 'NC_085927.1 chromosome 23 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_073273.2 chromosome Y ': 46954669, 'NC_073272.2 chromosome X ': 160241051, 'NC_073249.2 chromosome 1 ': 455410104, 'NC_073252.2 chromosome 3 ': 377228750, 'NC_073253.2 chromosome 4 ': 353102666, 'NC_073254.2 chromosome 5 ': 382303424, 'NC_073255.2 chromosome 6 ': 392619714, 'NC_073256.2 chromosome 7 ': 325587904, 'NC_073257.2 chromosome 8 ': 294056814, 'NC_073258.2 chromosome 9 ': 271500796, 'NC_073259.2 chromosome 10 ': 283630350, 'NC_073260.2 chromosome 11 ': 249517922, 'NC_073261.2 chromosome 12 ': 253102938, 'NC_073262.2 chromosome 13 ': 289744536, 'NC_073263.2 chromosome 14 ': 232252860, 'NC_073264.2 chromosome 15 ': 216905492, 'NC_073265.2 chromosome 16 ': 183719858, 'NC_073266.2 chromosome 17 ': 196540932, 'NC_073267.2 chromosome 18 ': 200854384, 'NC_073268.2 chromosome 19 ': 201584824, 'NC_073269.2 chromosome 20 ': 141442586, 'NC_073270.2 chromosome 21 ': 153582654, 'NC_073271.2 chromosome 22 ': 96966552, 'NC_085926.1 chromosome 2 ': 392863782, 'NC_085927.1 chromosome 23 ': 130104760}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_073273.2 chromosome Y ': 0.007474691505511036, 'NC_073272.2 chromosome X ': 0.025508696967789523, 'NC_073249.2 chromosome 1 ': 0.07249651862933369, 'NC_073252.2 chromosome 3 ': 0.060050865937518294, 'NC_073253.2 chromosome 4 ': 0.05621024605931096, 'NC_073254.2 chromosome 5 ': 0.060858700886605846, 'NC_073255.2 chromosome 6 ': 0.06250094620264435, 'NC_073256.2 chromosome 7 ': 0.05183018413623452, 'NC_073257.2 chromosome 8 ': 0.04681076486224275, 'NC_073258.2 chromosome 9 ': 0.04322008304649501, 'NC_073259.2 chromosome 10 ': 0.04515098099935753, 'NC_073260.2 chromosome 11 ': 0.03972063975248479, 'NC_073261.2 chromosome 12 ': 0.040291336750526055, 'NC_073262.2 chromosome 13 ': 0.04612429537108304, 'NC_073263.2 chromosome 14 ': 0.03697222271490496, 'NC_073264.2 chromosome 15 ': 0.03452908247635804, 'NC_073265.2 chromosome 16 ': 0.0292462771271222, 'NC_073266.2 chromosome 17 ': 0.031287257821061884, 'NC_073267.2 chromosome 18 ': 0.031973914200725206, 'NC_073268.2 chromosome 19 ': 0.03209019259815754, 'NC_073269.2 chromosome 20 ': 0.022516178233344893, 'NC_073270.2 chromosome 21 ': 0.024448749904884656, 'NC_073271.2 chromosome 22 ': 0.015436059458817484, 'NC_085926.1 chromosome 2 ': 0.06253979927189646, 'NC_085927.1 chromosome 23 ': 0.020711315085589294}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Apodemus sylvaticus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_947179515.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_067496.1 chromosome Y ', 'NW_026262995.1 chromosome Y unlocalized genomic scaffold', 'NW_026262996.1 chromosome Y unlocalized genomic scaffold', 'NW_026262997.1 chromosome Y unlocalized genomic scaffold', 'NW_026262998.1 chromosome Y unlocalized genomic scaffold', 'NW_026262999.1 chromosome Y unlocalized genomic scaffold', 'NW_026263000.1 chromosome Y unlocalized genomic scaffold', 'NW_026263001.1 chromosome Y unlocalized genomic scaffold', 'NW_026263002.1 chromosome Y unlocalized genomic scaffold', 'NW_026263003.1 chromosome Y unlocalized genomic scaffold', 'NC_067495.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_067472.1 chromosome 1 ', 'NC_067473.1 chromosome 2 ', 'NC_067474.1 chromosome 3 ', 'NC_067475.1 chromosome 4 ', 'NC_067476.1 chromosome 5 ', 'NC_067477.1 chromosome 6 ', 'NC_067478.1 chromosome 7 ', 'NC_067479.1 chromosome 8 ', 'NC_067480.1 chromosome 9 ', 'NC_067481.1 chromosome 10 ', 'NC_067482.1 chromosome 11 ', 'NC_067483.1 chromosome 12 ', 'NC_067484.1 chromosome 13 ', 'NC_067485.1 chromosome 14 ', 'NC_067486.1 chromosome 15 ', 'NC_067487.1 chromosome 16 ', 'NC_067488.1 chromosome 17 ', 'NC_067489.1 chromosome 18 ', 'NC_067490.1 chromosome 19 ', 'NC_067491.1 chromosome 20 ', 'NC_067492.1 chromosome 21 ', 'NC_067493.1 chromosome 22 ', 'NC_067494.1 chromosome 23 ', 'NW_026262993.1 chromosome 5 unlocalized genomic scaffold', 'NW_026262994.1 chromosome 15 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_067496.1 chromosome Y ': 3454884, 'NW_026262995.1 chromosome Y unlocalized genomic scaffold': 2319465, 'NW_026262996.1 chromosome Y unlocalized genomic scaffold': 2307501, 'NW_026262997.1 chromosome Y unlocalized genomic scaffold': 1800492, 'NW_026262998.1 chromosome Y unlocalized genomic scaffold': 1756322, 'NW_026262999.1 chromosome Y unlocalized genomic scaffold': 1504898, 'NW_026263000.1 chromosome Y unlocalized genomic scaffold': 974588, 'NW_026263001.1 chromosome Y unlocalized genomic scaffold': 855225, 'NW_026263002.1 chromosome Y unlocalized genomic scaffold': 354000, 'NW_026263003.1 chromosome Y unlocalized genomic scaffold': 333444, 'NC_067495.1 chromosome X ': 151773995, 'NC_067472.1 chromosome 1 ': 423528672, 'NC_067473.1 chromosome 2 ': 376121598, 'NC_067474.1 chromosome 3 ': 343320724, 'NC_067475.1 chromosome 4 ': 340525048, 'NC_067476.1 chromosome 5 ': 330219786, 'NC_067477.1 chromosome 6 ': 295131364, 'NC_067478.1 chromosome 7 ': 265624236, 'NC_067479.1 chromosome 8 ': 241876502, 'NC_067480.1 chromosome 9 ': 229934912, 'NC_067481.1 chromosome 10 ': 222463898, 'NC_067482.1 chromosome 11 ': 216648076, 'NC_067483.1 chromosome 12 ': 208942418, 'NC_067484.1 chromosome 13 ': 204787724, 'NC_067485.1 chromosome 14 ': 183482302, 'NC_067486.1 chromosome 15 ': 178861258, 'NC_067487.1 chromosome 16 ': 179680142, 'NC_067488.1 chromosome 17 ': 165585976, 'NC_067489.1 chromosome 18 ': 143008274, 'NC_067490.1 chromosome 19 ': 137700132, 'NC_067491.1 chromosome 20 ': 135996420, 'NC_067492.1 chromosome 21 ': 127553474, 'NC_067493.1 chromosome 22 ': 118583046, 'NC_067494.1 chromosome 23 ': 115249044, 'NW_026262993.1 chromosome 5 unlocalized genomic scaffold': 1312222, 'NW_026262994.1 chromosome 15 unlocalized genomic scaffold': 3911922}

{'labels': 0, 'species': 'Neomonachus schauinslandi', 'sampled_chromosomes': ['NC_058415.1 chromosome 13 ', 'NC_058411.1 chromosome 9 ', 'NC_058410.1 chromosome 8 ', 'NC_058412.1 chromosome 10 ', 'NC_058415.1 chromosome 13 ', 'NC_058405.1 chromosome 3 ', 'NC_058411.1 chromosome 9 ', 'NC_058417.1 chromosome 15 ', 'NC_058420.1 chromosome Y ', 'NC_058410.1 chromosome 8 '], 'chunks': ['CCTGTGCCTC', 'ATGTGCTGGG', 'GGATCATCAT', 'CAGCCCAGTG', 'AAGTATTAAA', 'GTTTTTGCCT', 'CAGGTCTCGA', 'CCCACGCGCC', 'NNNNNNNNNN', 'TAGAATCATG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Pongo abelii', 'sampled_chromosomes': ['NC_071994.2 chromosome 9 ', 'NC_071989.2 chromosome 4 ', 'NC_072005.2 chromosome 20 ', 'NC_072001.2 chromosome 16 ', 'NC_071992.2 chromosome 7 ', 'NC_072008.2 chromosome X ', 'NC_072003.2 chromosome 18 ', 'NC_071993.2 chromosome 8 ', 'NC_071993.2 chromosome 8 ', 'NC_071993.2 chromosome 8 '], 'chunks': ['GGCAATTGTT', 'TTTTTCATTC', 'CTAGCACCTC', 'TAGAACAAAT', 'CCAAGAGTGC', 'CCAGTCTGGA', 'TTCTTAACTG', 'GGTCACTGTG', 'AGTAATATTC', 'GGGCAGGGCA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 0, 'species': 'Ovis aries', 'sampled_chromosomes': ['NC_056059.1 chromosome 6 ', 'NC_056074.1 chromosome 21 ', 'NC_056057.1 chromosome 4 ', 'NC_056061.1 chromosome 8 ', 'NC_056062.1 chromosome 9 ', 'NC_056059.1 chromosome 6 ', 'NC_056061.1 chromosome 8 ', 'NC_056056.1 chromosome 3 ', 'NC_056057.1 chromosome 4 ', 'NC_082741.1 chromosome Y '], 'chunks': ['ATCAGTCCCT', 'TAGGGTTAGG', 'AGAGATAATC', 'CTACTGAGAA', 'GCAGAGGCAC', 'CTTGTGGTTT', 'AGTCATAGTT', 'ATGACAAGAG', 'GTCCATGAAG', 'AGAGTCAGAC'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Mustela lutreola', 'sampled_chromosomes': ['NC_081308.1 chromosome X ', 'NC_081290.1 chromosome 1 ', 'NC_081292.1 chromosome 3 ', 'NC_081295.1 chromosome 6 ', 'NC_081299.1 chromosome 10 ', 'NC_081305.1 chromosome 16 ', 'NC_081290.1 chromosome 1 ', 'NC_081302.1 chromosome 13 ', 'NC_081297.1 chromosome 8 ', 'NC_081290.1 chromosome 1 '], 'chunks': ['GAAAAGACGC', 'TGACAAATAT', 'AAGTGTCCCT', 'TCTCTACTGG', 'ACAAAATAAG', 'CTGGGCCCCA', 'TTCATTTTCC', 'AAAGGGGCCC', 'AGAACACCAC', 'GGAACCTTGG'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 0, 'species': 'Pan paniscus', 'sampled_chromosomes': ['NC_073272.2 chromosome X ', 'NC_085926.1 chromosome 2 ', 'NC_073253.2 chromosome 4 ', 'NC_073254.2 chromosome 5 ', 'NC_073259.2 chromosome 10 ', 'NC_073260.2 chromosome 11 ', 'NC_085926.1 chromosome 2 ', 'NC_085926.1 chromosome 2 ', 'NC_073264.2 chromosome 15 ', 'NC_073273.2 chromosome Y '], 'chunks': ['TTAGGTTTTG', 'TCAACAATGT', 'ATCCATGGGT', 'TACCTAATTA', 'TGATCTCGGC', 'AAGATTTTCC', 'TTAATTCAGG', 'GGTGGTCTAA', 'ATAAAGGGGA', 'GAAAGAAAAT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': True}

DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Rattus rattus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011064425.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_046172.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_046154.1 chromosome 1 ', 'NC_046155.1 chromosome 2 ', 'NC_046156.1 chromosome 3 ', 'NC_046157.1 chromosome 4 ', 'NC_046158.1 chromosome 5 ', 'NC_046159.1 chromosome 6 ', 'NC_046160.1 chromosome 7 ', 'NC_046161.1 chromosome 8 ', 'NC_046162.1 chromosome 9 ', 'NC_046163.1 chromosome 10 ', 'NC_046164.1 chromosome 11 ', 'NC_046165.1 chromosome 12 ', 'NC_046166.1 chromosome 13 ', 'NC_046167.1 chromosome 14 ', 'NC_046168.1 chromosome 15 ', 'NC_046169.1 chromosome 16 ', 'NC_046170.1 chromosome 17 ', 'NC_046171.1 chromosome 18 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_046172.1 chromosome X ': 260747026, 'NC_046154.1 chromosome 1 ': 545899780, 'NC_046155.1 chromosome 2 ': 460490430, 'NC_046156.1 chromosome 3 ': 446780580, 'NC_046157.1 chromosome 4 ': 365650368, 'NC_046158.1 chromosome 5 ': 317649504, 'NC_046159.1 chromosome 6 ': 319153832, 'NC_046160.1 chromosome 7 ': 261677498, 'NC_046161.1 chromosome 8 ': 230657978, 'NC_046162.1 chromosome 9 ': 193419404, 'NC_046163.1 chromosome 10 ': 189950930, 'NC_046164.1 chromosome 11 ': 197229706, 'NC_046165.1 chromosome 12 ': 188176076, 'NC_046166.1 chromosome 13 ': 157637022, 'NC_046167.1 chromosome 14 ': 163988198, 'NC_046168.1 chromosome 15 ': 158636486, 'NC_046169.1 chromosome 16 ': 88862024, 'NC_046170.1 chromosome 17 ': 97008248, 'NC_046171.1 chromosome 18 ': 99693070}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_046172.1 chromosome X ': 0.05497155512662285, 'NC_046154.1 chromosome 1 ': 0.11508840699061812, 'NC_046155.1 chromosome 2 ': 0.09708212379775047, 'NC_046156.1 chromosome 3 ': 0.09419176762911394, 'NC_046157.1 chromosome 4 ': 0.07708762653953312, 'NC_046158.1 chromosome 5 ': 0.0669679247658242, 'NC_046159.1 chromosome 6 ': 0.06728507219737542, 'NC_046160.1 chromosome 7 ': 0.055167720327915615, 'NC_046161.1 chromosome 8 ': 0.04862808196716445, 'NC_046162.1 chromosome 9 ': 0.040777321960882254, 'NC_046163.1 chromosome 10 ': 0.04004608673791078, 'NC_046164.1 chromosome 11 ': 0.04158062249955103, 'NC_046165.1 chromosome 12 ': 0.03967190611541461, 'NC_046166.1 chromosome 13 ': 0.03323356119455667, 'NC_046167.1 chromosome 14 ': 0.03457253723949489, 'NC_046168.1 chromosome 15 ': 0.03344427151871997, 'NC_046169.1 chromosome 16 ': 0.01873418740729677, 'NC_046170.1 chromosome 17 ': 0.020451601440965625, 'NC_046171.1 chromosome 18 ': 0.021017624543289214}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Rattus norvegicus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_036323735.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_086040.1 chromosome Y ', 'NW_026947367.1 chromosome Y unlocalized genomic scaffold', 'NW_026947368.1 chromosome Y unlocalized genomic scaffold', 'NW_026947369.1 chromosome Y unlocalized genomic scaffold', 'NW_026947370.1 chromosome Y unlocalized genomic scaffold', 'NW_026947371.1 chromosome Y unlocalized genomic scaffold', 'NW_026947372.1 chromosome Y unlocalized genomic scaffold', 'NW_026947373.1 chromosome Y unlocalized genomic scaffold', 'NW_026947374.1 chromosome Y unlocalized genomic scaffold', 'NW_026947375.1 chromosome Y unlocalized genomic scaffold', 'NW_026947376.1 chromosome Y unlocalized genomic scaffold', 'NW_026947377.1 chromosome Y unlocalized genomic scaffold', 'NW_026947378.1 chromosome Y unlocalized genomic scaffold', 'NW_026947379.1 chromosome Y unlocalized genomic scaffold', 'NW_026947380.1 chromosome Y unlocalized genomic scaffold', 'NW_026947381.1 chromosome Y unlocalized genomic scaffold', 'NW_026947382.1 chromosome Y unlocalized genomic scaffold', 'NW_026947383.1 chromosome Y unlocalized genomic scaffold', 'NW_026947384.1 chromosome Y unlocalized genomic scaffold', 'NW_026947385.1 chromosome Y unlocalized genomic scaffold', 'NW_026947386.1 chromosome Y unlocalized genomic scaffold', 'NW_026947387.1 chromosome Y unlocalized genomic scaffold', 'NW_026947388.1 chromosome Y unlocalized genomic scaffold', 'NW_026947389.1 chromosome Y unlocalized genomic scaffold', 'NW_026947390.1 chromosome Y unlocalized genomic scaffold', 'NW_026947391.1 chromosome Y unlocalized genomic scaffold', 'NW_026947392.1 chromosome Y unlocalized genomic scaffold', 'NW_026947393.1 chromosome Y unlocalized genomic scaffold', 'NW_026947394.1 chromosome Y unlocalized genomic scaffold', 'NW_026947395.1 chromosome Y unlocalized genomic scaffold', 'NW_026947396.1 chromosome Y unlocalized genomic scaffold', 'NW_026947397.1 chromosome Y unlocalized genomic scaffold', 'NW_026947398.1 chromosome Y unlocalized genomic scaffold', 'NW_026947399.1 chromosome Y unlocalized genomic scaffold', 'NW_026947400.1 chromosome Y unlocalized genomic scaffold', 'NW_026947401.1 chromosome Y unlocalized genomic scaffold', 'NW_026947402.1 chromosome Y unlocalized genomic scaffold', 'NW_026947403.1 chromosome Y unlocalized genomic scaffold', 'NW_026947404.1 chromosome Y unlocalized genomic scaffold', 'NW_026947405.1 chromosome Y unlocalized genomic scaffold', 'NW_026947406.1 chromosome Y unlocalized genomic scaffold', 'NW_026947407.1 chromosome Y unlocalized genomic scaffold', 'NW_026947408.1 chromosome Y unlocalized genomic scaffold', 'NW_026947409.1 chromosome Y unlocalized genomic scaffold', 'NW_026947410.1 chromosome Y unlocalized genomic scaffold', 'NW_026947411.1 chromosome Y unlocalized genomic scaffold', 'NW_026947412.1 chromosome Y unlocalized genomic scaffold', 'NC_086039.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_086019.1 chromosome 1 ', 'NC_086020.1 chromosome 2 ', 'NC_086021.1 chromosome 3 ', 'NC_086022.1 chromosome 4 ', 'NC_086023.1 chromosome 5 ', 'NC_086024.1 chromosome 6 ', 'NC_086025.1 chromosome 7 ', 'NC_086026.1 chromosome 8 ', 'NC_086027.1 chromosome 9 ', 'NC_086028.1 chromosome 10 ', 'NC_086029.1 chromosome 11 ', 'NC_086030.1 chromosome 12 ', 'NC_086031.1 chromosome 13 ', 'NC_086032.1 chromosome 14 ', 'NC_086033.1 chromosome 15 ', 'NC_086034.1 chromosome 16 ', 'NC_086035.1 chromosome 17 ', 'NC_086036.1 chromosome 18 ', 'NC_086037.1 chromosome 19 ', 'NC_086038.1 chromosome 20 ', 'NW_026947362.1 chromosome 3 unlocalized genomic scaffold', 'NW_026947363.1 chromosome 3 unlocalized genomic scaffold', 'NW_026947364.1 chromosome 3 unlocalized genomic scaffold', 'NW_026947365.1 chromosome 3 unlocalized genomic scaffold', 'NW_026947366.1 chromosome 3 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_086040.1 chromosome Y ': 59846084, 'NW_026947367.1 chromosome Y unlocalized genomic scaffold': 2057166, 'NW_026947368.1 chromosome Y unlocalized genomic scaffold': 991656, 'NW_026947369.1 chromosome Y unlocalized genomic scaffold': 926565, 'NW_026947370.1 chromosome Y unlocalized genomic scaffold': 903984, 'NW_026947371.1 chromosome Y unlocalized genomic scaffold': 890273, 'NW_026947372.1 chromosome Y unlocalized genomic scaffold': 885491, 'NW_026947373.1 chromosome Y unlocalized genomic scaffold': 793495, 'NW_026947374.1 chromosome Y unlocalized genomic scaffold': 779953, 'NW_026947375.1 chromosome Y unlocalized genomic scaffold': 745465, 'NW_026947376.1 chromosome Y unlocalized genomic scaffold': 720549, 'NW_026947377.1 chromosome Y unlocalized genomic scaffold': 716979, 'NW_026947378.1 chromosome Y unlocalized genomic scaffold': 1913966, 'NW_026947379.1 chromosome Y unlocalized genomic scaffold': 654985, 'NW_026947380.1 chromosome Y unlocalized genomic scaffold': 651350, 'NW_026947381.1 chromosome Y unlocalized genomic scaffold': 647876, 'NW_026947382.1 chromosome Y unlocalized genomic scaffold': 603879, 'NW_026947383.1 chromosome Y unlocalized genomic scaffold': 591746, 'NW_026947384.1 chromosome Y unlocalized genomic scaffold': 574096, 'NW_026947385.1 chromosome Y unlocalized genomic scaffold': 564375, 'NW_026947386.1 chromosome Y unlocalized genomic scaffold': 542769, 'NW_026947387.1 chromosome Y unlocalized genomic scaffold': 523357, 'NW_026947388.1 chromosome Y unlocalized genomic scaffold': 496250, 'NW_026947389.1 chromosome Y unlocalized genomic scaffold': 1696814, 'NW_026947390.1 chromosome Y unlocalized genomic scaffold': 474392, 'NW_026947391.1 chromosome Y unlocalized genomic scaffold': 446190, 'NW_026947392.1 chromosome Y unlocalized genomic scaffold': 429359, 'NW_026947393.1 chromosome Y unlocalized genomic scaffold': 413835, 'NW_026947394.1 chromosome Y unlocalized genomic scaffold': 381568, 'NW_026947395.1 chromosome Y unlocalized genomic scaffold': 350964, 'NW_026947396.1 chromosome Y unlocalized genomic scaffold': 316310, 'NW_026947397.1 chromosome Y unlocalized genomic scaffold': 288775, 'NW_026947398.1 chromosome Y unlocalized genomic scaffold': 285824, 'NW_026947399.1 chromosome Y unlocalized genomic scaffold': 285534, 'NW_026947400.1 chromosome Y unlocalized genomic scaffold': 1654197, 'NW_026947401.1 chromosome Y unlocalized genomic scaffold': 285417, 'NW_026947402.1 chromosome Y unlocalized genomic scaffold': 214303, 'NW_026947403.1 chromosome Y unlocalized genomic scaffold': 184496, 'NW_026947404.1 chromosome Y unlocalized genomic scaffold': 148250, 'NW_026947405.1 chromosome Y unlocalized genomic scaffold': 130679, 'NW_026947406.1 chromosome Y unlocalized genomic scaffold': 120978, 'NW_026947407.1 chromosome Y unlocalized genomic scaffold': 106421, 'NW_026947408.1 chromosome Y unlocalized genomic scaffold': 1487504, 'NW_026947409.1 chromosome Y unlocalized genomic scaffold': 1376544, 'NW_026947410.1 chromosome Y unlocalized genomic scaffold': 1160921, 'NW_026947411.1 chromosome Y unlocalized genomic scaffold': 1105183, 'NW_026947412.1 chromosome Y unlocalized genomic scaffold': 997779, 'NC_086039.1 chromosome X ': 157758123, 'NC_086019.1 chromosome 1 ': 541036360, 'NC_086020.1 chromosome 2 ': 503425416, 'NC_086021.1 chromosome 3 ': 378856620, 'NC_086022.1 chromosome 4 ': 368852962, 'NC_086023.1 chromosome 5 ': 344380610, 'NC_086024.1 chromosome 6 ': 294313306, 'NC_086025.1 chromosome 7 ': 274029192, 'NC_086026.1 chromosome 8 ': 265564872, 'NC_086027.1 chromosome 9 ': 243536300, 'NC_086028.1 chromosome 10 ': 215427616, 'NC_086029.1 chromosome 11 ': 199506734, 'NC_086030.1 chromosome 12 ': 104617662, 'NC_086031.1 chromosome 13 ': 218700572, 'NC_086032.1 chromosome 14 ': 218179712, 'NC_086033.1 chromosome 15 ': 216384338, 'NC_086034.1 chromosome 16 ': 182885816, 'NC_086035.1 chromosome 17 ': 187031608, 'NC_086036.1 chromosome 18 ': 172268044, 'NC_086037.1 chromosome 19 ': 148492490, 'NC_086038.1 chromosome 20 ': 112042296, 'NW_026947362.1 chromosome 3 unlocalized genomic scaffold': 4899856, 'NW_026947363.1 chromosome 3 unlocalized genomic scaffold': 1710804, 'NW_026947364.1 chromosome 3 unlocalized genomic scaffold': 1532044, 'NW_026947365.1 chromosome 3 unlocalized genomic scaffold': 495348, 'NW_026947366.1 chromosome 3 unlocalized genomic scaffold': 206968}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_086040.1 chromosome Y ': 0.010983955517747925, 'NW_026947367.1 chromosome Y unlocalized genomic scaffold': 0.0003775655536062046, 'NW_026947368.1 chromosome Y unlocalized genomic scaffold': 0.0001820053153838409, 'NW_026947369.1 chromosome Y unlocalized genomic scaffold': 0.0001700587250504495, 'NW_026947370.1 chromosome Y unlocalized genomic scaffold': 0.00016591428178919508, 'NW_026947371.1 chromosome Y unlocalized genomic scaffold': 0.00016339780946489327, 'NW_026947372.1 chromosome Y unlocalized genomic scaffold': 0.0001625201367455576, 'NW_026947373.1 chromosome Y unlocalized genomic scaffold': 0.00014563549026124065, 'NW_026947374.1 chromosome Y unlocalized genomic scaffold': 0.00014315003564701153, 'NW_026947375.1 chromosome Y unlocalized genomic scaffold': 0.00013682022035122558, 'NW_026947376.1 chromosome Y unlocalized genomic scaffold': 0.0001322472187880789, 'NW_026947377.1 chromosome Y unlocalized genomic scaffold': 0.00013159199260488603, 'NW_026947378.1 chromosome Y unlocalized genomic scaffold': 0.0003512830915800927, 'NW_026947379.1 chromosome Y unlocalized genomic scaffold': 0.0001202138155738331, 'NW_026947380.1 chromosome Y unlocalized genomic scaffold': 0.00011954665950215072, 'NW_026947381.1 chromosome Y unlocalized genomic scaffold': 0.00011890905284657312, 'NW_026947382.1 chromosome Y unlocalized genomic scaffold': 0.00011083398663314542, 'NW_026947383.1 chromosome Y unlocalized genomic scaffold': 0.00010860713529401963, 'NW_026947384.1 chromosome Y unlocalized genomic scaffold': 0.00010536771172725373, 'NW_026947385.1 chromosome Y unlocalized genomic scaffold': 0.0001035835510194616, 'NW_026947386.1 chromosome Y unlocalized genomic scaffold': 9.961805608554977e-05, 'NW_026947387.1 chromosome Y unlocalized genomic scaffold': 9.605524077234527e-05, 'NW_026947388.1 chromosome Y unlocalized genomic scaffold': 9.108011019872925e-05, 'NW_026947389.1 chromosome Y unlocalized genomic scaffold': 0.00031142772011435077, 'NW_026947390.1 chromosome Y unlocalized genomic scaffold': 8.706836400482734e-05, 'NW_026947391.1 chromosome Y unlocalized genomic scaffold': 8.189226069434963e-05, 'NW_026947392.1 chromosome Y unlocalized genomic scaffold': 7.880315372255152e-05, 'NW_026947393.1 chromosome Y unlocalized genomic scaffold': 7.595392927776548e-05, 'NW_026947394.1 chromosome Y unlocalized genomic scaffold': 7.003174909482866e-05, 'NW_026947395.1 chromosome Y unlocalized genomic scaffold': 6.44147905204772e-05, 'NW_026947396.1 chromosome Y unlocalized genomic scaffold': 5.805450812485652e-05, 'NW_026947397.1 chromosome Y unlocalized genomic scaffold': 5.3000823823955743e-05, 'NW_026947398.1 chromosome Y unlocalized genomic scaffold': 5.245920688653217e-05, 'NW_026947399.1 chromosome Y unlocalized genomic scaffold': 5.240598123019437e-05, 'NW_026947400.1 chromosome Y unlocalized genomic scaffold': 0.0003036059346103926, 'NW_026947401.1 chromosome Y unlocalized genomic scaffold': 5.238450743091326e-05, 'NW_026947402.1 chromosome Y unlocalized genomic scaffold': 3.933247527640962e-05, 'NW_026947403.1 chromosome Y unlocalized genomic scaffold': 3.386179548861411e-05, 'NW_026947404.1 chromosome Y unlocalized genomic scaffold': 2.7209322593373523e-05, 'NW_026947405.1 chromosome Y unlocalized genomic scaffold': 2.3984398429541038e-05, 'NW_026947406.1 chromosome Y unlocalized genomic scaffold': 2.2203908456668748e-05, 'NW_026947407.1 chromosome Y unlocalized genomic scaffold': 1.953216404525736e-05, 'NW_026947408.1 chromosome Y unlocalized genomic scaffold': 0.00027301164381068123, 'NW_026947409.1 chromosome Y unlocalized genomic scaffold': 0.00025264640647536436, 'NW_026947410.1 chromosome Y unlocalized genomic scaffold': 0.00021307166269424476, 'NW_026947411.1 chromosome Y unlocalized genomic scaffold': 0.00020284169154612027, 'NW_026947412.1 chromosome Y unlocalized genomic scaffold': 0.0001831291108795524, 'NC_086039.1 chromosome X ': 0.028954412549289033, 'NC_086019.1 chromosome 1 ': 0.0993000529779735, 'NC_086020.1 chromosome 2 ': 0.09239706270251107, 'NC_086021.1 chromosome 3 ': 0.06953411123247978, 'NC_086022.1 chromosome 4 ': 0.06769807239513892, 'NC_086023.1 chromosome 5 ': 0.06320649654227829, 'NC_086024.1 chromosome 6 ': 0.054017306485505935, 'NC_086025.1 chromosome 7 ': 0.050294426206607026, 'NC_086026.1 chromosome 8 ': 0.04874091245676862, 'NC_086027.1 chromosome 9 ': 0.044697860033029294, 'NC_086028.1 chromosome 10 ': 0.03953888363754061, 'NC_086029.1 chromosome 11 ': 0.03661681676193161, 'NC_086030.1 chromosome 12 ': 0.019201185256812914, 'NC_086031.1 chromosome 13 ': 0.040139591331556916, 'NC_086032.1 chromosome 14 ': 0.040043994382039316, 'NC_086033.1 chromosome 15 ': 0.039714477280239954, 'NC_086034.1 chromosome 16 ': 0.03356626755680508, 'NC_086035.1 chromosome 17 ': 0.03432717273004641, 'NC_086036.1 chromosome 18 ': 0.031617516234235844, 'NC_086037.1 chromosome 19 ': 0.02725382841890922, 'NC_086038.1 chromosome 20 ': 0.020563878421357464, 'NW_026947362.1 chromosome 3 unlocalized genomic scaffold': 0.0008993036260713445, 'NW_026947363.1 chromosome 3 unlocalized genomic scaffold': 0.00031399539919078445, 'NW_026947364.1 chromosome 3 unlocalized genomic scaffold': 0.0002811863704771828, 'NW_026947365.1 chromosome 3 unlocalized genomic scaffold': 9.09145600538441e-05, 'NW_026947366.1 chromosome 3 unlocalized genomic scaffold': 3.7986233244555355e-05}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999998
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Budorcas taxicolor
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_023091745.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_068935.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_068910.1 chromosome 1 ', 'NC_068911.1 chromosome 2 ', 'NC_068912.1 chromosome 3 ', 'NC_068913.1 chromosome 4 ', 'NC_068914.1 chromosome 5 ', 'NC_068915.1 chromosome 6 ', 'NC_068916.1 chromosome 7 ', 'NC_068917.1 chromosome 8 ', 'NC_068918.1 chromosome 9 ', 'NC_068919.1 chromosome 10 ', 'NC_068920.1 chromosome 11 ', 'NC_068921.1 chromosome 12 ', 'NC_068922.1 chromosome 13 ', 'NC_068923.1 chromosome 14 ', 'NC_068924.1 chromosome 15 ', 'NC_068925.1 chromosome 16 ', 'NC_068926.1 chromosome 17 ', 'NC_068927.1 chromosome 18 ', 'NC_068928.1 chromosome 19 ', 'NC_068929.1 chromosome 20 ', 'NC_068930.1 chromosome 21 ', 'NC_068931.1 chromosome 22 ', 'NC_068932.1 chromosome 23 ', 'NC_068933.1 chromosome 24 ', 'NC_068934.1 chromosome 25 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_068935.1 chromosome X ': 293495872, 'NC_068910.1 chromosome 1 ': 443363910, 'NC_068911.1 chromosome 2 ': 361581120, 'NC_068912.1 chromosome 3 ': 242514874, 'NC_068913.1 chromosome 4 ': 243786826, 'NC_068914.1 chromosome 5 ': 328459970, 'NC_068915.1 chromosome 6 ': 234941170, 'NC_068916.1 chromosome 7 ': 219495396, 'NC_068917.1 chromosome 8 ': 232665740, 'NC_068918.1 chromosome 9 ': 190522314, 'NC_068919.1 chromosome 10 ': 202531878, 'NC_068920.1 chromosome 11 ': 332203558, 'NC_068921.1 chromosome 12 ': 174640522, 'NC_068922.1 chromosome 13 ': 166773768, 'NC_068923.1 chromosome 14 ': 190390618, 'NC_068924.1 chromosome 15 ': 163768502, 'NC_068925.1 chromosome 16 ': 163692860, 'NC_068926.1 chromosome 17 ': 146250216, 'NC_068927.1 chromosome 18 ': 136107162, 'NC_068928.1 chromosome 19 ': 125218408, 'NC_068929.1 chromosome 20 ': 149592478, 'NC_068930.1 chromosome 21 ': 148734572, 'NC_068931.1 chromosome 22 ': 125252580, 'NC_068932.1 chromosome 23 ': 102628326, 'NC_068933.1 chromosome 24 ': 89805930, 'NC_068934.1 chromosome 25 ': 104042192}

{'labels': 0, 'species': 'Apodemus sylvaticus', 'sampled_chromosomes': ['NC_067486.1 chromosome 15 ', 'NC_067472.1 chromosome 1 ', 'NC_067481.1 chromosome 10 ', 'NC_067483.1 chromosome 12 ', 'NW_026262998.1 chromosome Y unlocalized genomic scaffold', 'NC_067481.1 chromosome 10 ', 'NC_067472.1 chromosome 1 ', 'NC_067479.1 chromosome 8 ', 'NC_067474.1 chromosome 3 ', 'NC_067479.1 chromosome 8 '], 'chunks': ['AAAACTAGTT', 'GGTGGAGACC', 'GATGAGTCAC', 'TCAGTCACCT', 'ATTCTGCAAG', 'GGCCTTAACG', 'TATAATTCAA', 'AATTCTTTCC', 'AGTGAGCTAG', 'GCAGTGTTCA'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Rattus rattus', 'sampled_chromosomes': ['NC_046171.1 chromosome 18 ', 'NC_046166.1 chromosome 13 ', 'NC_046156.1 chromosome 3 ', 'NC_046162.1 chromosome 9 ', 'NC_046172.1 chromosome X ', 'NC_046156.1 chromosome 3 ', 'NC_046154.1 chromosome 1 ', 'NC_046172.1 chromosome X ', 'NC_046161.1 chromosome 8 ', 'NC_046161.1 chromosome 8 '], 'chunks': ['AAGGCAAAGA', 'ATACTGATAA', 'AAACGGTGCT', 'CCTGTCATAG', 'AATCCATTCA', 'GGAGTTTGGA', 'GATGGTTTAC', 'AATCCAATTT', 'TGAAGAAGGA', 'GATTGCACAG'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 0, 'species': 'Rattus norvegicus', 'sampled_chromosomes': ['NC_086021.1 chromosome 3 ', 'NC_086022.1 chromosome 4 ', 'NC_086036.1 chromosome 18 ', 'NC_086019.1 chromosome 1 ', 'NC_086021.1 chromosome 3 ', 'NC_086019.1 chromosome 1 ', 'NC_086031.1 chromosome 13 ', 'NC_086024.1 chromosome 6 ', 'NC_086030.1 chromosome 12 ', 'NC_086040.1 chromosome Y '], 'chunks': ['TTTTCTGGTA', 'GCTTCACTCC', 'AGAATTCTGG', 'TCTTTCCCCT', 'CTCTCAGGTT', 'ACTCCTCCTG', 'AGACCTAAGT', 'TCTAACAGCT', 'CTAATGAGGC', 'TGAAATTGTT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Budorcas taxicolor', 'sampled_chromosomes': ['NC_068928.1 chromosome 19 ', 'NC_068911.1 chromosome 2 ', 'NC_068920.1 chromosome 11 ', 'NC_068922.1 chromosome 13 ', 'NC_068933.1 chromosome 24 ', 'NC_068920.1 chromosome 11 ', 'NC_068927.1 chromosome 18 ', 'NC_068928.1 chromosome 19 ', 'NC_068915.1 chromosome 6 ', 'NC_068926.1 chromosome 17 '], 'chunks': ['GGAGGGGGTC', 'ACCCCATGGA', 'TCGTGTACTA', 'TAAATTAGTT', 'CAACTGGAAA', 'CTCTCCCCTT', 'AAAGCCCCAA', 'TTTGCCTTCT', 'TGTTTTAAGC', 'CCCTGGAGGA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Ovis aries', 'sampled_chromosomes': ['NC_056068.1 chromosome 15 ', 'NC_056062.1 chromosome 9 ', 'NC_056063.1 chromosome 10 ', 'NC_056055.1 chromosome 2 ', 'NC_056066.1 chromosome 13 ', 'NC_056062.1 chromosome 9 ', 'NC_056070.1 chromosome 17 ', 'NC_056065.1 chromosome 12 ', 'NC_082741.1 chromosome Y ', 'NC_056056.1 chromosome 3 '], 'chunks': ['CAGCACACCA', 'CTCCAGGGTA', 'ATTTTAAAAT', 'GCTGGCTCTA', 'GTGTGACCCT', 'GGGCTTGGGG', 'CCCCCTGCCC', 'AGGCCAGGGA', 'GCATAAAACA', 'TATTGGAGGT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_027914.1 chromosome Y ': 11253682, 'NC_041774.1 chromosome X ': 153388924, 'NW_021160381.1 chromosome X unlocalized genomic scaffold': 48696, 'NW_021160382.1 chromosome X unlocalized genomic scaffold': 50511, 'NW_021160383.1 chromosome X unlocalized genomic scaffold': 68997, 'NW_021160384.1 chromosome X unlocalized genomic scaffold': 79627, 'NC_041754.1 chromosome 1 ': 447233884, 'NC_041755.1 chromosome 2 ': 392395928, 'NC_041756.1 chromosome 3 ': 370577894, 'NC_041757.1 chromosome 4 ': 339926080, 'NC_041758.1 chromosome 5 ': 374634384, 'NC_041759.1 chromosome 6 ': 358171132, 'NC_041760.1 chromosome 7 ': 339737128, 'NC_041761.1 chromosome 8 ': 291358640, 'NC_041762.1 chromosome 9 ': 268248332, 'NC_041763.1 chromosome 10 ': 199035516, 'NC_041764.1 chromosome 11 ': 266132172, 'NC_041765.1 chromosome 12 ': 260087712, 'NC_041766.1 chromosome 13 ': 217474260, 'NC_041767.1 chromosome 14 ': 256112612, 'NC_041768.1 chromosome 15 ': 226567208, 'NC_041769.1 chromosome 16 ': 159254128, 'NC_041770.1 chromosome 17 ': 190866918, 'NC_041771.1 chromosome 18 ': 148948086, 'NC_041772.1 chromosome 19 ': 116630466, 'NC_041773.1 chromosome 20 ': 154274990, 'NW_021160094.1 chromosome 1 unlocalized genomic scaffold': 53360, 'NW_021160095.1 chromosome 1 unlocalized genomic scaffold': 65160, 'NW_021160096.1 chromosome 1 unlocalized genomic scaffold': 67096, 'NW_021160097.1 chromosome 1 unlocalized genomic scaffold': 74102, 'NW_021160098.1 chromosome 1 unlocalized genomic scaffold': 79986, 'NW_021160099.1 chromosome 1 unlocalized genomic scaffold': 80876, 'NW_021160100.1 chromosome 1 unlocalized genomic scaffold': 87980, 'NW_021160101.1 chromosome 1 unlocalized genomic scaffold': 97790, 'NW_021160102.1 chromosome 1 unlocalized genomic scaffold': 100376, 'NW_021160103.1 chromosome 1 unlocalized genomic scaffold': 102726, 'NW_021160104.1 chromosome 1 unlocalized genomic scaffold': 71758, 'NW_021160105.1 chromosome 1 unlocalized genomic scaffold': 109720, 'NW_021160106.1 chromosome 1 unlocalized genomic scaffold': 111082, 'NW_021160107.1 chromosome 1 unlocalized genomic scaffold': 111164, 'NW_021160108.1 chromosome 1 unlocalized genomic scaffold': 119880, 'NW_021160109.1 chromosome 1 unlocalized genomic scaffold': 164610, 'NW_021160110.1 chromosome 1 unlocalized genomic scaffold': 236270, 'NW_021160111.1 chromosome 1 unlocalized genomic scaffold': 266050, 'NW_021160112.1 chromosome 1 unlocalized genomic scaffold': 104152, 'NW_021160113.1 chromosome 1 unlocalized genomic scaffold': 232668, 'NW_021160114.1 chromosome 1 unlocalized genomic scaffold': 131828, 'NW_021160115.1 chromosome 2 unlocalized genomic scaffold': 61172, 'NW_021160116.1 chromosome 2 unlocalized genomic scaffold': 70782, 'NW_021160117.1 chromosome 2 unlocalized genomic scaffold': 81312, 'NW_021160118.1 chromosome 2 unlocalized genomic scaffold': 102148, 'NW_021160119.1 chromosome 2 unlocalized genomic scaffold': 96684, 'NW_021160120.1 chromosome 2 unlocalized genomic scaffold': 105902, 'NW_021160121.1 chromosome 2 unlocalized genomic scaffold': 172402, 'NW_021160122.1 chromosome 2 unlocalized genomic scaffold': 184080, 'NW_021160123.1 chromosome 2 unlocalized genomic scaffold': 105868, 'NW_021160124.1 chromosome 2 unlocalized genomic scaffold': 109560, 'NW_021160125.1 chromosome 3 unlocalized genomic scaffold': 50600, 'NW_021160126.1 chromosome 3 unlocalized genomic scaffold': 58698, 'NW_021160127.1 chromosome 3 unlocalized genomic scaffold': 58890, 'NW_021160128.1 chromosome 3 unlocalized genomic scaffold': 59426, 'NW_021160129.1 chromosome 3 unlocalized genomic scaffold': 72976, 'NW_021160130.1 chromosome 3 unlocalized genomic scaffold': 59576, 'NW_021160131.1 chromosome 3 unlocalized genomic scaffold': 85088, 'NW_021160132.1 chromosome 3 unlocalized genomic scaffold': 87674, 'NW_021160133.1 chromosome 3 unlocalized genomic scaffold': 102124, 'NW_021160134.1 chromosome 3 unlocalized genomic scaffold': 108614, 'NW_021160135.1 chromosome 3 unlocalized genomic scaffold': 109520, 'NW_021160136.1 chromosome 3 unlocalized genomic scaffold': 119482, 'NW_021160137.1 chromosome 3 unlocalized genomic scaffold': 140592, 'NW_021160138.1 chromosome 3 unlocalized genomic scaffold': 145282, 'NW_021160139.1 chromosome 3 unlocalized genomic scaffold': 189430, 'NW_021160140.1 chromosome 3 unlocalized genomic scaffold': 260536, 'NW_021160141.1 chromosome 3 unlocalized genomic scaffold': 268316, 'NW_021160142.1 chromosome 3 unlocalized genomic scaffold': 95628, 'NW_021160143.1 chromosome 3 unlocalized genomic scaffold': 61006, 'NW_021160144.1 chromosome 3 unlocalized genomic scaffold': 2459778, 'NW_021160145.1 chromosome 4 unlocalized genomic scaffold': 53750, 'NW_021160146.1 chromosome 4 unlocalized genomic scaffold': 54022, 'NW_021160147.1 chromosome 4 unlocalized genomic scaffold': 60074, 'NW_021160148.1 chromosome 4 unlocalized genomic scaffold': 68638, 'NW_021160149.1 chromosome 4 unlocalized genomic scaffold': 72170, 'NW_021160150.1 chromosome 4 unlocalized genomic scaffold': 74996, 'NW_021160151.1 chromosome 4 unlocalized genomic scaffold': 91412, 'NW_021160152.1 chromosome 4 unlocalized genomic scaffold': 94276, 'NW_021160153.1 chromosome 4 unlocalized genomic scaffold': 104504, 'NW_021160154.1 chromosome 4 unlocalized genomic scaffold': 108742, 'NW_021160155.1 chromosome 4 unlocalized genomic scaffold': 109060, 'NW_021160156.1 chromosome 4 unlocalized genomic scaffold': 109358, 'NW_021160157.1 chromosome 4 unlocalized genomic scaffold': 120010, 'NW_021160158.1 chromosome 4 unlocalized genomic scaffold': 150730, 'NW_021160159.1 chromosome 4 unlocalized genomic scaffold': 171586, 'NW_021160160.1 chromosome 4 unlocalized genomic scaffold': 180604, 'NW_021160161.1 chromosome 4 unlocalized genomic scaffold': 1476784, 'NW_021160162.1 chromosome 5 unlocalized genomic scaffold': 53370, 'NW_021160163.1 chromosome 5 unlocalized genomic scaffold': 59582, 'NW_021160164.1 chromosome 5 unlocalized genomic scaffold': 65280, 'NW_021160165.1 chromosome 5 unlocalized genomic scaffold': 68444, 'NW_021160166.1 chromosome 5 unlocalized genomic scaffold': 71034, 'NW_021160167.1 chromosome 5 unlocalized genomic scaffold': 75676, 'NW_021160168.1 chromosome 5 unlocalized genomic scaffold': 83302, 'NW_021160169.1 chromosome 5 unlocalized genomic scaffold': 83682, 'NW_021160170.1 chromosome 5 unlocalized genomic scaffold': 72702, 'NW_021160171.1 chromosome 5 unlocalized genomic scaffold': 97876, 'NW_021160172.1 chromosome 5 unlocalized genomic scaffold': 112884, 'NW_021160173.1 chromosome 5 unlocalized genomic scaffold': 137538, 'NW_021160174.1 chromosome 5 unlocalized genomic scaffold': 207186, 'NW_021160175.1 chromosome 5 unlocalized genomic scaffold': 370286, 'NW_021160176.1 chromosome 5 unlocalized genomic scaffold': 78186, 'NW_021160177.1 chromosome 6 unlocalized genomic scaffold': 55206, 'NW_021160178.1 chromosome 6 unlocalized genomic scaffold': 56482, 'NW_021160179.1 chromosome 6 unlocalized genomic scaffold': 77752, 'NW_021160180.1 chromosome 6 unlocalized genomic scaffold': 78786, 'NW_021160181.1 chromosome 6 unlocalized genomic scaffold': 94664, 'NW_021160182.1 chromosome 6 unlocalized genomic scaffold': 116168, 'NW_021160183.1 chromosome 6 unlocalized genomic scaffold': 115996, 'NW_021160184.1 chromosome 6 unlocalized genomic scaffold': 122600, 'NW_021160185.1 chromosome 6 unlocalized genomic scaffold': 124252, 'NW_021160186.1 chromosome 6 unlocalized genomic scaffold': 128982, 'NW_021160187.1 chromosome 6 unlocalized genomic scaffold': 152812, 'NW_021160188.1 chromosome 6 unlocalized genomic scaffold': 165900, 'NW_021160189.1 chromosome 6 unlocalized genomic scaffold': 202668, 'NW_021160190.1 chromosome 6 unlocalized genomic scaffold': 71464, 'NW_021160191.1 chromosome 7 unlocalized genomic scaffold': 55718, 'NW_021160192.1 chromosome 7 unlocalized genomic scaffold': 57596, 'NW_021160193.1 chromosome 7 unlocalized genomic scaffold': 62324, 'NW_021160194.1 chromosome 7 unlocalized genomic scaffold': 71652, 'NW_021160195.1 chromosome 7 unlocalized genomic scaffold': 82732, 'NW_021160196.1 chromosome 7 unlocalized genomic scaffold': 92210, 'NW_021160197.1 chromosome 7 unlocalized genomic scaffold': 103624, 'NW_021160198.1 chromosome 7 unlocalized genomic scaffold': 107664, 'NW_021160199.1 chromosome 7 unlocalized genomic scaffold': 111840, 'NW_021160200.1 chromosome 7 unlocalized genomic scaffold': 117998, 'NW_021160201.1 chromosome 7 unlocalized genomic scaffold': 122892, 'NW_021160202.1 chromosome 7 unlocalized genomic scaffold': 130958, 'NW_021160203.1 chromosome 7 unlocalized genomic scaffold': 144412, 'NW_021160204.1 chromosome 7 unlocalized genomic scaffold': 145672, 'NW_021160205.1 chromosome 7 unlocalized genomic scaffold': 146494, 'NW_021160206.1 chromosome 7 unlocalized genomic scaffold': 167516, 'NW_021160207.1 chromosome 7 unlocalized genomic scaffold': 197640, 'NW_021160208.1 chromosome 7 unlocalized genomic scaffold': 63536, 'NW_021160209.1 chromosome 8 unlocalized genomic scaffold': 1339966, 'NW_021160210.1 chromosome 8 unlocalized genomic scaffold': 64388, 'NW_021160211.1 chromosome 8 unlocalized genomic scaffold': 266624, 'NW_021160212.1 chromosome 8 unlocalized genomic scaffold': 70546, 'NW_021160213.1 chromosome 8 unlocalized genomic scaffold': 71564, 'NW_021160214.1 chromosome 8 unlocalized genomic scaffold': 72336, 'NW_021160215.1 chromosome 8 unlocalized genomic scaffold': 76816, 'NW_021160216.1 chromosome 8 unlocalized genomic scaffold': 57208, 'NW_021160217.1 chromosome 8 unlocalized genomic scaffold': 91688, 'NW_021160218.1 chromosome 8 unlocalized genomic scaffold': 108598, 'NW_021160219.1 chromosome 8 unlocalized genomic scaffold': 119742, 'NW_021160220.1 chromosome 8 unlocalized genomic scaffold': 133438, 'NW_021160221.1 chromosome 8 unlocalized genomic scaffold': 141728, 'NW_021160222.1 chromosome 8 unlocalized genomic scaffold': 152752, 'NW_021160223.1 chromosome 8 unlocalized genomic scaffold': 166628, 'NW_021160224.1 chromosome 8 unlocalized genomic scaffold': 59442, 'NW_021160225.1 chromosome 8 unlocalized genomic scaffold': 107664, 'NW_021160226.1 chromosome 9 unlocalized genomic scaffold': 72062, 'NW_021160227.1 chromosome 9 unlocalized genomic scaffold': 79466, 'NW_021160228.1 chromosome 9 unlocalized genomic scaffold': 95666, 'NW_021160229.1 chromosome 9 unlocalized genomic scaffold': 95960, 'NW_021160230.1 chromosome 9 unlocalized genomic scaffold': 104164, 'NW_021160231.1 chromosome 9 unlocalized genomic scaffold': 108994, 'NW_021160232.1 chromosome 9 unlocalized genomic scaffold': 113432, 'NW_021160233.1 chromosome 9 unlocalized genomic scaffold': 129284, 'NW_021160234.1 chromosome 9 unlocalized genomic scaffold': 131092, 'NW_021160235.1 chromosome 9 unlocalized genomic scaffold': 133422, 'NW_021160236.1 chromosome 9 unlocalized genomic scaffold': 155598, 'NW_021160237.1 chromosome 9 unlocalized genomic scaffold': 171448, 'NW_021160238.1 chromosome 9 unlocalized genomic scaffold': 208894, 'NW_021160239.1 chromosome 9 unlocalized genomic scaffold': 58324, 'NW_021160240.1 chromosome 9 unlocalized genomic scaffold': 95108, 'NW_021160241.1 chromosome 10 unlocalized genomic scaffold': 58980, 'NW_021160242.1 chromosome 10 unlocalized genomic scaffold': 59102, 'NW_021160243.1 chromosome 10 unlocalized genomic scaffold': 63042, 'NW_021160244.1 chromosome 10 unlocalized genomic scaffold': 70440, 'NW_021160245.1 chromosome 10 unlocalized genomic scaffold': 87524, 'NW_021160246.1 chromosome 10 unlocalized genomic scaffold': 87336, 'NW_021160247.1 chromosome 10 unlocalized genomic scaffold': 90528, 'NW_021160248.1 chromosome 10 unlocalized genomic scaffold': 149502, 'NW_021160249.1 chromosome 10 unlocalized genomic scaffold': 151384, 'NW_021160250.1 chromosome 10 unlocalized genomic scaffold': 128602, 'NW_021160251.1 chromosome 10 unlocalized genomic scaffold': 168852, 'NW_021160252.1 chromosome 10 unlocalized genomic scaffold': 177270, 'NW_021160253.1 chromosome 10 unlocalized genomic scaffold': 231098, 'NW_021160254.1 chromosome 10 unlocalized genomic scaffold': 63478, 'NW_021160255.1 chromosome 11 unlocalized genomic scaffold': 56152, 'NW_021160256.1 chromosome 11 unlocalized genomic scaffold': 61948, 'NW_021160257.1 chromosome 11 unlocalized genomic scaffold': 68188, 'NW_021160258.1 chromosome 11 unlocalized genomic scaffold': 71672, 'NW_021160259.1 chromosome 11 unlocalized genomic scaffold': 73986, 'NW_021160260.1 chromosome 11 unlocalized genomic scaffold': 85206, 'NW_021160261.1 chromosome 11 unlocalized genomic scaffold': 89586, 'NW_021160262.1 chromosome 11 unlocalized genomic scaffold': 73802, 'NW_021160263.1 chromosome 11 unlocalized genomic scaffold': 105250, 'NW_021160264.1 chromosome 11 unlocalized genomic scaffold': 130372, 'NW_021160265.1 chromosome 11 unlocalized genomic scaffold': 140178, 'NW_021160266.1 chromosome 11 unlocalized genomic scaffold': 150052, 'NW_021160267.1 chromosome 11 unlocalized genomic scaffold': 173168, 'NW_021160268.1 chromosome 11 unlocalized genomic scaffold': 135452, 'NW_021160269.1 chromosome 12 unlocalized genomic scaffold': 60922, 'NW_021160270.1 chromosome 12 unlocalized genomic scaffold': 69656, 'NW_021160271.1 chromosome 12 unlocalized genomic scaffold': 69516, 'NW_021160272.1 chromosome 12 unlocalized genomic scaffold': 69986, 'NW_021160273.1 chromosome 12 unlocalized genomic scaffold': 80400, 'NW_021160274.1 chromosome 12 unlocalized genomic scaffold': 70390, 'NW_021160275.1 chromosome 12 unlocalized genomic scaffold': 78320, 'NW_021160276.1 chromosome 13 unlocalized genomic scaffold': 107016, 'NW_021160277.1 chromosome 13 unlocalized genomic scaffold': 89706, 'NW_021160278.1 chromosome 13 unlocalized genomic scaffold': 111278, 'NW_021160279.1 chromosome 13 unlocalized genomic scaffold': 131980, 'NW_021160280.1 chromosome 13 unlocalized genomic scaffold': 115084, 'NW_021160281.1 chromosome 13 unlocalized genomic scaffold': 179740, 'NW_021160282.1 chromosome 13 unlocalized genomic scaffold': 247430, 'NW_021160283.1 chromosome 14 unlocalized genomic scaffold': 65100, 'NW_021160284.1 chromosome 14 unlocalized genomic scaffold': 69586, 'NW_021160285.1 chromosome 14 unlocalized genomic scaffold': 89210, 'NW_021160286.1 chromosome 14 unlocalized genomic scaffold': 73786, 'NW_021160287.1 chromosome 14 unlocalized genomic scaffold': 75150, 'NW_021160288.1 chromosome 14 unlocalized genomic scaffold': 75662, 'NW_021160289.1 chromosome 14 unlocalized genomic scaffold': 75322, 'NW_021160290.1 chromosome 14 unlocalized genomic scaffold': 88840, 'NW_021160291.1 chromosome 14 unlocalized genomic scaffold': 90562, 'NW_021160292.1 chromosome 14 unlocalized genomic scaffold': 92512, 'NW_021160293.1 chromosome 14 unlocalized genomic scaffold': 105660, 'NW_021160294.1 chromosome 14 unlocalized genomic scaffold': 159260, 'NW_021160295.1 chromosome 14 unlocalized genomic scaffold': 165086, 'NW_021160296.1 chromosome 14 unlocalized genomic scaffold': 102466, 'NW_021160297.1 chromosome 14 unlocalized genomic scaffold': 112454, 'NW_021160298.1 chromosome 14 unlocalized genomic scaffold': 54490, 'NW_021160299.1 chromosome 14 unlocalized genomic scaffold': 59800, 'NW_021160300.1 chromosome 14 unlocalized genomic scaffold': 124546, 'NW_021160301.1 chromosome 15 unlocalized genomic scaffold': 70822, 'NW_021160302.1 chromosome 15 unlocalized genomic scaffold': 72340, 'NW_021160303.1 chromosome 15 unlocalized genomic scaffold': 77424, 'NW_021160304.1 chromosome 15 unlocalized genomic scaffold': 79554, 'NW_021160305.1 chromosome 15 unlocalized genomic scaffold': 80612, 'NW_021160306.1 chromosome 15 unlocalized genomic scaffold': 78932, 'NW_021160307.1 chromosome 15 unlocalized genomic scaffold': 105374, 'NW_021160308.1 chromosome 15 unlocalized genomic scaffold': 107850, 'NW_021160309.1 chromosome 15 unlocalized genomic scaffold': 107852, 'NW_021160310.1 chromosome 15 unlocalized genomic scaffold': 116524, 'NW_021160311.1 chromosome 15 unlocalized genomic scaffold': 157496, 'NW_021160312.1 chromosome 15 unlocalized genomic scaffold': 176838, 'NW_021160313.1 chromosome 15 unlocalized genomic scaffold': 189254, 'NW_021160314.1 chromosome 15 unlocalized genomic scaffold': 55582, 'NW_021160315.1 chromosome 16 unlocalized genomic scaffold': 56354, 'NW_021160316.1 chromosome 16 unlocalized genomic scaffold': 67768, 'NW_021160317.1 chromosome 16 unlocalized genomic scaffold': 69490, 'NW_021160318.1 chromosome 16 unlocalized genomic scaffold': 100876, 'NW_021160319.1 chromosome 16 unlocalized genomic scaffold': 86874, 'NW_021160320.1 chromosome 16 unlocalized genomic scaffold': 105104, 'NW_021160321.1 chromosome 16 unlocalized genomic scaffold': 108116, 'NW_021160322.1 chromosome 16 unlocalized genomic scaffold': 108142, 'NW_021160323.1 chromosome 16 unlocalized genomic scaffold': 108698, 'NW_021160324.1 chromosome 16 unlocalized genomic scaffold': 127222, 'NW_021160325.1 chromosome 16 unlocalized genomic scaffold': 130300, 'NW_021160326.1 chromosome 16 unlocalized genomic scaffold': 130280, 'NW_021160327.1 chromosome 16 unlocalized genomic scaffold': 131958, 'NW_021160328.1 chromosome 16 unlocalized genomic scaffold': 126650, 'NW_021160329.1 chromosome 16 unlocalized genomic scaffold': 107402, 'NW_021160330.1 chromosome 16 unlocalized genomic scaffold': 54458, 'NW_021160331.1 chromosome 17 unlocalized genomic scaffold': 51894, 'NW_021160332.1 chromosome 17 unlocalized genomic scaffold': 363778, 'NW_021160333.1 chromosome 17 unlocalized genomic scaffold': 62182, 'NW_021160334.1 chromosome 17 unlocalized genomic scaffold': 62332, 'NW_021160335.1 chromosome 17 unlocalized genomic scaffold': 62368, 'NW_021160336.1 chromosome 17 unlocalized genomic scaffold': 62500, 'NW_021160337.1 chromosome 17 unlocalized genomic scaffold': 87220, 'NW_021160338.1 chromosome 17 unlocalized genomic scaffold': 75046, 'NW_021160339.1 chromosome 17 unlocalized genomic scaffold': 77082, 'NW_021160340.1 chromosome 17 unlocalized genomic scaffold': 90186, 'NW_021160341.1 chromosome 17 unlocalized genomic scaffold': 92612, 'NW_021160342.1 chromosome 17 unlocalized genomic scaffold': 92694, 'NW_021160343.1 chromosome 17 unlocalized genomic scaffold': 100750, 'NW_021160344.1 chromosome 17 unlocalized genomic scaffold': 118052, 'NW_021160345.1 chromosome 17 unlocalized genomic scaffold': 123372, 'NW_021160346.1 chromosome 17 unlocalized genomic scaffold': 123814, 'NW_021160347.1 chromosome 17 unlocalized genomic scaffold': 330538, 'NW_021160348.1 chromosome 17 unlocalized genomic scaffold': 54250, 'NW_021160349.1 chromosome 17 unlocalized genomic scaffold': 30708, 'NW_021160350.1 chromosome 18 unlocalized genomic scaffold': 64600, 'NW_021160351.1 chromosome 18 unlocalized genomic scaffold': 74290, 'NW_021160352.1 chromosome 18 unlocalized genomic scaffold': 75328, 'NW_021160353.1 chromosome 18 unlocalized genomic scaffold': 82352, 'NW_021160354.1 chromosome 18 unlocalized genomic scaffold': 83948, 'NW_021160355.1 chromosome 18 unlocalized genomic scaffold': 111108, 'NW_021160356.1 chromosome 18 unlocalized genomic scaffold': 152632, 'NW_021160357.1 chromosome 19 unlocalized genomic scaffold': 60900, 'NW_021160358.1 chromosome 19 unlocalized genomic scaffold': 78910, 'NW_021160359.1 chromosome 19 unlocalized genomic scaffold': 82112, 'NW_021160360.1 chromosome 19 unlocalized genomic scaffold': 88364, 'NW_021160361.1 chromosome 19 unlocalized genomic scaffold': 94152, 'NW_021160362.1 chromosome 19 unlocalized genomic scaffold': 107334, 'NW_021160363.1 chromosome 19 unlocalized genomic scaffold': 121856, 'NW_021160364.1 chromosome 19 unlocalized genomic scaffold': 123634, 'NW_021160365.1 chromosome 19 unlocalized genomic scaffold': 132866, 'NW_021160366.1 chromosome 19 unlocalized genomic scaffold': 142514, 'NW_021160367.1 chromosome 19 unlocalized genomic scaffold': 152780, 'NW_021160368.1 chromosome 19 unlocalized genomic scaffold': 157878, 'NW_021160369.1 chromosome 19 unlocalized genomic scaffold': 163558, 'NW_021160370.1 chromosome 19 un

{'labels': 0, 'species': 'Macaca mulatta', 'sampled_chromosomes': ['NC_041768.1 chromosome 15 ', 'NC_027914.1 chromosome Y ', 'NC_041766.1 chromosome 13 ', 'NC_041773.1 chromosome 20 ', 'NC_041770.1 chromosome 17 ', 'NC_041763.1 chromosome 10 ', 'NC_041756.1 chromosome 3 ', 'NC_041762.1 chromosome 9 ', 'NC_041759.1 chromosome 6 ', 'NC_041766.1 chromosome 13 '], 'chunks': ['TGCCTGACTG', 'GGATAAATTG', 'TGAGATATCG', 'GCTCGCAGCG', 'GACACGTTCT', 'ACAGCCTTTT', 'AATAGTATTT', 'CCTAGCCCAA', 'GCTATGTTTC', 'ATCTCATTTC'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Piliocolobus tephrosceles', 'sampled_chromosomes': ['NC_045442.1 chromosome 9 ', 'NC_045438.1 chromosome 5 ', 'NC_045451.1 chromosome 18 ', 'NC_045456.1 chromosome Y ', 'NC_045445.1 chromosome 12 ', 'NC_045441.1 chromosome 8 ', 'NC_045439.1 chromosome 6 ', 'NC_045440.1 chromosome 7 ', 'NC_045446.1 chromosome 13 ', 'NC_045436.1 chromosome 3 '], 'chunks': ['TTTCCGGGAA', 'TCGCTCTGTC', 'AAGGGTGTAT', 'TGCACCACTG', 'TCACTGTCAG', 'TGAAGTAATA', 'TTAATTCCTG', 'CCCGCGGCCG', 'TCTGGGTGGG', 'CAGCAAAAAA'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Tursiops truncatus', 'sampled_chromosomes': ['NC_047044.1 chromosome 11 ', 'NC_047038.1 chromosome 5 ', 'NC_047043.1 chromosome 10 ', 'NC_047037.1 chromosome 4 ', 'NC_047047.1 chromosome 14 ', 'NC_047037.1 chromosome 4 ', 'NC_047036.1 chromosome 3 ', 'NW_022983135.1 chromosome Y unlocalized genomic scaffold', 'NC_047043.1 chromosome 10 ', 'NC_047041.1 chromosome 8 '], 'chunks': ['AGTGTTTATA', 'TGTGACCCAA', 'GGCCACAGAA', 'TTTTTTTTTT', 'ATTCATTTTG', 'CTGCGCTTCC', 'AATACTCTTA', 'GCTAGAGAAG', 'AGGTTTTTGG', 'AATTCTCCTT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Bos javanicus', 'sampled_chromosomes': ['NC_083882.1 chromosome 15 ', 'NC_083884.1 chromosome 17 ', 'NC_083868.1 chromosome 1 ', 'NC_083874.1 chromosome 7 ', 'NC_083883.1 chromosome 16 ', 'NC_083895.1 chromosome 28 ', 'NC_083871.1 chromosome 4 ', 'NC_083873.1 chromosome 6 ', 'NC_083869.1 chromosome 2 ', 'NC_083881.1 chromosome 14 '], 'chunks': ['GCTAAACTGA', 'AGGTCTCCTG', 'TAATAGTAAT', 'CTAAACTTTT', 'AATTAAAAGA', 'TGCTTATCAT', 'ATTAATGCAG', 'CATCAAAATT', 'CCTTAAAACT', 'CTTAAAACTT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Mus musculus', 'sampled_chromosomes': ['NC_000075.7 chromosome 9 ', 'NC_000081.7 chromosome 15 ', 'NC_000073.7 chromosome 7 ', 'NC_000067.7 chromosome 1 ', 'NC_000076.7 chromosome 10 ', 'NC_000069.7 chromosome 3 ', 'NC_000071.7 chromosome 5 ', 'NC_000073.7 chromosome 7 ', 'NC_000077.7 chromosome 11 ', 'NC_000067.7 chromosome 1 '], 'chunks': ['ATGTGTGGAA', 'TGTACCCGGT', 'GCCTCTGGCC', 'CAGTGACCCT', 'CCCCAGGGAT', 'GCTAGAGAAA', 'ACTGTTGCTG', 'CCCATCAGAC', 'AGAGTGTACT', 'TAAACCTTGG'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Neomonachus schauinslandi', 'sampled_chromosomes': ['NC_058418.1 chromosome 16 ', 'NC_058406.1 chromosome 4 ', 'NC_058404.1 chromosome 2 ', 'NC_058407.1 chromosome 5 ', 'NC_058411.1 chromosome 9 ', 'NC_058404.1 chromosome 2 ', 'NC_058411.1 chromosome 9 ', 'NC_058410.1 chromosome 8 ', 'NC_058419.1 chromosome X ', 'NC_058405.1 chromosome 3 '], 'chunks': ['CGGATGTGGG', 'GTGGTCAACA', 'AGTCGGTTAA', 'TCAACTTAAG', 'ACCAGGAAGG', 'TCTGTTGTCC', 'TTTTAAGCCT', 'TATGGAAAAC', 'AAACACTAAA', 'TTGTATTGCC'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}

DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_086040.1 chromosome Y ': 59846084, 'NW_026947367.1 chromosome Y unlocalized genomic scaffold': 2057166, 'NW_026947368.1 chromosome Y unlocalized genomic scaffold': 991656, 'NW_026947369.1 chromosome Y unlocalized genomic scaffold': 926565, 'NW_026947370.1 chromosome Y unlocalized genomic scaffold': 903984, 'NW_026947371.1 chromosome Y unlocalized genomic scaffold': 890273, 'NW_026947372.1 chromosome Y unlocalized genomic scaffold': 885491, 'NW_026947373.1 chromosome Y unlocalized genomic scaffold': 793495, 'NW_026947374.1 chromosome Y unlocalized genomic scaffold': 779953, 'NW_026947375.1 chromosome Y unlocalized genomic scaffold': 745465, 'NW_026947376.1 chromosome Y unlocalized genomic scaffold': 720549, 'NW_026947377.1 chromosome Y unlocalized genomic scaffold': 716979, 'NW_026947378.1 chromosome Y unlocalized genomic scaffold': 1913966, 'NW_026947379.1 chromosome Y unlocalized genomic scaffold': 654985, 'NW_026947380.1 chromosome Y unlocalized genomic scaffold': 651350, 'NW_026947381.1 chromosome Y unlocalized genomic scaffold': 647876, 'NW_026947382.1 chromosome Y unlocalized genomic scaffold': 603879, 'NW_026947383.1 chromosome Y unlocalized genomic scaffold': 591746, 'NW_026947384.1 chromosome Y unlocalized genomic scaffold': 574096, 'NW_026947385.1 chromosome Y unlocalized genomic scaffold': 564375, 'NW_026947386.1 chromosome Y unlocalized genomic scaffold': 542769, 'NW_026947387.1 chromosome Y unlocalized genomic scaffold': 523357, 'NW_026947388.1 chromosome Y unlocalized genomic scaffold': 496250, 'NW_026947389.1 chromosome Y unlocalized genomic scaffold': 1696814, 'NW_026947390.1 chromosome Y unlocalized genomic scaffold': 474392, 'NW_026947391.1 chromosome Y unlocalized genomic scaffold': 446190, 'NW_026947392.1 chromosome Y unlocalized genomic scaffold': 429359, 'NW_026947393.1 chromosome Y unlocalized genomic scaffold': 413835, 'NW_026947394.1 chromosome Y unlocalized genomic scaffold': 381568, 'NW_026947395.1 chromosome Y unlocalized genomic scaffold': 350964, 'NW_026947396.1 chromosome Y unlocalized genomic scaffold': 316310, 'NW_026947397.1 chromosome Y unlocalized genomic scaffold': 288775, 'NW_026947398.1 chromosome Y unlocalized genomic scaffold': 285824, 'NW_026947399.1 chromosome Y unlocalized genomic scaffold': 285534, 'NW_026947400.1 chromosome Y unlocalized genomic scaffold': 1654197, 'NW_026947401.1 chromosome Y unlocalized genomic scaffold': 285417, 'NW_026947402.1 chromosome Y unlocalized genomic scaffold': 214303, 'NW_026947403.1 chromosome Y unlocalized genomic scaffold': 184496, 'NW_026947404.1 chromosome Y unlocalized genomic scaffold': 148250, 'NW_026947405.1 chromosome Y unlocalized genomic scaffold': 130679, 'NW_026947406.1 chromosome Y unlocalized genomic scaffold': 120978, 'NW_026947407.1 chromosome Y unlocalized genomic scaffold': 106421, 'NW_026947408.1 chromosome Y unlocalized genomic scaffold': 1487504, 'NW_026947409.1 chromosome Y unlocalized genomic scaffold': 1376544, 'NW_026947410.1 chromosome Y unlocalized genomic scaffold': 1160921, 'NW_026947411.1 chromosome Y unlocalized genomic scaffold': 1105183, 'NW_026947412.1 chromosome Y unlocalized genomic scaffold': 997779, 'NC_086039.1 chromosome X ': 157758123, 'NC_086019.1 chromosome 1 ': 541036360, 'NC_086020.1 chromosome 2 ': 503425416, 'NC_086021.1 chromosome 3 ': 378856620, 'NC_086022.1 chromosome 4 ': 368852962, 'NC_086023.1 chromosome 5 ': 344380610, 'NC_086024.1 chromosome 6 ': 294313306, 'NC_086025.1 chromosome 7 ': 274029192, 'NC_086026.1 chromosome 8 ': 265564872, 'NC_086027.1 chromosome 9 ': 243536300, 'NC_086028.1 chromosome 10 ': 215427616, 'NC_086029.1 chromosome 11 ': 199506734, 'NC_086030.1 chromosome 12 ': 104617662, 'NC_086031.1 chromosome 13 ': 218700572, 'NC_086032.1 chromosome 14 ': 218179712, 'NC_086033.1 chromosome 15 ': 216384338, 'NC_086034.1 chromosome 16 ': 182885816, 'NC_086035.1 chromosome 17 ': 187031608, 'NC_086036.1 chromosome 18 ': 172268044, 'NC_086037.1 chromosome 19 ': 148492490, 'NC_086038.1 chromosome 20 ': 112042296, 'NW_026947362.1 chromosome 3 unlocalized genomic scaffold': 4899856, 'NW_026947363.1 chromosome 3 unlocalized genomic scaffold': 1710804, 'NW_026947364.1 chromosome 3 unlocalized genomic scaffold': 1532044, 'NW_026947365.1 chromosome 3 unlocalized genomic scaffold': 495348, 'NW_026947366.1 chromosome 3 unlocalized genomic scaffold': 206968}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_086040.1 chromosome Y ': 0.010983955517747925, 'NW_026947367.1 chromosome Y unlocalized genomic scaffold': 0.0003775655536062046, 'NW_026947368.1 chromosome Y unlocalized genomic scaffold': 0.0001820053153838409, 'NW_026947369.1 chromosome Y unlocalized genomic scaffold': 0.0001700587250504495, 'NW_026947370.1 chromosome Y unlocalized genomic scaffold': 0.00016591428178919508, 'NW_026947371.1 chromosome Y unlocalized genomic scaffold': 0.00016339780946489327, 'NW_026947372.1 chromosome Y unlocalized genomic scaffold': 0.0001625201367455576, 'NW_026947373.1 chromosome Y unlocalized genomic scaffold': 0.00014563549026124065, 'NW_026947374.1 chromosome Y unlocalized genomic scaffold': 0.00014315003564701153, 'NW_026947375.1 chromosome Y unlocalized genomic scaffold': 0.00013682022035122558, 'NW_026947376.1 chromosome Y unlocalized genomic scaffold': 0.0001322472187880789, 'NW_026947377.1 chromosome Y unlocalized genomic scaffold': 0.00013159199260488603, 'NW_026947378.1 chromosome Y unlocalized genomic scaffold': 0.0003512830915800927, 'NW_026947379.1 chromosome Y unlocalized genomic scaffold': 0.0001202138155738331, 'NW_026947380.1 chromosome Y unlocalized genomic scaffold': 0.00011954665950215072, 'NW_026947381.1 chromosome Y unlocalized genomic scaffold': 0.00011890905284657312, 'NW_026947382.1 chromosome Y unlocalized genomic scaffold': 0.00011083398663314542, 'NW_026947383.1 chromosome Y unlocalized genomic scaffold': 0.00010860713529401963, 'NW_026947384.1 chromosome Y unlocalized genomic scaffold': 0.00010536771172725373, 'NW_026947385.1 chromosome Y unlocalized genomic scaffold': 0.0001035835510194616, 'NW_026947386.1 chromosome Y unlocalized genomic scaffold': 9.961805608554977e-05, 'NW_026947387.1 chromosome Y unlocalized genomic scaffold': 9.605524077234527e-05, 'NW_026947388.1 chromosome Y unlocalized genomic scaffold': 9.108011019872925e-05, 'NW_026947389.1 chromosome Y unlocalized genomic scaffold': 0.00031142772011435077, 'NW_026947390.1 chromosome Y unlocalized genomic scaffold': 8.706836400482734e-05, 'NW_026947391.1 chromosome Y unlocalized genomic scaffold': 8.189226069434963e-05, 'NW_026947392.1 chromosome Y unlocalized genomic scaffold': 7.880315372255152e-05, 'NW_026947393.1 chromosome Y unlocalized genomic scaffold': 7.595392927776548e-05, 'NW_026947394.1 chromosome Y unlocalized genomic scaffold': 7.003174909482866e-05, 'NW_026947395.1 chromosome Y unlocalized genomic scaffold': 6.44147905204772e-05, 'NW_026947396.1 chromosome Y unlocalized genomic scaffold': 5.805450812485652e-05, 'NW_026947397.1 chromosome Y unlocalized genomic scaffold': 5.3000823823955743e-05, 'NW_026947398.1 chromosome Y unlocalized genomic scaffold': 5.245920688653217e-05, 'NW_026947399.1 chromosome Y unlocalized genomic scaffold': 5.240598123019437e-05, 'NW_026947400.1 chromosome Y unlocalized genomic scaffold': 0.0003036059346103926, 'NW_026947401.1 chromosome Y unlocalized genomic scaffold': 5.238450743091326e-05, 'NW_026947402.1 chromosome Y unlocalized genomic scaffold': 3.933247527640962e-05, 'NW_026947403.1 chromosome Y unlocalized genomic scaffold': 3.386179548861411e-05, 'NW_026947404.1 chromosome Y unlocalized genomic scaffold': 2.7209322593373523e-05, 'NW_026947405.1 chromosome Y unlocalized genomic scaffold': 2.3984398429541038e-05, 'NW_026947406.1 chromosome Y unlocalized genomic scaffold': 2.2203908456668748e-05, 'NW_026947407.1 chromosome Y unlocalized genomic scaffold': 1.953216404525736e-05, 'NW_026947408.1 chromosome Y unlocalized genomic scaffold': 0.00027301164381068123, 'NW_026947409.1 chromosome Y unlocalized genomic scaffold': 0.00025264640647536436, 'NW_026947410.1 chromosome Y unlocalized genomic scaffold': 0.00021307166269424476, 'NW_026947411.1 chromosome Y unlocalized genomic scaffold': 0.00020284169154612027, 'NW_026947412.1 chromosome Y unlocalized genomic scaffold': 0.0001831291108795524, 'NC_086039.1 chromosome X ': 0.028954412549289033, 'NC_086019.1 chromosome 1 ': 0.0993000529779735, 'NC_086020.1 chromosome 2 ': 0.09239706270251107, 'NC_086021.1 chromosome 3 ': 0.06953411123247978, 'NC_086022.1 chromosome 4 ': 0.06769807239513892, 'NC_086023.1 chromosome 5 ': 0.06320649654227829, 'NC_086024.1 chromosome 6 ': 0.054017306485505935, 'NC_086025.1 chromosome 7 ': 0.050294426206607026, 'NC_086026.1 chromosome 8 ': 0.04874091245676862, 'NC_086027.1 chromosome 9 ': 0.044697860033029294, 'NC_086028.1 chromosome 10 ': 0.03953888363754061, 'NC_086029.1 chromosome 11 ': 0.03661681676193161, 'NC_086030.1 chromosome 12 ': 0.019201185256812914, 'NC_086031.1 chromosome 13 ': 0.040139591331556916, 'NC_086032.1 chromosome 14 ': 0.040043994382039316, 'NC_086033.1 chromosome 15 ': 0.039714477280239954, 'NC_086034.1 chromosome 16 ': 0.03356626755680508, 'NC_086035.1 chromosome 17 ': 0.03432717273004641, 'NC_086036.1 chromosome 18 ': 0.031617516234235844, 'NC_086037.1 chromosome 19 ': 0.02725382841890922, 'NC_086038.1 chromosome 20 ': 0.020563878421357464, 'NW_026947362.1 chromosome 3 unlocalized genomic scaffold': 0.0008993036260713445, 'NW_026947363.1 chromosome 3 unlocalized genomic scaffold': 0.00031399539919078445, 'NW_026947364.1 chromosome 3 unlocalized genomic scaffold': 0.0002811863704771828, 'NW_026947365.1 chromosome 3 unlocalized genomic scaffold': 9.09145600538441e-05, 'NW_026947366.1 chromosome 3 unlocalized genomic scaffold': 3.7986233244555355e-05}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999998
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Mesoplodon densirostris
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_025265405.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_082682.1 chromosome Y ', 'NW_026778236.1 chromosome Y unlocalized genomic scaffold', 'NW_026778237.1 chromosome Y unlocalized genomic scaffold', 'NC_082681.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_082661.1 chromosome 1 ', 'NC_082662.1 chromosome 2 ', 'NC_082663.1 chromosome 3 ', 'NC_082664.1 chromosome 4 ', 'NC_082665.1 chromosome 5 ', 'NC_082666.1 chromosome 6 ', 'NC_082667.1 chromosome 7 ', 'NC_082668.1 chromosome 8 ', 'NC_082669.1 chromosome 9 ', 'NC_082670.1 chromosome 10 ', 'NC_082671.1 chromosome 11 ', 'NC_082672.1 chromosome 12 ', 'NC_082673.1 chromosome 13 ', 'NC_082674.1 chromosome 14 ', 'NC_082675.1 chromosome 15 ', 'NC_082676.1 chromosome 16 ', 'NC_082677.1 chromosome 17 ', 'NC_082678.1 chromosome 18 ', 'NC_082679.1 chromosome 19 ', 'NC_082680.1 chromosome 20 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_082682.1 chromosome Y ': 12710753, 'NW_026778236.1 chromosome Y unlocalized genomic scaffold': 6823000, 'NW_026778237.1 chromosome Y unlocalized genomic scaffold': 2935457, 'NC_082681.1 chromosome X ': 142130375, 'NC_082661.1 chromosome 1 ': 494568720, 'NC_082662.1 chromosome 2 ': 386830698, 'NC_082663.1 chromosome 3 ': 370973532, 'NC_082664.1 chromosome 4 ': 369816576, 'NC_082665.1 chromosome 5 ': 311038254, 'NC_082666.1 chromosome 6 ': 273731452, 'NC_082667.1 chromosome 7 ': 251611380, 'NC_082668.1 chromosome 8 ': 234670390, 'NC_082669.1 chromosome 9 ': 228226422, 'NC_082670.1 chromosome 10 ': 222585620, 'NC_082671.1 chromosome 11 ': 212261872, 'NC_082672.1 chromosome 12 ': 209401840, 'NC_082673.1 chromosome 13 ': 186724664, 'NC_082674.1 chromosome 14 ': 183971348, 'NC_082675.1 chromosome 15 ': 182393564, 'NC_082676.1 chromosome 16 ': 177466300, 'NC_082677.1 chromosome 17 ': 157194532, 'NC_082678.1 chromosome 18 ': 134099418, 'NC_082679.1 chromosome 19 ': 133134426, 'NC_082680.1 chromosome 20 ': 90065488}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_082682.1 chromosome Y ': 0.0025547372380376205, 'NW_026778236.1 chromosome Y unlocalized genomic scaffold': 0.0013713563763791715, 'NW_026778237.1 chromosome Y unlocalized genomic scaffold': 0.0005899981935419718, 'NC_082681.1 chromosome X ': 0.028566817533843294, 'NC_082661.1 chromosome 1 ': 0.09940348347203358, 'NC_082662.1 chromosome 2 ': 0.077749193064855, 'NC_082663.1 chromosome 3 ': 0.0745620575371688, 'NC_082664.1 chromosome 4 ': 0.07432952067833981, 'NC_082665.1 chromosome 5 ': 0.06251565190103245, 'NC_082666.1 chromosome 6 ': 0.0550173489836918, 'NC_082667.1 chromosome 7 ': 0.05057143050455266, 'NC_082668.1 chromosome 8 ': 0.047166456935935366, 'NC_082669.1 chromosome 9 ': 0.045871282290473936, 'NC_082670.1 chromosome 10 ': 0.04473753616844662, 'NC_082671.1 chromosome 11 ': 0.042662563627345676, 'NC_082672.1 chromosome 12 ': 0.04208772512231146, 'NC_082673.1 chromosome 13 ': 0.03752983417905003, 'NC_082674.1 chromosome 14 ': 0.03697644454798059, 'NC_082675.1 chromosome 15 ': 0.03665932537035359, 'NC_082676.1 chromosome 16 ': 0.035668993418938734, 'NC_082677.1 chromosome 17 ': 0.031594565995916715, 'NC_082678.1 chromosome 18 ': 0.026952673595637675, 'NC_082679.1 chromosome 19 ': 0.026758719626363912, 'NC_082680.1 chromosome 20 ': 0.018102283637769567}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Homo sapiens
DEBUG:mammals_gender_dataset:Sample/assembly id: HG03129
DEBUG:mammals_gender_dataset:Diploid: True
DEBUG:mammals_gender_dataset:Label: 1.0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['h1_chrX', 'h2_chrX']
DEBUG:mammals_gender_dataset:Autosomes: ['h1_chr1', 'h1_chr10', 'h1_chr11', 'h1_chr12', 'h1_chr13', 'h1_chr14', 'h1_chr15', 'h1_chr16', 'h1_chr17', 'h1_chr18', 'h1_chr19', 'h1_chr2', 'h1_chr20', 'h1_chr21', 'h1_chr22', 'h1_chr3', 'h1_chr4', 'h1_chr5', 'h1_chr6', 'h1_chr7', 'h1_chr8', 'h1_chr9', 'h2_chr1', 'h2_chr10', 'h2_chr11', 'h2_chr12', 'h2_chr13', 'h2_chr14', 'h2_chr15', 'h2_chr16', 'h2_chr17', 'h2_chr18', 'h2_chr19', 'h2_chr2', 'h2_chr20', 'h2_chr21', 'h2_chr22', 'h2_chr3', 'h2_chr4', 'h2_chr5', 'h2_chr6', 'h2_chr7', 'h2_chr8', 'h2_chr9']
DEBUG:mammals_gender_dataset:Chromosomes length: {'h1_chrX': 156014580, 'h2_chrX': 156012771, 'h1_chr1': 248919044, 'h1_chr10': 133766958, 'h1_chr11': 135006805, 'h1_chr12': 133245288, 'h1_chr13': 98346949, 'h1_chr14': 90854302, 'h1_chr15': 84973985, 'h1_chr16': 90209573, 'h1_chr17': 83179451, 'h1_chr18': 80247415, 'h1_chr19': 58540765, 'h1_chr2': 242160021, 'h1_chr20': 64268726, 'h1_chr21': 41687308, 'h1_chr22': 40293356, 'h1_chr3': 198214863, 'h1_chr4': 190180803, 'h1_chr5': 181455503, 'h1_chr6': 170676097, 'h1_chr7': 159314357, 'h1_chr8': 145006446, 'h1_chr9': 138323291, 'h2_chr1': 248918096, 'h2_chr10': 133766397, 'h2_chr11': 135007413, 'h2_chr12': 133244256, 'h2_chr13': 98347472, 'h2_chr14': 90854959, 'h2_chr15': 84974623, 'h2_chr16': 90210770, 'h2_chr17': 83179761, 'h2_chr18': 80247314, 'h2_chr19': 58540256, 'h2_chr2': 242160115, 'h2_chr20': 64268361, 'h2_chr21': 41686303, 'h2_chr22': 40294704, 'h2_chr3': 198214560, 'h2_chr4': 190179591, 'h2_chr5': 181456413, 'h2_chr6': 170673739, 'h2_chr7': 159311640, 'h2_chr8': 145007289, 'h2_chr9': 138323270}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'h1_chrX': 0.026310411081774027, 'h2_chrX': 0.02631010601071178, 'h1_chr1': 0.041977886770083905, 'h1_chr10': 0.022558556092247283, 'h1_chr11': 0.022767644782858792, 'h1_chr12': 0.0224705812879115, 'h1_chr13': 0.016585300276604053, 'h1_chr14': 0.015321734892775048, 'h1_chr15': 0.014330074000817745, 'h1_chr16': 0.015213007330092503, 'h1_chr17': 0.014027442495222432, 'h1_chr18': 0.013532981833490942, 'h1_chr19': 0.009872356751474952, 'h1_chr2': 0.04083804026573049, 'h1_chr20': 0.010838324217915394, 'h1_chr21': 0.0070301776306581545, 'h1_chr22': 0.006795100561910727, 'h1_chr3': 0.033427097185708673, 'h1_chr4': 0.03207222752381145, 'h1_chr5': 0.0306007866507097, 'h1_chr6': 0.028782939863073946, 'h1_chr7': 0.026866887850472077, 'h1_chr8': 0.024453991439563325, 'h1_chr9': 0.023326939369345184, 'h2_chr1': 0.04197772689868147, 'h2_chr10': 0.022558461484803435, 'h2_chr11': 0.02276774731641647, 'h2_chr12': 0.022470407250688593, 'h2_chr13': 0.016585388475700548, 'h2_chr14': 0.015321845689728004, 'h2_chr15': 0.014330181593597023, 'h2_chr16': 0.01521320919303419, 'h2_chr17': 0.014027494773845593, 'h2_chr18': 0.013532964800778235, 'h2_chr19': 0.009872270913348538, 'h2_chr2': 0.04083805611795816, 'h2_chr20': 0.01083826266405264, 'h2_chr21': 0.007030008146734683, 'h2_chr22': 0.0067953278896011144, 'h2_chr3': 0.03342704608757055, 'h2_chr4': 0.03207202313125897, 'h2_chr5': 0.030600940113764782, 'h2_chr6': 0.028782542208256486, 'h2_chr7': 0.026866429653636184, 'h2_chr8': 0.024454133603690177, 'h2_chr9': 0.023326935827890066}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002

{'labels': 0, 'species': 'Rattus norvegicus', 'sampled_chromosomes': ['NC_086026.1 chromosome 8 ', 'NC_086027.1 chromosome 9 ', 'NC_086035.1 chromosome 17 ', 'NC_086024.1 chromosome 6 ', 'NC_086028.1 chromosome 10 ', 'NC_086040.1 chromosome Y ', 'NC_086019.1 chromosome 1 ', 'NC_086023.1 chromosome 5 ', 'NC_086028.1 chromosome 10 ', 'NC_086019.1 chromosome 1 '], 'chunks': ['AAGATTCCAC', 'ATCTCATTAA', 'TCCACCCACC', 'AGAAAGACTT', 'GTGTGAAGAA', 'ATGGCTCATC', 'TGCCTTAGTC', 'GGGGGGTTGT', 'TTCATCGTCC', 'CTCCTCCTCT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Mesoplodon densirostris', 'sampled_chromosomes': ['NC_082675.1 chromosome 15 ', 'NC_082663.1 chromosome 3 ', 'NC_082670.1 chromosome 10 ', 'NC_082670.1 chromosome 10 ', 'NC_082671.1 chromosome 11 ', 'NC_082663.1 chromosome 3 ', 'NC_082661.1 chromosome 1 ', 'NC_082667.1 chromosome 7 ', 'NC_082682.1 chromosome Y ', 'NC_082663.1 chromosome 3 '], 'chunks': ['CCTGTGGTCT', 'GCATTCTTCC', 'ATGTAAAGCA', 'GTGTGTGTGT', 'TGGCAATTTT', 'TCAACAAAAA', 'TGTGATGGAA', 'GATAAACAAC', 'TGTGATGAGA', 'ATATTAAAAA'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Label: 1.0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Pongo abelii
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_028885655.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_072008.2 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_071985.2 chromosome 1 ', 'NC_071988.2 chromosome 3 ', 'NC_071989.2 chromosome 4 ', 'NC_071990.2 chromosome 5 ', 'NC_071991.2 chromosome 6 ', 'NC_071992.2 chromosome 7 ', 'NC_071993.2 chromosome 8 ', 'NC_071994.2 chromosome 9 ', 'NC_071995.2 chromosome 10 ', 'NC_071996.2 chromosome 11 ', 'NC_071997.2 chromosome 12 ', 'NC_071998.2 chromosome 13 ', 'NC_071999.2 chromosome 14 ', 'NC_072000.2 chromosome 15 ', 'NC_072001.2 chromosome 16 ', 'NC_072002.2 chromosome 17 ', 'NC_072003.2 chromosome 18 ', 'NC_072004.2 chromosome 19 ', 'NC_072005.2 chromosome 20 ', 'NC_072006.2 chromosome 21 ', 'NC_072007.2 chromosome 22 ', 'NC_085928.1 chromosome 2 ', 'NC_085929.1 chromosome 23 ', 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_072008.2 chromosome X ': 325172642, 'NC_071985.2 chromosome 1 ': 467591038, 'NC_071988.2 chromosome 3 ': 425833550, 'NC_071989.2 chromosome 4 ': 380757808, 'NC_071990.2 chromosome 5 ': 345210726, 'NC_071991.2 chromosome 6 ': 313933982, 'NC_071992.2 chromosome 7 ': 323262792, 'NC_071993.2 chromosome 8 ': 281708270, 'NC_071994.2 chromosome 9 ': 276942042, 'NC_071995.2 chromosome 10 ': 264563434, 'NC_071996.2 chromosome 11 ': 292394356, 'NC_071997.2 chromosome 12 ': 266366248, 'NC_071998.2 chromosome 13 ': 259236340, 'NC_071999.2 chromosome 14 ': 241159696, 'NC_072000.2 chromosome 15 ': 223483318, 'NC_072001.2 chromosome 16 ': 210667690, 'NC_072002.2 chromosome 17 ': 190920258, 'NC_072003.2 chromosome 18 ': 179106226, 'NC_072004.2 chromosome 19 ': 197338576, 'NC_072005.2 chromosome 20 ': 130800294, 'NC_072006.2 chromosome 21 ': 137501336, 'NC_072007.2 chromosome 22 ': 114286206, 'NC_085928.1 chromosome 2 ': 419089974, 'NC_085929.1 chromosome 23 ': 115186842, 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold': 443016, 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold': 266400, 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold': 230424, 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold': 598924}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_072008.2 chromosome X ': 0.05093514608252884, 'NC_071985.2 chromosome 1 ': 0.07324360893623792, 'NC_071988.2 chromosome 3 ': 0.06670270273257443, 'NC_071989.2 chromosome 4 ': 0.05964202416679158, 'NC_071990.2 chromosome 5 ': 0.05407391793454087, 'NC_071991.2 chromosome 6 ': 0.04917471880503397, 'NC_071992.2 chromosome 7 ': 0.05063598657099245, 'NC_071993.2 chromosome 8 ': 0.04412687302613384, 'NC_071994.2 chromosome 9 ': 0.043380289556044005, 'NC_071995.2 chromosome 10 ': 0.04144130046120386, 'NC_071996.2 chromosome 11 ': 0.04580074493649113, 'NC_071997.2 chromosome 12 ': 0.04172369381965136, 'NC_071998.2 chromosome 13 ': 0.0406068627624587, 'NC_071999.2 chromosome 14 ': 0.0377753314959942, 'NC_072000.2 chromosome 15 ': 0.035006498023097056, 'NC_072001.2 chromosome 16 ': 0.03299905397643785, 'NC_072002.2 chromosome 17 ': 0.029905809946164215, 'NC_072003.2 chromosome 18 ': 0.028055256215559564, 'NC_072004.2 chromosome 19 ': 0.030911177319395213, 'NC_072005.2 chromosome 20 ': 0.020488599660631105, 'NC_072006.2 chromosome 21 ': 0.02153825301115855, 'NC_072007.2 chromosome 22 ': 0.01790182766306639, 'NC_085928.1 chromosome 2 ': 0.06564638684275663, 'NC_085929.1 chromosome 23 ': 0.018042903572604883, 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold': 6.939416716642969e-05, 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold': 4.1728980743668106e-05, 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold': 3.609368865945563e-05, 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold': 9.381564588183437e-05}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Pongo abelii
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_028885655.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_072008.2 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_071985.2 chromosome 1 ', 'NC_071988.2 chromosome 3 ', 'NC_071989.2 chromosome 4 ', 'NC_071990.2 chromosome 5 ', 'NC_071991.2 chromosome 6 ', 'NC_071992.2 chromosome 7 ', 'NC_071993.2 chromosome 8 ', 'NC_071994.2 chromosome 9 ', 'NC_071995.2 chromosome 10 ', 'NC_071996.2 chromosome 11 ', 'NC_071997.2 chromosome 12 ', 'NC_071998.2 chromosome 13 ', 'NC_071999.2 chromosome 14 ', 'NC_072000.2 chromosome 15 ', 'NC_072001.2 chromosome 16 ', 'NC_072002.2 chromosome 17 ', 'NC_072003.2 chromosome 18 ', 'NC_072004.2 chromosome 19 ', 'NC_072005.2 chromosome 20 ', 'NC_072006.2 chromosome 21 ', 'NC_072007.2 chromosome 22 ', 'NC_085928.1 chromosome 2 ', 'NC_085929.1 chromosome 23 ', 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold', 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_072008.2 chromosome X ': 325172642, 'NC_071985.2 chromosome 1 ': 467591038, 'NC_071988.2 chromosome 3 ': 425833550, 'NC_071989.2 chromosome 4 ': 380757808, 'NC_071990.2 chromosome 5 ': 345210726, 'NC_071991.2 chromosome 6 ': 313933982, 'NC_071992.2 chromosome 7 ': 323262792, 'NC_071993.2 chromosome 8 ': 281708270, 'NC_071994.2 chromosome 9 ': 276942042, 'NC_071995.2 chromosome 10 ': 264563434, 'NC_071996.2 chromosome 11 ': 292394356, 'NC_071997.2 chromosome 12 ': 266366248, 'NC_071998.2 chromosome 13 ': 259236340, 'NC_071999.2 chromosome 14 ': 241159696, 'NC_072000.2 chromosome 15 ': 223483318, 'NC_072001.2 chromosome 16 ': 210667690, 'NC_072002.2 chromosome 17 ': 190920258, 'NC_072003.2 chromosome 18 ': 179106226, 'NC_072004.2 chromosome 19 ': 197338576, 'NC_072005.2 chromosome 20 ': 130800294, 'NC_072006.2 chromosome 21 ': 137501336, 'NC_072007.2 chromosome 22 ': 114286206, 'NC_085928.1 chromosome 2 ': 419089974, 'NC_085929.1 chromosome 23 ': 115186842, 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold': 443016, 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold': 266400, 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold': 230424, 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold': 598924}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_072008.2 chromosome X ': 0.05093514608252884, 'NC_071985.2 chromosome 1 ': 0.07324360893623792, 'NC_071988.2 chromosome 3 ': 0.06670270273257443, 'NC_071989.2 chromosome 4 ': 0.05964202416679158, 'NC_071990.2 chromosome 5 ': 0.05407391793454087, 'NC_071991.2 chromosome 6 ': 0.04917471880503397, 'NC_071992.2 chromosome 7 ': 0.05063598657099245, 'NC_071993.2 chromosome 8 ': 0.04412687302613384, 'NC_071994.2 chromosome 9 ': 0.043380289556044005, 'NC_071995.2 chromosome 10 ': 0.04144130046120386, 'NC_071996.2 chromosome 11 ': 0.04580074493649113, 'NC_071997.2 chromosome 12 ': 0.04172369381965136, 'NC_071998.2 chromosome 13 ': 0.0406068627624587, 'NC_071999.2 chromosome 14 ': 0.0377753314959942, 'NC_072000.2 chromosome 15 ': 0.035006498023097056, 'NC_072001.2 chromosome 16 ': 0.03299905397643785, 'NC_072002.2 chromosome 17 ': 0.029905809946164215, 'NC_072003.2 chromosome 18 ': 0.028055256215559564, 'NC_072004.2 chromosome 19 ': 0.030911177319395213, 'NC_072005.2 chromosome 20 ': 0.020488599660631105, 'NC_072006.2 chromosome 21 ': 0.02153825301115855, 'NC_072007.2 chromosome 22 ': 0.01790182766306639, 'NC_085928.1 chromosome 2 ': 0.06564638684275663, 'NC_085929.1 chromosome 23 ': 0.018042903572604883, 'NW_026946739.1 chromosome 18 unlocalized genomic scaffold': 6.939416716642969e-05, 'NW_026946740.1 chromosome 18 unlocalized genomic scaffold': 4.1728980743668106e-05, 'NW_026946741.1 chromosome 18 unlocalized genomic scaffold': 3.609368865945563e-05, 'NW_026946742.1 chromosome 18 unlocalized genomic scaffold': 9.381564588183437e-05}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Meles meles
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_922984935.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_060087.1 chromosome X ', 'NW_025721105.1 chromosome X unlocalized genomic scaffold', 'NW_025721106.1 chromosome X unlocalized genomic scaffold', 'NW_025721107.1 chromosome X unlocalized genomic scaffold']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_060066.1 chromosome 1 ', 'NC_060067.1 chromosome 2 ', 'NC_060068.1 chromosome 3 ', 'NC_060069.1 chromosome 4 ', 'NC_060070.1 chromosome 5 ', 'NC_060071.1 chromosome 6 ', 'NC_060072.1 chromosome 7 ', 'NC_060073.1 chromosome 8 ', 'NC_060074.1 chromosome 9 ', 'NC_060075.1 chromosome 10 ', 'NC_060076.1 chromosome 11 ', 'NC_060077.1 chromosome 12 ', 'NC_060078.1 chromosome 13 ', 'NC_060079.1 chromosome 14 ', 'NC_060080.1 chromosome 15 ', 'NC_060081.1 chromosome 16 ', 'NC_060082.1 chromosome 17 ', 'NC_060083.1 chromosome 18 ', 'NC_060084.1 chromosome 19 ', 'NC_060085.1 chromosome 20 ', 'NC_060086.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_060087.1 chromosome X ': 265911500, 'NW_025721105.1 chromosome X unlocalized genomic scaffold': 176822, 'NW_025721106.1 chromosome X unlocalized genomic scaffold': 47392, 'NW_025721107.1 chromosome X unlocalized genomic scaffold': 39558, 'NC_060066.1 chromosome 1 ': 433931002, 'NC_060067.1 chromosome 2 ': 421458882, 'NC_060068.1 chromosome 3 ': 368596490, 'NC_060069.1 chromosome 4 ': 329533118, 'NC_060070.1 chromosome 5 ': 316065892, 'NC_060071.1 chromosome 6 ': 307541514, 'NC_060072.1 chromosome 7 ': 302275162, 'NC_060073.1 chromosome 8 ': 240260840, 'NC_060074.1 chromosome 9 ': 237412256, 'NC_060075.1 chromosome 10 ': 219946646, 'NC_060076.1 chromosome 11 ': 197097284, 'NC_060077.1 chromosome 12 ': 192867276, 'NC_060078.1 chromosome 13 ': 175700910, 'NC_060079.1 chromosome 14 ': 173070976, 'NC_060080.1 chromosome 15 ': 169968488, 'NC_060081.1 chromosome 16 ': 165907548, 'NC_060082.1 chromosome 17 ': 138477822, 'NC_060083.1 chromosome 18 ': 129040510, 'NC_060084.1 chromosome 19 ': 124339868, 'NC_060085.1 chromosome 20 ': 122973998, 'NC_060086.1 chromosome 21 ': 90235732}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_060087.1 chromosome X ': 0.05190666783008053, 'NW_025721105.1 chromosome X unlocalized genomic scaffold': 3.451614848944291e-05, 'NW_025721106.1 chromosome X unlocalized genomic scaffold': 9.251050826320698e-06, 'NW_025721107.1 chromosome X unlocalized genomic scaffold': 7.721832135963752e-06, 'NC_060066.1 chromosome 1 ': 0.08470454411331593, 'NC_060067.1 chromosome 2 ': 0.08226995143877232, 'NC_060068.1 chromosome 3 ': 0.0719510648082674, 'NC_060069.1 chromosome 4 ': 0.06432578544003073, 'NC_060070.1 chromosome 5 ': 0.06169694529368645, 'NC_060071.1 chromosome 6 ': 0.06003296288862294, 'NC_060072.1 chromosome 7 ': 0.05900495626258277, 'NC_060073.1 chromosome 8 ': 0.04689958732306096, 'NC_060074.1 chromosome 9 ': 0.0463435357665315, 'NC_060075.1 chromosome 10 ': 0.04293419989079942, 'NC_060076.1 chromosome 11 ': 0.03847394058097918, 'NC_060077.1 chromosome 12 ': 0.03764823119957002, 'NC_060078.1 chromosome 13 ': 0.03429730858880821, 'NC_060079.1 chromosome 14 ': 0.03378393812324717, 'NC_060080.1 chromosome 15 ': 0.033178323796439896, 'NC_060081.1 chromosome 16 ': 0.03238561696105336, 'NC_060082.1 chromosome 17 ': 0.02703125779963265, 'NC_060083.1 chromosome 18 ': 0.025189068126779717, 'NC_060084.1 chromosome 19 ': 0.024271489673489334, 'NC_060085.1 chromosome 20 ': 0.02400486803287179, 'NC_060086.1 chromosome 21 ': 0.017614267029926002}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Tursiops truncatus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011762595.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NW_022983135.1 chromosome Y unlocalized genomic scaffold', 'NW_022983136.1 chromosome Y unlocalized genomic scaffold', 'NW_022983137.1 chromosome Y unlocalized genomic scaffold', 'NW_022983138.1 chromosome Y unlocalized genomic scaffold', 'NC_047055.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_047034.1 chromosome 1 ', 'NC_047035.1 chromosome 2 ', 'NC_047036.1 chromosome 3 ', 'NC_047037.1 chromosome 4 ', 'NC_047038.1 chromosome 5 ', 'NC_047039.1 chromosome 6 ', 'NC_047040.1 chromosome 7 ', 'NC_047041.1 chromosome 8 ', 'NC_047042.1 chromosome 9 ', 'NC_047043.1 chromosome 10 ', 'NC_047044.1 chromosome 11 ', 'NC_047045.1 chromosome 12 ', 'NC_047046.1 chromosome 13 ', 'NC_047047.1 chromosome 14 ', 'NC_047048.1 chromosome 15 ', 'NC_047049.1 chromosome 16 ', 'NC_047050.1 chromosome 17 ', 'NC_047051.1 chromosome 18 ', 'NC_047052.1 chromosome 19 ', 'NC_047053.1 chromosome 20 ', 'NC_047054.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NW_022983135.1 chromosome Y unlocalized genomic scaffold': 7055931, 'NW_022983136.1 chromosome Y unlocalized genomic scaffold': 4926226, 'NW_022983137.1 chromosome Y unlocalized genomic scaffold': 596945, 'NW_022983138.1 chromosome Y unlocalized genomic scaffold': 124658, 'NC_047055.1 chromosome X ': 128693445, 'NC_047034.1 chromosome 1 ': 367485760, 'NC_047035.1 chromosome 2 ': 352945496, 'NC_047036.1 chromosome 3 ': 342843538, 'NC_047037.1 chromosome 4 ': 288366400, 'NC_047038.1 chromosome 5 ': 274975098, 'NC_047039.1 chromosome 6 ': 231199232, 'NC_047040.1 chromosome 7 ': 228030614, 'NC_047041.1 chromosome 8 ': 216860270, 'NC_047042.1 chromosome 9 ': 210670356, 'NC_047043.1 chromosome 10 ': 205625018, 'NC_047044.1 chromosome 11 ': 204335466, 'NC_047045.1 chromosome 12 ': 178661934, 'NC_047046.1 chromosome 13 ': 176970138, 'NC_047047.1 chromosome 14 ': 176966308, 'NC_047048.1 chromosome 15 ': 172587980, 'NC_047049.1 chromosome 16 ': 167017088, 'NC_047050.1 chromosome 17 ': 156885544, 'NC_047051.1 chromosome 18 ': 156303926, 'NC_047052.1 chromosome 19 ': 117272254, 'NC_047053.1 chromosome 20 ': 116934582, 'NC_047054.1 chromosome 21 ': 71364496}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NW_022983135.1 chromosome Y unlocalized genomic scaffold': 0.0015488142346537443, 'NW_022983136.1 chromosome Y unlocalized genomic scaffold': 0.001081332704631235, 'NW_022983137.1 chromosome Y unlocalized genomic scaffold': 0.00013103258993113443, 'NW_022983138.1 chromosome Y unlocalized genomic scaffold': 2.7363091399769418e-05, 'NC_047055.1 chromosome X ': 0.028248892955816705, 'NC_047034.1 chromosome 1 ': 0.08066507114660695, 'NC_047035.1 chromosome 2 ': 0.07747340616875734, 'NC_047036.1 chromosome 3 ': 0.07525597287068876, 'NC_047037.1 chromosome 4 ': 0.0632979524765556, 'NC_047038.1 chromosome 5 ': 0.060358490744553524, 'NC_047039.1 chromosome 6 ': 0.0507494562464703, 'NC_047040.1 chromosome 7 ': 0.05005392780910604, 'NC_047041.1 chromosome 8 ': 0.04760197812405682, 'NC_047042.1 chromosome 9 ': 0.046243259208794955, 'NC_047043.1 chromosome 10 ': 0.04513578078914496, 'NC_047044.1 chromosome 11 ': 0.04485271729349481, 'NC_047045.1 chromosome 12 ': 0.039217241009013235, 'NC_047046.1 chromosome 13 ': 0.03884588282439801, 'NC_047047.1 chromosome 14 ': 0.03884504211910785, 'NC_047048.1 chromosome 15 ': 0.037883975928071814, 'NC_047049.1 chromosome 16 ': 0.03666113562119826, 'NC_047050.1 chromosome 17 ': 0.03443720803939215, 'NC_047051.1 chromosome 18 ': 0.03430953980715875, 'NC_047052.1 chromosome 19 ': 0.025741881025357176, 'NC_047053.1 chromosome 20 ': 0.025667760232474707, 'NC_047054.1 chromosome 21 ': 0.01566488493916539}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Macaca mulatta
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_003339765.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_041774.1 chromosome X ', 'NW_021160381.1 chromosome X unlocalized genomic scaffold', 'NW_021160382.1 chromosome X unlocalized genomic scaffold', 'NW_021160383.1 chromosome X unlocalized genomic scaffold', 'NW_021160384.1 chromosome X unlocalized genomic scaffold']

{'labels': 1.0, 'species': 'Homo sapiens', 'sampled_chromosomes': ['h2_chr3', 'h1_chr1', 'h2_chr4', 'h2_chr13', 'h2_chr6', 'h2_chr20', 'h2_chr1', 'h2_chr8', 'h1_chr3', 'h2_chr9'], 'chunks': ['CTCTTTCCAG', 'GTCCTGAAAA', 'GCTTTAGAAT', 'CCAGCAATCC', 'ATGCTACATG', 'TTCTAACAAG', 'CACAAAAAAT', 'AAGAGTGATG', 'TCAAGTGATT', 'TGTGTCACAT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Pongo abelii', 'sampled_chromosomes': ['NC_071993.2 chromosome 8 ', 'NC_085929.1 chromosome 23 ', 'NC_071992.2 chromosome 7 ', 'NC_071992.2 chromosome 7 ', 'NC_071999.2 chromosome 14 ', 'NC_071988.2 chromosome 3 ', 'NC_071997.2 chromosome 12 ', 'NC_085928.1 chromosome 2 ', 'NC_085929.1 chromosome 23 ', 'NC_071990.2 chromosome 5 '], 'chunks': ['TATCATTTGT', 'GTGTCCCAGG', 'ATGCTATGTA', 'AAAAATTGTT', 'AAGAATAACA', 'ATCACAATTA', 'TTGTAATAAA', 'TATCATTATT', 'GACCAAAGTC', 'TCCGCCTCCC'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Pongo abelii', 'sampled_chromosomes': ['NC_072008.2 chromosome X ', 'NC_071991.2 chromosome 6 ', 'NC_071990.2 chromosome 5 ', 'NC_071989.2 chromosome 4 ', 'NC_071990.2 chromosome 5 ', 'NC_071990.2 chromosome 5 ', 'NC_072004.2 chromosome 19 ', 'NC_071998.2 chromosome 13 ', 'NC_071988.2 chromosome 3 ', 'NC_072008.2 chromosome X '], 'chunks': ['TGCTCCATGA', 'CAACTTACAA', 'AAGAAAATGC', 'CCAACCCTCC', 'TCAAGTATTT', 'CGCATTGCGT', 'GTCTAAACCA', 'GACGTCACCA', 'TCTTTTGATA', 'AACACTTGCA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Meles meles', 'sampled_chromosomes': ['NC_060069.1 chromosome 4 ', 'NC_060076.1 chromosome 11 ', 'NC_060070.1 chromosome 5 ', 'NC_060069.1 chromosome 4 ', 'NC_060077.1 chromosome 12 ', 'NC_060072.1 chromosome 7 ', 'NC_060076.1 chromosome 11 ', 'NC_060078.1 chromosome 13 ', 'NC_060071.1 chromosome 6 ', 'NC_060077.1 chromosome 12 '], 'chunks': ['GGTGTTAGAC', 'ACTATAGACT', 'TGTGCTATGC', 'ATGTCTTCAC', 'AATGCTTCGG', 'GCTTTTAAAT', 'ATCAACAAAA', 'AAATAAATAT', 'CTAGTGCTAC', 'TCACAGTAAA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Tursiops truncatus', 'sampled_chromosomes': ['NC_047050.1 chromosome 17 ', 'NC_047049.1 chromosome 16 ', 'NC_047035.1 chromosome 2 ', 'NC_047039.1 chromosome 6 ', 'NC_047037.1 chromosome 4 ', 'NC_047054.1 chromosome 21 ', 'NW_022983135.1 chromosome Y unlocalized genomic scaffold', 'NC_047039.1 chromosome 6 ', 'NC_047042.1 chromosome 9 ', 'NC_047037.1 chromosome 4 '], 'chunks': ['TGCTTTTCCT', 'TAAAGTATGG', 'CCCACACCAA', 'GAGGGAGACG', 'AGATAAATGG', 'GCATGGAAGG', 'CACTCCATCC', 'TACAGTATAT', 'AATGATTTTG', 'TTGATGACAT'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_041774.1 chromosome X ': 306777848, 'NW_021160381.1 chromosome X unlocalized genomic scaffold': 97392, 'NW_021160382.1 chromosome X unlocalized genomic scaffold': 101022, 'NW_021160383.1 chromosome X unlocalized genomic scaffold': 137994, 'NW_021160384.1 chromosome X unlocalized genomic scaffold': 159254, 'NC_041754.1 chromosome 1 ': 447233884, 'NC_041755.1 chromosome 2 ': 392395928, 'NC_041756.1 chromosome 3 ': 370577894, 'NC_041757.1 chromosome 4 ': 339926080, 'NC_041758.1 chromosome 5 ': 374634384, 'NC_041759.1 chromosome 6 ': 358171132, 'NC_041760.1 chromosome 7 ': 339737128, 'NC_041761.1 chromosome 8 ': 291358640, 'NC_041762.1 chromosome 9 ': 268248332, 'NC_041763.1 chromosome 10 ': 199035516, 'NC_041764.1 chromosome 11 ': 266132172, 'NC_041765.1 chromosome 12 ': 260087712, 'NC_041766.1 chromosome 13 ': 217474260, 'NC_041767.1 chromosome 14 ': 256112612, 'NC_041768.1 chromosome 15 ': 226567208, 'NC_041769.1 chromosome 16 ': 159254128, 'NC_041770.1 chromosome 17 ': 190866918, 'NC_041771.1 chromosome 18 ': 148948086, 'NC_041772.1 chromosome 19 ': 116630466, 'NC_041773.1 chromosome 20 ': 154274990, 'NW_021160094.1 chromosome 1 unlocalized genomic scaffold': 53360, 'NW_021160095.1 chromosome 1 unlocalized genomic scaffold': 65160, 'NW_021160096.1 chromosome 1 unlocalized genomic scaffold': 67096, 'NW_021160097.1 chromosome 1 unlocalized genomic scaffold': 74102, 'NW_021160098.1 chromosome 1 unlocalized genomic scaffold': 79986, 'NW_021160099.1 chromosome 1 unlocalized genomic scaffold': 80876, 'NW_021160100.1 chromosome 1 unlocalized genomic scaffold': 87980, 'NW_021160101.1 chromosome 1 unlocalized genomic scaffold': 97790, 'NW_021160102.1 chromosome 1 unlocalized genomic scaffold': 100376, 'NW_021160103.1 chromosome 1 unlocalized genomic scaffold': 102726, 'NW_021160104.1 chromosome 1 unlocalized genomic scaffold': 71758, 'NW_021160105.1 chromosome 1 unlocalized genomic scaffold': 109720, 'NW_021160106.1 chromosome 1 unlocalized genomic scaffold': 111082, 'NW_021160107.1 chromosome 1 unlocalized genomic scaffold': 111164, 'NW_021160108.1 chromosome 1 unlocalized genomic scaffold': 119880, 'NW_021160109.1 chromosome 1 unlocalized genomic scaffold': 164610, 'NW_021160110.1 chromosome 1 unlocalized genomic scaffold': 236270, 'NW_021160111.1 chromosome 1 unlocalized genomic scaffold': 266050, 'NW_021160112.1 chromosome 1 unlocalized genomic scaffold': 104152, 'NW_021160113.1 chromosome 1 unlocalized genomic scaffold': 232668, 'NW_021160114.1 chromosome 1 unlocalized genomic scaffold': 131828, 'NW_021160115.1 chromosome 2 unlocalized genomic scaffold': 61172, 'NW_021160116.1 chromosome 2 unlocalized genomic scaffold': 70782, 'NW_021160117.1 chromosome 2 unlocalized genomic scaffold': 81312, 'NW_021160118.1 chromosome 2 unlocalized genomic scaffold': 102148, 'NW_021160119.1 chromosome 2 unlocalized genomic scaffold': 96684, 'NW_021160120.1 chromosome 2 unlocalized genomic scaffold': 105902, 'NW_021160121.1 chromosome 2 unlocalized genomic scaffold': 172402, 'NW_021160122.1 chromosome 2 unlocalized genomic scaffold': 184080, 'NW_021160123.1 chromosome 2 unlocalized genomic scaffold': 105868, 'NW_021160124.1 chromosome 2 unlocalized genomic scaffold': 109560, 'NW_021160125.1 chromosome 3 unlocalized genomic scaffold': 50600, 'NW_021160126.1 chromosome 3 unlocalized genomic scaffold': 58698, 'NW_021160127.1 chromosome 3 unlocalized genomic scaffold': 58890, 'NW_021160128.1 chromosome 3 unlocalized genomic scaffold': 59426, 'NW_021160129.1 chromosome 3 unlocalized genomic scaffold': 72976, 'NW_021160130.1 chromosome 3 unlocalized genomic scaffold': 59576, 'NW_021160131.1 chromosome 3 unlocalized genomic scaffold': 85088, 'NW_021160132.1 chromosome 3 unlocalized genomic scaffold': 87674, 'NW_021160133.1 chromosome 3 unlocalized genomic scaffold': 102124, 'NW_021160134.1 chromosome 3 unlocalized genomic scaffold': 108614, 'NW_021160135.1 chromosome 3 unlocalized genomic scaffold': 109520, 'NW_021160136.1 chromosome 3 unlocalized genomic scaffold': 119482, 'NW_021160137.1 chromosome 3 unlocalized genomic scaffold': 140592, 'NW_021160138.1 chromosome 3 unlocalized genomic scaffold': 145282, 'NW_021160139.1 chromosome 3 unlocalized genomic scaffold': 189430, 'NW_021160140.1 chromosome 3 unlocalized genomic scaffold': 260536, 'NW_021160141.1 chromosome 3 unlocalized genomic scaffold': 268316, 'NW_021160142.1 chromosome 3 unlocalized genomic scaffold': 95628, 'NW_021160143.1 chromosome 3 unlocalized genomic scaffold': 61006, 'NW_021160144.1 chromosome 3 unlocalized genomic scaffold': 2459778, 'NW_021160145.1 chromosome 4 unlocalized genomic scaffold': 53750, 'NW_021160146.1 chromosome 4 unlocalized genomic scaffold': 54022, 'NW_021160147.1 chromosome 4 unlocalized genomic scaffold': 60074, 'NW_021160148.1 chromosome 4 unlocalized genomic scaffold': 68638, 'NW_021160149.1 chromosome 4 unlocalized genomic scaffold': 72170, 'NW_021160150.1 chromosome 4 unlocalized genomic scaffold': 74996, 'NW_021160151.1 chromosome 4 unlocalized genomic scaffold': 91412, 'NW_021160152.1 chromosome 4 unlocalized genomic scaffold': 94276, 'NW_021160153.1 chromosome 4 unlocalized genomic scaffold': 104504, 'NW_021160154.1 chromosome 4 unlocalized genomic scaffold': 108742, 'NW_021160155.1 chromosome 4 unlocalized genomic scaffold': 109060, 'NW_021160156.1 chromosome 4 unlocalized genomic scaffold': 109358, 'NW_021160157.1 chromosome 4 unlocalized genomic scaffold': 120010, 'NW_021160158.1 chromosome 4 unlocalized genomic scaffold': 150730, 'NW_021160159.1 chromosome 4 unlocalized genomic scaffold': 171586, 'NW_021160160.1 chromosome 4 unlocalized genomic scaffold': 180604, 'NW_021160161.1 chromosome 4 unlocalized genomic scaffold': 1476784, 'NW_021160162.1 chromosome 5 unlocalized genomic scaffold': 53370, 'NW_021160163.1 chromosome 5 unlocalized genomic scaffold': 59582, 'NW_021160164.1 chromosome 5 unlocalized genomic scaffold': 65280, 'NW_021160165.1 chromosome 5 unlocalized genomic scaffold': 68444, 'NW_021160166.1 chromosome 5 unlocalized genomic scaffold': 71034, 'NW_021160167.1 chromosome 5 unlocalized genomic scaffold': 75676, 'NW_021160168.1 chromosome 5 unlocalized genomic scaffold': 83302, 'NW_021160169.1 chromosome 5 unlocalized genomic scaffold': 83682, 'NW_021160170.1 chromosome 5 unlocalized genomic scaffold': 72702, 'NW_021160171.1 chromosome 5 unlocalized genomic scaffold': 97876, 'NW_021160172.1 chromosome 5 unlocalized genomic scaffold': 112884, 'NW_021160173.1 chromosome 5 unlocalized genomic scaffold': 137538, 'NW_021160174.1 chromosome 5 unlocalized genomic scaffold': 207186, 'NW_021160175.1 chromosome 5 unlocalized genomic scaffold': 370286, 'NW_021160176.1 chromosome 5 unlocalized genomic scaffold': 78186, 'NW_021160177.1 chromosome 6 unlocalized genomic scaffold': 55206, 'NW_021160178.1 chromosome 6 unlocalized genomic scaffold': 56482, 'NW_021160179.1 chromosome 6 unlocalized genomic scaffold': 77752, 'NW_021160180.1 chromosome 6 unlocalized genomic scaffold': 78786, 'NW_021160181.1 chromosome 6 unlocalized genomic scaffold': 94664, 'NW_021160182.1 chromosome 6 unlocalized genomic scaffold': 116168, 'NW_021160183.1 chromosome 6 unlocalized genomic scaffold': 115996, 'NW_021160184.1 chromosome 6 unlocalized genomic scaffold': 122600, 'NW_021160185.1 chromosome 6 unlocalized genomic scaffold': 124252, 'NW_021160186.1 chromosome 6 unlocalized genomic scaffold': 128982, 'NW_021160187.1 chromosome 6 unlocalized genomic scaffold': 152812, 'NW_021160188.1 chromosome 6 unlocalized genomic scaffold': 165900, 'NW_021160189.1 chromosome 6 unlocalized genomic scaffold': 202668, 'NW_021160190.1 chromosome 6 unlocalized genomic scaffold': 71464, 'NW_021160191.1 chromosome 7 unlocalized genomic scaffold': 55718, 'NW_021160192.1 chromosome 7 unlocalized genomic scaffold': 57596, 'NW_021160193.1 chromosome 7 unlocalized genomic scaffold': 62324, 'NW_021160194.1 chromosome 7 unlocalized genomic scaffold': 71652, 'NW_021160195.1 chromosome 7 unlocalized genomic scaffold': 82732, 'NW_021160196.1 chromosome 7 unlocalized genomic scaffold': 92210, 'NW_021160197.1 chromosome 7 unlocalized genomic scaffold': 103624, 'NW_021160198.1 chromosome 7 unlocalized genomic scaffold': 107664, 'NW_021160199.1 chromosome 7 unlocalized genomic scaffold': 111840, 'NW_021160200.1 chromosome 7 unlocalized genomic scaffold': 117998, 'NW_021160201.1 chromosome 7 unlocalized genomic scaffold': 122892, 'NW_021160202.1 chromosome 7 unlocalized genomic scaffold': 130958, 'NW_021160203.1 chromosome 7 unlocalized genomic scaffold': 144412, 'NW_021160204.1 chromosome 7 unlocalized genomic scaffold': 145672, 'NW_021160205.1 chromosome 7 unlocalized genomic scaffold': 146494, 'NW_021160206.1 chromosome 7 unlocalized genomic scaffold': 167516, 'NW_021160207.1 chromosome 7 unlocalized genomic scaffold': 197640, 'NW_021160208.1 chromosome 7 unlocalized genomic scaffold': 63536, 'NW_021160209.1 chromosome 8 unlocalized genomic scaffold': 1339966, 'NW_021160210.1 chromosome 8 unlocalized genomic scaffold': 64388, 'NW_021160211.1 chromosome 8 unlocalized genomic scaffold': 266624, 'NW_021160212.1 chromosome 8 unlocalized genomic scaffold': 70546, 'NW_021160213.1 chromosome 8 unlocalized genomic scaffold': 71564, 'NW_021160214.1 chromosome 8 unlocalized genomic scaffold': 72336, 'NW_021160215.1 chromosome 8 unlocalized genomic scaffold': 76816, 'NW_021160216.1 chromosome 8 unlocalized genomic scaffold': 57208, 'NW_021160217.1 chromosome 8 unlocalized genomic scaffold': 91688, 'NW_021160218.1 chromosome 8 unlocalized genomic scaffold': 108598, 'NW_021160219.1 chromosome 8 unlocalized genomic scaffold': 119742, 'NW_021160220.1 chromosome 8 unlocalized genomic scaffold': 133438, 'NW_021160221.1 chromosome 8 unlocalized genomic scaffold': 141728, 'NW_021160222.1 chromosome 8 unlocalized genomic scaffold': 152752, 'NW_021160223.1 chromosome 8 unlocalized genomic scaffold': 166628, 'NW_021160224.1 chromosome 8 unlocalized genomic scaffold': 59442, 'NW_021160225.1 chromosome 8 unlocalized genomic scaffold': 107664, 'NW_021160226.1 chromosome 9 unlocalized genomic scaffold': 72062, 'NW_021160227.1 chromosome 9 unlocalized genomic scaffold': 79466, 'NW_021160228.1 chromosome 9 unlocalized genomic scaffold': 95666, 'NW_021160229.1 chromosome 9 unlocalized genomic scaffold': 95960, 'NW_021160230.1 chromosome 9 unlocalized genomic scaffold': 104164, 'NW_021160231.1 chromosome 9 unlocalized genomic scaffold': 108994, 'NW_021160232.1 chromosome 9 unlocalized genomic scaffold': 113432, 'NW_021160233.1 chromosome 9 unlocalized genomic scaffold': 129284, 'NW_021160234.1 chromosome 9 unlocalized genomic scaffold': 131092, 'NW_021160235.1 chromosome 9 unlocalized genomic scaffold': 133422, 'NW_021160236.1 chromosome 9 unlocalized genomic scaffold': 155598, 'NW_021160237.1 chromosome 9 unlocalized genomic scaffold': 171448, 'NW_021160238.1 chromosome 9 unlocalized genomic scaffold': 208894, 'NW_021160239.1 chromosome 9 unlocalized genomic scaffold': 58324, 'NW_021160240.1 chromosome 9 unlocalized genomic scaffold': 95108, 'NW_021160241.1 chromosome 10 unlocalized genomic scaffold': 58980, 'NW_021160242.1 chromosome 10 unlocalized genomic scaffold': 59102, 'NW_021160243.1 chromosome 10 unlocalized genomic scaffold': 63042, 'NW_021160244.1 chromosome 10 unlocalized genomic scaffold': 70440, 'NW_021160245.1 chromosome 10 unlocalized genomic scaffold': 87524, 'NW_021160246.1 chromosome 10 unlocalized genomic scaffold': 87336, 'NW_021160247.1 chromosome 10 unlocalized genomic scaffold': 90528, 'NW_021160248.1 chromosome 10 unlocalized genomic scaffold': 149502, 'NW_021160249.1 chromosome 10 unlocalized genomic scaffold': 151384, 'NW_021160250.1 chromosome 10 unlocalized genomic scaffold': 128602, 'NW_021160251.1 chromosome 10 unlocalized genomic scaffold': 168852, 'NW_021160252.1 chromosome 10 unlocalized genomic scaffold': 177270, 'NW_021160253.1 chromosome 10 unlocalized genomic scaffold': 231098, 'NW_021160254.1 chromosome 10 unlocalized genomic scaffold': 63478, 'NW_021160255.1 chromosome 11 unlocalized genomic scaffold': 56152, 'NW_021160256.1 chromosome 11 unlocalized genomic scaffold': 61948, 'NW_021160257.1 chromosome 11 unlocalized genomic scaffold': 68188, 'NW_021160258.1 chromosome 11 unlocalized genomic scaffold': 71672, 'NW_021160259.1 chromosome 11 unlocalized genomic scaffold': 73986, 'NW_021160260.1 chromosome 11 unlocalized genomic scaffold': 85206, 'NW_021160261.1 chromosome 11 unlocalized genomic scaffold': 89586, 'NW_021160262.1 chromosome 11 unlocalized genomic scaffold': 73802, 'NW_021160263.1 chromosome 11 unlocalized genomic scaffold': 105250, 'NW_021160264.1 chromosome 11 unlocalized genomic scaffold': 130372, 'NW_021160265.1 chromosome 11 unlocalized genomic scaffold': 140178, 'NW_021160266.1 chromosome 11 unlocalized genomic scaffold': 150052, 'NW_021160267.1 chromosome 11 unlocalized genomic scaffold': 173168, 'NW_021160268.1 chromosome 11 unlocalized genomic scaffold': 135452, 'NW_021160269.1 chromosome 12 unlocalized genomic scaffold': 60922, 'NW_021160270.1 chromosome 12 unlocalized genomic scaffold': 69656, 'NW_021160271.1 chromosome 12 unlocalized genomic scaffold': 69516, 'NW_021160272.1 chromosome 12 unlocalized genomic scaffold': 69986, 'NW_021160273.1 chromosome 12 unlocalized genomic scaffold': 80400, 'NW_021160274.1 chromosome 12 unlocalized genomic scaffold': 70390, 'NW_021160275.1 chromosome 12 unlocalized genomic scaffold': 78320, 'NW_021160276.1 chromosome 13 unlocalized genomic scaffold': 107016, 'NW_021160277.1 chromosome 13 unlocalized genomic scaffold': 89706, 'NW_021160278.1 chromosome 13 unlocalized genomic scaffold': 111278, 'NW_021160279.1 chromosome 13 unlocalized genomic scaffold': 131980, 'NW_021160280.1 chromosome 13 unlocalized genomic scaffold': 115084, 'NW_021160281.1 chromosome 13 unlocalized genomic scaffold': 179740, 'NW_021160282.1 chromosome 13 unlocalized genomic scaffold': 247430, 'NW_021160283.1 chromosome 14 unlocalized genomic scaffold': 65100, 'NW_021160284.1 chromosome 14 unlocalized genomic scaffold': 69586, 'NW_021160285.1 chromosome 14 unlocalized genomic scaffold': 89210, 'NW_021160286.1 chromosome 14 unlocalized genomic scaffold': 73786, 'NW_021160287.1 chromosome 14 unlocalized genomic scaffold': 75150, 'NW_021160288.1 chromosome 14 unlocalized genomic scaffold': 75662, 'NW_021160289.1 chromosome 14 unlocalized genomic scaffold': 75322, 'NW_021160290.1 chromosome 14 unlocalized genomic scaffold': 88840, 'NW_021160291.1 chromosome 14 unlocalized genomic scaffold': 90562, 'NW_021160292.1 chromosome 14 unlocalized genomic scaffold': 92512, 'NW_021160293.1 chromosome 14 unlocalized genomic scaffold': 105660, 'NW_021160294.1 chromosome 14 unlocalized genomic scaffold': 159260, 'NW_021160295.1 chromosome 14 unlocalized genomic scaffold': 165086, 'NW_021160296.1 chromosome 14 unlocalized genomic scaffold': 102466, 'NW_021160297.1 chromosome 14 unlocalized genomic scaffold': 112454, 'NW_021160298.1 chromosome 14 unlocalized genomic scaffold': 54490, 'NW_021160299.1 chromosome 14 unlocalized genomic scaffold': 59800, 'NW_021160300.1 chromosome 14 unlocalized genomic scaffold': 124546, 'NW_021160301.1 chromosome 15 unlocalized genomic scaffold': 70822, 'NW_021160302.1 chromosome 15 unlocalized genomic scaffold': 72340, 'NW_021160303.1 chromosome 15 unlocalized genomic scaffold': 77424, 'NW_021160304.1 chromosome 15 unlocalized genomic scaffold': 79554, 'NW_021160305.1 chromosome 15 unlocalized genomic scaffold': 80612, 'NW_021160306.1 chromosome 15 unlocalized genomic scaffold': 78932, 'NW_021160307.1 chromosome 15 unlocalized genomic scaffold': 105374, 'NW_021160308.1 chromosome 15 unlocalized genomic scaffold': 107850, 'NW_021160309.1 chromosome 15 unlocalized genomic scaffold': 107852, 'NW_021160310.1 chromosome 15 unlocalized genomic scaffold': 116524, 'NW_021160311.1 chromosome 15 unlocalized genomic scaffold': 157496, 'NW_021160312.1 chromosome 15 unlocalized genomic scaffold': 176838, 'NW_021160313.1 chromosome 15 unlocalized genomic scaffold': 189254, 'NW_021160314.1 chromosome 15 unlocalized genomic scaffold': 55582, 'NW_021160315.1 chromosome 16 unlocalized genomic scaffold': 56354, 'NW_021160316.1 chromosome 16 unlocalized genomic scaffold': 67768, 'NW_021160317.1 chromosome 16 unlocalized genomic scaffold': 69490, 'NW_021160318.1 chromosome 16 unlocalized genomic scaffold': 100876, 'NW_021160319.1 chromosome 16 unlocalized genomic scaffold': 86874, 'NW_021160320.1 chromosome 16 unlocalized genomic scaffold': 105104, 'NW_021160321.1 chromosome 16 unlocalized genomic scaffold': 108116, 'NW_021160322.1 chromosome 16 unlocalized genomic scaffold': 108142, 'NW_021160323.1 chromosome 16 unlocalized genomic scaffold': 108698, 'NW_021160324.1 chromosome 16 unlocalized genomic scaffold': 127222, 'NW_021160325.1 chromosome 16 unlocalized genomic scaffold': 130300, 'NW_021160326.1 chromosome 16 unlocalized genomic scaffold': 130280, 'NW_021160327.1 chromosome 16 unlocalized genomic scaffold': 131958, 'NW_021160328.1 chromosome 16 unlocalized genomic scaffold': 126650, 'NW_021160329.1 chromosome 16 unlocalized genomic scaffold': 107402, 'NW_021160330.1 chromosome 16 unlocalized genomic scaffold': 54458, 'NW_021160331.1 chromosome 17 unlocalized genomic scaffold': 51894, 'NW_021160332.1 chromosome 17 unlocalized genomic scaffold': 363778, 'NW_021160333.1 chromosome 17 unlocalized genomic scaffold': 62182, 'NW_021160334.1 chromosome 17 unlocalized genomic scaffold': 62332, 'NW_021160335.1 chromosome 17 unlocalized genomic scaffold': 62368, 'NW_021160336.1 chromosome 17 unlocalized genomic scaffold': 62500, 'NW_021160337.1 chromosome 17 unlocalized genomic scaffold': 87220, 'NW_021160338.1 chromosome 17 unlocalized genomic scaffold': 75046, 'NW_021160339.1 chromosome 17 unlocalized genomic scaffold': 77082, 'NW_021160340.1 chromosome 17 unlocalized genomic scaffold': 90186, 'NW_021160341.1 chromosome 17 unlocalized genomic scaffold': 92612, 'NW_021160342.1 chromosome 17 unlocalized genomic scaffold': 92694, 'NW_021160343.1 chromosome 17 unlocalized genomic scaffold': 100750, 'NW_021160344.1 chromosome 17 unlocalized genomic scaffold': 118052, 'NW_021160345.1 chromosome 17 unlocalized genomic scaffold': 123372, 'NW_021160346.1 chromosome 17 unlocalized genomic scaffold': 123814, 'NW_021160347.1 chromosome 17 unlocalized genomic scaffold': 330538, 'NW_021160348.1 chromosome 17 unlocalized genomic scaffold': 54250, 'NW_021160349.1 chromosome 17 unlocalized genomic scaffold': 30708, 'NW_021160350.1 chromosome 18 unlocalized genomic scaffold': 64600, 'NW_021160351.1 chromosome 18 unlocalized genomic scaffold': 74290, 'NW_021160352.1 chromosome 18 unlocalized genomic scaffold': 75328, 'NW_021160353.1 chromosome 18 unlocalized genomic scaffold': 82352, 'NW_021160354.1 chromosome 18 unlocalized genomic scaffold': 83948, 'NW_021160355.1 chromosome 18 unlocalized genomic scaffold': 111108, 'NW_021160356.1 chromosome 18 unlocalized genomic scaffold': 152632, 'NW_021160357.1 chromosome 19 unlocalized genomic scaffold': 60900, 'NW_021160358.1 chromosome 19 unlocalized genomic scaffold': 78910, 'NW_021160359.1 chromosome 19 unlocalized genomic scaffold': 82112, 'NW_021160360.1 chromosome 19 unlocalized genomic scaffold': 88364, 'NW_021160361.1 chromosome 19 unlocalized genomic scaffold': 94152, 'NW_021160362.1 chromosome 19 unlocalized genomic scaffold': 107334, 'NW_021160363.1 chromosome 19 unlocalized genomic scaffold': 121856, 'NW_021160364.1 chromosome 19 unlocalized genomic scaffold': 123634, 'NW_021160365.1 chromosome 19 unlocalized genomic scaffold': 132866, 'NW_021160366.1 chromosome 19 unlocalized genomic scaffold': 142514, 'NW_021160367.1 chromosome 19 unlocalized genomic scaffold': 152780, 'NW_021160368.1 chromosome 19 unlocalized genomic scaffold': 157878, 'NW_021160369.1 chromosome 19 unlocalized genomic scaffold': 163558, 'NW_021160370.1 chromosome 19 unlocalized genomic scaffold': 178986,

{'labels': 1, 'species': 'Macaca mulatta', 'sampled_chromosomes': ['NC_041773.1 chromosome 20 ', 'NC_041767.1 chromosome 14 ', 'NC_041767.1 chromosome 14 ', 'NC_041754.1 chromosome 1 ', 'NC_041758.1 chromosome 5 ', 'NC_041774.1 chromosome X ', 'NC_041755.1 chromosome 2 ', 'NC_041765.1 chromosome 12 ', 'NC_041760.1 chromosome 7 ', 'NC_041756.1 chromosome 3 '], 'chunks': ['ATGTGTGTGT', 'AACTTTCTCC', 'TTTTCCTCAA', 'GTCTCGATCT', 'ACGAGATCTG', 'TTACTTACAG', 'AAGCTGCTGT', 'TAATACTTTC', 'AATTACCTTG', 'TGGCTCTGTT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Mustela lutreola', 'sampled_chromosomes': ['NC_081291.1 chromosome 2 ', 'NC_081292.1 chromosome 3 ', 'NC_081304.1 chromosome 15 ', 'NC_081290.1 chromosome 1 ', 'NC_081294.1 chromosome 5 ', 'NC_081297.1 chromosome 8 ', 'NC_081297.1 chromosome 8 ', 'NC_081298.1 chromosome 9 ', 'NC_081296.1 chromosome 7 ', 'NC_081293.1 chromosome 4 '], 'chunks': ['GGAAAGGCTC', 'GGATTTTCCA', 'GATGACCTCC', 'TTTTGTTTGT', 'CTGTGGATTC', 'AATTATAACC', 'AATTATGTGC', 'CTCAGCGGCC', 'TGCCACTCTG', 'AGCTGTTCCC'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}

DEBUG:mammals_gender_dataset:Label: 0.0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Rattus rattus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011064425.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_046172.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_046154.1 chromosome 1 ', 'NC_046155.1 chromosome 2 ', 'NC_046156.1 chromosome 3 ', 'NC_046157.1 chromosome 4 ', 'NC_046158.1 chromosome 5 ', 'NC_046159.1 chromosome 6 ', 'NC_046160.1 chromosome 7 ', 'NC_046161.1 chromosome 8 ', 'NC_046162.1 chromosome 9 ', 'NC_046163.1 chromosome 10 ', 'NC_046164.1 chromosome 11 ', 'NC_046165.1 chromosome 12 ', 'NC_046166.1 chromosome 13 ', 'NC_046167.1 chromosome 14 ', 'NC_046168.1 chromosome 15 ', 'NC_046169.1 chromosome 16 ', 'NC_046170.1 chromosome 17 ', 'NC_046171.1 chromosome 18 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_046172.1 chromosome X ': 260747026, 'NC_046154.1 chromosome 1 ': 545899780, 'NC_046155.1 chromosome 2 ': 460490430, 'NC_046156.1 chromosome 3 ': 446780580, 'NC_046157.1 chromosome 4 ': 365650368, 'NC_046158.1 chromosome 5 ': 317649504, 'NC_046159.1 chromosome 6 ': 319153832, 'NC_046160.1 chromosome 7 ': 261677498, 'NC_046161.1 chromosome 8 ': 230657978, 'NC_046162.1 chromosome 9 ': 193419404, 'NC_046163.1 chromosome 10 ': 189950930, 'NC_046164.1 chromosome 11 ': 197229706, 'NC_046165.1 chromosome 12 ': 188176076, 'NC_046166.1 chromosome 13 ': 157637022, 'NC_046167.1 chromosome 14 ': 163988198, 'NC_046168.1 chromosome 15 ': 158636486, 'NC_046169.1 chromosome 16 ': 88862024, 'NC_046170.1 chromosome 17 ': 97008248, 'NC_046171.1 chromosome 18 ': 99693070}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_046172.1 chromosome X ': 0.05497155512662285, 'NC_046154.1 chromosome 1 ': 0.11508840699061812, 'NC_046155.1 chromosome 2 ': 0.09708212379775047, 'NC_046156.1 chromosome 3 ': 0.09419176762911394, 'NC_046157.1 chromosome 4 ': 0.07708762653953312, 'NC_046158.1 chromosome 5 ': 0.0669679247658242, 'NC_046159.1 chromosome 6 ': 0.06728507219737542, 'NC_046160.1 chromosome 7 ': 0.055167720327915615, 'NC_046161.1 chromosome 8 ': 0.04862808196716445, 'NC_046162.1 chromosome 9 ': 0.040777321960882254, 'NC_046163.1 chromosome 10 ': 0.04004608673791078, 'NC_046164.1 chromosome 11 ': 0.04158062249955103, 'NC_046165.1 chromosome 12 ': 0.03967190611541461, 'NC_046166.1 chromosome 13 ': 0.03323356119455667, 'NC_046167.1 chromosome 14 ': 0.03457253723949489, 'NC_046168.1 chromosome 15 ': 0.03344427151871997, 'NC_046169.1 chromosome 16 ': 0.01873418740729677, 'NC_046170.1 chromosome 17 ': 0.020451601440965625, 'NC_046171.1 chromosome 18 ': 0.021017624543289214}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Rattus rattus
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_011064425.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_046172.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_046154.1 chromosome 1 ', 'NC_046155.1 chromosome 2 ', 'NC_046156.1 chromosome 3 ', 'NC_046157.1 chromosome 4 ', 'NC_046158.1 chromosome 5 ', 'NC_046159.1 chromosome 6 ', 'NC_046160.1 chromosome 7 ', 'NC_046161.1 chromosome 8 ', 'NC_046162.1 chromosome 9 ', 'NC_046163.1 chromosome 10 ', 'NC_046164.1 chromosome 11 ', 'NC_046165.1 chromosome 12 ', 'NC_046166.1 chromosome 13 ', 'NC_046167.1 chromosome 14 ', 'NC_046168.1 chromosome 15 ', 'NC_046169.1 chromosome 16 ', 'NC_046170.1 chromosome 17 ', 'NC_046171.1 chromosome 18 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_046172.1 chromosome X ': 260747026, 'NC_046154.1 chromosome 1 ': 545899780, 'NC_046155.1 chromosome 2 ': 460490430, 'NC_046156.1 chromosome 3 ': 446780580, 'NC_046157.1 chromosome 4 ': 365650368, 'NC_046158.1 chromosome 5 ': 317649504, 'NC_046159.1 chromosome 6 ': 319153832, 'NC_046160.1 chromosome 7 ': 261677498, 'NC_046161.1 chromosome 8 ': 230657978, 'NC_046162.1 chromosome 9 ': 193419404, 'NC_046163.1 chromosome 10 ': 189950930, 'NC_046164.1 chromosome 11 ': 197229706, 'NC_046165.1 chromosome 12 ': 188176076, 'NC_046166.1 chromosome 13 ': 157637022, 'NC_046167.1 chromosome 14 ': 163988198, 'NC_046168.1 chromosome 15 ': 158636486, 'NC_046169.1 chromosome 16 ': 88862024, 'NC_046170.1 chromosome 17 ': 97008248, 'NC_046171.1 chromosome 18 ': 99693070}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_046172.1 chromosome X ': 0.05497155512662285, 'NC_046154.1 chromosome 1 ': 0.11508840699061812, 'NC_046155.1 chromosome 2 ': 0.09708212379775047, 'NC_046156.1 chromosome 3 ': 0.09419176762911394, 'NC_046157.1 chromosome 4 ': 0.07708762653953312, 'NC_046158.1 chromosome 5 ': 0.0669679247658242, 'NC_046159.1 chromosome 6 ': 0.06728507219737542, 'NC_046160.1 chromosome 7 ': 0.055167720327915615, 'NC_046161.1 chromosome 8 ': 0.04862808196716445, 'NC_046162.1 chromosome 9 ': 0.040777321960882254, 'NC_046163.1 chromosome 10 ': 0.04004608673791078, 'NC_046164.1 chromosome 11 ': 0.04158062249955103, 'NC_046165.1 chromosome 12 ': 0.03967190611541461, 'NC_046166.1 chromosome 13 ': 0.03323356119455667, 'NC_046167.1 chromosome 14 ': 0.03457253723949489, 'NC_046168.1 chromosome 15 ': 0.03344427151871997, 'NC_046169.1 chromosome 16 ': 0.01873418740729677, 'NC_046170.1 chromosome 17 ': 0.020451601440965625, 'NC_046171.1 chromosome 18 ': 0.021017624543289214}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:Sample organism name: Neomonachus schauinslandi
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_002201575.2
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_058420.1 chromosome Y ', 'NC_058419.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_058403.1 chromosome 1 ', 'NC_058404.1 chromosome 2 ', 'NC_058405.1 chromosome 3 ', 'NC_058406.1 chromosome 4 ', 'NC_058407.1 chromosome 5 ', 'NC_058408.1 chromosome 6 ', 'NC_058409.1 chromosome 7 ', 'NC_058410.1 chromosome 8 ', 'NC_058411.1 chromosome 9 ', 'NC_058412.1 chromosome 10 ', 'NC_058413.1 chromosome 11 ', 'NC_058414.1 chromosome 12 ', 'NC_058415.1 chromosome 13 ', 'NC_058416.1 chromosome 14 ', 'NC_058417.1 chromosome 15 ', 'NC_058418.1 chromosome 16 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_058420.1 chromosome Y ': 5277812, 'NC_058419.1 chromosome X ': 126494893, 'NC_058403.1 chromosome 1 ': 429366354, 'NC_058404.1 chromosome 2 ': 407736248, 'NC_058405.1 chromosome 3 ': 385675150, 'NC_058406.1 chromosome 4 ': 376368364, 'NC_058407.1 chromosome 5 ': 352990000, 'NC_058408.1 chromosome 6 ': 309600356, 'NC_058409.1 chromosome 7 ': 301621650, 'NC_058410.1 chromosome 8 ': 291868190, 'NC_058411.1 chromosome 9 ': 287733078, 'NC_058412.1 chromosome 10 ': 276814350, 'NC_058413.1 chromosome 11 ': 222157914, 'NC_058414.1 chromosome 12 ': 211869670, 'NC_058415.1 chromosome 13 ': 187349136, 'NC_058416.1 chromosome 14 ': 184857912, 'NC_058417.1 chromosome 15 ': 120033060, 'NC_058418.1 chromosome 16 ': 118930010}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_058420.1 chromosome Y ': 0.0011481630978840728, 'NC_058419.1 chromosome X ': 0.02751836712133633, 'NC_058403.1 chromosome 1 ': 0.09340662439962422, 'NC_058404.1 chromosome 2 ': 0.08870109689835648, 'NC_058405.1 chromosome 3 ': 0.08390180912107223, 'NC_058406.1 chromosome 4 ': 0.08187716173971342, 'NC_058407.1 chromosome 5 ': 0.07679130895948906, 'NC_058408.1 chromosome 6 ': 0.06735209663606279, 'NC_058409.1 chromosome 7 ': 0.06561636679231954, 'NC_058410.1 chromosome 8 ': 0.06349454758983783, 'NC_058411.1 chromosome 9 ': 0.06259497348526237, 'NC_058412.1 chromosome 10 ': 0.06021965572755642, 'NC_058413.1 chromosome 11 ': 0.04832940596552197, 'NC_058414.1 chromosome 12 ': 0.04609124702715372, 'NC_058415.1 chromosome 13 ': 0.04075692055262, 'NC_058416.1 chromosome 14 ': 0.04021496652595836, 'NC_058417.1 chromosome 15 ': 0.026112625841561765, 'NC_058418.1 chromosome 16 ': 0.025872662518669435}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Delphinus delphis
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_949987515.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_082704.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_082683.1 chromosome 1 ', 'NC_082684.1 chromosome 2 ', 'NC_082685.1 chromosome 3 ', 'NC_082686.1 chromosome 4 ', 'NC_082687.1 chromosome 5 ', 'NC_082688.1 chromosome 6 ', 'NC_082689.1 chromosome 7 ', 'NC_082690.1 chromosome 8 ', 'NC_082691.1 chromosome 9 ', 'NC_082692.1 chromosome 10 ', 'NC_082693.1 chromosome 11 ', 'NC_082694.1 chromosome 12 ', 'NC_082695.1 chromosome 13 ', 'NC_082696.1 chromosome 14 ', 'NC_082697.1 chromosome 15 ', 'NC_082698.1 chromosome 16 ', 'NC_082699.1 chromosome 17 ', 'NC_082700.1 chromosome 18 ', 'NC_082701.1 chromosome 19 ', 'NC_082702.1 chromosome 20 ', 'NC_082703.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_082704.1 chromosome X ': 252958184, 'NC_082683.1 chromosome 1 ': 369735110, 'NC_082684.1 chromosome 2 ': 356731664, 'NC_082685.1 chromosome 3 ': 346114934, 'NC_082686.1 chromosome 4 ': 289038024, 'NC_082687.1 chromosome 5 ': 278427586, 'NC_082688.1 chromosome 6 ': 233193856, 'NC_082689.1 chromosome 7 ': 231072564, 'NC_082690.1 chromosome 8 ': 221068098, 'NC_082691.1 chromosome 9 ': 214161966, 'NC_082692.1 chromosome 10 ': 209825618, 'NC_082693.1 chromosome 11 ': 204893786, 'NC_082694.1 chromosome 12 ': 179785098, 'NC_082695.1 chromosome 13 ': 179611866, 'NC_082696.1 chromosome 14 ': 177695210, 'NC_082697.1 chromosome 15 ': 176080914, 'NC_082698.1 chromosome 16 ': 170657774, 'NC_082699.1 chromosome 17 ': 161332118, 'NC_082700.1 chromosome 18 ': 157641024, 'NC_082701.1 chromosome 19 ': 120427388, 'NC_082702.1 chromosome 20 ': 118940318, 'NC_082703.1 chromosome 21 ': 71183194}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_082704.1 chromosome X ': 0.053586292911210386, 'NC_082683.1 chromosome 1 ': 0.07832414666614855, 'NC_082684.1 chromosome 2 ': 0.0755695156232126, 'NC_082685.1 chromosome 3 ': 0.07332048301812702, 'NC_082686.1 chromosome 4 ': 0.06122939361606683, 'NC_082687.1 chromosome 5 ': 0.05898169389908816, 'NC_082688.1 chromosome 6 ': 0.04939944648207396, 'NC_082689.1 chromosome 7 ': 0.048950075077422314, 'NC_082690.1 chromosome 8 ': 0.046830743585478, 'NC_082691.1 chromosome 9 ': 0.04536775865103728, 'NC_082692.1 chromosome 10 ': 0.044449153012672396, 'NC_082693.1 chromosome 11 ': 0.04340440091190273, 'NC_082694.1 chromosome 12 ': 0.038085413051900566, 'NC_082695.1 chromosome 13 ': 0.038048715837575235, 'NC_082696.1 chromosome 14 ': 0.037642694224825086, 'NC_082697.1 chromosome 15 ': 0.03730072411366475, 'NC_082698.1 chromosome 16 ': 0.03615189404245227, 'NC_082699.1 chromosome 17 ': 0.03417636067127189, 'NC_082700.1 chromosome 18 ': 0.03339444469955218, 'NC_082701.1 chromosome 19 ': 0.0255111623030152, 'NC_082702.1 chromosome 20 ': 0.02519614356221228, 'NC_082703.1 chromosome 21 ': 0.015079344039090326}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 0.9999999999999999
DEBUG:mammals_gender_dataset:Label: 1
DEBUG:mammals_gender_dataset:Sample has Y chromosome: False
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: False
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:Sample organism name: Mustela erminea
DEBUG:mammals_gender_dataset:Sample/assembly id: GCF_009829155.1
DEBUG:mammals_gender_dataset:Diploid: False
DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sex chromosomes: ['NC_045636.1 chromosome Y ', 'NC_045635.1 chromosome X ']
DEBUG:mammals_gender_dataset:Autosomes: ['NC_045614.1 chromosome 1 ', 'NC_045615.1 chromosome 2 ', 'NC_045616.1 chromosome 3 ', 'NC_045617.1 chromosome 4 ', 'NC_045618.1 chromosome 5 ', 'NC_045619.1 chromosome 6 ', 'NC_045620.1 chromosome 7 ', 'NC_045621.1 chromosome 8 ', 'NC_045622.1 chromosome 9 ', 'NC_045623.1 chromosome 10 ', 'NC_045624.1 chromosome 11 ', 'NC_045625.1 chromosome 12 ', 'NC_045626.1 chromosome 13 ', 'NC_045627.1 chromosome 14 ', 'NC_045628.1 chromosome 15 ', 'NC_045629.1 chromosome 16 ', 'NC_045630.1 chromosome 17 ', 'NC_045631.1 chromosome 18 ', 'NC_045632.1 chromosome 19 ', 'NC_045633.1 chromosome 20 ', 'NC_045634.1 chromosome 21 ']
DEBUG:mammals_gender_dataset:Chromosomes length: {'NC_045636.1 chromosome Y ': 5451993, 'NC_045635.1 chromosome X ': 130149454, 'NC_045614.1 chromosome 1 ': 440707378, 'NC_045615.1 chromosome 2 ': 331357966, 'NC_045616.1 chromosome 3 ': 328770848, 'NC_045617.1 chromosome 4 ': 302680028, 'NC_045618.1 chromosome 5 ': 296174906, 'NC_045619.1 chromosome 6 ': 290223092, 'NC_045620.1 chromosome 7 ': 282916320, 'NC_045621.1 chromosome 8 ': 229450082, 'NC_045622.1 chromosome 9 ': 228192686, 'NC_045623.1 chromosome 10 ': 219496374, 'NC_045624.1 chromosome 11 ': 213757318, 'NC_045625.1 chromosome 12 ': 187231206, 'NC_045626.1 chromosome 13 ': 185798618, 'NC_045627.1 chromosome 14 ': 184280032, 'NC_045628.1 chromosome 15 ': 172274730, 'NC_045629.1 chromosome 16 ': 170932264, 'NC_045630.1 chromosome 17 ': 141640406, 'NC_045631.1 chromosome 18 ': 123844424, 'NC_045632.1 chromosome 19 ': 121449576, 'NC_045633.1 chromosome 20 ': 80416618, 'NC_045634.1 chromosome 21 ': 80414020}
DEBUG:mammals_gender_dataset:Chromosomes probabilities: {'NC_045636.1 chromosome Y ': 0.0011483657273247, 'NC_045635.1 chromosome X ': 0.02741367650391748, 'NC_045614.1 chromosome 1 ': 0.09282720074554965, 'NC_045615.1 chromosome 2 ': 0.0697946845548817, 'NC_045616.1 chromosome 3 ': 0.0692497539866024, 'NC_045617.1 chromosome 4 ': 0.06375418502937927, 'NC_045618.1 chromosome 5 ': 0.06238399633748881, 'NC_045619.1 chromosome 6 ': 0.061130352172316306, 'NC_045620.1 chromosome 7 ': 0.0595913101115184, 'NC_045621.1 chromosome 8 ': 0.04832959438881195, 'NC_045622.1 chromosome 9 ': 0.04806474619988816, 'NC_045623.1 chromosome 10 ': 0.04623302215788691, 'NC_045624.1 chromosome 11 ': 0.045024191695779356, 'NC_045625.1 chromosome 12 ': 0.03943693619123698, 'NC_045626.1 chromosome 13 ': 0.03913518691155584, 'NC_045627.1 chromosome 14 ': 0.03881532367688274, 'NC_045628.1 chromosome 15 ': 0.03628661951989232, 'NC_045629.1 chromosome 16 ': 0.03600385284273432, 'NC_045630.1 chromosome 17 ': 0.029834041946634155, 'NC_045631.1 chromosome 18 ': 0.02608563364660749, 'NC_045632.1 chromosome 19 ': 0.02558120134719843, 'NC_045633.1 chromosome 20 ': 0.016938335764290702, 'NC_045634.1 chromosome 21 ': 0.01693778854162193}
DEBUG:mammals_gender_dataset:Chromosomes probabilities sum: 1.0000000000000002

{'labels': 0.0, 'species': 'Mus musculus', 'sampled_chromosomes': ['T+_Itpr3tf_J_chr15', 'T+_Itpr3tf_J_chr2', 'T+_Itpr3tf_J_chrY', 'T+_Itpr3tf_J_chr9', 'T+_Itpr3tf_J_chr7', 'T+_Itpr3tf_J_chr4', 'T+_Itpr3tf_J_chrX', 'T+_Itpr3tf_J_chr4', 'T+_Itpr3tf_J_chr3', 'T+_Itpr3tf_J_chr14'], 'chunks': ['CAATCCCAGA', 'ATACATAATA', 'TACATACCAT', 'TCCCATTTGT', 'GCCAACATCA', 'TTCTTTTCTT', 'CTCCCACAAA', 'AACCTTCCCA', 'ATTTCCATAC', 'CAGAGGCAGG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Rattus rattus', 'sampled_chromosomes': ['NC_046154.1 chromosome 1 ', 'NC_046158.1 chromosome 5 ', 'NC_046164.1 chromosome 11 ', 'NC_046159.1 chromosome 6 ', 'NC_046171.1 chromosome 18 ', 'NC_046167.1 chromosome 14 ', 'NC_046159.1 chromosome 6 ', 'NC_046161.1 chromosome 8 ', 'NC_046160.1 chromosome 7 ', 'NC_046161.1 chromosome 8 '], 'chunks': ['TCTTCTAGTG', 'TTCCACTGTC', 'TGTAAATGGC', 'TTTTCTGACC', 'GACAGATGGT', 'ATTTCAGGAT', 'GCTCACTGAA', 'AATCATAATT', 'TAACGTCCAT', 'GAGCCTTCAG'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 1, 'species': 'Rattus rattus', 'sampled_chromosomes': ['NC_046155.1 chromosome 2 ', 'NC_046166.1 chromosome 13 ', 'NC_046158.1 chromosome 5 ', 'NC_046161.1 chromosome 8 ', 'NC_046159.1 chromosome 6 ', 'NC_046155.1 chromosome 2 ', 'NC_046162.1 chromosome 9 ', 'NC_046165.1 chromosome 12 ', 'NC_046163.1 chromosome 10 ', 'NC_046167.1 chromosome 14 '], 'chunks': ['GAAGTAAAGT', 'GAGAAGCTGG', 'ATCACCACTG', 'TGAAGACAAG', 'TTGTAACTCT', 'CAAGGCTGGT', 'TGCGCAATGA', 'GTGTCATAGA', 'TAGATAACCT', 'CATTTCAGTT'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': False}
{'labels': 0, 'species': 'Neomonachus schauinslandi', 'sampled_chromosomes': ['NC_058419.1 chromosome X ', 'NC_058405.1 chromosome 3 ', 'NC_058420.1 chromosome Y ', 'NC_058416.1 chromosome 14 ', 'NC_058416.1 chromosome 14 ', 'NC_058404.1 chromosome 2 ', 'NC_058409.1 chromosome 7 ', 'NC_058413.1 chromosome 11 ', 'NC_058415.1 chromosome 13 ', 'NC_058409.1 chromosome 7 '], 'chunks': ['TACACATTTA', 'ATTGAAGGGG', 'ACACTGGGAA', 'TACATATATT', 'AGTGCCAGCC', 'AGTATAAATC', 'TAGGTTAAGA', 'TATTTAACAT', 'TTGATTTTGG', 'CCTTTAAGAC'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': True}
{'labels': 1, 'species': 'Delphinus delphis', 'sampled_chromosomes': ['NC_082686.1 chromosome 4 ', 'NC_082699.1 chromosome 17 ', 'NC_082703.1 chromosome 21 ', 'NC_082683.1 chromosome 1 ', 'NC_082687.1 chromosome 5 ', 'NC_082699.1 chromosome 17 ', 'NC_082692.1 chromosome 10 ', 'NC_082685.1 chromosome 3 ', 'NC_082704.1 chromosome X ', 'NC_082685.1 chromosome 3 '], 'chunks': ['CTAAAGGTGT', 'TGTGAAGGAA', 'AGCAGAGGGC', 'TAAGCATATC', 'ATTCTTTTGT', 'TGCCGCGGAG', 'ATTTCATCTG', 'CTGTGTGTCT', 'TGCTGCAGGC', 'TTACTCACCA'], 'full_sample_has_y_chr': False, 'has_y_chr_sampled': False, 'has_x_chr_sampled': True}

DEBUG:mammals_gender_dataset:Label: 0
DEBUG:mammals_gender_dataset:Sample has Y chromosome: True
DEBUG:mammals_gender_dataset:Y chromosome in sampled chromosomes: True
DEBUG:mammals_gender_dataset:X chromosome in sampled chromosomes: False

{'labels': 0, 'species': 'Mustela erminea', 'sampled_chromosomes': ['NC_045614.1 chromosome 1 ', 'NC_045626.1 chromosome 13 ', 'NC_045615.1 chromosome 2 ', 'NC_045618.1 chromosome 5 ', 'NC_045615.1 chromosome 2 ', 'NC_045618.1 chromosome 5 ', 'NC_045626.1 chromosome 13 ', 'NC_045636.1 chromosome Y ', 'NC_045615.1 chromosome 2 ', 'NC_045627.1 chromosome 14 '], 'chunks': ['AAAAAAAGAG', 'ACAAGTAGAC', 'TGTGGTGAGC', 'CACTTATCTT', 'TATGGTTTTG', 'AATTACGTGA', 'TTCGAGCGAA', 'CCTGGATGAT', 'AATTGGATAT', 'TGTATGAATG'], 'full_sample_has_y_chr': True, 'has_y_chr_sampled': True, 'has_x_chr_sampled': False}