In [1]:
import pandas as pd
import os

import re

from Bio import SeqIO
import h5py

In [2]:
# ! pip install opentree
# ! pip install biopython
# ! pip install ete3
# ! pip install matplotlib
# ! pip install PyQt5
# ! pip install ete3

In [5]:
def read_chunk_from_hdf5(hdf5_path, dataset_name, start, length):
    with h5py.File(hdf5_path, 'r') as hdf5_file:
        dset = hdf5_file[dataset_name]
        chunk = dset[start:start + length].astype(str)
        return ''.join(chunk)

In [11]:
with h5py.File("mammals_gender_data/train.h5", 'r') as hdf5_file:
    print(hdf5_file['GCF_000001405.40'].keys())

<KeysViewHDF5 ['NC_000001.11 chromosome 1 ', 'NC_000002.12 chromosome 2 ', 'NC_000003.12 chromosome 3 ', 'NC_000004.12 chromosome 4 ', 'NC_000005.10 chromosome 5 ', 'NC_000006.12 chromosome 6 ', 'NC_000007.14 chromosome 7 ', 'NC_000008.11 chromosome 8 ', 'NC_000009.12 chromosome 9 ', 'NC_000010.11 chromosome 10 ', 'NC_000011.10 chromosome 11 ', 'NC_000012.12 chromosome 12 ', 'NC_000013.11 chromosome 13 ', 'NC_000014.9 chromosome 14 ', 'NC_000015.10 chromosome 15 ', 'NC_000016.10 chromosome 16 ', 'NC_000017.11 chromosome 17 ', 'NC_000018.10 chromosome 18 ', 'NC_000019.10 chromosome 19 ', 'NC_000020.11 chromosome 20 ', 'NC_000021.9 chromosome 21 ', 'NC_000022.11 chromosome 22 ', 'NC_000023.11 chromosome X ', 'NC_000024.10 chromosome Y ', 'NT_113793.3 chromosome 4 unlocalized genomic scaffold', 'NT_113796.3 chromosome 14 unlocalized genomic scaffold', 'NT_113888.1 chromosome 14 unlocalized genomic scaffold', 'NT_113891.3 chromosome 6 genomic scaffold', 'NT_113930.2 chromosome 17 unlocalized genomic scaffold', 'NT_113948.1 chromosome 5 unlocalized genomic scaffold', 'NT_113949.2 chromosome 19 genomic scaffold', 'NT_167215.1 chromosome 3 unlocalized genomic scaffold', 'NT_167219.1 chromosome 14 unlocalized genomic scaffold', 'NT_167244.2 chromosome 6 genomic scaffold', 'NT_167245.2 chromosome 6 genomic scaffold', 'NT_167246.2 chromosome 6 genomic scaffold', 'NT_167247.2 chromosome 6 genomic scaffold', 'NT_167248.2 chromosome 6 genomic scaffold', 'NT_167249.2 chromosome 6 genomic scaffold', 'NT_167250.2 chromosome 4 genomic scaffold', 'NT_167251.2 chromosome 17 genomic scaffold', 'NT_187361.1 chromosome 1 unlocalized genomic scaffold', 'NT_187362.1 chromosome 1 unlocalized genomic scaffold', 'NT_187363.1 chromosome 1 unlocalized genomic scaffold', 'NT_187364.1 chromosome 1 unlocalized genomic scaffold', 'NT_187365.1 chromosome 1 unlocalized genomic scaffold', 'NT_187366.1 chromosome 1 unlocalized genomic scaffold', 'NT_187367.1 chromosome 1 unlocalized genomic scaffold', 'NT_187368.1 chromosome 1 unlocalized genomic scaffold', 'NT_187369.1 chromosome 1 unlocalized genomic scaffold', 'NT_187370.1 chromosome 2 unlocalized genomic scaffold', 'NT_187371.1 chromosome 2 unlocalized genomic scaffold', 'NT_187372.1 chromosome 9 unlocalized genomic scaffold', 'NT_187373.1 chromosome 9 unlocalized genomic scaffold', 'NT_187374.1 chromosome 9 unlocalized genomic scaffold', 'NT_187375.1 chromosome 9 unlocalized genomic scaffold', 'NT_187377.1 chromosome 14 unlocalized genomic scaffold', 'NT_187378.1 chromosome 14 unlocalized genomic scaffold', 'NT_187379.1 chromosome 14 unlocalized genomic scaffold', 'NT_187380.1 chromosome 14 unlocalized genomic scaffold', 'NT_187381.1 chromosome 14 unlocalized genomic scaffold', 'NT_187382.1 chromosome 15 unlocalized genomic scaffold', 'NT_187383.1 chromosome 16 unlocalized genomic scaffold', 'NT_187384.1 chromosome 17 unlocalized genomic scaffold', 'NT_187385.1 chromosome 17 unlocalized genomic scaffold', 'NT_187386.1 chromosome 22 unlocalized genomic scaffold', 'NT_187387.1 chromosome 22 unlocalized genomic scaffold', 'NT_187388.1 chromosome 22 unlocalized genomic scaffold', 'NT_187390.1 chromosome 22 unlocalized genomic scaffold', 'NT_187391.1 chromosome 22 unlocalized genomic scaffold', 'NT_187392.1 chromosome 22 unlocalized genomic scaffold', 'NT_187393.1 chromosome 22 unlocalized genomic scaffold', 'NT_187394.1 chromosome 22 unlocalized genomic scaffold', 'NT_187395.1 chromosome Y unlocalized genomic scaffold', 'NT_187514.1 chromosome 1 genomic scaffold', 'NT_187515.1 chromosome 1 genomic scaffold', 'NT_187516.1 chromosome 1 genomic scaffold', 'NT_187517.1 chromosome 1 genomic scaffold', 'NT_187518.1 chromosome 1 genomic scaffold', 'NT_187519.1 chromosome 1 genomic scaffold', 'NT_187520.1 chromosome 1 genomic scaffold', 'NT_187521.1 chromosome 1 genomic scaffold', 'NT_187522.1 chromosome 2 genomic scaffold', 'NT_187523.1 chromosome 2 genomic scaffold', 'NT_187524.1 chromosome 2 genomic scaffold', 'NT_187525.1 chromosome 2 genomic scaffold', 'NT_187526.1 chromosome 2 genomic scaffold', 'NT_187527.1 chromosome 2 genomic scaffold', 'NT_187528.1 chromosome 2 genomic scaffold', 'NT_187529.1 chromosome 2 genomic scaffold', 'NT_187530.1 chromosome 2 genomic scaffold', 'NT_187531.1 chromosome 2 genomic scaffold', 'NT_187532.1 chromosome 3 genomic scaffold', 'NT_187533.1 chromosome 3 genomic scaffold', 'NT_187534.1 chromosome 3 genomic scaffold', 'NT_187535.1 chromosome 3 genomic scaffold', 'NT_187536.1 chromosome 3 genomic scaffold', 'NT_187537.1 chromosome 3 genomic scaffold', 'NT_187538.1 chromosome 3 genomic scaffold', 'NT_187539.1 chromosome 3 genomic scaffold', 'NT_187540.1 chromosome 4 genomic scaffold', 'NT_187541.1 chromosome 4 genomic scaffold', 'NT_187542.1 chromosome 4 genomic scaffold', 'NT_187543.1 chromosome 4 genomic scaffold', 'NT_187544.1 chromosome 4 genomic scaffold', 'NT_187545.1 chromosome 4 genomic scaffold', 'NT_187546.1 chromosome 5 genomic scaffold', 'NT_187547.1 chromosome 5 genomic scaffold', 'NT_187548.1 chromosome 5 genomic scaffold', 'NT_187549.1 chromosome 5 genomic scaffold', 'NT_187550.1 chromosome 5 genomic scaffold', 'NT_187551.1 chromosome 5 genomic scaffold', 'NT_187552.1 chromosome 6 genomic scaffold', 'NT_187553.1 chromosome 6 genomic scaffold', 'NT_187554.1 chromosome 6 genomic scaffold', 'NT_187555.1 chromosome 6 genomic scaffold', 'NT_187556.1 chromosome 6 genomic scaffold', 'NT_187557.1 chromosome 6 genomic scaffold', 'NT_187558.1 chromosome 7 genomic scaffold', 'NT_187559.1 chromosome 7 genomic scaffold', 'NT_187560.1 chromosome 7 genomic scaffold', 'NT_187561.1 chromosome 7 genomic scaffold', 'NT_187562.1 chromosome 7 genomic scaffold', 'NT_187563.1 chromosome 7 genomic scaffold', 'NT_187564.1 chromosome 7 genomic scaffold', 'NT_187565.1 chromosome 8 genomic scaffold', 'NT_187566.1 chromosome 8 genomic scaffold', 'NT_187567.1 chromosome 8 genomic scaffold', 'NT_187568.1 chromosome 8 genomic scaffold', 'NT_187569.1 chromosome 8 genomic scaffold', 'NT_187570.1 chromosome 8 genomic scaffold', 'NT_187571.1 chromosome 8 genomic scaffold', 'NT_187572.1 chromosome 8 genomic scaffold', 'NT_187573.1 chromosome 8 genomic scaffold', 'NT_187574.1 chromosome 8 genomic scaffold', 'NT_187575.1 chromosome 8 genomic scaffold', 'NT_187576.1 chromosome 8 genomic scaffold', 'NT_187577.1 chromosome 8 genomic scaffold', 'NT_187578.1 chromosome 9 genomic scaffold', 'NT_187579.1 chromosome 10 genomic scaffold', 'NT_187581.1 chromosome 11 genomic scaffold', 'NT_187582.1 chromosome 11 genomic scaffold', 'NT_187583.1 chromosome 11 genomic scaffold', 'NT_187584.1 chromosome 11 genomic scaffold', 'NT_187585.1 chromosome 11 genomic scaffold', 'NT_187586.1 chromosome 11 genomic scaffold', 'NT_187587.1 chromosome 12 genomic scaffold', 'NT_187588.1 chromosome 12 genomic scaffold', 'NT_187589.1 chromosome 12 genomic scaffold', 'NT_187590.1 chromosome 12 genomic scaffold', 'NT_187591.1 chromosome 12 genomic scaffold', 'NT_187592.1 chromosome 13 genomic scaffold', 'NT_187593.1 chromosome 13 genomic scaffold', 'NT_187594.1 chromosome 13 genomic scaffold', 'NT_187595.1 chromosome 13 genomic scaffold', 'NT_187596.1 chromosome 13 genomic scaffold', 'NT_187597.1 chromosome 13 genomic scaffold', 'NT_187598.1 chromosome 14 genomic scaffold', 'NT_187599.1 chromosome 14 genomic scaffold', 'NT_187600.1 chromosome 14 genomic scaffold', 'NT_187601.1 chromosome 14 genomic scaffold', 'NT_187602.1 chromosome 15 genomic scaffold', 'NT_187603.1 chromosome 15 genomic scaffold', 'NT_187604.1 chromosome 15 genomic scaffold', 'NT_187605.1 chromosome 15 genomic scaffold', 'NT_187606.1 chromosome 15 genomic scaffold', 'NT_187607.1 chromosome 16 genomic scaffold', 'NT_187608.1 chromosome 16 genomic scaffold', 'NT_187609.1 chromosome 16 genomic scaffold', 'NT_187610.1 chromosome 16 genomic scaffold', 'NT_187611.1 chromosome 17 genomic scaffold', 'NT_187612.1 chromosome 17 genomic scaffold', 'NT_187613.1 chromosome 17 genomic scaffold', 'NT_187614.1 chromosome 17 genomic scaffold', 'NT_187615.1 chromosome 17 genomic scaffold', 'NT_187616.1 chromosome 17 genomic scaffold', 'NT_187617.1 chromosome 18 genomic scaffold', 'NT_187618.1 chromosome 18 genomic scaffold', 'NT_187619.1 chromosome 19 genomic scaffold', 'NT_187620.1 chromosome 19 genomic scaffold', 'NT_187621.1 chromosome 19 genomic scaffold', 'NT_187622.1 chromosome 19 genomic scaffold', 'NT_187623.1 chromosome 20 genomic scaffold', 'NT_187624.1 chromosome 20 genomic scaffold', 'NT_187625.1 chromosome 20 genomic scaffold', 'NT_187626.1 chromosome 21 genomic scaffold', 'NT_187627.1 chromosome 21 genomic scaffold', 'NT_187628.1 chromosome 21 genomic scaffold', 'NT_187629.1 chromosome 22 genomic scaffold', 'NT_187630.1 chromosome 22 genomic scaffold', 'NT_187631.1 chromosome 22 genomic scaffold', 'NT_187632.1 chromosome 22 genomic scaffold', 'NT_187633.1 chromosome 22 genomic scaffold', 'NT_187634.1 chromosome X genomic scaffold', 'NT_187635.1 chromosome X genomic scaffold', 'NT_187636.1 chromosome 19 genomic scaffold', 'NT_187637.1 chromosome 19 genomic scaffold', 'NT_187638.1 chromosome 19 genomic scaffold', 'NT_187639.1 chromosome 19 genomic scaffold', 'NT_187640.1 chromosome 19 genomic scaffold', 'NT_187641.1 chromosome 19 genomic scaffold', 'NT_187642.1 chromosome 19 genomic scaffold', 'NT_187643.1 chromosome 19 genomic scaffold', 'NT_187644.1 chromosome 19 genomic scaffold', 'NT_187645.1 chromosome 19 genomic scaffold', 'NT_187646.1 chromosome 1 genomic scaffold', 'NT_187647.1 chromosome 2 genomic scaffold', 'NT_187648.1 chromosome 2 genomic scaffold', 'NT_187649.1 chromosome 3 genomic scaffold', 'NT_187650.1 chromosome 4 genomic scaffold', 'NT_187651.1 chromosome 5 genomic scaffold', 'NT_187652.1 chromosome 5 genomic scaffold', 'NT_187653.1 chromosome 7 genomic scaffold', 'NT_187654.1 chromosome 8 genomic scaffold', 'NT_187655.1 chromosome 8 genomic scaffold', 'NT_187656.1 chromosome 11 genomic scaffold', 'NT_187657.1 chromosome 11 genomic scaffold', 'NT_187658.1 chromosome 12 genomic scaffold', 'NT_187659.1 chromosome 15 genomic scaffold', 'NT_187660.1 chromosome 15 genomic scaffold', 'NT_187661.1 chromosome 17 genomic scaffold', 'NT_187662.1 chromosome 17 genomic scaffold', 'NT_187663.1 chromosome 17 genomic scaffold', 'NT_187664.1 chromosome 17 genomic scaffold', 'NT_187665.1 chromosome 18 genomic scaffold', 'NT_187666.1 chromosome 18 genomic scaffold', 'NT_187667.1 chromosome X genomic scaffold', 'NT_187668.1 chromosome 19 genomic scaffold', 'NT_187669.1 chromosome 19 genomic scaffold', 'NT_187670.1 chromosome 19 genomic scaffold', 'NT_187671.1 chromosome 19 genomic scaffold', 'NT_187672.1 chromosome 19 genomic scaffold', 'NT_187673.1 chromosome 19 genomic scaffold', 'NT_187674.1 chromosome 19 genomic scaffold', 'NT_187675.1 chromosome 19 genomic scaffold', 'NT_187676.1 chromosome 19 genomic scaffold', 'NT_187677.1 chromosome 19 genomic scaffold', 'NT_187678.1 chromosome 3 genomic scaffold', 'NT_187679.1 chromosome 4 genomic scaffold', 'NT_187680.1 chromosome 8 genomic scaffold', 'NT_187681.1 chromosome 11 genomic scaffold', 'NT_187682.1 chromosome 22 genomic scaffold', 'NT_187683.1 chromosome 19 genomic scaffold', 'NT_187684.1 chromosome 19 genomic scaffold', 'NT_187685.1 chromosome 19 genomic scaffold', 'NT_187686.1 chromosome 19 genomic scaffold', 'NT_187687.1 chromosome 19 genomic scaffold', 'NT_187688.1 chromosome 3 genomic scaffold', 'NT_187689.1 chromosome 3 genomic scaffold', 'NT_187690.1 chromosome 3 genomic scaffold', 'NT_187691.1 chromosome 3 genomic scaffold', 'NT_187692.1 chromosome 6 genomic scaffold', 'NT_187693.1 chromosome 19 genomic scaffold', 'NW_003315905.1 chromosome 1 genomic scaffold', 'NW_003315906.1 chromosome 1 genomic scaffold', 'NW_003315907.2 chromosome 1 genomic scaffold', 'NW_003315908.1 chromosome 2 genomic scaffold', 'NW_003315909.1 chromosome 2 genomic scaffold', 'NW_003315913.1 chromosome 3 genomic scaffold', 'NW_003315914.1 chromosome 4 genomic scaffold', 'NW_003315915.1 chromosome 4 genomic scaffold', 'NW_003315917.2 chromosome 5 genomic scaffold', 'NW_003315918.1 chromosome 5 genomic scaffold', 'NW_003315919.1 chromosome 5 genomic scaffold', 'NW_003315920.1 chromosome 5 genomic scaffold', 'NW_003315921.1 chromosome 6 genomic scaffold', 'NW_003315922.2 chromosome 7 genomic scaffold', 'NW_003315928.1 chromosome 9 genomic scaffold', 'NW_003315929.1 chromosome 9 genomic scaffold', 'NW_003315930.1 chromosome 9 genomic scaffold', 'NW_003315931.1 chromosome 9 genomic scaffold', 'NW_003315934.1 chromosome 10 genomic scaffold', 'NW_003315935.1 chromosome 10 genomic scaffold', 'NW_003315936.1 chromosome 11 genomic scaffold', 'NW_003315938.1 chromosome 12 genomic scaffold', 'NW_003315939.2 chromosome 12 genomic scaffold', 'NW_003315940.1 chromosome 12 genomic scaffold', 'NW_003315941.1 chromosome 12 genomic scaffold', 'NW_003315942.2 chromosome 12 genomic scaffold', 'NW_003315943.1 chromosome 15 genomic scaffold', 'NW_003315944.2 chromosome 15 genomic scaffold', 'NW_003315945.1 chromosome 16 genomic scaffold', 'NW_003315946.1 chromosome 16 genomic scaffold', 'NW_003315952.3 chromosome 17 genomic scaffold', 'NW_003315953.2 chromosome 17 genomic scaffold', 'NW_003315954.1 chromosome 17 genomic scaffold', 'NW_003315955.1 chromosome 17 genomic scaffold', 'NW_003315956.1 chromosome 18 genomic scaffold', 'NW_003315957.1 chromosome 18 genomic scaffold', 'NW_003315958.1 chromosome 18 genomic scaffold', 'NW_003315959.1 chromosome 18 genomic scaffold', 'NW_003315960.1 chromosome 18 genomic scaffold', 'NW_003315961.1 chromosome 18 genomic scaffold', 'NW_003315962.1 chromosome 19 genomic scaffold', 'NW_003315963.1 chromosome 19 genomic scaffold', 'NW_003315964.2 chromosome 19 genomic scaffold', 'NW_003315965.1 chromosome 19 genomic scaffold', 'NW_003315966.2 chromosome 20 genomic scaffold', 'NW_003315967.2 chromosome 21 genomic scaffold', 'NW_003315968.2 chromosome 21 genomic scaffold', 'NW_003315969.2 chromosome 21 genomic scaffold', 'NW_003315970.2 chromosome 21 genomic scaffold', 'NW_003315971.2 chromosome 22 genomic scaffold', 'NW_003315972.2 chromosome 22 genomic scaffold', 'NW_003571033.2 chromosome 2 genomic scaffold', 'NW_003571036.1 chromosome 5 genomic scaffold', 'NW_003571049.1 chromosome 12 genomic scaffold', 'NW_003571050.1 chromosome 12 genomic scaffold', 'NW_003571054.1 chromosome 19 genomic scaffold', 'NW_003571055.2 chromosome 19 genomic scaffold', 'NW_003571056.2 chromosome 19 genomic scaffold', 'NW_003571057.2 chromosome 19 genomic scaffold', 'NW_003571058.2 chromosome 19 genomic scaffold', 'NW_003571059.2 chromosome 19 genomic scaffold', 'NW_003571060.1 chromosome 19 genomic scaffold', 'NW_003571061.2 chromosome 19 genomic scaffold', 'NW_003871060.2 chromosome 3 genomic scaffold', 'NW_003871073.1 chromosome 11 genomic scaffold', 'NW_003871074.1 chromosome 11 genomic scaffold', 'NW_003871091.1 chromosome 17 genomic scaffold', 'NW_003871092.1 chromosome 17 genomic scaffold', 'NW_003871093.1 chromosome 17 genomic scaffold', 'NW_004166862.2 chromosome 6 genomic scaffold', 'NW_004504305.1 chromosome 22 genomic scaffold']>

In [7]:
dir = '/mnt/20tb/vsfishman/nn_interpretator/mammals_fasta_dataset/dataset'

In [8]:
df = pd.read_csv(os.path.join(dir, 'mammals_dataset_metadata3.txt'), sep='\t')
df

,assembly_accession,organism_name,n_autosomes,number_of_x,number_of_y
0,GCF_004115215.2,Ornithorhynchus anatinus,21,5,20
1,GCF_015852505.1,Tachyglossus aculeatus,31,5,9
2,GCF_902635505.1,Sarcophilus harrisii,6,1,1
3,GCF_011100635.1,Trichosurus vulpecula,9,10,0
4,GCF_030445035.1,Dasypus novemcinctus,46,1,0
...,...,...,...,...,...
120,GCF_002776525.5,Piliocolobus tephrosceles,21,1,1
121,GCF_903992535.2,Arvicola amphibius,17,1,0
122,GCF_019320065.1,Cervus canadensis,33,1,1
123,GCF_028023285.1,Balaenoptera ricei,54,1,0
124,GCF_029407905.1,Bubalus kerabau,23,1,0

In [9]:
len(df[(df['number_of_x'] > 0) & (df['number_of_y'] > 0)])

60

In [10]:
df[(df['number_of_x'] != 0) & (df['number_of_y'] != 0)]

,assembly_accession,organism_name,n_autosomes,number_of_x,number_of_y
0,GCF_004115215.2,Ornithorhynchus anatinus,21,5,20
1,GCF_015852505.1,Tachyglossus aculeatus,31,5,9
2,GCF_902635505.1,Sarcophilus harrisii,6,1,1
7,GCF_020740605.2,Lemur catta,37,1,1
8,GCF_027406575.1,Nycticebus coucang,24,1,1
9,GCF_011100555.1,Callithrix jacchus,22,16,87
10,GCF_003339765.1,Macaca mulatta,307,5,1
11,GCF_008728515.1,Papio anubis,20,1,1
13,GCF_029289425.2,Pan paniscus,23,1,1
14,GCF_028885655.2,Pongo abelii,27,1,1
15,GCF_000001405.40,Homo sapiens,557,15,6
18,GCF_014441545.1,Canis lupus familiaris,38,1,3
19,GCF_023065955.2,Ursus arctos,0,1,1
21,GCF_902655055.1,Lutra lutra,18,1,1
22,GCF_922984935.1,Meles meles,21,4,1
23,GCF_030435805.1,Mustela lutreola,21,1,2
28,GCF_009762305.2,Zalophus californianus,17,1,1
29,GCF_949987515.1,Delphinus delphis,21,1,1
30,GCF_963455315.1,Globicephala melas,21,1,1
32,GCF_011762595.1,Tursiops truncatus,21,1,4
36,GCF_009873245.2,Balaenoptera musculus,21,1,1
37,GCF_030014295.1,Loxodonta africana,55,2,17
38,GCF_016077325.2,Equus asinus,30,1,1
40,GCF_000003025.6,Sus scrofa,18,1,10
41,GCF_036321535.1,Camelus dromedarius,36,1,1
44,GCF_032452875.1,Bos javanicus,29,1,1
45,GCF_002263795.3,Bos taurus,29,1,1
46,GCF_000247795.1,Bos indicus,29,1,1
48,GCF_016772045.2,Ovis aries,26,1,1
49,GCF_030435755.1,Ochotona princeps,33,1,1
50,GCF_033115175.1,Lepus europaeus,42,1,1
54,GCF_030254825.1,Meriones unguiculatus,151,6,6
56,GCF_000001635.27,Mus musculus,32,2,5
58,GCF_036323735.1,Rattus norvegicus,25,1,47
59,GCF_011064425.1,Rattus rattus,18,1,1
60,GCF_947179515.1,Apodemus sylvaticus,25,1,10
61,GCF_027887165.1,Monodelphis domestica,8,1,4
62,GCF_028564815.1,Eubalaena glacialis,21,1,9
65,GCF_015220235.1,Choloepus didactylus,75,4,8
68,GCF_002201575.2,Neomonachus schauinslandi,16,1,1
70,GCF_033118175.1,Dama dama,33,1,1
72,GCF_902686445.1,Sciurus carolinensis,29,1,4
75,GCF_008632895.1,Mastomys coucha,0,1,1
76,GCF_009829155.1,Mustela erminea,21,1,1
79,GCF_023091745.1,Budorcas taxicolor,25,1,1
88,GCF_025265405.1,Mesoplodon densirostris,20,1,3
89,GCF_020740685.1,Jaculus jaculus,24,1,6
93,GCF_011762505.1,Arvicanthis niloticus,21,1,4
94,GCF_007474595.2,Lynx canadensis,18,1,5
96,GCF_028018385.1,Neofelis nebulosa,18,1,4
103,GCF_004126475.2,Phyllostomus discolor,22,1,1
104,GCF_963259705.1,Myotis daubentonii,22,1,1
105,GCF_024166365.1,Elephas maximus indicus,36,1,7
106,GCF_024139225.1,Suncus etruscus,39,27,4
107,GCF_027409185.1,Cynocephalus volans,29,1,1
108,GCF_030020395.1,Manis pentadactyla,31,4,17
113,GCF_024542745.1,Macaca thibetana thibetana,20,1,1
114,GCF_950005125.1,Chionomys nivalis,27,1,1
120,GCF_002776525.5,Piliocolobus tephrosceles,21,1,1
122,GCF_019320065.1,Cervus canadensis,33,1,1

In [8]:
df = df[(df['number_of_x'] != 0) & (df['number_of_y'] != 0)] 
len(df)

60

In [9]:
len(df.organism_name.unique())

60

In [10]:
print("\n".join(df.organism_name))

Ornithorhynchus anatinus
Tachyglossus aculeatus
Sarcophilus harrisii
Lemur catta
Nycticebus coucang
Callithrix jacchus
Macaca mulatta
Papio anubis
Pan paniscus
Pongo abelii
Homo sapiens
Canis lupus familiaris
Ursus arctos
Lutra lutra
Meles meles
Mustela lutreola
Zalophus californianus
Delphinus delphis
Globicephala melas
Tursiops truncatus
Balaenoptera musculus
Loxodonta africana
Equus asinus
Sus scrofa
Camelus dromedarius
Bos javanicus
Bos taurus
Bos indicus
Ovis aries
Ochotona princeps
Lepus europaeus
Meriones unguiculatus
Mus musculus
Rattus norvegicus
Rattus rattus
Apodemus sylvaticus
Monodelphis domestica
Eubalaena glacialis
Choloepus didactylus
Neomonachus schauinslandi
Dama dama
Sciurus carolinensis
Mastomys coucha
Mustela erminea
Budorcas taxicolor
Mesoplodon densirostris
Jaculus jaculus
Arvicanthis niloticus
Lynx canadensis
Neofelis nebulosa
Phyllostomus discolor
Myotis daubentonii
Elephas maximus indicus
Suncus etruscus
Cynocephalus volans
Manis pentadactyla
Macaca thibetana thibetana
Chionomys nivalis
Piliocolobus tephrosceles
Cervus canadensis

In [11]:
species = list(df.organism_name)
len(set(species))

60

In [12]:
assembly_accession_list = list(df.assembly_accession)
assembly_accession_list

['GCF_004115215.2',
 'GCF_015852505.1',
 'GCF_902635505.1',
 'GCF_020740605.2',
 'GCF_027406575.1',
 'GCF_011100555.1',
 'GCF_003339765.1',
 'GCF_008728515.1',
 'GCF_029289425.2',
 'GCF_028885655.2',
 'GCF_000001405.40',
 'GCF_014441545.1',
 'GCF_023065955.2',
 'GCF_902655055.1',
 'GCF_922984935.1',
 'GCF_030435805.1',
 'GCF_009762305.2',
 'GCF_949987515.1',
 'GCF_963455315.1',
 'GCF_011762595.1',
 'GCF_009873245.2',
 'GCF_030014295.1',
 'GCF_016077325.2',
 'GCF_000003025.6',
 'GCF_036321535.1',
 'GCF_032452875.1',
 'GCF_002263795.3',
 'GCF_000247795.1',
 'GCF_016772045.2',
 'GCF_030435755.1',
 'GCF_033115175.1',
 'GCF_030254825.1',
 'GCF_000001635.27',
 'GCF_036323735.1',
 'GCF_011064425.1',
 'GCF_947179515.1',
 'GCF_027887165.1',
 'GCF_028564815.1',
 'GCF_015220235.1',
 'GCF_002201575.2',
 'GCF_033118175.1',
 'GCF_902686445.1',
 'GCF_008632895.1',
 'GCF_009829155.1',
 'GCF_023091745.1',
 'GCF_025265405.1',
 'GCF_020740685.1',
 'GCF_011762505.1',
 'GCF_007474595.2',
 'GCF_028018385.1',
 'GCF_004126475.2',
 'GCF_963259705.1',
 'GCF_024166365.1',
 'GCF_024139225.1',
 'GCF_027409185.1',
 'GCF_030020395.1',
 'GCF_024542745.1',
 'GCF_950005125.1',
 'GCF_002776525.5',
 'GCF_019320065.1']

In [13]:
chromosomes_filenames = ['x_chromosome.fasta', 'y_chromosome.fasta', 'autosomes.fasta']
for a_a in assembly_accession_list:
    species_path = os.path.join(dir, a_a)
    for chr_file in chromosomes_filenames:
        species_chr_path = os.path.join(species_path, chr_file)
        with open(species_chr_path, 'r') as f:
            for line in f:
                if line.startswith(">"):
                    print(line)

>NC_041749.1 Ornithorhynchus anatinus isolate Pmale09 chromosome X1, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041750.1 Ornithorhynchus anatinus isolate Pmale09 chromosome X2, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041751.1 Ornithorhynchus anatinus isolate Pmale09 chromosome X3, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041752.1 Ornithorhynchus anatinus isolate Pmale09 chromosome X4, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041753.1 Ornithorhynchus anatinus isolate Pmale09 chromosome X5, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_053175.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y1, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_053176.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2, mOrnAna1.pri.v4, whole genome shotgun sequence

>NW_024396656.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_128_arrow_ctg1, whole genome shotgun sequence

>NW_024396657.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_167_arrow_ctg1, whole genome shotgun sequence

>NW_024396658.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_257_arrow_ctg1, whole genome shotgun sequence

>NW_024396659.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_267_arrow_ctg1, whole genome shotgun sequence

>NW_024396660.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_285_arrow_ctg1, whole genome shotgun sequence

>NW_024396661.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_330_arrow_ctg1, whole genome shotgun sequence

>NW_024396662.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_395_arrow_ctg1, whole genome shotgun sequence

>NW_024396663.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_499_arrow_ctg1, whole genome shotgun sequence

>NW_024396664.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_531_arrow_ctg1, whole genome shotgun sequence

>NW_024396665.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_622_arrow_ctg1, whole genome shotgun sequence

>NW_024396666.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_672_arrow_ctg1, whole genome shotgun sequence

>NC_053177.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y3, mOrnAna1.pri.v4, whole genome shotgun sequence

>NW_024396667.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y3 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_233_arrow_ctg1_1, whole genome shotgun sequence

>NW_024396668.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y3 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_32_arrow_ctg1, whole genome shotgun sequence

>NW_024396669.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y3 unlocalized genomic scaffold, mOrnAna1.pri.v4 scaffold_538_arrow_ctg1, whole genome shotgun sequence

>NC_053178.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y4, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_053179.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y5, mOrnAna1.pri.v4, whole genome shotgun sequence

>NW_024396670.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y5 unlocalized genomic scaffold, mOrnAna1.pri.v4 Super_Scaffold_Y5, whole genome shotgun sequence

>NC_041728.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 1, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041729.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 2, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041730.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 3, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041731.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 4, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041732.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 5, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041733.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 6, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041734.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 7, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041735.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 8, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041736.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 9, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041737.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 10, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041738.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 11, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041739.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 12, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041740.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 13, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041741.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 14, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041742.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 15, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041743.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 16, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041744.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 17, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041745.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 18, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041746.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 19, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041747.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 20, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041748.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 21, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_052097.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome X5, mTacAcu1.pri, whole genome shotgun sequence

>NC_052098.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome X4, mTacAcu1.pri, whole genome shotgun sequence

>NC_052099.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome X3, mTacAcu1.pri, whole genome shotgun sequence

>NC_052100.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome X2, mTacAcu1.pri, whole genome shotgun sequence

>NC_052101.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome X1, mTacAcu1.pri, whole genome shotgun sequence

>NC_052093.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y1, mTacAcu1.pri, whole genome shotgun sequence

>NC_052094.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y2, mTacAcu1.pri, whole genome shotgun sequence

>NC_052095.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y3, mTacAcu1.pri, whole genome shotgun sequence

>NW_024044832.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y3 unlocalized genomic scaffold, mTacAcu1.pri scaffold_183_arrow_ctg1, whole genome shotgun sequence

>NW_024044833.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y3 unlocalized genomic scaffold, mTacAcu1.pri scaffold_232_arrow_ctg1, whole genome shotgun sequence

>NW_024044834.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y3 unlocalized genomic scaffold, mTacAcu1.pri scaffold_288_arrow_ctg1, whole genome shotgun sequence

>NW_024044835.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y3 unlocalized genomic scaffold, mTacAcu1.pri scaffold_320_arrow_ctg1, whole genome shotgun sequence

>NC_052096.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y4, mTacAcu1.pri, whole genome shotgun sequence

>NW_024044836.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y4 unlocalized genomic scaffold, mTacAcu1.pri scaffold_167_arrow_ctg1, whole genome shotgun sequence

>NC_052066.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 1, mTacAcu1.pri, whole genome shotgun sequence

>NC_052067.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 2, mTacAcu1.pri, whole genome shotgun sequence

>NC_052068.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 3, mTacAcu1.pri, whole genome shotgun sequence

>NC_052069.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 4, mTacAcu1.pri, whole genome shotgun sequence

>NC_052070.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 5, mTacAcu1.pri, whole genome shotgun sequence

>NC_052071.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 6, mTacAcu1.pri, whole genome shotgun sequence

>NC_052072.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 7, mTacAcu1.pri, whole genome shotgun sequence

>NC_052073.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 8, mTacAcu1.pri, whole genome shotgun sequence

>NC_052074.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 9, mTacAcu1.pri, whole genome shotgun sequence

>NC_052075.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 10, mTacAcu1.pri, whole genome shotgun sequence

>NC_052076.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 11, mTacAcu1.pri, whole genome shotgun sequence

>NC_052077.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 12, mTacAcu1.pri, whole genome shotgun sequence

>NW_024044828.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 12 unlocalized genomic scaffold, mTacAcu1.pri SUPER_6_unloc_1, whole genome shotgun sequence

>NW_024044829.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 12 unlocalized genomic scaffold, mTacAcu1.pri SUPER_6_unloc_2, whole genome shotgun sequence

>NW_024044830.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 12 unlocalized genomic scaffold, mTacAcu1.pri SUPER_6_unloc_3, whole genome shotgun sequence

>NW_024044831.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 12 unlocalized genomic scaffold, mTacAcu1.pri SUPER_6_unloc_4, whole genome shotgun sequence

>NC_052078.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 13, mTacAcu1.pri, whole genome shotgun sequence

>NC_052079.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 14, mTacAcu1.pri, whole genome shotgun sequence

>NC_052080.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 15, mTacAcu1.pri, whole genome shotgun sequence

>NC_052081.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 16, mTacAcu1.pri, whole genome shotgun sequence

>NC_052082.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 17, mTacAcu1.pri, whole genome shotgun sequence

>NC_052083.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 18, mTacAcu1.pri, whole genome shotgun sequence

>NC_052084.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 19, mTacAcu1.pri, whole genome shotgun sequence

>NC_052085.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 20, mTacAcu1.pri, whole genome shotgun sequence

>NC_052086.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 21, mTacAcu1.pri, whole genome shotgun sequence

>NC_052087.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 22, mTacAcu1.pri, whole genome shotgun sequence

>NC_052088.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 23, mTacAcu1.pri, whole genome shotgun sequence

>NC_052089.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 24, mTacAcu1.pri, whole genome shotgun sequence

>NC_052090.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 25, mTacAcu1.pri, whole genome shotgun sequence

>NC_052091.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 26, mTacAcu1.pri, whole genome shotgun sequence

>NC_052092.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 27, mTacAcu1.pri, whole genome shotgun sequence

>NC_045432.1 Sarcophilus harrisii chromosome X, mSarHar1.11, whole genome shotgun sequence

>NC_045433.1 Sarcophilus harrisii chromosome Y, mSarHar1.11, whole genome shotgun sequence

>NC_045426.1 Sarcophilus harrisii chromosome 1, mSarHar1.11, whole genome shotgun sequence

>NC_045427.1 Sarcophilus harrisii chromosome 2, mSarHar1.11, whole genome shotgun sequence

>NC_045428.1 Sarcophilus harrisii chromosome 3, mSarHar1.11, whole genome shotgun sequence

>NC_045429.1 Sarcophilus harrisii chromosome 4, mSarHar1.11, whole genome shotgun sequence

>NC_045430.1 Sarcophilus harrisii chromosome 5, mSarHar1.11, whole genome shotgun sequence

>NC_045431.1 Sarcophilus harrisii chromosome 6, mSarHar1.11, whole genome shotgun sequence

>NC_059155.1 Lemur catta isolate mLemCat1 chromosome X, mLemCat1.pri, whole genome shotgun sequence

>NC_059156.1 Lemur catta isolate mLemCat1 chromosome Y, mLemCat1.pri, whole genome shotgun sequence

>NC_059128.1 Lemur catta isolate mLemCat1 chromosome 1, mLemCat1.pri, whole genome shotgun sequence

>NC_059129.1 Lemur catta isolate mLemCat1 chromosome 2, mLemCat1.pri, whole genome shotgun sequence

>NC_059130.1 Lemur catta isolate mLemCat1 chromosome 3, mLemCat1.pri, whole genome shotgun sequence

>NC_059131.1 Lemur catta isolate mLemCat1 chromosome 4, mLemCat1.pri, whole genome shotgun sequence

>NC_059132.1 Lemur catta isolate mLemCat1 chromosome 5, mLemCat1.pri, whole genome shotgun sequence

>NC_059133.1 Lemur catta isolate mLemCat1 chromosome 6, mLemCat1.pri, whole genome shotgun sequence

>NC_059134.1 Lemur catta isolate mLemCat1 chromosome 7, mLemCat1.pri, whole genome shotgun sequence

>NC_059135.1 Lemur catta isolate mLemCat1 chromosome 8, mLemCat1.pri, whole genome shotgun sequence

>NC_059136.1 Lemur catta isolate mLemCat1 chromosome 9, mLemCat1.pri, whole genome shotgun sequence

>NC_059137.1 Lemur catta isolate mLemCat1 chromosome 10, mLemCat1.pri, whole genome shotgun sequence

>NW_025423732.1 Lemur catta isolate mLemCat1 chromosome 10 unlocalized genomic scaffold, mLemCat1.pri SUPER_10_unloc_1, whole genome shotgun sequence

>NW_025423733.1 Lemur catta isolate mLemCat1 chromosome 10 unlocalized genomic scaffold, mLemCat1.pri SUPER_10_unloc_2, whole genome shotgun sequence

>NW_025423734.1 Lemur catta isolate mLemCat1 chromosome 10 unlocalized genomic scaffold, mLemCat1.pri SUPER_10_unloc_3, whole genome shotgun sequence

>NW_025423735.1 Lemur catta isolate mLemCat1 chromosome 10 unlocalized genomic scaffold, mLemCat1.pri SUPER_10_unloc_4, whole genome shotgun sequence

>NW_025423736.1 Lemur catta isolate mLemCat1 chromosome 10 unlocalized genomic scaffold, mLemCat1.pri SUPER_10_unloc_5, whole genome shotgun sequence

>NW_025423737.1 Lemur catta isolate mLemCat1 chromosome 10 unlocalized genomic scaffold, mLemCat1.pri SUPER_10_unloc_6, whole genome shotgun sequence

>NW_025423738.1 Lemur catta isolate mLemCat1 chromosome 10 unlocalized genomic scaffold, mLemCat1.pri SUPER_10_unloc_7, whole genome shotgun sequence

>NW_025423739.1 Lemur catta isolate mLemCat1 chromosome 10 unlocalized genomic scaffold, mLemCat1.pri SUPER_10_unloc_8, whole genome shotgun sequence

>NW_025423740.1 Lemur catta isolate mLemCat1 chromosome 10 unlocalized genomic scaffold, mLemCat1.pri SUPER_10_unloc_9, whole genome shotgun sequence

>NC_059138.1 Lemur catta isolate mLemCat1 chromosome 11, mLemCat1.pri, whole genome shotgun sequence

>NC_059139.1 Lemur catta isolate mLemCat1 chromosome 12, mLemCat1.pri, whole genome shotgun sequence

>NC_059140.1 Lemur catta isolate mLemCat1 chromosome 13, mLemCat1.pri, whole genome shotgun sequence

>NC_059141.1 Lemur catta isolate mLemCat1 chromosome 14, mLemCat1.pri, whole genome shotgun sequence

>NC_059142.1 Lemur catta isolate mLemCat1 chromosome 15, mLemCat1.pri, whole genome shotgun sequence

>NC_059143.1 Lemur catta isolate mLemCat1 chromosome 16, mLemCat1.pri, whole genome shotgun sequence

>NC_059144.1 Lemur catta isolate mLemCat1 chromosome 17, mLemCat1.pri, whole genome shotgun sequence

>NC_059145.1 Lemur catta isolate mLemCat1 chromosome 18, mLemCat1.pri, whole genome shotgun sequence

>NC_059146.1 Lemur catta isolate mLemCat1 chromosome 19, mLemCat1.pri, whole genome shotgun sequence

>NC_059147.1 Lemur catta isolate mLemCat1 chromosome 20, mLemCat1.pri, whole genome shotgun sequence

>NW_025423741.1 Lemur catta isolate mLemCat1 chromosome 20 unlocalized genomic scaffold, mLemCat1.pri SUPER_20_unloc_1, whole genome shotgun sequence

>NC_059148.1 Lemur catta isolate mLemCat1 chromosome 21, mLemCat1.pri, whole genome shotgun sequence

>NC_059149.1 Lemur catta isolate mLemCat1 chromosome 22, mLemCat1.pri, whole genome shotgun sequence

>NC_059150.1 Lemur catta isolate mLemCat1 chromosome 23, mLemCat1.pri, whole genome shotgun sequence

>NC_059151.1 Lemur catta isolate mLemCat1 chromosome 24, mLemCat1.pri, whole genome shotgun sequence

>NC_059152.1 Lemur catta isolate mLemCat1 chromosome 25, mLemCat1.pri, whole genome shotgun sequence

>NC_059153.1 Lemur catta isolate mLemCat1 chromosome 26, mLemCat1.pri, whole genome shotgun sequence

>NC_059154.1 Lemur catta isolate mLemCat1 chromosome 27, mLemCat1.pri, whole genome shotgun sequence

>NC_069804.1 Nycticebus coucang isolate mNycCou1 chromosome X, mNycCou1.pri, whole genome shotgun sequence

>NC_069805.1 Nycticebus coucang isolate mNycCou1 chromosome Y, mNycCou1.pri, whole genome shotgun sequence

>NC_069780.1 Nycticebus coucang isolate mNycCou1 chromosome 1, mNycCou1.pri, whole genome shotgun sequence

>NC_069781.1 Nycticebus coucang isolate mNycCou1 chromosome 2, mNycCou1.pri, whole genome shotgun sequence

>NC_069782.1 Nycticebus coucang isolate mNycCou1 chromosome 3, mNycCou1.pri, whole genome shotgun sequence

>NC_069783.1 Nycticebus coucang isolate mNycCou1 chromosome 4, mNycCou1.pri, whole genome shotgun sequence

>NC_069784.1 Nycticebus coucang isolate mNycCou1 chromosome 5, mNycCou1.pri, whole genome shotgun sequence

>NC_069785.1 Nycticebus coucang isolate mNycCou1 chromosome 6, mNycCou1.pri, whole genome shotgun sequence

>NC_069786.1 Nycticebus coucang isolate mNycCou1 chromosome 7, mNycCou1.pri, whole genome shotgun sequence

>NC_069787.1 Nycticebus coucang isolate mNycCou1 chromosome 8, mNycCou1.pri, whole genome shotgun sequence

>NC_069788.1 Nycticebus coucang isolate mNycCou1 chromosome 9, mNycCou1.pri, whole genome shotgun sequence

>NC_069789.1 Nycticebus coucang isolate mNycCou1 chromosome 10, mNycCou1.pri, whole genome shotgun sequence

>NC_069790.1 Nycticebus coucang isolate mNycCou1 chromosome 11, mNycCou1.pri, whole genome shotgun sequence

>NC_069791.1 Nycticebus coucang isolate mNycCou1 chromosome 12, mNycCou1.pri, whole genome shotgun sequence

>NC_069792.1 Nycticebus coucang isolate mNycCou1 chromosome 13, mNycCou1.pri, whole genome shotgun sequence

>NC_069793.1 Nycticebus coucang isolate mNycCou1 chromosome 14, mNycCou1.pri, whole genome shotgun sequence

>NC_069794.1 Nycticebus coucang isolate mNycCou1 chromosome 15, mNycCou1.pri, whole genome shotgun sequence

>NC_069795.1 Nycticebus coucang isolate mNycCou1 chromosome 16, mNycCou1.pri, whole genome shotgun sequence

>NC_069796.1 Nycticebus coucang isolate mNycCou1 chromosome 17, mNycCou1.pri, whole genome shotgun sequence

>NC_069797.1 Nycticebus coucang isolate mNycCou1 chromosome 18, mNycCou1.pri, whole genome shotgun sequence

>NC_069798.1 Nycticebus coucang isolate mNycCou1 chromosome 19, mNycCou1.pri, whole genome shotgun sequence

>NC_069799.1 Nycticebus coucang isolate mNycCou1 chromosome 20, mNycCou1.pri, whole genome shotgun sequence

>NC_069800.1 Nycticebus coucang isolate mNycCou1 chromosome 21, mNycCou1.pri, whole genome shotgun sequence

>NC_069801.1 Nycticebus coucang isolate mNycCou1 chromosome 22, mNycCou1.pri, whole genome shotgun sequence

>NC_069802.1 Nycticebus coucang isolate mNycCou1 chromosome 23, mNycCou1.pri, whole genome shotgun sequence

>NC_069803.1 Nycticebus coucang isolate mNycCou1 chromosome 24, mNycCou1.pri, whole genome shotgun sequence

>NC_071464.1 Callithrix jacchus isolate mCalJac1 chromosome X, mCalJa1.2.pat.X, whole genome shotgun sequence


In [21]:
headers = []
chromosomes_filenames = ['x_chromosome.fasta', 'y_chromosome.fasta', 'autosomes.fasta']
for a_a in assembly_accession_list:
    species_path = os.path.join(dir, a_a)
    for chr_file in chromosomes_filenames:
        species_chr_path = os.path.join(species_path, chr_file)
        with open(species_chr_path, 'r') as f:
            for line in f:
                if line.startswith(">"):
                    headers.append(line)

In [37]:
chromosomes = []
descriptions = []
for line in headers:
    chr, desc = re.findall("(chromosome [A-Z]?\d*)([^,]*)", line)[0]
    if desc =='':
        print(line)
    chromosomes.append(chr)
    descriptions.append(desc)

>NC_041749.1 Ornithorhynchus anatinus isolate Pmale09 chromosome X1, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041750.1 Ornithorhynchus anatinus isolate Pmale09 chromosome X2, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041751.1 Ornithorhynchus anatinus isolate Pmale09 chromosome X3, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041752.1 Ornithorhynchus anatinus isolate Pmale09 chromosome X4, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041753.1 Ornithorhynchus anatinus isolate Pmale09 chromosome X5, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_053175.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y1, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_053176.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y2, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_053177.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y3, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_053178.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y4, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_053179.1 Ornithorhynchus anatinus isolate Pmale09 chromosome Y5, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041728.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 1, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041729.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 2, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041730.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 3, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041731.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 4, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041732.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 5, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041733.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 6, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041734.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 7, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041735.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 8, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041736.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 9, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041737.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 10, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041738.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 11, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041739.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 12, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041740.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 13, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041741.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 14, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041742.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 15, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041743.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 16, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041744.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 17, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041745.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 18, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041746.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 19, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041747.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 20, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_041748.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 21, mOrnAna1.pri.v4, whole genome shotgun sequence

>NC_052097.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome X5, mTacAcu1.pri, whole genome shotgun sequence

>NC_052098.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome X4, mTacAcu1.pri, whole genome shotgun sequence

>NC_052099.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome X3, mTacAcu1.pri, whole genome shotgun sequence

>NC_052100.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome X2, mTacAcu1.pri, whole genome shotgun sequence

>NC_052101.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome X1, mTacAcu1.pri, whole genome shotgun sequence

>NC_052093.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y1, mTacAcu1.pri, whole genome shotgun sequence

>NC_052094.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y2, mTacAcu1.pri, whole genome shotgun sequence

>NC_052095.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y3, mTacAcu1.pri, whole genome shotgun sequence

>NC_052096.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome Y4, mTacAcu1.pri, whole genome shotgun sequence

>NC_052066.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 1, mTacAcu1.pri, whole genome shotgun sequence

>NC_052067.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 2, mTacAcu1.pri, whole genome shotgun sequence

>NC_052068.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 3, mTacAcu1.pri, whole genome shotgun sequence

>NC_052069.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 4, mTacAcu1.pri, whole genome shotgun sequence

>NC_052070.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 5, mTacAcu1.pri, whole genome shotgun sequence

>NC_052071.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 6, mTacAcu1.pri, whole genome shotgun sequence

>NC_052072.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 7, mTacAcu1.pri, whole genome shotgun sequence

>NC_052073.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 8, mTacAcu1.pri, whole genome shotgun sequence

>NC_052074.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 9, mTacAcu1.pri, whole genome shotgun sequence

>NC_052075.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 10, mTacAcu1.pri, whole genome shotgun sequence

>NC_052076.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 11, mTacAcu1.pri, whole genome shotgun sequence

>NC_052077.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 12, mTacAcu1.pri, whole genome shotgun sequence

>NC_052078.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 13, mTacAcu1.pri, whole genome shotgun sequence

>NC_052079.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 14, mTacAcu1.pri, whole genome shotgun sequence

>NC_052080.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 15, mTacAcu1.pri, whole genome shotgun sequence

>NC_052081.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 16, mTacAcu1.pri, whole genome shotgun sequence

>NC_052082.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 17, mTacAcu1.pri, whole genome shotgun sequence

>NC_052083.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 18, mTacAcu1.pri, whole genome shotgun sequence

>NC_052084.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 19, mTacAcu1.pri, whole genome shotgun sequence

>NC_052085.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 20, mTacAcu1.pri, whole genome shotgun sequence

>NC_052086.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 21, mTacAcu1.pri, whole genome shotgun sequence

>NC_052087.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 22, mTacAcu1.pri, whole genome shotgun sequence

>NC_052088.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 23, mTacAcu1.pri, whole genome shotgun sequence

>NC_052089.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 24, mTacAcu1.pri, whole genome shotgun sequence

>NC_052090.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 25, mTacAcu1.pri, whole genome shotgun sequence

>NC_052091.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 26, mTacAcu1.pri, whole genome shotgun sequence

>NC_052092.1 Tachyglossus aculeatus isolate mTacAcu1 chromosome 27, mTacAcu1.pri, whole genome shotgun sequence

>NC_045432.1 Sarcophilus harrisii chromosome X, mSarHar1.11, whole genome shotgun sequence

>NC_045433.1 Sarcophilus harrisii chromosome Y, mSarHar1.11, whole genome shotgun sequence

>NC_045426.1 Sarcophilus harrisii chromosome 1, mSarHar1.11, whole genome shotgun sequence

>NC_045427.1 Sarcophilus harrisii chromosome 2, mSarHar1.11, whole genome shotgun sequence

>NC_045428.1 Sarcophilus harrisii chromosome 3, mSarHar1.11, whole genome shotgun sequence

>NC_045429.1 Sarcophilus harrisii chromosome 4, mSarHar1.11, whole genome shotgun sequence

>NC_045430.1 Sarcophilus harrisii chromosome 5, mSarHar1.11, whole genome shotgun sequence

>NC_045431.1 Sarcophilus harrisii chromosome 6, mSarHar1.11, whole genome shotgun sequence

>NC_059155.1 Lemur catta isolate mLemCat1 chromosome X, mLemCat1.pri, whole genome shotgun sequence

>NC_059156.1 Lemur catta isolate mLemCat1 chromosome Y, mLemCat1.pri, whole genome shotgun sequence

>NC_059128.1 Lemur catta isolate mLemCat1 chromosome 1, mLemCat1.pri, whole genome shotgun sequence

>NC_059129.1 Lemur catta isolate mLemCat1 chromosome 2, mLemCat1.pri, whole genome shotgun sequence

>NC_059130.1 Lemur catta isolate mLemCat1 chromosome 3, mLemCat1.pri, whole genome shotgun sequence

>NC_059131.1 Lemur catta isolate mLemCat1 chromosome 4, mLemCat1.pri, whole genome shotgun sequence

>NC_059132.1 Lemur catta isolate mLemCat1 chromosome 5, mLemCat1.pri, whole genome shotgun sequence

>NC_059133.1 Lemur catta isolate mLemCat1 chromosome 6, mLemCat1.pri, whole genome shotgun sequence

>NC_059134.1 Lemur catta isolate mLemCat1 chromosome 7, mLemCat1.pri, whole genome shotgun sequence

>NC_059135.1 Lemur catta isolate mLemCat1 chromosome 8, mLemCat1.pri, whole genome shotgun sequence

>NC_059136.1 Lemur catta isolate mLemCat1 chromosome 9, mLemCat1.pri, whole genome shotgun sequence

>NC_059137.1 Lemur catta isolate mLemCat1 chromosome 10, mLemCat1.pri, whole genome shotgun sequence

>NC_059138.1 Lemur catta isolate mLemCat1 chromosome 11, mLemCat1.pri, whole genome shotgun sequence

>NC_059139.1 Lemur catta isolate mLemCat1 chromosome 12, mLemCat1.pri, whole genome shotgun sequence

>NC_059140.1 Lemur catta isolate mLemCat1 chromosome 13, mLemCat1.pri, whole genome shotgun sequence

>NC_059141.1 Lemur catta isolate mLemCat1 chromosome 14, mLemCat1.pri, whole genome shotgun sequence

>NC_059142.1 Lemur catta isolate mLemCat1 chromosome 15, mLemCat1.pri, whole genome shotgun sequence

>NC_059143.1 Lemur catta isolate mLemCat1 chromosome 16, mLemCat1.pri, whole genome shotgun sequence

>NC_059144.1 Lemur catta isolate mLemCat1 chromosome 17, mLemCat1.pri, whole genome shotgun sequence

>NC_059145.1 Lemur catta isolate mLemCat1 chromosome 18, mLemCat1.pri, whole genome shotgun sequence

>NC_059146.1 Lemur catta isolate mLemCat1 chromosome 19, mLemCat1.pri, whole genome shotgun sequence

>NC_059147.1 Lemur catta isolate mLemCat1 chromosome 20, mLemCat1.pri, whole genome shotgun sequence

>NC_059148.1 Lemur catta isolate mLemCat1 chromosome 21, mLemCat1.pri, whole genome shotgun sequence

>NC_059149.1 Lemur catta isolate mLemCat1 chromosome 22, mLemCat1.pri, whole genome shotgun sequence

>NC_059150.1 Lemur catta isolate mLemCat1 chromosome 23, mLemCat1.pri, whole genome shotgun sequence

>NC_059151.1 Lemur catta isolate mLemCat1 chromosome 24, mLemCat1.pri, whole genome shotgun sequence

>NC_059152.1 Lemur catta isolate mLemCat1 chromosome 25, mLemCat1.pri, whole genome shotgun sequence

>NC_059153.1 Lemur catta isolate mLemCat1 chromosome 26, mLemCat1.pri, whole genome shotgun sequence

>NC_059154.1 Lemur catta isolate mLemCat1 chromosome 27, mLemCat1.pri, whole genome shotgun sequence

>NC_069804.1 Nycticebus coucang isolate mNycCou1 chromosome X, mNycCou1.pri, whole genome shotgun sequence

>NC_069805.1 Nycticebus coucang isolate mNycCou1 chromosome Y, mNycCou1.pri, whole genome shotgun sequence

>NC_069780.1 Nycticebus coucang isolate mNycCou1 chromosome 1, mNycCou1.pri, whole genome shotgun sequence

>NC_069781.1 Nycticebus coucang isolate mNycCou1 chromosome 2, mNycCou1.pri, whole genome shotgun sequence

>NC_069782.1 Nycticebus coucang isolate mNycCou1 chromosome 3, mNycCou1.pri, whole genome shotgun sequence

>NC_069783.1 Nycticebus coucang isolate mNycCou1 chromosome 4, mNycCou1.pri, whole genome shotgun sequence

>NC_069784.1 Nycticebus coucang isolate mNycCou1 chromosome 5, mNycCou1.pri, whole genome shotgun sequence

>NC_069785.1 Nycticebus coucang isolate mNycCou1 chromosome 6, mNycCou1.pri, whole genome shotgun sequence

>NC_069786.1 Nycticebus coucang isolate mNycCou1 chromosome 7, mNycCou1.pri, whole genome shotgun sequence

>NC_069787.1 Nycticebus coucang isolate mNycCou1 chromosome 8, mNycCou1.pri, whole genome shotgun sequence

>NC_069788.1 Nycticebus coucang isolate mNycCou1 chromosome 9, mNycCou1.pri, whole genome shotgun sequence

>NC_069789.1 Nycticebus coucang isolate mNycCou1 chromosome 10, mNycCou1.pri, whole genome shotgun sequence

>NC_069790.1 Nycticebus coucang isolate mNycCou1 chromosome 11, mNycCou1.pri, whole genome shotgun sequence

>NC_069791.1 Nycticebus coucang isolate mNycCou1 chromosome 12, mNycCou1.pri, whole genome shotgun sequence

>NC_069792.1 Nycticebus coucang isolate mNycCou1 chromosome 13, mNycCou1.pri, whole genome shotgun sequence

>NC_069793.1 Nycticebus coucang isolate mNycCou1 chromosome 14, mNycCou1.pri, whole genome shotgun sequence

>NC_069794.1 Nycticebus coucang isolate mNycCou1 chromosome 15, mNycCou1.pri, whole genome shotgun sequence

>NC_069795.1 Nycticebus coucang isolate mNycCou1 chromosome 16, mNycCou1.pri, whole genome shotgun sequence

>NC_069796.1 Nycticebus coucang isolate mNycCou1 chromosome 17, mNycCou1.pri, whole genome shotgun sequence

>NC_069797.1 Nycticebus coucang isolate mNycCou1 chromosome 18, mNycCou1.pri, whole genome shotgun sequence

>NC_069798.1 Nycticebus coucang isolate mNycCou1 chromosome 19, mNycCou1.pri, whole genome shotgun sequence

>NC_069799.1 Nycticebus coucang isolate mNycCou1 chromosome 20, mNycCou1.pri, whole genome shotgun sequence

>NC_069800.1 Nycticebus coucang isolate mNycCou1 chromosome 21, mNycCou1.pri, whole genome shotgun sequence

>NC_069801.1 Nycticebus coucang isolate mNycCou1 chromosome 22, mNycCou1.pri, whole genome shotgun sequence

>NC_069802.1 Nycticebus coucang isolate mNycCou1 chromosome 23, mNycCou1.pri, whole genome shotgun sequence

>NC_069803.1 Nycticebus coucang isolate mNycCou1 chromosome 24, mNycCou1.pri, whole genome shotgun sequence

>NC_071464.1 Callithrix jacchus isolate mCalJac1 chromosome X, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071465.1 Callithrix jacchus isolate mCalJac1 chromosome Y, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071442.1 Callithrix jacchus isolate mCalJac1 chromosome 1, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071443.1 Callithrix jacchus isolate mCalJac1 chromosome 2, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071444.1 Callithrix jacchus isolate mCalJac1 chromosome 3, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071445.1 Callithrix jacchus isolate mCalJac1 chromosome 4, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071446.1 Callithrix jacchus isolate mCalJac1 chromosome 5, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071447.1 Callithrix jacchus isolate mCalJac1 chromosome 6, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071448.1 Callithrix jacchus isolate mCalJac1 chromosome 7, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071449.1 Callithrix jacchus isolate mCalJac1 chromosome 8, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071450.1 Callithrix jacchus isolate mCalJac1 chromosome 9, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071451.1 Callithrix jacchus isolate mCalJac1 chromosome 10, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071452.1 Callithrix jacchus isolate mCalJac1 chromosome 11, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071453.1 Callithrix jacchus isolate mCalJac1 chromosome 12, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071454.1 Callithrix jacchus isolate mCalJac1 chromosome 13, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071455.1 Callithrix jacchus isolate mCalJac1 chromosome 14, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071456.1 Callithrix jacchus isolate mCalJac1 chromosome 15, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071457.1 Callithrix jacchus isolate mCalJac1 chromosome 16, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071458.1 Callithrix jacchus isolate mCalJac1 chromosome 17, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071459.1 Callithrix jacchus isolate mCalJac1 chromosome 18, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071460.1 Callithrix jacchus isolate mCalJac1 chromosome 19, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071461.1 Callithrix jacchus isolate mCalJac1 chromosome 20, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071462.1 Callithrix jacchus isolate mCalJac1 chromosome 21, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_071463.1 Callithrix jacchus isolate mCalJac1 chromosome 22, mCalJa1.2.pat.X, whole genome shotgun sequence

>NC_041774.1 Macaca mulatta isolate AG07107 chromosome X, Mmul_10, whole genome shotgun sequence

>NC_027914.1 Macaca mulatta chromosome Y, Mmul_10, whole genome shotgun sequence

>NC_041754.1 Macaca mulatta isolate AG07107 chromosome 1, Mmul_10, whole genome shotgun sequence

>NC_041755.1 Macaca mulatta isolate AG07107 chromosome 2, Mmul_10, whole genome shotgun sequence

>NC_041756.1 Macaca mulatta isolate AG07107 chromosome 3, Mmul_10, whole genome shotgun sequence

>NC_041757.1 Macaca mulatta isolate AG07107 chromosome 4, Mmul_10, whole genome shotgun sequence

>NC_041758.1 Macaca mulatta isolate AG07107 chromosome 5, Mmul_10, whole genome shotgun sequence

>NC_041759.1 Macaca mulatta isolate AG07107 chromosome 6, Mmul_10, whole genome shotgun sequence

>NC_041760.1 Macaca mulatta isolate AG07107 chromosome 7, Mmul_10, whole genome shotgun sequence

>NC_041761.1 Macaca mulatta isolate AG07107 chromosome 8, Mmul_10, whole genome shotgun sequence

>NC_041762.1 Macaca mulatta isolate AG07107 chromosome 9, Mmul_10, whole genome shotgun sequence

>NC_041763.1 Macaca mulatta isolate AG07107 chromosome 10, Mmul_10, whole genome shotgun sequence

>NC_041764.1 Macaca mulatta isolate AG07107 chromosome 11, Mmul_10, whole genome shotgun sequence

>NC_041765.1 Macaca mulatta isolate AG07107 chromosome 12, Mmul_10, whole genome shotgun sequence

>NC_041766.1 Macaca mulatta isolate AG07107 chromosome 13, Mmul_10, whole genome shotgun sequence

>NC_041767.1 Macaca mulatta isolate AG07107 chromosome 14, Mmul_10, whole genome shotgun sequence

>NC_041768.1 Macaca mulatta isolate AG07107 chromosome 15, Mmul_10, whole genome shotgun sequence

>NC_041769.1 Macaca mulatta isolate AG07107 chromosome 16, Mmul_10, whole genome shotgun sequence

>NC_041770.1 Macaca mulatta isolate AG07107 chromosome 17, Mmul_10, whole genome shotgun sequence

>NC_041771.1 Macaca mulatta isolate AG07107 chromosome 18, Mmul_10, whole genome shotgun sequence

>NC_041772.1 Macaca mulatta isolate AG07107 chromosome 19, Mmul_10, whole genome shotgun sequence

>NC_041773.1 Macaca mulatta isolate AG07107 chromosome 20, Mmul_10, whole genome shotgun sequence

>NC_044996.1 Papio anubis isolate 15944 chromosome X, Panubis1.0, whole genome shotgun sequence

>NC_044997.1 Papio anubis isolate 15944 chromosome Y, Panubis1.0, whole genome shotgun sequence

>NC_044976.1 Papio anubis isolate 15944 chromosome 1, Panubis1.0, whole genome shotgun sequence

>NC_044977.1 Papio anubis isolate 15944 chromosome 2, Panubis1.0, whole genome shotgun sequence

>NC_044978.1 Papio anubis isolate 15944 chromosome 3, Panubis1.0, whole genome shotgun sequence

>NC_044979.1 Papio anubis isolate 15944 chromosome 4, Panubis1.0, whole genome shotgun sequence

>NC_044980.1 Papio anubis isolate 15944 chromosome 5, Panubis1.0, whole genome shotgun sequence

>NC_044981.1 Papio anubis isolate 15944 chromosome 6, Panubis1.0, whole genome shotgun sequence

>NC_044982.1 Papio anubis isolate 15944 chromosome 7, Panubis1.0, whole genome shotgun sequence

>NC_044983.1 Papio anubis isolate 15944 chromosome 8, Panubis1.0, whole genome shotgun sequence


In [35]:
set(chromosomes)

{'chromosome 1',
 'chromosome 10',
 'chromosome 11',
 'chromosome 12',
 'chromosome 13',
 'chromosome 14',
 'chromosome 15',
 'chromosome 16',
 'chromosome 17',
 'chromosome 18',
 'chromosome 19',
 'chromosome 2',
 'chromosome 20',
 'chromosome 21',
 'chromosome 22',
 'chromosome 23',
 'chromosome 24',
 'chromosome 25',
 'chromosome 26',
 'chromosome 27',
 'chromosome 28',
 'chromosome 29',
 'chromosome 3',
 'chromosome 30',
 'chromosome 31',
 'chromosome 32',
 'chromosome 33',
 'chromosome 34',
 'chromosome 35',
 'chromosome 36',
 'chromosome 37',
 'chromosome 38',
 'chromosome 4',
 'chromosome 5',
 'chromosome 6',
 'chromosome 7',
 'chromosome 8',
 'chromosome 9',
 'chromosome A1',
 'chromosome A2',
 'chromosome A3',
 'chromosome B1',
 'chromosome B2',
 'chromosome B3',
 'chromosome B4',
 'chromosome C1',
 'chromosome C2',
 'chromosome D1',
 'chromosome D2',
 'chromosome D3',
 'chromosome D4',
 'chromosome E1',
 'chromosome E2',
 'chromosome E3',
 'chromosome F1',
 'chromosome F2',
 'chromosome X',
 'chromosome X1',
 'chromosome X2',
 'chromosome X3',
 'chromosome X4',
 'chromosome X5',
 'chromosome Y',
 'chromosome Y1',
 'chromosome Y2',
 'chromosome Y3',
 'chromosome Y4',
 'chromosome Y5'}

In [38]:
set(descriptions)

{'',
 ' genomic patch of type FIX',
 ' genomic patch of type NOVEL',
 ' genomic scaffold',
 ' unlocalized genomic scaffold'}

In [16]:
df

,assembly_accession,organism_name,n_autosomes,number_of_x,number_of_y
0,GCF_004115215.2,Ornithorhynchus anatinus,21,5,20
1,GCF_015852505.1,Tachyglossus aculeatus,31,5,9
2,GCF_902635505.1,Sarcophilus harrisii,6,1,1
7,GCF_020740605.2,Lemur catta,37,1,1
8,GCF_027406575.1,Nycticebus coucang,24,1,1
9,GCF_011100555.1,Callithrix jacchus,22,16,87
10,GCF_003339765.1,Macaca mulatta,307,5,1
11,GCF_008728515.1,Papio anubis,20,1,1
13,GCF_029289425.2,Pan paniscus,23,1,1
14,GCF_028885655.2,Pongo abelii,27,1,1
15,GCF_000001405.40,Homo sapiens,557,15,6
18,GCF_014441545.1,Canis lupus familiaris,38,1,3
19,GCF_023065955.2,Ursus arctos,0,1,1
21,GCF_902655055.1,Lutra lutra,18,1,1
22,GCF_922984935.1,Meles meles,21,4,1
23,GCF_030435805.1,Mustela lutreola,21,1,2
28,GCF_009762305.2,Zalophus californianus,17,1,1
29,GCF_949987515.1,Delphinus delphis,21,1,1
30,GCF_963455315.1,Globicephala melas,21,1,1
32,GCF_011762595.1,Tursiops truncatus,21,1,4
36,GCF_009873245.2,Balaenoptera musculus,21,1,1
37,GCF_030014295.1,Loxodonta africana,55,2,17
38,GCF_016077325.2,Equus asinus,30,1,1
40,GCF_000003025.6,Sus scrofa,18,1,10
41,GCF_036321535.1,Camelus dromedarius,36,1,1
44,GCF_032452875.1,Bos javanicus,29,1,1
45,GCF_002263795.3,Bos taurus,29,1,1
46,GCF_000247795.1,Bos indicus,29,1,1
48,GCF_016772045.2,Ovis aries,26,1,1
49,GCF_030435755.1,Ochotona princeps,33,1,1
50,GCF_033115175.1,Lepus europaeus,42,1,1
54,GCF_030254825.1,Meriones unguiculatus,151,6,6
56,GCF_000001635.27,Mus musculus,32,2,5
58,GCF_036323735.1,Rattus norvegicus,25,1,47
59,GCF_011064425.1,Rattus rattus,18,1,1
60,GCF_947179515.1,Apodemus sylvaticus,25,1,10
61,GCF_027887165.1,Monodelphis domestica,8,1,4
62,GCF_028564815.1,Eubalaena glacialis,21,1,9
65,GCF_015220235.1,Choloepus didactylus,75,4,8
68,GCF_002201575.2,Neomonachus schauinslandi,16,1,1
70,GCF_033118175.1,Dama dama,33,1,1
72,GCF_902686445.1,Sciurus carolinensis,29,1,4
75,GCF_008632895.1,Mastomys coucha,0,1,1
76,GCF_009829155.1,Mustela erminea,21,1,1
79,GCF_023091745.1,Budorcas taxicolor,25,1,1
88,GCF_025265405.1,Mesoplodon densirostris,20,1,3
89,GCF_020740685.1,Jaculus jaculus,24,1,6
93,GCF_011762505.1,Arvicanthis niloticus,21,1,4
94,GCF_007474595.2,Lynx canadensis,18,1,5
96,GCF_028018385.1,Neofelis nebulosa,18,1,4
103,GCF_004126475.2,Phyllostomus discolor,22,1,1
104,GCF_963259705.1,Myotis daubentonii,22,1,1
105,GCF_024166365.1,Elephas maximus indicus,36,1,7
106,GCF_024139225.1,Suncus etruscus,39,27,4
107,GCF_027409185.1,Cynocephalus volans,29,1,1
108,GCF_030020395.1,Manis pentadactyla,31,4,17
113,GCF_024542745.1,Macaca thibetana thibetana,20,1,1
114,GCF_950005125.1,Chionomys nivalis,27,1,1
120,GCF_002776525.5,Piliocolobus tephrosceles,21,1,1
122,GCF_019320065.1,Cervus canadensis,33,1,1

In [18]:
test_species = ["Sarcophilus harrisii", "Monodelphis domestica", "Manis pentadactyla", "Equus asinus", "Sus scrofa", "Camelus dromedarius", 
                "Phyllostomus discolor", "Myotis daubentonii", "Suncus etruscus", "Lepus europaeus", "Ochotona princeps", 
                "Sciurus carolinensis", "Nycticebus coucang", "Lemur catta", "Cynocephalus volans", 'Elephas maximus indicus', 'Loxodonta africana',
                "Choloepus didactylus", "Ornithorhynchus anatinus", "Tachyglossus aculeatus"]

valid_species = ["Lynx canadensis", "Neofelis nebulosa", "Eubalaena glacialis", "Balaenoptera musculus", "Cervus canadensis", "Dama dama",
                 "Meriones unguiculatus", "Chionomys nivalis", "Jaculus jaculus", "Callithrix jacchus"]

train_species = [species for species in df.organism_name if species not in test_species and species not in valid_species]

In [19]:
assert len(test_species) == 20
assert len(valid_species) == 10
assert len(train_species) == 30

In [22]:
train_df = df[df['organism_name'].apply(lambda x: (x not in valid_species) and (x not in test_species))]
train_df

,assembly_accession,organism_name,n_autosomes,number_of_x,number_of_y
10,GCF_003339765.1,Macaca mulatta,307,5,1
11,GCF_008728515.1,Papio anubis,20,1,1
13,GCF_029289425.2,Pan paniscus,23,1,1
14,GCF_028885655.2,Pongo abelii,27,1,1
15,GCF_000001405.40,Homo sapiens,557,15,6
18,GCF_014441545.1,Canis lupus familiaris,38,1,3
19,GCF_023065955.2,Ursus arctos,0,1,1
21,GCF_902655055.1,Lutra lutra,18,1,1
22,GCF_922984935.1,Meles meles,21,4,1
23,GCF_030435805.1,Mustela lutreola,21,1,2
28,GCF_009762305.2,Zalophus californianus,17,1,1
29,GCF_949987515.1,Delphinus delphis,21,1,1
30,GCF_963455315.1,Globicephala melas,21,1,1
32,GCF_011762595.1,Tursiops truncatus,21,1,4
44,GCF_032452875.1,Bos javanicus,29,1,1
45,GCF_002263795.3,Bos taurus,29,1,1
46,GCF_000247795.1,Bos indicus,29,1,1
48,GCF_016772045.2,Ovis aries,26,1,1
56,GCF_000001635.27,Mus musculus,32,2,5
58,GCF_036323735.1,Rattus norvegicus,25,1,47
59,GCF_011064425.1,Rattus rattus,18,1,1
60,GCF_947179515.1,Apodemus sylvaticus,25,1,10
68,GCF_002201575.2,Neomonachus schauinslandi,16,1,1
75,GCF_008632895.1,Mastomys coucha,0,1,1
76,GCF_009829155.1,Mustela erminea,21,1,1
79,GCF_023091745.1,Budorcas taxicolor,25,1,1
88,GCF_025265405.1,Mesoplodon densirostris,20,1,3
93,GCF_011762505.1,Arvicanthis niloticus,21,1,4
113,GCF_024542745.1,Macaca thibetana thibetana,20,1,1
120,GCF_002776525.5,Piliocolobus tephrosceles,21,1,1

In [23]:
len(train_df)

30

In [21]:
with open(dir+"/"+assembly_accession_list[0]+"/autosomes.fasta") as handle:
    for record in SeqIO.parse(handle, "fasta"):
        print(record.description)

NC_041728.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 1, mOrnAna1.pri.v4, whole genome shotgun sequence
NC_041729.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 2, mOrnAna1.pri.v4, whole genome shotgun sequence
NC_041730.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 3, mOrnAna1.pri.v4, whole genome shotgun sequence
NC_041731.1 Ornithorhynchus anatinus isolate Pmale09 chromosome 4, mOrnAna1.pri.v4, whole genome shotgun sequence

KeyboardInterrupt: